{-# LANGUAGE OverloadedStrings #-}
module Reflex.Dom.Icons.Raw.FA where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


fa :: ClassName
fa = ClassName "fa"

fa2X :: ClassName
fa2X = ClassName "fa-2x"

fa3X :: ClassName
fa3X = ClassName "fa-3x"

fa4X :: ClassName
fa4X = ClassName "fa-4x"

fa500Px :: ClassName
fa500Px = ClassName "fa-500px"

fa5X :: ClassName
fa5X = ClassName "fa-5x"

faAddressBook :: ClassName
faAddressBook = ClassName "fa-address-book"

faAddressBookO :: ClassName
faAddressBookO = ClassName "fa-address-book-o"

faAddressCard :: ClassName
faAddressCard = ClassName "fa-address-card"

faAddressCardO :: ClassName
faAddressCardO = ClassName "fa-address-card-o"

faAdjust :: ClassName
faAdjust = ClassName "fa-adjust"

faAdn :: ClassName
faAdn = ClassName "fa-adn"

faAlignCenter :: ClassName
faAlignCenter = ClassName "fa-align-center"

faAlignJustify :: ClassName
faAlignJustify = ClassName "fa-align-justify"

faAlignLeft :: ClassName
faAlignLeft = ClassName "fa-align-left"

faAlignRight :: ClassName
faAlignRight = ClassName "fa-align-right"

faAmazon :: ClassName
faAmazon = ClassName "fa-amazon"

faAmbulance :: ClassName
faAmbulance = ClassName "fa-ambulance"

faAmericanSignLanguageInterpreting :: ClassName
faAmericanSignLanguageInterpreting = ClassName "fa-american-sign-language-interpreting"

faAnchor :: ClassName
faAnchor = ClassName "fa-anchor"

faAndroid :: ClassName
faAndroid = ClassName "fa-android"

faAngellist :: ClassName
faAngellist = ClassName "fa-angellist"

faAngleDoubleDown :: ClassName
faAngleDoubleDown = ClassName "fa-angle-double-down"

faAngleDoubleLeft :: ClassName
faAngleDoubleLeft = ClassName "fa-angle-double-left"

faAngleDoubleRight :: ClassName
faAngleDoubleRight = ClassName "fa-angle-double-right"

faAngleDoubleUp :: ClassName
faAngleDoubleUp = ClassName "fa-angle-double-up"

faAngleDown :: ClassName
faAngleDown = ClassName "fa-angle-down"

faAngleLeft :: ClassName
faAngleLeft = ClassName "fa-angle-left"

faAngleRight :: ClassName
faAngleRight = ClassName "fa-angle-right"

faAngleUp :: ClassName
faAngleUp = ClassName "fa-angle-up"

faApple :: ClassName
faApple = ClassName "fa-apple"

faArchive :: ClassName
faArchive = ClassName "fa-archive"

faAreaChart :: ClassName
faAreaChart = ClassName "fa-area-chart"

faArrowCircleDown :: ClassName
faArrowCircleDown = ClassName "fa-arrow-circle-down"

faArrowCircleLeft :: ClassName
faArrowCircleLeft = ClassName "fa-arrow-circle-left"

faArrowCircleODown :: ClassName
faArrowCircleODown = ClassName "fa-arrow-circle-o-down"

faArrowCircleOLeft :: ClassName
faArrowCircleOLeft = ClassName "fa-arrow-circle-o-left"

faArrowCircleORight :: ClassName
faArrowCircleORight = ClassName "fa-arrow-circle-o-right"

faArrowCircleOUp :: ClassName
faArrowCircleOUp = ClassName "fa-arrow-circle-o-up"

faArrowCircleRight :: ClassName
faArrowCircleRight = ClassName "fa-arrow-circle-right"

faArrowCircleUp :: ClassName
faArrowCircleUp = ClassName "fa-arrow-circle-up"

faArrowDown :: ClassName
faArrowDown = ClassName "fa-arrow-down"

faArrowLeft :: ClassName
faArrowLeft = ClassName "fa-arrow-left"

faArrowRight :: ClassName
faArrowRight = ClassName "fa-arrow-right"

faArrowUp :: ClassName
faArrowUp = ClassName "fa-arrow-up"

faArrows :: ClassName
faArrows = ClassName "fa-arrows"

faArrowsAlt :: ClassName
faArrowsAlt = ClassName "fa-arrows-alt"

faArrowsH :: ClassName
faArrowsH = ClassName "fa-arrows-h"

faArrowsV :: ClassName
faArrowsV = ClassName "fa-arrows-v"

faAslInterpreting :: ClassName
faAslInterpreting = ClassName "fa-asl-interpreting"

faAssistiveListeningSystems :: ClassName
faAssistiveListeningSystems = ClassName "fa-assistive-listening-systems"

faAsterisk :: ClassName
faAsterisk = ClassName "fa-asterisk"

faAt :: ClassName
faAt = ClassName "fa-at"

faAudioDescription :: ClassName
faAudioDescription = ClassName "fa-audio-description"

faAutomobile :: ClassName
faAutomobile = ClassName "fa-automobile"

faBackward :: ClassName
faBackward = ClassName "fa-backward"

faBalanceScale :: ClassName
faBalanceScale = ClassName "fa-balance-scale"

faBan :: ClassName
faBan = ClassName "fa-ban"

faBandcamp :: ClassName
faBandcamp = ClassName "fa-bandcamp"

faBank :: ClassName
faBank = ClassName "fa-bank"

faBarChart :: ClassName
faBarChart = ClassName "fa-bar-chart"

faBarChartO :: ClassName
faBarChartO = ClassName "fa-bar-chart-o"

faBarcode :: ClassName
faBarcode = ClassName "fa-barcode"

faBars :: ClassName
faBars = ClassName "fa-bars"

faBath :: ClassName
faBath = ClassName "fa-bath"

faBathtub :: ClassName
faBathtub = ClassName "fa-bathtub"

faBattery :: ClassName
faBattery = ClassName "fa-battery"

faBattery0 :: ClassName
faBattery0 = ClassName "fa-battery-0"

faBattery1 :: ClassName
faBattery1 = ClassName "fa-battery-1"

faBattery2 :: ClassName
faBattery2 = ClassName "fa-battery-2"

faBattery3 :: ClassName
faBattery3 = ClassName "fa-battery-3"

faBattery4 :: ClassName
faBattery4 = ClassName "fa-battery-4"

faBatteryEmpty :: ClassName
faBatteryEmpty = ClassName "fa-battery-empty"

faBatteryFull :: ClassName
faBatteryFull = ClassName "fa-battery-full"

faBatteryHalf :: ClassName
faBatteryHalf = ClassName "fa-battery-half"

faBatteryQuarter :: ClassName
faBatteryQuarter = ClassName "fa-battery-quarter"

faBatteryThreeQuarters :: ClassName
faBatteryThreeQuarters = ClassName "fa-battery-three-quarters"

faBed :: ClassName
faBed = ClassName "fa-bed"

faBeer :: ClassName
faBeer = ClassName "fa-beer"

faBehance :: ClassName
faBehance = ClassName "fa-behance"

faBehanceSquare :: ClassName
faBehanceSquare = ClassName "fa-behance-square"

faBell :: ClassName
faBell = ClassName "fa-bell"

faBellO :: ClassName
faBellO = ClassName "fa-bell-o"

faBellSlash :: ClassName
faBellSlash = ClassName "fa-bell-slash"

faBellSlashO :: ClassName
faBellSlashO = ClassName "fa-bell-slash-o"

faBicycle :: ClassName
faBicycle = ClassName "fa-bicycle"

faBinoculars :: ClassName
faBinoculars = ClassName "fa-binoculars"

faBirthdayCake :: ClassName
faBirthdayCake = ClassName "fa-birthday-cake"

faBitbucket :: ClassName
faBitbucket = ClassName "fa-bitbucket"

faBitbucketSquare :: ClassName
faBitbucketSquare = ClassName "fa-bitbucket-square"

faBitcoin :: ClassName
faBitcoin = ClassName "fa-bitcoin"

faBlackTie :: ClassName
faBlackTie = ClassName "fa-black-tie"

faBlind :: ClassName
faBlind = ClassName "fa-blind"

faBluetooth :: ClassName
faBluetooth = ClassName "fa-bluetooth"

faBluetoothB :: ClassName
faBluetoothB = ClassName "fa-bluetooth-b"

faBold :: ClassName
faBold = ClassName "fa-bold"

faBolt :: ClassName
faBolt = ClassName "fa-bolt"

faBomb :: ClassName
faBomb = ClassName "fa-bomb"

faBook :: ClassName
faBook = ClassName "fa-book"

faBookmark :: ClassName
faBookmark = ClassName "fa-bookmark"

faBookmarkO :: ClassName
faBookmarkO = ClassName "fa-bookmark-o"

faBorder :: ClassName
faBorder = ClassName "fa-border"

faBraille :: ClassName
faBraille = ClassName "fa-braille"

faBriefcase :: ClassName
faBriefcase = ClassName "fa-briefcase"

faBtc :: ClassName
faBtc = ClassName "fa-btc"

faBug :: ClassName
faBug = ClassName "fa-bug"

faBuilding :: ClassName
faBuilding = ClassName "fa-building"

faBuildingO :: ClassName
faBuildingO = ClassName "fa-building-o"

faBullhorn :: ClassName
faBullhorn = ClassName "fa-bullhorn"

faBullseye :: ClassName
faBullseye = ClassName "fa-bullseye"

faBus :: ClassName
faBus = ClassName "fa-bus"

faBuysellads :: ClassName
faBuysellads = ClassName "fa-buysellads"

faCab :: ClassName
faCab = ClassName "fa-cab"

faCalculator :: ClassName
faCalculator = ClassName "fa-calculator"

faCalendar :: ClassName
faCalendar = ClassName "fa-calendar"

faCalendarCheckO :: ClassName
faCalendarCheckO = ClassName "fa-calendar-check-o"

faCalendarMinusO :: ClassName
faCalendarMinusO = ClassName "fa-calendar-minus-o"

faCalendarO :: ClassName
faCalendarO = ClassName "fa-calendar-o"

faCalendarPlusO :: ClassName
faCalendarPlusO = ClassName "fa-calendar-plus-o"

faCalendarTimesO :: ClassName
faCalendarTimesO = ClassName "fa-calendar-times-o"

faCamera :: ClassName
faCamera = ClassName "fa-camera"

faCameraRetro :: ClassName
faCameraRetro = ClassName "fa-camera-retro"

faCar :: ClassName
faCar = ClassName "fa-car"

faCaretDown :: ClassName
faCaretDown = ClassName "fa-caret-down"

faCaretLeft :: ClassName
faCaretLeft = ClassName "fa-caret-left"

faCaretRight :: ClassName
faCaretRight = ClassName "fa-caret-right"

faCaretSquareODown :: ClassName
faCaretSquareODown = ClassName "fa-caret-square-o-down"

faCaretSquareOLeft :: ClassName
faCaretSquareOLeft = ClassName "fa-caret-square-o-left"

faCaretSquareORight :: ClassName
faCaretSquareORight = ClassName "fa-caret-square-o-right"

faCaretSquareOUp :: ClassName
faCaretSquareOUp = ClassName "fa-caret-square-o-up"

faCaretUp :: ClassName
faCaretUp = ClassName "fa-caret-up"

faCartArrowDown :: ClassName
faCartArrowDown = ClassName "fa-cart-arrow-down"

faCartPlus :: ClassName
faCartPlus = ClassName "fa-cart-plus"

faCc :: ClassName
faCc = ClassName "fa-cc"

faCcAmex :: ClassName
faCcAmex = ClassName "fa-cc-amex"

faCcDinersClub :: ClassName
faCcDinersClub = ClassName "fa-cc-diners-club"

faCcDiscover :: ClassName
faCcDiscover = ClassName "fa-cc-discover"

faCcJcb :: ClassName
faCcJcb = ClassName "fa-cc-jcb"

faCcMastercard :: ClassName
faCcMastercard = ClassName "fa-cc-mastercard"

faCcPaypal :: ClassName
faCcPaypal = ClassName "fa-cc-paypal"

faCcStripe :: ClassName
faCcStripe = ClassName "fa-cc-stripe"

faCcVisa :: ClassName
faCcVisa = ClassName "fa-cc-visa"

faCertificate :: ClassName
faCertificate = ClassName "fa-certificate"

faChain :: ClassName
faChain = ClassName "fa-chain"

faChainBroken :: ClassName
faChainBroken = ClassName "fa-chain-broken"

faCheck :: ClassName
faCheck = ClassName "fa-check"

faCheckCircle :: ClassName
faCheckCircle = ClassName "fa-check-circle"

faCheckCircleO :: ClassName
faCheckCircleO = ClassName "fa-check-circle-o"

faCheckSquare :: ClassName
faCheckSquare = ClassName "fa-check-square"

faCheckSquareO :: ClassName
faCheckSquareO = ClassName "fa-check-square-o"

faChevronCircleDown :: ClassName
faChevronCircleDown = ClassName "fa-chevron-circle-down"

faChevronCircleLeft :: ClassName
faChevronCircleLeft = ClassName "fa-chevron-circle-left"

faChevronCircleRight :: ClassName
faChevronCircleRight = ClassName "fa-chevron-circle-right"

faChevronCircleUp :: ClassName
faChevronCircleUp = ClassName "fa-chevron-circle-up"

faChevronDown :: ClassName
faChevronDown = ClassName "fa-chevron-down"

faChevronLeft :: ClassName
faChevronLeft = ClassName "fa-chevron-left"

faChevronRight :: ClassName
faChevronRight = ClassName "fa-chevron-right"

faChevronUp :: ClassName
faChevronUp = ClassName "fa-chevron-up"

faChild :: ClassName
faChild = ClassName "fa-child"

faChrome :: ClassName
faChrome = ClassName "fa-chrome"

faCircle :: ClassName
faCircle = ClassName "fa-circle"

faCircleO :: ClassName
faCircleO = ClassName "fa-circle-o"

faCircleONotch :: ClassName
faCircleONotch = ClassName "fa-circle-o-notch"

faCircleThin :: ClassName
faCircleThin = ClassName "fa-circle-thin"

faClipboard :: ClassName
faClipboard = ClassName "fa-clipboard"

faClockO :: ClassName
faClockO = ClassName "fa-clock-o"

faClone :: ClassName
faClone = ClassName "fa-clone"

faClose :: ClassName
faClose = ClassName "fa-close"

faCloud :: ClassName
faCloud = ClassName "fa-cloud"

faCloudDownload :: ClassName
faCloudDownload = ClassName "fa-cloud-download"

faCloudUpload :: ClassName
faCloudUpload = ClassName "fa-cloud-upload"

faCny :: ClassName
faCny = ClassName "fa-cny"

faCode :: ClassName
faCode = ClassName "fa-code"

faCodeFork :: ClassName
faCodeFork = ClassName "fa-code-fork"

faCodepen :: ClassName
faCodepen = ClassName "fa-codepen"

faCodiepie :: ClassName
faCodiepie = ClassName "fa-codiepie"

faCoffee :: ClassName
faCoffee = ClassName "fa-coffee"

faCog :: ClassName
faCog = ClassName "fa-cog"

faCogs :: ClassName
faCogs = ClassName "fa-cogs"

faColumns :: ClassName
faColumns = ClassName "fa-columns"

faComment :: ClassName
faComment = ClassName "fa-comment"

faCommentO :: ClassName
faCommentO = ClassName "fa-comment-o"

faCommenting :: ClassName
faCommenting = ClassName "fa-commenting"

faCommentingO :: ClassName
faCommentingO = ClassName "fa-commenting-o"

faComments :: ClassName
faComments = ClassName "fa-comments"

faCommentsO :: ClassName
faCommentsO = ClassName "fa-comments-o"

faCompass :: ClassName
faCompass = ClassName "fa-compass"

faCompress :: ClassName
faCompress = ClassName "fa-compress"

faConnectdevelop :: ClassName
faConnectdevelop = ClassName "fa-connectdevelop"

faContao :: ClassName
faContao = ClassName "fa-contao"

faCopy :: ClassName
faCopy = ClassName "fa-copy"

faCopyright :: ClassName
faCopyright = ClassName "fa-copyright"

faCreativeCommons :: ClassName
faCreativeCommons = ClassName "fa-creative-commons"

faCreditCard :: ClassName
faCreditCard = ClassName "fa-credit-card"

faCreditCardAlt :: ClassName
faCreditCardAlt = ClassName "fa-credit-card-alt"

faCrop :: ClassName
faCrop = ClassName "fa-crop"

faCrosshairs :: ClassName
faCrosshairs = ClassName "fa-crosshairs"

faCss3 :: ClassName
faCss3 = ClassName "fa-css3"

faCube :: ClassName
faCube = ClassName "fa-cube"

faCubes :: ClassName
faCubes = ClassName "fa-cubes"

faCut :: ClassName
faCut = ClassName "fa-cut"

faCutlery :: ClassName
faCutlery = ClassName "fa-cutlery"

faDashboard :: ClassName
faDashboard = ClassName "fa-dashboard"

faDashcube :: ClassName
faDashcube = ClassName "fa-dashcube"

faDatabase :: ClassName
faDatabase = ClassName "fa-database"

faDeaf :: ClassName
faDeaf = ClassName "fa-deaf"

faDeafness :: ClassName
faDeafness = ClassName "fa-deafness"

faDedent :: ClassName
faDedent = ClassName "fa-dedent"

faDelicious :: ClassName
faDelicious = ClassName "fa-delicious"

faDesktop :: ClassName
faDesktop = ClassName "fa-desktop"

faDeviantart :: ClassName
faDeviantart = ClassName "fa-deviantart"

faDiamond :: ClassName
faDiamond = ClassName "fa-diamond"

faDigg :: ClassName
faDigg = ClassName "fa-digg"

faDollar :: ClassName
faDollar = ClassName "fa-dollar"

faDotCircleO :: ClassName
faDotCircleO = ClassName "fa-dot-circle-o"

faDownload :: ClassName
faDownload = ClassName "fa-download"

faDribbble :: ClassName
faDribbble = ClassName "fa-dribbble"

faDriversLicense :: ClassName
faDriversLicense = ClassName "fa-drivers-license"

faDriversLicenseO :: ClassName
faDriversLicenseO = ClassName "fa-drivers-license-o"

faDropbox :: ClassName
faDropbox = ClassName "fa-dropbox"

faDrupal :: ClassName
faDrupal = ClassName "fa-drupal"

faEdge :: ClassName
faEdge = ClassName "fa-edge"

faEdit :: ClassName
faEdit = ClassName "fa-edit"

faEercast :: ClassName
faEercast = ClassName "fa-eercast"

faEject :: ClassName
faEject = ClassName "fa-eject"

faEllipsisH :: ClassName
faEllipsisH = ClassName "fa-ellipsis-h"

faEllipsisV :: ClassName
faEllipsisV = ClassName "fa-ellipsis-v"

faEmpire :: ClassName
faEmpire = ClassName "fa-empire"

faEnvelope :: ClassName
faEnvelope = ClassName "fa-envelope"

faEnvelopeO :: ClassName
faEnvelopeO = ClassName "fa-envelope-o"

faEnvelopeOpen :: ClassName
faEnvelopeOpen = ClassName "fa-envelope-open"

faEnvelopeOpenO :: ClassName
faEnvelopeOpenO = ClassName "fa-envelope-open-o"

faEnvelopeSquare :: ClassName
faEnvelopeSquare = ClassName "fa-envelope-square"

faEnvira :: ClassName
faEnvira = ClassName "fa-envira"

faEraser :: ClassName
faEraser = ClassName "fa-eraser"

faEtsy :: ClassName
faEtsy = ClassName "fa-etsy"

faEur :: ClassName
faEur = ClassName "fa-eur"

faEuro :: ClassName
faEuro = ClassName "fa-euro"

faExchange :: ClassName
faExchange = ClassName "fa-exchange"

faExclamation :: ClassName
faExclamation = ClassName "fa-exclamation"

faExclamationCircle :: ClassName
faExclamationCircle = ClassName "fa-exclamation-circle"

faExclamationTriangle :: ClassName
faExclamationTriangle = ClassName "fa-exclamation-triangle"

faExpand :: ClassName
faExpand = ClassName "fa-expand"

faExpeditedssl :: ClassName
faExpeditedssl = ClassName "fa-expeditedssl"

faExternalLink :: ClassName
faExternalLink = ClassName "fa-external-link"

faExternalLinkSquare :: ClassName
faExternalLinkSquare = ClassName "fa-external-link-square"

faEye :: ClassName
faEye = ClassName "fa-eye"

faEyeSlash :: ClassName
faEyeSlash = ClassName "fa-eye-slash"

faEyedropper :: ClassName
faEyedropper = ClassName "fa-eyedropper"

faFa :: ClassName
faFa = ClassName "fa-fa"

faFacebook :: ClassName
faFacebook = ClassName "fa-facebook"

faFacebookF :: ClassName
faFacebookF = ClassName "fa-facebook-f"

faFacebookOfficial :: ClassName
faFacebookOfficial = ClassName "fa-facebook-official"

faFacebookSquare :: ClassName
faFacebookSquare = ClassName "fa-facebook-square"

faFastBackward :: ClassName
faFastBackward = ClassName "fa-fast-backward"

faFastForward :: ClassName
faFastForward = ClassName "fa-fast-forward"

faFax :: ClassName
faFax = ClassName "fa-fax"

faFeed :: ClassName
faFeed = ClassName "fa-feed"

faFemale :: ClassName
faFemale = ClassName "fa-female"

faFighterJet :: ClassName
faFighterJet = ClassName "fa-fighter-jet"

faFile :: ClassName
faFile = ClassName "fa-file"

faFileArchiveO :: ClassName
faFileArchiveO = ClassName "fa-file-archive-o"

faFileAudioO :: ClassName
faFileAudioO = ClassName "fa-file-audio-o"

faFileCodeO :: ClassName
faFileCodeO = ClassName "fa-file-code-o"

faFileExcelO :: ClassName
faFileExcelO = ClassName "fa-file-excel-o"

faFileImageO :: ClassName
faFileImageO = ClassName "fa-file-image-o"

faFileMovieO :: ClassName
faFileMovieO = ClassName "fa-file-movie-o"

faFileO :: ClassName
faFileO = ClassName "fa-file-o"

faFilePdfO :: ClassName
faFilePdfO = ClassName "fa-file-pdf-o"

faFilePhotoO :: ClassName
faFilePhotoO = ClassName "fa-file-photo-o"

faFilePictureO :: ClassName
faFilePictureO = ClassName "fa-file-picture-o"

faFilePowerpointO :: ClassName
faFilePowerpointO = ClassName "fa-file-powerpoint-o"

faFileSoundO :: ClassName
faFileSoundO = ClassName "fa-file-sound-o"

faFileText :: ClassName
faFileText = ClassName "fa-file-text"

faFileTextO :: ClassName
faFileTextO = ClassName "fa-file-text-o"

faFileVideoO :: ClassName
faFileVideoO = ClassName "fa-file-video-o"

faFileWordO :: ClassName
faFileWordO = ClassName "fa-file-word-o"

faFileZipO :: ClassName
faFileZipO = ClassName "fa-file-zip-o"

faFilesO :: ClassName
faFilesO = ClassName "fa-files-o"

faFilm :: ClassName
faFilm = ClassName "fa-film"

faFilter :: ClassName
faFilter = ClassName "fa-filter"

faFire :: ClassName
faFire = ClassName "fa-fire"

faFireExtinguisher :: ClassName
faFireExtinguisher = ClassName "fa-fire-extinguisher"

faFirefox :: ClassName
faFirefox = ClassName "fa-firefox"

faFirstOrder :: ClassName
faFirstOrder = ClassName "fa-first-order"

faFlag :: ClassName
faFlag = ClassName "fa-flag"

faFlagCheckered :: ClassName
faFlagCheckered = ClassName "fa-flag-checkered"

faFlagO :: ClassName
faFlagO = ClassName "fa-flag-o"

faFlash :: ClassName
faFlash = ClassName "fa-flash"

faFlask :: ClassName
faFlask = ClassName "fa-flask"

faFlickr :: ClassName
faFlickr = ClassName "fa-flickr"

faFlipHorizontal :: ClassName
faFlipHorizontal = ClassName "fa-flip-horizontal"

faFlipVertical :: ClassName
faFlipVertical = ClassName "fa-flip-vertical"

faFloppyO :: ClassName
faFloppyO = ClassName "fa-floppy-o"

faFolder :: ClassName
faFolder = ClassName "fa-folder"

faFolderO :: ClassName
faFolderO = ClassName "fa-folder-o"

faFolderOpen :: ClassName
faFolderOpen = ClassName "fa-folder-open"

faFolderOpenO :: ClassName
faFolderOpenO = ClassName "fa-folder-open-o"

faFont :: ClassName
faFont = ClassName "fa-font"

faFontAwesome :: ClassName
faFontAwesome = ClassName "fa-font-awesome"

faFonticons :: ClassName
faFonticons = ClassName "fa-fonticons"

faFortAwesome :: ClassName
faFortAwesome = ClassName "fa-fort-awesome"

faForumbee :: ClassName
faForumbee = ClassName "fa-forumbee"

faForward :: ClassName
faForward = ClassName "fa-forward"

faFoursquare :: ClassName
faFoursquare = ClassName "fa-foursquare"

faFreeCodeCamp :: ClassName
faFreeCodeCamp = ClassName "fa-free-code-camp"

faFrownO :: ClassName
faFrownO = ClassName "fa-frown-o"

faFutbolO :: ClassName
faFutbolO = ClassName "fa-futbol-o"

faFw :: ClassName
faFw = ClassName "fa-fw"

faGamepad :: ClassName
faGamepad = ClassName "fa-gamepad"

faGavel :: ClassName
faGavel = ClassName "fa-gavel"

faGbp :: ClassName
faGbp = ClassName "fa-gbp"

faGe :: ClassName
faGe = ClassName "fa-ge"

faGear :: ClassName
faGear = ClassName "fa-gear"

faGears :: ClassName
faGears = ClassName "fa-gears"

faGenderless :: ClassName
faGenderless = ClassName "fa-genderless"

faGetPocket :: ClassName
faGetPocket = ClassName "fa-get-pocket"

faGg :: ClassName
faGg = ClassName "fa-gg"

faGgCircle :: ClassName
faGgCircle = ClassName "fa-gg-circle"

faGift :: ClassName
faGift = ClassName "fa-gift"

faGit :: ClassName
faGit = ClassName "fa-git"

faGitSquare :: ClassName
faGitSquare = ClassName "fa-git-square"

faGithub :: ClassName
faGithub = ClassName "fa-github"

faGithubAlt :: ClassName
faGithubAlt = ClassName "fa-github-alt"

faGithubSquare :: ClassName
faGithubSquare = ClassName "fa-github-square"

faGitlab :: ClassName
faGitlab = ClassName "fa-gitlab"

faGittip :: ClassName
faGittip = ClassName "fa-gittip"

faGlass :: ClassName
faGlass = ClassName "fa-glass"

faGlide :: ClassName
faGlide = ClassName "fa-glide"

faGlideG :: ClassName
faGlideG = ClassName "fa-glide-g"

faGlobe :: ClassName
faGlobe = ClassName "fa-globe"

faGoogle :: ClassName
faGoogle = ClassName "fa-google"

faGooglePlus :: ClassName
faGooglePlus = ClassName "fa-google-plus"

faGooglePlusCircle :: ClassName
faGooglePlusCircle = ClassName "fa-google-plus-circle"

faGooglePlusOfficial :: ClassName
faGooglePlusOfficial = ClassName "fa-google-plus-official"

faGooglePlusSquare :: ClassName
faGooglePlusSquare = ClassName "fa-google-plus-square"

faGoogleWallet :: ClassName
faGoogleWallet = ClassName "fa-google-wallet"

faGraduationCap :: ClassName
faGraduationCap = ClassName "fa-graduation-cap"

faGratipay :: ClassName
faGratipay = ClassName "fa-gratipay"

faGrav :: ClassName
faGrav = ClassName "fa-grav"

faGroup :: ClassName
faGroup = ClassName "fa-group"

faHSquare :: ClassName
faHSquare = ClassName "fa-h-square"

faHackerNews :: ClassName
faHackerNews = ClassName "fa-hacker-news"

faHandGrabO :: ClassName
faHandGrabO = ClassName "fa-hand-grab-o"

faHandLizardO :: ClassName
faHandLizardO = ClassName "fa-hand-lizard-o"

faHandODown :: ClassName
faHandODown = ClassName "fa-hand-o-down"

faHandOLeft :: ClassName
faHandOLeft = ClassName "fa-hand-o-left"

faHandORight :: ClassName
faHandORight = ClassName "fa-hand-o-right"

faHandOUp :: ClassName
faHandOUp = ClassName "fa-hand-o-up"

faHandPaperO :: ClassName
faHandPaperO = ClassName "fa-hand-paper-o"

faHandPeaceO :: ClassName
faHandPeaceO = ClassName "fa-hand-peace-o"

faHandPointerO :: ClassName
faHandPointerO = ClassName "fa-hand-pointer-o"

faHandRockO :: ClassName
faHandRockO = ClassName "fa-hand-rock-o"

faHandScissorsO :: ClassName
faHandScissorsO = ClassName "fa-hand-scissors-o"

faHandSpockO :: ClassName
faHandSpockO = ClassName "fa-hand-spock-o"

faHandStopO :: ClassName
faHandStopO = ClassName "fa-hand-stop-o"

faHandshakeO :: ClassName
faHandshakeO = ClassName "fa-handshake-o"

faHardOfHearing :: ClassName
faHardOfHearing = ClassName "fa-hard-of-hearing"

faHashtag :: ClassName
faHashtag = ClassName "fa-hashtag"

faHddO :: ClassName
faHddO = ClassName "fa-hdd-o"

faHeader :: ClassName
faHeader = ClassName "fa-header"

faHeadphones :: ClassName
faHeadphones = ClassName "fa-headphones"

faHeart :: ClassName
faHeart = ClassName "fa-heart"

faHeartO :: ClassName
faHeartO = ClassName "fa-heart-o"

faHeartbeat :: ClassName
faHeartbeat = ClassName "fa-heartbeat"

faHistory :: ClassName
faHistory = ClassName "fa-history"

faHome :: ClassName
faHome = ClassName "fa-home"

faHospitalO :: ClassName
faHospitalO = ClassName "fa-hospital-o"

faHotel :: ClassName
faHotel = ClassName "fa-hotel"

faHourglass :: ClassName
faHourglass = ClassName "fa-hourglass"

faHourglass1 :: ClassName
faHourglass1 = ClassName "fa-hourglass-1"

faHourglass2 :: ClassName
faHourglass2 = ClassName "fa-hourglass-2"

faHourglass3 :: ClassName
faHourglass3 = ClassName "fa-hourglass-3"

faHourglassEnd :: ClassName
faHourglassEnd = ClassName "fa-hourglass-end"

faHourglassHalf :: ClassName
faHourglassHalf = ClassName "fa-hourglass-half"

faHourglassO :: ClassName
faHourglassO = ClassName "fa-hourglass-o"

faHourglassStart :: ClassName
faHourglassStart = ClassName "fa-hourglass-start"

faHouzz :: ClassName
faHouzz = ClassName "fa-houzz"

faHtml5 :: ClassName
faHtml5 = ClassName "fa-html5"

faICursor :: ClassName
faICursor = ClassName "fa-i-cursor"

faIdBadge :: ClassName
faIdBadge = ClassName "fa-id-badge"

faIdCard :: ClassName
faIdCard = ClassName "fa-id-card"

faIdCardO :: ClassName
faIdCardO = ClassName "fa-id-card-o"

faIls :: ClassName
faIls = ClassName "fa-ils"

faImage :: ClassName
faImage = ClassName "fa-image"

faImdb :: ClassName
faImdb = ClassName "fa-imdb"

faInbox :: ClassName
faInbox = ClassName "fa-inbox"

faIndent :: ClassName
faIndent = ClassName "fa-indent"

faIndustry :: ClassName
faIndustry = ClassName "fa-industry"

faInfo :: ClassName
faInfo = ClassName "fa-info"

faInfoCircle :: ClassName
faInfoCircle = ClassName "fa-info-circle"

faInr :: ClassName
faInr = ClassName "fa-inr"

faInstagram :: ClassName
faInstagram = ClassName "fa-instagram"

faInstitution :: ClassName
faInstitution = ClassName "fa-institution"

faInternetExplorer :: ClassName
faInternetExplorer = ClassName "fa-internet-explorer"

faIntersex :: ClassName
faIntersex = ClassName "fa-intersex"

faInverse :: ClassName
faInverse = ClassName "fa-inverse"

faIoxhost :: ClassName
faIoxhost = ClassName "fa-ioxhost"

faItalic :: ClassName
faItalic = ClassName "fa-italic"

faJoomla :: ClassName
faJoomla = ClassName "fa-joomla"

faJpy :: ClassName
faJpy = ClassName "fa-jpy"

faJsfiddle :: ClassName
faJsfiddle = ClassName "fa-jsfiddle"

faKey :: ClassName
faKey = ClassName "fa-key"

faKeyboardO :: ClassName
faKeyboardO = ClassName "fa-keyboard-o"

faKrw :: ClassName
faKrw = ClassName "fa-krw"

faLanguage :: ClassName
faLanguage = ClassName "fa-language"

faLaptop :: ClassName
faLaptop = ClassName "fa-laptop"

faLastfm :: ClassName
faLastfm = ClassName "fa-lastfm"

faLastfmSquare :: ClassName
faLastfmSquare = ClassName "fa-lastfm-square"

faLeaf :: ClassName
faLeaf = ClassName "fa-leaf"

faLeanpub :: ClassName
faLeanpub = ClassName "fa-leanpub"

faLegal :: ClassName
faLegal = ClassName "fa-legal"

faLemonO :: ClassName
faLemonO = ClassName "fa-lemon-o"

faLevelDown :: ClassName
faLevelDown = ClassName "fa-level-down"

faLevelUp :: ClassName
faLevelUp = ClassName "fa-level-up"

faLg :: ClassName
faLg = ClassName "fa-lg"

faLi :: ClassName
faLi = ClassName "fa-li"

faLifeBouy :: ClassName
faLifeBouy = ClassName "fa-life-bouy"

faLifeBuoy :: ClassName
faLifeBuoy = ClassName "fa-life-buoy"

faLifeRing :: ClassName
faLifeRing = ClassName "fa-life-ring"

faLifeSaver :: ClassName
faLifeSaver = ClassName "fa-life-saver"

faLightbulbO :: ClassName
faLightbulbO = ClassName "fa-lightbulb-o"

faLineChart :: ClassName
faLineChart = ClassName "fa-line-chart"

faLink :: ClassName
faLink = ClassName "fa-link"

faLinkedin :: ClassName
faLinkedin = ClassName "fa-linkedin"

faLinkedinSquare :: ClassName
faLinkedinSquare = ClassName "fa-linkedin-square"

faLinode :: ClassName
faLinode = ClassName "fa-linode"

faLinux :: ClassName
faLinux = ClassName "fa-linux"

faList :: ClassName
faList = ClassName "fa-list"

faListAlt :: ClassName
faListAlt = ClassName "fa-list-alt"

faListOl :: ClassName
faListOl = ClassName "fa-list-ol"

faListUl :: ClassName
faListUl = ClassName "fa-list-ul"

faLocationArrow :: ClassName
faLocationArrow = ClassName "fa-location-arrow"

faLock :: ClassName
faLock = ClassName "fa-lock"

faLongArrowDown :: ClassName
faLongArrowDown = ClassName "fa-long-arrow-down"

faLongArrowLeft :: ClassName
faLongArrowLeft = ClassName "fa-long-arrow-left"

faLongArrowRight :: ClassName
faLongArrowRight = ClassName "fa-long-arrow-right"

faLongArrowUp :: ClassName
faLongArrowUp = ClassName "fa-long-arrow-up"

faLowVision :: ClassName
faLowVision = ClassName "fa-low-vision"

faMagic :: ClassName
faMagic = ClassName "fa-magic"

faMagnet :: ClassName
faMagnet = ClassName "fa-magnet"

faMailForward :: ClassName
faMailForward = ClassName "fa-mail-forward"

faMailReply :: ClassName
faMailReply = ClassName "fa-mail-reply"

faMailReplyAll :: ClassName
faMailReplyAll = ClassName "fa-mail-reply-all"

faMale :: ClassName
faMale = ClassName "fa-male"

faMap :: ClassName
faMap = ClassName "fa-map"

faMapMarker :: ClassName
faMapMarker = ClassName "fa-map-marker"

faMapO :: ClassName
faMapO = ClassName "fa-map-o"

faMapPin :: ClassName
faMapPin = ClassName "fa-map-pin"

faMapSigns :: ClassName
faMapSigns = ClassName "fa-map-signs"

faMars :: ClassName
faMars = ClassName "fa-mars"

faMarsDouble :: ClassName
faMarsDouble = ClassName "fa-mars-double"

faMarsStroke :: ClassName
faMarsStroke = ClassName "fa-mars-stroke"

faMarsStrokeH :: ClassName
faMarsStrokeH = ClassName "fa-mars-stroke-h"

faMarsStrokeV :: ClassName
faMarsStrokeV = ClassName "fa-mars-stroke-v"

faMaxcdn :: ClassName
faMaxcdn = ClassName "fa-maxcdn"

faMeanpath :: ClassName
faMeanpath = ClassName "fa-meanpath"

faMedium :: ClassName
faMedium = ClassName "fa-medium"

faMedkit :: ClassName
faMedkit = ClassName "fa-medkit"

faMeetup :: ClassName
faMeetup = ClassName "fa-meetup"

faMehO :: ClassName
faMehO = ClassName "fa-meh-o"

faMercury :: ClassName
faMercury = ClassName "fa-mercury"

faMicrochip :: ClassName
faMicrochip = ClassName "fa-microchip"

faMicrophone :: ClassName
faMicrophone = ClassName "fa-microphone"

faMicrophoneSlash :: ClassName
faMicrophoneSlash = ClassName "fa-microphone-slash"

faMinus :: ClassName
faMinus = ClassName "fa-minus"

faMinusCircle :: ClassName
faMinusCircle = ClassName "fa-minus-circle"

faMinusSquare :: ClassName
faMinusSquare = ClassName "fa-minus-square"

faMinusSquareO :: ClassName
faMinusSquareO = ClassName "fa-minus-square-o"

faMixcloud :: ClassName
faMixcloud = ClassName "fa-mixcloud"

faMobile :: ClassName
faMobile = ClassName "fa-mobile"

faMobilePhone :: ClassName
faMobilePhone = ClassName "fa-mobile-phone"

faModx :: ClassName
faModx = ClassName "fa-modx"

faMoney :: ClassName
faMoney = ClassName "fa-money"

faMoonO :: ClassName
faMoonO = ClassName "fa-moon-o"

faMortarBoard :: ClassName
faMortarBoard = ClassName "fa-mortar-board"

faMotorcycle :: ClassName
faMotorcycle = ClassName "fa-motorcycle"

faMousePointer :: ClassName
faMousePointer = ClassName "fa-mouse-pointer"

faMusic :: ClassName
faMusic = ClassName "fa-music"

faNavicon :: ClassName
faNavicon = ClassName "fa-navicon"

faNeuter :: ClassName
faNeuter = ClassName "fa-neuter"

faNewspaperO :: ClassName
faNewspaperO = ClassName "fa-newspaper-o"

faObjectGroup :: ClassName
faObjectGroup = ClassName "fa-object-group"

faObjectUngroup :: ClassName
faObjectUngroup = ClassName "fa-object-ungroup"

faOdnoklassniki :: ClassName
faOdnoklassniki = ClassName "fa-odnoklassniki"

faOdnoklassnikiSquare :: ClassName
faOdnoklassnikiSquare = ClassName "fa-odnoklassniki-square"

faOpencart :: ClassName
faOpencart = ClassName "fa-opencart"

faOpenid :: ClassName
faOpenid = ClassName "fa-openid"

faOpera :: ClassName
faOpera = ClassName "fa-opera"

faOptinMonster :: ClassName
faOptinMonster = ClassName "fa-optin-monster"

faOutdent :: ClassName
faOutdent = ClassName "fa-outdent"

faPagelines :: ClassName
faPagelines = ClassName "fa-pagelines"

faPaintBrush :: ClassName
faPaintBrush = ClassName "fa-paint-brush"

faPaperPlane :: ClassName
faPaperPlane = ClassName "fa-paper-plane"

faPaperPlaneO :: ClassName
faPaperPlaneO = ClassName "fa-paper-plane-o"

faPaperclip :: ClassName
faPaperclip = ClassName "fa-paperclip"

faParagraph :: ClassName
faParagraph = ClassName "fa-paragraph"

faPaste :: ClassName
faPaste = ClassName "fa-paste"

faPause :: ClassName
faPause = ClassName "fa-pause"

faPauseCircle :: ClassName
faPauseCircle = ClassName "fa-pause-circle"

faPauseCircleO :: ClassName
faPauseCircleO = ClassName "fa-pause-circle-o"

faPaw :: ClassName
faPaw = ClassName "fa-paw"

faPaypal :: ClassName
faPaypal = ClassName "fa-paypal"

faPencil :: ClassName
faPencil = ClassName "fa-pencil"

faPencilSquare :: ClassName
faPencilSquare = ClassName "fa-pencil-square"

faPencilSquareO :: ClassName
faPencilSquareO = ClassName "fa-pencil-square-o"

faPercent :: ClassName
faPercent = ClassName "fa-percent"

faPhone :: ClassName
faPhone = ClassName "fa-phone"

faPhoneSquare :: ClassName
faPhoneSquare = ClassName "fa-phone-square"

faPhoto :: ClassName
faPhoto = ClassName "fa-photo"

faPictureO :: ClassName
faPictureO = ClassName "fa-picture-o"

faPieChart :: ClassName
faPieChart = ClassName "fa-pie-chart"

faPiedPiper :: ClassName
faPiedPiper = ClassName "fa-pied-piper"

faPiedPiperAlt :: ClassName
faPiedPiperAlt = ClassName "fa-pied-piper-alt"

faPiedPiperPp :: ClassName
faPiedPiperPp = ClassName "fa-pied-piper-pp"

faPinterest :: ClassName
faPinterest = ClassName "fa-pinterest"

faPinterestP :: ClassName
faPinterestP = ClassName "fa-pinterest-p"

faPinterestSquare :: ClassName
faPinterestSquare = ClassName "fa-pinterest-square"

faPlane :: ClassName
faPlane = ClassName "fa-plane"

faPlay :: ClassName
faPlay = ClassName "fa-play"

faPlayCircle :: ClassName
faPlayCircle = ClassName "fa-play-circle"

faPlayCircleO :: ClassName
faPlayCircleO = ClassName "fa-play-circle-o"

faPlug :: ClassName
faPlug = ClassName "fa-plug"

faPlus :: ClassName
faPlus = ClassName "fa-plus"

faPlusCircle :: ClassName
faPlusCircle = ClassName "fa-plus-circle"

faPlusSquare :: ClassName
faPlusSquare = ClassName "fa-plus-square"

faPlusSquareO :: ClassName
faPlusSquareO = ClassName "fa-plus-square-o"

faPodcast :: ClassName
faPodcast = ClassName "fa-podcast"

faPowerOff :: ClassName
faPowerOff = ClassName "fa-power-off"

faPrint :: ClassName
faPrint = ClassName "fa-print"

faProductHunt :: ClassName
faProductHunt = ClassName "fa-product-hunt"

faPullLeft :: ClassName
faPullLeft = ClassName "fa-pull-left"

faPullRight :: ClassName
faPullRight = ClassName "fa-pull-right"

faPulse :: ClassName
faPulse = ClassName "fa-pulse"

faPuzzlePiece :: ClassName
faPuzzlePiece = ClassName "fa-puzzle-piece"

faQq :: ClassName
faQq = ClassName "fa-qq"

faQrcode :: ClassName
faQrcode = ClassName "fa-qrcode"

faQuestion :: ClassName
faQuestion = ClassName "fa-question"

faQuestionCircle :: ClassName
faQuestionCircle = ClassName "fa-question-circle"

faQuestionCircleO :: ClassName
faQuestionCircleO = ClassName "fa-question-circle-o"

faQuora :: ClassName
faQuora = ClassName "fa-quora"

faQuoteLeft :: ClassName
faQuoteLeft = ClassName "fa-quote-left"

faQuoteRight :: ClassName
faQuoteRight = ClassName "fa-quote-right"

faRa :: ClassName
faRa = ClassName "fa-ra"

faRandom :: ClassName
faRandom = ClassName "fa-random"

faRavelry :: ClassName
faRavelry = ClassName "fa-ravelry"

faRebel :: ClassName
faRebel = ClassName "fa-rebel"

faRecycle :: ClassName
faRecycle = ClassName "fa-recycle"

faReddit :: ClassName
faReddit = ClassName "fa-reddit"

faRedditAlien :: ClassName
faRedditAlien = ClassName "fa-reddit-alien"

faRedditSquare :: ClassName
faRedditSquare = ClassName "fa-reddit-square"

faRefresh :: ClassName
faRefresh = ClassName "fa-refresh"

faRegistered :: ClassName
faRegistered = ClassName "fa-registered"

faRemove :: ClassName
faRemove = ClassName "fa-remove"

faRenren :: ClassName
faRenren = ClassName "fa-renren"

faReorder :: ClassName
faReorder = ClassName "fa-reorder"

faRepeat :: ClassName
faRepeat = ClassName "fa-repeat"

faReply :: ClassName
faReply = ClassName "fa-reply"

faReplyAll :: ClassName
faReplyAll = ClassName "fa-reply-all"

faResistance :: ClassName
faResistance = ClassName "fa-resistance"

faRetweet :: ClassName
faRetweet = ClassName "fa-retweet"

faRmb :: ClassName
faRmb = ClassName "fa-rmb"

faRoad :: ClassName
faRoad = ClassName "fa-road"

faRocket :: ClassName
faRocket = ClassName "fa-rocket"

faRotate180 :: ClassName
faRotate180 = ClassName "fa-rotate-180"

faRotate270 :: ClassName
faRotate270 = ClassName "fa-rotate-270"

faRotate90 :: ClassName
faRotate90 = ClassName "fa-rotate-90"

faRotateLeft :: ClassName
faRotateLeft = ClassName "fa-rotate-left"

faRotateRight :: ClassName
faRotateRight = ClassName "fa-rotate-right"

faRouble :: ClassName
faRouble = ClassName "fa-rouble"

faRss :: ClassName
faRss = ClassName "fa-rss"

faRssSquare :: ClassName
faRssSquare = ClassName "fa-rss-square"

faRub :: ClassName
faRub = ClassName "fa-rub"

faRuble :: ClassName
faRuble = ClassName "fa-ruble"

faRupee :: ClassName
faRupee = ClassName "fa-rupee"

faS15 :: ClassName
faS15 = ClassName "fa-s15"

faSafari :: ClassName
faSafari = ClassName "fa-safari"

faSave :: ClassName
faSave = ClassName "fa-save"

faScissors :: ClassName
faScissors = ClassName "fa-scissors"

faScribd :: ClassName
faScribd = ClassName "fa-scribd"

faSearch :: ClassName
faSearch = ClassName "fa-search"

faSearchMinus :: ClassName
faSearchMinus = ClassName "fa-search-minus"

faSearchPlus :: ClassName
faSearchPlus = ClassName "fa-search-plus"

faSellsy :: ClassName
faSellsy = ClassName "fa-sellsy"

faSend :: ClassName
faSend = ClassName "fa-send"

faSendO :: ClassName
faSendO = ClassName "fa-send-o"

faServer :: ClassName
faServer = ClassName "fa-server"

faShare :: ClassName
faShare = ClassName "fa-share"

faShareAlt :: ClassName
faShareAlt = ClassName "fa-share-alt"

faShareAltSquare :: ClassName
faShareAltSquare = ClassName "fa-share-alt-square"

faShareSquare :: ClassName
faShareSquare = ClassName "fa-share-square"

faShareSquareO :: ClassName
faShareSquareO = ClassName "fa-share-square-o"

faShekel :: ClassName
faShekel = ClassName "fa-shekel"

faSheqel :: ClassName
faSheqel = ClassName "fa-sheqel"

faShield :: ClassName
faShield = ClassName "fa-shield"

faShip :: ClassName
faShip = ClassName "fa-ship"

faShirtsinbulk :: ClassName
faShirtsinbulk = ClassName "fa-shirtsinbulk"

faShoppingBag :: ClassName
faShoppingBag = ClassName "fa-shopping-bag"

faShoppingBasket :: ClassName
faShoppingBasket = ClassName "fa-shopping-basket"

faShoppingCart :: ClassName
faShoppingCart = ClassName "fa-shopping-cart"

faShower :: ClassName
faShower = ClassName "fa-shower"

faSignIn :: ClassName
faSignIn = ClassName "fa-sign-in"

faSignLanguage :: ClassName
faSignLanguage = ClassName "fa-sign-language"

faSignOut :: ClassName
faSignOut = ClassName "fa-sign-out"

faSignal :: ClassName
faSignal = ClassName "fa-signal"

faSigning :: ClassName
faSigning = ClassName "fa-signing"

faSimplybuilt :: ClassName
faSimplybuilt = ClassName "fa-simplybuilt"

faSitemap :: ClassName
faSitemap = ClassName "fa-sitemap"

faSkyatlas :: ClassName
faSkyatlas = ClassName "fa-skyatlas"

faSkype :: ClassName
faSkype = ClassName "fa-skype"

faSlack :: ClassName
faSlack = ClassName "fa-slack"

faSliders :: ClassName
faSliders = ClassName "fa-sliders"

faSlideshare :: ClassName
faSlideshare = ClassName "fa-slideshare"

faSmileO :: ClassName
faSmileO = ClassName "fa-smile-o"

faSnapchat :: ClassName
faSnapchat = ClassName "fa-snapchat"

faSnapchatGhost :: ClassName
faSnapchatGhost = ClassName "fa-snapchat-ghost"

faSnapchatSquare :: ClassName
faSnapchatSquare = ClassName "fa-snapchat-square"

faSnowflakeO :: ClassName
faSnowflakeO = ClassName "fa-snowflake-o"

faSoccerBallO :: ClassName
faSoccerBallO = ClassName "fa-soccer-ball-o"

faSort :: ClassName
faSort = ClassName "fa-sort"

faSortAlphaAsc :: ClassName
faSortAlphaAsc = ClassName "fa-sort-alpha-asc"

faSortAlphaDesc :: ClassName
faSortAlphaDesc = ClassName "fa-sort-alpha-desc"

faSortAmountAsc :: ClassName
faSortAmountAsc = ClassName "fa-sort-amount-asc"

faSortAmountDesc :: ClassName
faSortAmountDesc = ClassName "fa-sort-amount-desc"

faSortAsc :: ClassName
faSortAsc = ClassName "fa-sort-asc"

faSortDesc :: ClassName
faSortDesc = ClassName "fa-sort-desc"

faSortDown :: ClassName
faSortDown = ClassName "fa-sort-down"

faSortNumericAsc :: ClassName
faSortNumericAsc = ClassName "fa-sort-numeric-asc"

faSortNumericDesc :: ClassName
faSortNumericDesc = ClassName "fa-sort-numeric-desc"

faSortUp :: ClassName
faSortUp = ClassName "fa-sort-up"

faSoundcloud :: ClassName
faSoundcloud = ClassName "fa-soundcloud"

faSpaceShuttle :: ClassName
faSpaceShuttle = ClassName "fa-space-shuttle"

faSpin :: ClassName
faSpin = ClassName "fa-spin"

faSpinner :: ClassName
faSpinner = ClassName "fa-spinner"

faSpoon :: ClassName
faSpoon = ClassName "fa-spoon"

faSpotify :: ClassName
faSpotify = ClassName "fa-spotify"

faSquare :: ClassName
faSquare = ClassName "fa-square"

faSquareO :: ClassName
faSquareO = ClassName "fa-square-o"

faStack :: ClassName
faStack = ClassName "fa-stack"

faStack1X :: ClassName
faStack1X = ClassName "fa-stack-1x"

faStack2X :: ClassName
faStack2X = ClassName "fa-stack-2x"

faStackExchange :: ClassName
faStackExchange = ClassName "fa-stack-exchange"

faStackOverflow :: ClassName
faStackOverflow = ClassName "fa-stack-overflow"

faStar :: ClassName
faStar = ClassName "fa-star"

faStarHalf :: ClassName
faStarHalf = ClassName "fa-star-half"

faStarHalfEmpty :: ClassName
faStarHalfEmpty = ClassName "fa-star-half-empty"

faStarHalfFull :: ClassName
faStarHalfFull = ClassName "fa-star-half-full"

faStarHalfO :: ClassName
faStarHalfO = ClassName "fa-star-half-o"

faStarO :: ClassName
faStarO = ClassName "fa-star-o"

faSteam :: ClassName
faSteam = ClassName "fa-steam"

faSteamSquare :: ClassName
faSteamSquare = ClassName "fa-steam-square"

faStepBackward :: ClassName
faStepBackward = ClassName "fa-step-backward"

faStepForward :: ClassName
faStepForward = ClassName "fa-step-forward"

faStethoscope :: ClassName
faStethoscope = ClassName "fa-stethoscope"

faStickyNote :: ClassName
faStickyNote = ClassName "fa-sticky-note"

faStickyNoteO :: ClassName
faStickyNoteO = ClassName "fa-sticky-note-o"

faStop :: ClassName
faStop = ClassName "fa-stop"

faStopCircle :: ClassName
faStopCircle = ClassName "fa-stop-circle"

faStopCircleO :: ClassName
faStopCircleO = ClassName "fa-stop-circle-o"

faStreetView :: ClassName
faStreetView = ClassName "fa-street-view"

faStrikethrough :: ClassName
faStrikethrough = ClassName "fa-strikethrough"

faStumbleupon :: ClassName
faStumbleupon = ClassName "fa-stumbleupon"

faStumbleuponCircle :: ClassName
faStumbleuponCircle = ClassName "fa-stumbleupon-circle"

faSubscript :: ClassName
faSubscript = ClassName "fa-subscript"

faSubway :: ClassName
faSubway = ClassName "fa-subway"

faSuitcase :: ClassName
faSuitcase = ClassName "fa-suitcase"

faSunO :: ClassName
faSunO = ClassName "fa-sun-o"

faSuperpowers :: ClassName
faSuperpowers = ClassName "fa-superpowers"

faSuperscript :: ClassName
faSuperscript = ClassName "fa-superscript"

faSupport :: ClassName
faSupport = ClassName "fa-support"

faTable :: ClassName
faTable = ClassName "fa-table"

faTablet :: ClassName
faTablet = ClassName "fa-tablet"

faTachometer :: ClassName
faTachometer = ClassName "fa-tachometer"

faTag :: ClassName
faTag = ClassName "fa-tag"

faTags :: ClassName
faTags = ClassName "fa-tags"

faTasks :: ClassName
faTasks = ClassName "fa-tasks"

faTaxi :: ClassName
faTaxi = ClassName "fa-taxi"

faTelegram :: ClassName
faTelegram = ClassName "fa-telegram"

faTelevision :: ClassName
faTelevision = ClassName "fa-television"

faTencentWeibo :: ClassName
faTencentWeibo = ClassName "fa-tencent-weibo"

faTerminal :: ClassName
faTerminal = ClassName "fa-terminal"

faTextHeight :: ClassName
faTextHeight = ClassName "fa-text-height"

faTextWidth :: ClassName
faTextWidth = ClassName "fa-text-width"

faTh :: ClassName
faTh = ClassName "fa-th"

faThLarge :: ClassName
faThLarge = ClassName "fa-th-large"

faThList :: ClassName
faThList = ClassName "fa-th-list"

faThemeisle :: ClassName
faThemeisle = ClassName "fa-themeisle"

faThermometer :: ClassName
faThermometer = ClassName "fa-thermometer"

faThermometer0 :: ClassName
faThermometer0 = ClassName "fa-thermometer-0"

faThermometer1 :: ClassName
faThermometer1 = ClassName "fa-thermometer-1"

faThermometer2 :: ClassName
faThermometer2 = ClassName "fa-thermometer-2"

faThermometer3 :: ClassName
faThermometer3 = ClassName "fa-thermometer-3"

faThermometer4 :: ClassName
faThermometer4 = ClassName "fa-thermometer-4"

faThermometerEmpty :: ClassName
faThermometerEmpty = ClassName "fa-thermometer-empty"

faThermometerFull :: ClassName
faThermometerFull = ClassName "fa-thermometer-full"

faThermometerHalf :: ClassName
faThermometerHalf = ClassName "fa-thermometer-half"

faThermometerQuarter :: ClassName
faThermometerQuarter = ClassName "fa-thermometer-quarter"

faThermometerThreeQuarters :: ClassName
faThermometerThreeQuarters = ClassName "fa-thermometer-three-quarters"

faThumbTack :: ClassName
faThumbTack = ClassName "fa-thumb-tack"

faThumbsDown :: ClassName
faThumbsDown = ClassName "fa-thumbs-down"

faThumbsODown :: ClassName
faThumbsODown = ClassName "fa-thumbs-o-down"

faThumbsOUp :: ClassName
faThumbsOUp = ClassName "fa-thumbs-o-up"

faThumbsUp :: ClassName
faThumbsUp = ClassName "fa-thumbs-up"

faTicket :: ClassName
faTicket = ClassName "fa-ticket"

faTimes :: ClassName
faTimes = ClassName "fa-times"

faTimesCircle :: ClassName
faTimesCircle = ClassName "fa-times-circle"

faTimesCircleO :: ClassName
faTimesCircleO = ClassName "fa-times-circle-o"

faTimesRectangle :: ClassName
faTimesRectangle = ClassName "fa-times-rectangle"

faTimesRectangleO :: ClassName
faTimesRectangleO = ClassName "fa-times-rectangle-o"

faTint :: ClassName
faTint = ClassName "fa-tint"

faToggleDown :: ClassName
faToggleDown = ClassName "fa-toggle-down"

faToggleLeft :: ClassName
faToggleLeft = ClassName "fa-toggle-left"

faToggleOff :: ClassName
faToggleOff = ClassName "fa-toggle-off"

faToggleOn :: ClassName
faToggleOn = ClassName "fa-toggle-on"

faToggleRight :: ClassName
faToggleRight = ClassName "fa-toggle-right"

faToggleUp :: ClassName
faToggleUp = ClassName "fa-toggle-up"

faTrademark :: ClassName
faTrademark = ClassName "fa-trademark"

faTrain :: ClassName
faTrain = ClassName "fa-train"

faTransgender :: ClassName
faTransgender = ClassName "fa-transgender"

faTransgenderAlt :: ClassName
faTransgenderAlt = ClassName "fa-transgender-alt"

faTrash :: ClassName
faTrash = ClassName "fa-trash"

faTrashO :: ClassName
faTrashO = ClassName "fa-trash-o"

faTree :: ClassName
faTree = ClassName "fa-tree"

faTrello :: ClassName
faTrello = ClassName "fa-trello"

faTripadvisor :: ClassName
faTripadvisor = ClassName "fa-tripadvisor"

faTrophy :: ClassName
faTrophy = ClassName "fa-trophy"

faTruck :: ClassName
faTruck = ClassName "fa-truck"

faTry :: ClassName
faTry = ClassName "fa-try"

faTty :: ClassName
faTty = ClassName "fa-tty"

faTumblr :: ClassName
faTumblr = ClassName "fa-tumblr"

faTumblrSquare :: ClassName
faTumblrSquare = ClassName "fa-tumblr-square"

faTurkishLira :: ClassName
faTurkishLira = ClassName "fa-turkish-lira"

faTv :: ClassName
faTv = ClassName "fa-tv"

faTwitch :: ClassName
faTwitch = ClassName "fa-twitch"

faTwitter :: ClassName
faTwitter = ClassName "fa-twitter"

faTwitterSquare :: ClassName
faTwitterSquare = ClassName "fa-twitter-square"

faUl :: ClassName
faUl = ClassName "fa-ul"

faUmbrella :: ClassName
faUmbrella = ClassName "fa-umbrella"

faUnderline :: ClassName
faUnderline = ClassName "fa-underline"

faUndo :: ClassName
faUndo = ClassName "fa-undo"

faUniversalAccess :: ClassName
faUniversalAccess = ClassName "fa-universal-access"

faUniversity :: ClassName
faUniversity = ClassName "fa-university"

faUnlink :: ClassName
faUnlink = ClassName "fa-unlink"

faUnlock :: ClassName
faUnlock = ClassName "fa-unlock"

faUnlockAlt :: ClassName
faUnlockAlt = ClassName "fa-unlock-alt"

faUnsorted :: ClassName
faUnsorted = ClassName "fa-unsorted"

faUpload :: ClassName
faUpload = ClassName "fa-upload"

faUsb :: ClassName
faUsb = ClassName "fa-usb"

faUsd :: ClassName
faUsd = ClassName "fa-usd"

faUser :: ClassName
faUser = ClassName "fa-user"

faUserCircle :: ClassName
faUserCircle = ClassName "fa-user-circle"

faUserCircleO :: ClassName
faUserCircleO = ClassName "fa-user-circle-o"

faUserMd :: ClassName
faUserMd = ClassName "fa-user-md"

faUserO :: ClassName
faUserO = ClassName "fa-user-o"

faUserPlus :: ClassName
faUserPlus = ClassName "fa-user-plus"

faUserSecret :: ClassName
faUserSecret = ClassName "fa-user-secret"

faUserTimes :: ClassName
faUserTimes = ClassName "fa-user-times"

faUsers :: ClassName
faUsers = ClassName "fa-users"

faVcard :: ClassName
faVcard = ClassName "fa-vcard"

faVcardO :: ClassName
faVcardO = ClassName "fa-vcard-o"

faVenus :: ClassName
faVenus = ClassName "fa-venus"

faVenusDouble :: ClassName
faVenusDouble = ClassName "fa-venus-double"

faVenusMars :: ClassName
faVenusMars = ClassName "fa-venus-mars"

faViacoin :: ClassName
faViacoin = ClassName "fa-viacoin"

faViadeo :: ClassName
faViadeo = ClassName "fa-viadeo"

faViadeoSquare :: ClassName
faViadeoSquare = ClassName "fa-viadeo-square"

faVideoCamera :: ClassName
faVideoCamera = ClassName "fa-video-camera"

faVimeo :: ClassName
faVimeo = ClassName "fa-vimeo"

faVimeoSquare :: ClassName
faVimeoSquare = ClassName "fa-vimeo-square"

faVine :: ClassName
faVine = ClassName "fa-vine"

faVk :: ClassName
faVk = ClassName "fa-vk"

faVolumeControlPhone :: ClassName
faVolumeControlPhone = ClassName "fa-volume-control-phone"

faVolumeDown :: ClassName
faVolumeDown = ClassName "fa-volume-down"

faVolumeOff :: ClassName
faVolumeOff = ClassName "fa-volume-off"

faVolumeUp :: ClassName
faVolumeUp = ClassName "fa-volume-up"

faWarning :: ClassName
faWarning = ClassName "fa-warning"

faWechat :: ClassName
faWechat = ClassName "fa-wechat"

faWeibo :: ClassName
faWeibo = ClassName "fa-weibo"

faWeixin :: ClassName
faWeixin = ClassName "fa-weixin"

faWhatsapp :: ClassName
faWhatsapp = ClassName "fa-whatsapp"

faWheelchair :: ClassName
faWheelchair = ClassName "fa-wheelchair"

faWheelchairAlt :: ClassName
faWheelchairAlt = ClassName "fa-wheelchair-alt"

faWifi :: ClassName
faWifi = ClassName "fa-wifi"

faWikipediaW :: ClassName
faWikipediaW = ClassName "fa-wikipedia-w"

faWindowClose :: ClassName
faWindowClose = ClassName "fa-window-close"

faWindowCloseO :: ClassName
faWindowCloseO = ClassName "fa-window-close-o"

faWindowMaximize :: ClassName
faWindowMaximize = ClassName "fa-window-maximize"

faWindowMinimize :: ClassName
faWindowMinimize = ClassName "fa-window-minimize"

faWindowRestore :: ClassName
faWindowRestore = ClassName "fa-window-restore"

faWindows :: ClassName
faWindows = ClassName "fa-windows"

faWon :: ClassName
faWon = ClassName "fa-won"

faWordpress :: ClassName
faWordpress = ClassName "fa-wordpress"

faWpbeginner :: ClassName
faWpbeginner = ClassName "fa-wpbeginner"

faWpexplorer :: ClassName
faWpexplorer = ClassName "fa-wpexplorer"

faWpforms :: ClassName
faWpforms = ClassName "fa-wpforms"

faWrench :: ClassName
faWrench = ClassName "fa-wrench"

faXing :: ClassName
faXing = ClassName "fa-xing"

faXingSquare :: ClassName
faXingSquare = ClassName "fa-xing-square"

faYCombinator :: ClassName
faYCombinator = ClassName "fa-y-combinator"

faYCombinatorSquare :: ClassName
faYCombinatorSquare = ClassName "fa-y-combinator-square"

faYahoo :: ClassName
faYahoo = ClassName "fa-yahoo"

faYc :: ClassName
faYc = ClassName "fa-yc"

faYcSquare :: ClassName
faYcSquare = ClassName "fa-yc-square"

faYelp :: ClassName
faYelp = ClassName "fa-yelp"

faYen :: ClassName
faYen = ClassName "fa-yen"

faYoast :: ClassName
faYoast = ClassName "fa-yoast"

faYoutube :: ClassName
faYoutube = ClassName "fa-youtube"

faYoutubePlay :: ClassName
faYoutubePlay = ClassName "fa-youtube-play"

faYoutubeSquare :: ClassName
faYoutubeSquare = ClassName "fa-youtube-square"

