{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Icon.Raw.FlagIcons
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= FlagIcons

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Icon.Raw.FlagIcons where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for flag-icon
flagIcon :: ClassName
flagIcon = ClassName "flag-icon"

-- | A ClassName for flag-icon-ad
flagIconAd :: ClassName
flagIconAd = ClassName "flag-icon-ad"

-- | A ClassName for flag-icon-ae
flagIconAe :: ClassName
flagIconAe = ClassName "flag-icon-ae"

-- | A ClassName for flag-icon-af
flagIconAf :: ClassName
flagIconAf = ClassName "flag-icon-af"

-- | A ClassName for flag-icon-ag
flagIconAg :: ClassName
flagIconAg = ClassName "flag-icon-ag"

-- | A ClassName for flag-icon-ai
flagIconAi :: ClassName
flagIconAi = ClassName "flag-icon-ai"

-- | A ClassName for flag-icon-al
flagIconAl :: ClassName
flagIconAl = ClassName "flag-icon-al"

-- | A ClassName for flag-icon-am
flagIconAm :: ClassName
flagIconAm = ClassName "flag-icon-am"

-- | A ClassName for flag-icon-ao
flagIconAo :: ClassName
flagIconAo = ClassName "flag-icon-ao"

-- | A ClassName for flag-icon-aq
flagIconAq :: ClassName
flagIconAq = ClassName "flag-icon-aq"

-- | A ClassName for flag-icon-ar
flagIconAr :: ClassName
flagIconAr = ClassName "flag-icon-ar"

-- | A ClassName for flag-icon-as
flagIconAs :: ClassName
flagIconAs = ClassName "flag-icon-as"

-- | A ClassName for flag-icon-at
flagIconAt :: ClassName
flagIconAt = ClassName "flag-icon-at"

-- | A ClassName for flag-icon-au
flagIconAu :: ClassName
flagIconAu = ClassName "flag-icon-au"

-- | A ClassName for flag-icon-aw
flagIconAw :: ClassName
flagIconAw = ClassName "flag-icon-aw"

-- | A ClassName for flag-icon-ax
flagIconAx :: ClassName
flagIconAx = ClassName "flag-icon-ax"

-- | A ClassName for flag-icon-az
flagIconAz :: ClassName
flagIconAz = ClassName "flag-icon-az"

-- | A ClassName for flag-icon-ba
flagIconBa :: ClassName
flagIconBa = ClassName "flag-icon-ba"

-- | A ClassName for flag-icon-background
flagIconBackground :: ClassName
flagIconBackground = ClassName "flag-icon-background"

-- | A ClassName for flag-icon-bb
flagIconBb :: ClassName
flagIconBb = ClassName "flag-icon-bb"

-- | A ClassName for flag-icon-bd
flagIconBd :: ClassName
flagIconBd = ClassName "flag-icon-bd"

-- | A ClassName for flag-icon-be
flagIconBe :: ClassName
flagIconBe = ClassName "flag-icon-be"

-- | A ClassName for flag-icon-bf
flagIconBf :: ClassName
flagIconBf = ClassName "flag-icon-bf"

-- | A ClassName for flag-icon-bg
flagIconBg :: ClassName
flagIconBg = ClassName "flag-icon-bg"

-- | A ClassName for flag-icon-bh
flagIconBh :: ClassName
flagIconBh = ClassName "flag-icon-bh"

-- | A ClassName for flag-icon-bi
flagIconBi :: ClassName
flagIconBi = ClassName "flag-icon-bi"

-- | A ClassName for flag-icon-bj
flagIconBj :: ClassName
flagIconBj = ClassName "flag-icon-bj"

-- | A ClassName for flag-icon-bl
flagIconBl :: ClassName
flagIconBl = ClassName "flag-icon-bl"

-- | A ClassName for flag-icon-bm
flagIconBm :: ClassName
flagIconBm = ClassName "flag-icon-bm"

-- | A ClassName for flag-icon-bn
flagIconBn :: ClassName
flagIconBn = ClassName "flag-icon-bn"

-- | A ClassName for flag-icon-bo
flagIconBo :: ClassName
flagIconBo = ClassName "flag-icon-bo"

-- | A ClassName for flag-icon-bq
flagIconBq :: ClassName
flagIconBq = ClassName "flag-icon-bq"

-- | A ClassName for flag-icon-br
flagIconBr :: ClassName
flagIconBr = ClassName "flag-icon-br"

-- | A ClassName for flag-icon-bs
flagIconBs :: ClassName
flagIconBs = ClassName "flag-icon-bs"

-- | A ClassName for flag-icon-bt
flagIconBt :: ClassName
flagIconBt = ClassName "flag-icon-bt"

-- | A ClassName for flag-icon-bv
flagIconBv :: ClassName
flagIconBv = ClassName "flag-icon-bv"

-- | A ClassName for flag-icon-bw
flagIconBw :: ClassName
flagIconBw = ClassName "flag-icon-bw"

-- | A ClassName for flag-icon-by
flagIconBy :: ClassName
flagIconBy = ClassName "flag-icon-by"

-- | A ClassName for flag-icon-bz
flagIconBz :: ClassName
flagIconBz = ClassName "flag-icon-bz"

-- | A ClassName for flag-icon-ca
flagIconCa :: ClassName
flagIconCa = ClassName "flag-icon-ca"

-- | A ClassName for flag-icon-cc
flagIconCc :: ClassName
flagIconCc = ClassName "flag-icon-cc"

-- | A ClassName for flag-icon-cd
flagIconCd :: ClassName
flagIconCd = ClassName "flag-icon-cd"

-- | A ClassName for flag-icon-cf
flagIconCf :: ClassName
flagIconCf = ClassName "flag-icon-cf"

-- | A ClassName for flag-icon-cg
flagIconCg :: ClassName
flagIconCg = ClassName "flag-icon-cg"

-- | A ClassName for flag-icon-ch
flagIconCh :: ClassName
flagIconCh = ClassName "flag-icon-ch"

-- | A ClassName for flag-icon-ci
flagIconCi :: ClassName
flagIconCi = ClassName "flag-icon-ci"

-- | A ClassName for flag-icon-ck
flagIconCk :: ClassName
flagIconCk = ClassName "flag-icon-ck"

-- | A ClassName for flag-icon-cl
flagIconCl :: ClassName
flagIconCl = ClassName "flag-icon-cl"

-- | A ClassName for flag-icon-cm
flagIconCm :: ClassName
flagIconCm = ClassName "flag-icon-cm"

-- | A ClassName for flag-icon-cn
flagIconCn :: ClassName
flagIconCn = ClassName "flag-icon-cn"

-- | A ClassName for flag-icon-co
flagIconCo :: ClassName
flagIconCo = ClassName "flag-icon-co"

-- | A ClassName for flag-icon-cr
flagIconCr :: ClassName
flagIconCr = ClassName "flag-icon-cr"

-- | A ClassName for flag-icon-cu
flagIconCu :: ClassName
flagIconCu = ClassName "flag-icon-cu"

-- | A ClassName for flag-icon-cv
flagIconCv :: ClassName
flagIconCv = ClassName "flag-icon-cv"

-- | A ClassName for flag-icon-cw
flagIconCw :: ClassName
flagIconCw = ClassName "flag-icon-cw"

-- | A ClassName for flag-icon-cx
flagIconCx :: ClassName
flagIconCx = ClassName "flag-icon-cx"

-- | A ClassName for flag-icon-cy
flagIconCy :: ClassName
flagIconCy = ClassName "flag-icon-cy"

-- | A ClassName for flag-icon-cz
flagIconCz :: ClassName
flagIconCz = ClassName "flag-icon-cz"

-- | A ClassName for flag-icon-de
flagIconDe :: ClassName
flagIconDe = ClassName "flag-icon-de"

-- | A ClassName for flag-icon-dj
flagIconDj :: ClassName
flagIconDj = ClassName "flag-icon-dj"

-- | A ClassName for flag-icon-dk
flagIconDk :: ClassName
flagIconDk = ClassName "flag-icon-dk"

-- | A ClassName for flag-icon-dm
flagIconDm :: ClassName
flagIconDm = ClassName "flag-icon-dm"

-- | A ClassName for flag-icon-do
flagIconDo :: ClassName
flagIconDo = ClassName "flag-icon-do"

-- | A ClassName for flag-icon-dz
flagIconDz :: ClassName
flagIconDz = ClassName "flag-icon-dz"

-- | A ClassName for flag-icon-ec
flagIconEc :: ClassName
flagIconEc = ClassName "flag-icon-ec"

-- | A ClassName for flag-icon-ee
flagIconEe :: ClassName
flagIconEe = ClassName "flag-icon-ee"

-- | A ClassName for flag-icon-eg
flagIconEg :: ClassName
flagIconEg = ClassName "flag-icon-eg"

-- | A ClassName for flag-icon-eh
flagIconEh :: ClassName
flagIconEh = ClassName "flag-icon-eh"

-- | A ClassName for flag-icon-er
flagIconEr :: ClassName
flagIconEr = ClassName "flag-icon-er"

-- | A ClassName for flag-icon-es
flagIconEs :: ClassName
flagIconEs = ClassName "flag-icon-es"

-- | A ClassName for flag-icon-es-ct
flagIconEsCt :: ClassName
flagIconEsCt = ClassName "flag-icon-es-ct"

-- | A ClassName for flag-icon-et
flagIconEt :: ClassName
flagIconEt = ClassName "flag-icon-et"

-- | A ClassName for flag-icon-eu
flagIconEu :: ClassName
flagIconEu = ClassName "flag-icon-eu"

-- | A ClassName for flag-icon-fi
flagIconFi :: ClassName
flagIconFi = ClassName "flag-icon-fi"

-- | A ClassName for flag-icon-fj
flagIconFj :: ClassName
flagIconFj = ClassName "flag-icon-fj"

-- | A ClassName for flag-icon-fk
flagIconFk :: ClassName
flagIconFk = ClassName "flag-icon-fk"

-- | A ClassName for flag-icon-fm
flagIconFm :: ClassName
flagIconFm = ClassName "flag-icon-fm"

-- | A ClassName for flag-icon-fo
flagIconFo :: ClassName
flagIconFo = ClassName "flag-icon-fo"

-- | A ClassName for flag-icon-fr
flagIconFr :: ClassName
flagIconFr = ClassName "flag-icon-fr"

-- | A ClassName for flag-icon-ga
flagIconGa :: ClassName
flagIconGa = ClassName "flag-icon-ga"

-- | A ClassName for flag-icon-gb
flagIconGb :: ClassName
flagIconGb = ClassName "flag-icon-gb"

-- | A ClassName for flag-icon-gb-eng
flagIconGbEng :: ClassName
flagIconGbEng = ClassName "flag-icon-gb-eng"

-- | A ClassName for flag-icon-gb-nir
flagIconGbNir :: ClassName
flagIconGbNir = ClassName "flag-icon-gb-nir"

-- | A ClassName for flag-icon-gb-sct
flagIconGbSct :: ClassName
flagIconGbSct = ClassName "flag-icon-gb-sct"

-- | A ClassName for flag-icon-gb-wls
flagIconGbWls :: ClassName
flagIconGbWls = ClassName "flag-icon-gb-wls"

-- | A ClassName for flag-icon-gd
flagIconGd :: ClassName
flagIconGd = ClassName "flag-icon-gd"

-- | A ClassName for flag-icon-ge
flagIconGe :: ClassName
flagIconGe = ClassName "flag-icon-ge"

-- | A ClassName for flag-icon-gf
flagIconGf :: ClassName
flagIconGf = ClassName "flag-icon-gf"

-- | A ClassName for flag-icon-gg
flagIconGg :: ClassName
flagIconGg = ClassName "flag-icon-gg"

-- | A ClassName for flag-icon-gh
flagIconGh :: ClassName
flagIconGh = ClassName "flag-icon-gh"

-- | A ClassName for flag-icon-gi
flagIconGi :: ClassName
flagIconGi = ClassName "flag-icon-gi"

-- | A ClassName for flag-icon-gl
flagIconGl :: ClassName
flagIconGl = ClassName "flag-icon-gl"

-- | A ClassName for flag-icon-gm
flagIconGm :: ClassName
flagIconGm = ClassName "flag-icon-gm"

-- | A ClassName for flag-icon-gn
flagIconGn :: ClassName
flagIconGn = ClassName "flag-icon-gn"

-- | A ClassName for flag-icon-gp
flagIconGp :: ClassName
flagIconGp = ClassName "flag-icon-gp"

-- | A ClassName for flag-icon-gq
flagIconGq :: ClassName
flagIconGq = ClassName "flag-icon-gq"

-- | A ClassName for flag-icon-gr
flagIconGr :: ClassName
flagIconGr = ClassName "flag-icon-gr"

-- | A ClassName for flag-icon-gs
flagIconGs :: ClassName
flagIconGs = ClassName "flag-icon-gs"

-- | A ClassName for flag-icon-gt
flagIconGt :: ClassName
flagIconGt = ClassName "flag-icon-gt"

-- | A ClassName for flag-icon-gu
flagIconGu :: ClassName
flagIconGu = ClassName "flag-icon-gu"

-- | A ClassName for flag-icon-gw
flagIconGw :: ClassName
flagIconGw = ClassName "flag-icon-gw"

-- | A ClassName for flag-icon-gy
flagIconGy :: ClassName
flagIconGy = ClassName "flag-icon-gy"

-- | A ClassName for flag-icon-hk
flagIconHk :: ClassName
flagIconHk = ClassName "flag-icon-hk"

-- | A ClassName for flag-icon-hm
flagIconHm :: ClassName
flagIconHm = ClassName "flag-icon-hm"

-- | A ClassName for flag-icon-hn
flagIconHn :: ClassName
flagIconHn = ClassName "flag-icon-hn"

-- | A ClassName for flag-icon-hr
flagIconHr :: ClassName
flagIconHr = ClassName "flag-icon-hr"

-- | A ClassName for flag-icon-ht
flagIconHt :: ClassName
flagIconHt = ClassName "flag-icon-ht"

-- | A ClassName for flag-icon-hu
flagIconHu :: ClassName
flagIconHu = ClassName "flag-icon-hu"

-- | A ClassName for flag-icon-id
flagIconId :: ClassName
flagIconId = ClassName "flag-icon-id"

-- | A ClassName for flag-icon-ie
flagIconIe :: ClassName
flagIconIe = ClassName "flag-icon-ie"

-- | A ClassName for flag-icon-il
flagIconIl :: ClassName
flagIconIl = ClassName "flag-icon-il"

-- | A ClassName for flag-icon-im
flagIconIm :: ClassName
flagIconIm = ClassName "flag-icon-im"

-- | A ClassName for flag-icon-in
flagIconIn :: ClassName
flagIconIn = ClassName "flag-icon-in"

-- | A ClassName for flag-icon-io
flagIconIo :: ClassName
flagIconIo = ClassName "flag-icon-io"

-- | A ClassName for flag-icon-iq
flagIconIq :: ClassName
flagIconIq = ClassName "flag-icon-iq"

-- | A ClassName for flag-icon-ir
flagIconIr :: ClassName
flagIconIr = ClassName "flag-icon-ir"

-- | A ClassName for flag-icon-is
flagIconIs :: ClassName
flagIconIs = ClassName "flag-icon-is"

-- | A ClassName for flag-icon-it
flagIconIt :: ClassName
flagIconIt = ClassName "flag-icon-it"

-- | A ClassName for flag-icon-je
flagIconJe :: ClassName
flagIconJe = ClassName "flag-icon-je"

-- | A ClassName for flag-icon-jm
flagIconJm :: ClassName
flagIconJm = ClassName "flag-icon-jm"

-- | A ClassName for flag-icon-jo
flagIconJo :: ClassName
flagIconJo = ClassName "flag-icon-jo"

-- | A ClassName for flag-icon-jp
flagIconJp :: ClassName
flagIconJp = ClassName "flag-icon-jp"

-- | A ClassName for flag-icon-ke
flagIconKe :: ClassName
flagIconKe = ClassName "flag-icon-ke"

-- | A ClassName for flag-icon-kg
flagIconKg :: ClassName
flagIconKg = ClassName "flag-icon-kg"

-- | A ClassName for flag-icon-kh
flagIconKh :: ClassName
flagIconKh = ClassName "flag-icon-kh"

-- | A ClassName for flag-icon-ki
flagIconKi :: ClassName
flagIconKi = ClassName "flag-icon-ki"

-- | A ClassName for flag-icon-km
flagIconKm :: ClassName
flagIconKm = ClassName "flag-icon-km"

-- | A ClassName for flag-icon-kn
flagIconKn :: ClassName
flagIconKn = ClassName "flag-icon-kn"

-- | A ClassName for flag-icon-kp
flagIconKp :: ClassName
flagIconKp = ClassName "flag-icon-kp"

-- | A ClassName for flag-icon-kr
flagIconKr :: ClassName
flagIconKr = ClassName "flag-icon-kr"

-- | A ClassName for flag-icon-kw
flagIconKw :: ClassName
flagIconKw = ClassName "flag-icon-kw"

-- | A ClassName for flag-icon-ky
flagIconKy :: ClassName
flagIconKy = ClassName "flag-icon-ky"

-- | A ClassName for flag-icon-kz
flagIconKz :: ClassName
flagIconKz = ClassName "flag-icon-kz"

-- | A ClassName for flag-icon-la
flagIconLa :: ClassName
flagIconLa = ClassName "flag-icon-la"

-- | A ClassName for flag-icon-lb
flagIconLb :: ClassName
flagIconLb = ClassName "flag-icon-lb"

-- | A ClassName for flag-icon-lc
flagIconLc :: ClassName
flagIconLc = ClassName "flag-icon-lc"

-- | A ClassName for flag-icon-li
flagIconLi :: ClassName
flagIconLi = ClassName "flag-icon-li"

-- | A ClassName for flag-icon-lk
flagIconLk :: ClassName
flagIconLk = ClassName "flag-icon-lk"

-- | A ClassName for flag-icon-lr
flagIconLr :: ClassName
flagIconLr = ClassName "flag-icon-lr"

-- | A ClassName for flag-icon-ls
flagIconLs :: ClassName
flagIconLs = ClassName "flag-icon-ls"

-- | A ClassName for flag-icon-lt
flagIconLt :: ClassName
flagIconLt = ClassName "flag-icon-lt"

-- | A ClassName for flag-icon-lu
flagIconLu :: ClassName
flagIconLu = ClassName "flag-icon-lu"

-- | A ClassName for flag-icon-lv
flagIconLv :: ClassName
flagIconLv = ClassName "flag-icon-lv"

-- | A ClassName for flag-icon-ly
flagIconLy :: ClassName
flagIconLy = ClassName "flag-icon-ly"

-- | A ClassName for flag-icon-ma
flagIconMa :: ClassName
flagIconMa = ClassName "flag-icon-ma"

-- | A ClassName for flag-icon-mc
flagIconMc :: ClassName
flagIconMc = ClassName "flag-icon-mc"

-- | A ClassName for flag-icon-md
flagIconMd :: ClassName
flagIconMd = ClassName "flag-icon-md"

-- | A ClassName for flag-icon-me
flagIconMe :: ClassName
flagIconMe = ClassName "flag-icon-me"

-- | A ClassName for flag-icon-mf
flagIconMf :: ClassName
flagIconMf = ClassName "flag-icon-mf"

-- | A ClassName for flag-icon-mg
flagIconMg :: ClassName
flagIconMg = ClassName "flag-icon-mg"

-- | A ClassName for flag-icon-mh
flagIconMh :: ClassName
flagIconMh = ClassName "flag-icon-mh"

-- | A ClassName for flag-icon-mk
flagIconMk :: ClassName
flagIconMk = ClassName "flag-icon-mk"

-- | A ClassName for flag-icon-ml
flagIconMl :: ClassName
flagIconMl = ClassName "flag-icon-ml"

-- | A ClassName for flag-icon-mm
flagIconMm :: ClassName
flagIconMm = ClassName "flag-icon-mm"

-- | A ClassName for flag-icon-mn
flagIconMn :: ClassName
flagIconMn = ClassName "flag-icon-mn"

-- | A ClassName for flag-icon-mo
flagIconMo :: ClassName
flagIconMo = ClassName "flag-icon-mo"

-- | A ClassName for flag-icon-mp
flagIconMp :: ClassName
flagIconMp = ClassName "flag-icon-mp"

-- | A ClassName for flag-icon-mq
flagIconMq :: ClassName
flagIconMq = ClassName "flag-icon-mq"

-- | A ClassName for flag-icon-mr
flagIconMr :: ClassName
flagIconMr = ClassName "flag-icon-mr"

-- | A ClassName for flag-icon-ms
flagIconMs :: ClassName
flagIconMs = ClassName "flag-icon-ms"

-- | A ClassName for flag-icon-mt
flagIconMt :: ClassName
flagIconMt = ClassName "flag-icon-mt"

-- | A ClassName for flag-icon-mu
flagIconMu :: ClassName
flagIconMu = ClassName "flag-icon-mu"

-- | A ClassName for flag-icon-mv
flagIconMv :: ClassName
flagIconMv = ClassName "flag-icon-mv"

-- | A ClassName for flag-icon-mw
flagIconMw :: ClassName
flagIconMw = ClassName "flag-icon-mw"

-- | A ClassName for flag-icon-mx
flagIconMx :: ClassName
flagIconMx = ClassName "flag-icon-mx"

-- | A ClassName for flag-icon-my
flagIconMy :: ClassName
flagIconMy = ClassName "flag-icon-my"

-- | A ClassName for flag-icon-mz
flagIconMz :: ClassName
flagIconMz = ClassName "flag-icon-mz"

-- | A ClassName for flag-icon-na
flagIconNa :: ClassName
flagIconNa = ClassName "flag-icon-na"

-- | A ClassName for flag-icon-nc
flagIconNc :: ClassName
flagIconNc = ClassName "flag-icon-nc"

-- | A ClassName for flag-icon-ne
flagIconNe :: ClassName
flagIconNe = ClassName "flag-icon-ne"

-- | A ClassName for flag-icon-nf
flagIconNf :: ClassName
flagIconNf = ClassName "flag-icon-nf"

-- | A ClassName for flag-icon-ng
flagIconNg :: ClassName
flagIconNg = ClassName "flag-icon-ng"

-- | A ClassName for flag-icon-ni
flagIconNi :: ClassName
flagIconNi = ClassName "flag-icon-ni"

-- | A ClassName for flag-icon-nl
flagIconNl :: ClassName
flagIconNl = ClassName "flag-icon-nl"

-- | A ClassName for flag-icon-no
flagIconNo :: ClassName
flagIconNo = ClassName "flag-icon-no"

-- | A ClassName for flag-icon-np
flagIconNp :: ClassName
flagIconNp = ClassName "flag-icon-np"

-- | A ClassName for flag-icon-nr
flagIconNr :: ClassName
flagIconNr = ClassName "flag-icon-nr"

-- | A ClassName for flag-icon-nu
flagIconNu :: ClassName
flagIconNu = ClassName "flag-icon-nu"

-- | A ClassName for flag-icon-nz
flagIconNz :: ClassName
flagIconNz = ClassName "flag-icon-nz"

-- | A ClassName for flag-icon-om
flagIconOm :: ClassName
flagIconOm = ClassName "flag-icon-om"

-- | A ClassName for flag-icon-pa
flagIconPa :: ClassName
flagIconPa = ClassName "flag-icon-pa"

-- | A ClassName for flag-icon-pe
flagIconPe :: ClassName
flagIconPe = ClassName "flag-icon-pe"

-- | A ClassName for flag-icon-pf
flagIconPf :: ClassName
flagIconPf = ClassName "flag-icon-pf"

-- | A ClassName for flag-icon-pg
flagIconPg :: ClassName
flagIconPg = ClassName "flag-icon-pg"

-- | A ClassName for flag-icon-ph
flagIconPh :: ClassName
flagIconPh = ClassName "flag-icon-ph"

-- | A ClassName for flag-icon-pk
flagIconPk :: ClassName
flagIconPk = ClassName "flag-icon-pk"

-- | A ClassName for flag-icon-pl
flagIconPl :: ClassName
flagIconPl = ClassName "flag-icon-pl"

-- | A ClassName for flag-icon-pm
flagIconPm :: ClassName
flagIconPm = ClassName "flag-icon-pm"

-- | A ClassName for flag-icon-pn
flagIconPn :: ClassName
flagIconPn = ClassName "flag-icon-pn"

-- | A ClassName for flag-icon-pr
flagIconPr :: ClassName
flagIconPr = ClassName "flag-icon-pr"

-- | A ClassName for flag-icon-ps
flagIconPs :: ClassName
flagIconPs = ClassName "flag-icon-ps"

-- | A ClassName for flag-icon-pt
flagIconPt :: ClassName
flagIconPt = ClassName "flag-icon-pt"

-- | A ClassName for flag-icon-pw
flagIconPw :: ClassName
flagIconPw = ClassName "flag-icon-pw"

-- | A ClassName for flag-icon-py
flagIconPy :: ClassName
flagIconPy = ClassName "flag-icon-py"

-- | A ClassName for flag-icon-qa
flagIconQa :: ClassName
flagIconQa = ClassName "flag-icon-qa"

-- | A ClassName for flag-icon-re
flagIconRe :: ClassName
flagIconRe = ClassName "flag-icon-re"

-- | A ClassName for flag-icon-ro
flagIconRo :: ClassName
flagIconRo = ClassName "flag-icon-ro"

-- | A ClassName for flag-icon-rs
flagIconRs :: ClassName
flagIconRs = ClassName "flag-icon-rs"

-- | A ClassName for flag-icon-ru
flagIconRu :: ClassName
flagIconRu = ClassName "flag-icon-ru"

-- | A ClassName for flag-icon-rw
flagIconRw :: ClassName
flagIconRw = ClassName "flag-icon-rw"

-- | A ClassName for flag-icon-sa
flagIconSa :: ClassName
flagIconSa = ClassName "flag-icon-sa"

-- | A ClassName for flag-icon-sb
flagIconSb :: ClassName
flagIconSb = ClassName "flag-icon-sb"

-- | A ClassName for flag-icon-sc
flagIconSc :: ClassName
flagIconSc = ClassName "flag-icon-sc"

-- | A ClassName for flag-icon-sd
flagIconSd :: ClassName
flagIconSd = ClassName "flag-icon-sd"

-- | A ClassName for flag-icon-se
flagIconSe :: ClassName
flagIconSe = ClassName "flag-icon-se"

-- | A ClassName for flag-icon-sg
flagIconSg :: ClassName
flagIconSg = ClassName "flag-icon-sg"

-- | A ClassName for flag-icon-sh
flagIconSh :: ClassName
flagIconSh = ClassName "flag-icon-sh"

-- | A ClassName for flag-icon-si
flagIconSi :: ClassName
flagIconSi = ClassName "flag-icon-si"

-- | A ClassName for flag-icon-sj
flagIconSj :: ClassName
flagIconSj = ClassName "flag-icon-sj"

-- | A ClassName for flag-icon-sk
flagIconSk :: ClassName
flagIconSk = ClassName "flag-icon-sk"

-- | A ClassName for flag-icon-sl
flagIconSl :: ClassName
flagIconSl = ClassName "flag-icon-sl"

-- | A ClassName for flag-icon-sm
flagIconSm :: ClassName
flagIconSm = ClassName "flag-icon-sm"

-- | A ClassName for flag-icon-sn
flagIconSn :: ClassName
flagIconSn = ClassName "flag-icon-sn"

-- | A ClassName for flag-icon-so
flagIconSo :: ClassName
flagIconSo = ClassName "flag-icon-so"

-- | A ClassName for flag-icon-squared
flagIconSquared :: ClassName
flagIconSquared = ClassName "flag-icon-squared"

-- | A ClassName for flag-icon-sr
flagIconSr :: ClassName
flagIconSr = ClassName "flag-icon-sr"

-- | A ClassName for flag-icon-ss
flagIconSs :: ClassName
flagIconSs = ClassName "flag-icon-ss"

-- | A ClassName for flag-icon-st
flagIconSt :: ClassName
flagIconSt = ClassName "flag-icon-st"

-- | A ClassName for flag-icon-sv
flagIconSv :: ClassName
flagIconSv = ClassName "flag-icon-sv"

-- | A ClassName for flag-icon-sx
flagIconSx :: ClassName
flagIconSx = ClassName "flag-icon-sx"

-- | A ClassName for flag-icon-sy
flagIconSy :: ClassName
flagIconSy = ClassName "flag-icon-sy"

-- | A ClassName for flag-icon-sz
flagIconSz :: ClassName
flagIconSz = ClassName "flag-icon-sz"

-- | A ClassName for flag-icon-tc
flagIconTc :: ClassName
flagIconTc = ClassName "flag-icon-tc"

-- | A ClassName for flag-icon-td
flagIconTd :: ClassName
flagIconTd = ClassName "flag-icon-td"

-- | A ClassName for flag-icon-tf
flagIconTf :: ClassName
flagIconTf = ClassName "flag-icon-tf"

-- | A ClassName for flag-icon-tg
flagIconTg :: ClassName
flagIconTg = ClassName "flag-icon-tg"

-- | A ClassName for flag-icon-th
flagIconTh :: ClassName
flagIconTh = ClassName "flag-icon-th"

-- | A ClassName for flag-icon-tj
flagIconTj :: ClassName
flagIconTj = ClassName "flag-icon-tj"

-- | A ClassName for flag-icon-tk
flagIconTk :: ClassName
flagIconTk = ClassName "flag-icon-tk"

-- | A ClassName for flag-icon-tl
flagIconTl :: ClassName
flagIconTl = ClassName "flag-icon-tl"

-- | A ClassName for flag-icon-tm
flagIconTm :: ClassName
flagIconTm = ClassName "flag-icon-tm"

-- | A ClassName for flag-icon-tn
flagIconTn :: ClassName
flagIconTn = ClassName "flag-icon-tn"

-- | A ClassName for flag-icon-to
flagIconTo :: ClassName
flagIconTo = ClassName "flag-icon-to"

-- | A ClassName for flag-icon-tr
flagIconTr :: ClassName
flagIconTr = ClassName "flag-icon-tr"

-- | A ClassName for flag-icon-tt
flagIconTt :: ClassName
flagIconTt = ClassName "flag-icon-tt"

-- | A ClassName for flag-icon-tv
flagIconTv :: ClassName
flagIconTv = ClassName "flag-icon-tv"

-- | A ClassName for flag-icon-tw
flagIconTw :: ClassName
flagIconTw = ClassName "flag-icon-tw"

-- | A ClassName for flag-icon-tz
flagIconTz :: ClassName
flagIconTz = ClassName "flag-icon-tz"

-- | A ClassName for flag-icon-ua
flagIconUa :: ClassName
flagIconUa = ClassName "flag-icon-ua"

-- | A ClassName for flag-icon-ug
flagIconUg :: ClassName
flagIconUg = ClassName "flag-icon-ug"

-- | A ClassName for flag-icon-um
flagIconUm :: ClassName
flagIconUm = ClassName "flag-icon-um"

-- | A ClassName for flag-icon-un
flagIconUn :: ClassName
flagIconUn = ClassName "flag-icon-un"

-- | A ClassName for flag-icon-us
flagIconUs :: ClassName
flagIconUs = ClassName "flag-icon-us"

-- | A ClassName for flag-icon-uy
flagIconUy :: ClassName
flagIconUy = ClassName "flag-icon-uy"

-- | A ClassName for flag-icon-uz
flagIconUz :: ClassName
flagIconUz = ClassName "flag-icon-uz"

-- | A ClassName for flag-icon-va
flagIconVa :: ClassName
flagIconVa = ClassName "flag-icon-va"

-- | A ClassName for flag-icon-vc
flagIconVc :: ClassName
flagIconVc = ClassName "flag-icon-vc"

-- | A ClassName for flag-icon-ve
flagIconVe :: ClassName
flagIconVe = ClassName "flag-icon-ve"

-- | A ClassName for flag-icon-vg
flagIconVg :: ClassName
flagIconVg = ClassName "flag-icon-vg"

-- | A ClassName for flag-icon-vi
flagIconVi :: ClassName
flagIconVi = ClassName "flag-icon-vi"

-- | A ClassName for flag-icon-vn
flagIconVn :: ClassName
flagIconVn = ClassName "flag-icon-vn"

-- | A ClassName for flag-icon-vu
flagIconVu :: ClassName
flagIconVu = ClassName "flag-icon-vu"

-- | A ClassName for flag-icon-wf
flagIconWf :: ClassName
flagIconWf = ClassName "flag-icon-wf"

-- | A ClassName for flag-icon-ws
flagIconWs :: ClassName
flagIconWs = ClassName "flag-icon-ws"

-- | A ClassName for flag-icon-ye
flagIconYe :: ClassName
flagIconYe = ClassName "flag-icon-ye"

-- | A ClassName for flag-icon-yt
flagIconYt :: ClassName
flagIconYt = ClassName "flag-icon-yt"

-- | A ClassName for flag-icon-za
flagIconZa :: ClassName
flagIconZa = ClassName "flag-icon-za"

-- | A ClassName for flag-icon-zm
flagIconZm :: ClassName
flagIconZm = ClassName "flag-icon-zm"

-- | A ClassName for flag-icon-zw
flagIconZw :: ClassName
flagIconZw = ClassName "flag-icon-zw"

