{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Icon.Raw.IcoMoon
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= IcoMoon

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Icon.Raw.IcoMoon where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for icon
icon :: ClassName
icon = ClassName "icon"

-- | A ClassName for icon-500px
icon500Px :: ClassName
icon500Px = ClassName "icon-500px"

-- | A ClassName for icon-accessibility
iconAccessibility :: ClassName
iconAccessibility = ClassName "icon-accessibility"

-- | A ClassName for icon-address-book
iconAddressBook :: ClassName
iconAddressBook = ClassName "icon-address-book"

-- | A ClassName for icon-aid-kit
iconAidKit :: ClassName
iconAidKit = ClassName "icon-aid-kit"

-- | A ClassName for icon-airplane
iconAirplane :: ClassName
iconAirplane = ClassName "icon-airplane"

-- | A ClassName for icon-alarm
iconAlarm :: ClassName
iconAlarm = ClassName "icon-alarm"

-- | A ClassName for icon-amazon
iconAmazon :: ClassName
iconAmazon = ClassName "icon-amazon"

-- | A ClassName for icon-android
iconAndroid :: ClassName
iconAndroid = ClassName "icon-android"

-- | A ClassName for icon-angry
iconAngry :: ClassName
iconAngry = ClassName "icon-angry"

-- | A ClassName for icon-angry2
iconAngry2 :: ClassName
iconAngry2 = ClassName "icon-angry2"

-- | A ClassName for icon-appleinc
iconAppleinc :: ClassName
iconAppleinc = ClassName "icon-appleinc"

-- | A ClassName for icon-arrow-down
iconArrowDown :: ClassName
iconArrowDown = ClassName "icon-arrow-down"

-- | A ClassName for icon-arrow-down2
iconArrowDown2 :: ClassName
iconArrowDown2 = ClassName "icon-arrow-down2"

-- | A ClassName for icon-arrow-down-left
iconArrowDownLeft :: ClassName
iconArrowDownLeft = ClassName "icon-arrow-down-left"

-- | A ClassName for icon-arrow-down-left2
iconArrowDownLeft2 :: ClassName
iconArrowDownLeft2 = ClassName "icon-arrow-down-left2"

-- | A ClassName for icon-arrow-down-right
iconArrowDownRight :: ClassName
iconArrowDownRight = ClassName "icon-arrow-down-right"

-- | A ClassName for icon-arrow-down-right2
iconArrowDownRight2 :: ClassName
iconArrowDownRight2 = ClassName "icon-arrow-down-right2"

-- | A ClassName for icon-arrow-left
iconArrowLeft :: ClassName
iconArrowLeft = ClassName "icon-arrow-left"

-- | A ClassName for icon-arrow-left2
iconArrowLeft2 :: ClassName
iconArrowLeft2 = ClassName "icon-arrow-left2"

-- | A ClassName for icon-arrow-right
iconArrowRight :: ClassName
iconArrowRight = ClassName "icon-arrow-right"

-- | A ClassName for icon-arrow-right2
iconArrowRight2 :: ClassName
iconArrowRight2 = ClassName "icon-arrow-right2"

-- | A ClassName for icon-arrow-up
iconArrowUp :: ClassName
iconArrowUp = ClassName "icon-arrow-up"

-- | A ClassName for icon-arrow-up2
iconArrowUp2 :: ClassName
iconArrowUp2 = ClassName "icon-arrow-up2"

-- | A ClassName for icon-arrow-up-left
iconArrowUpLeft :: ClassName
iconArrowUpLeft = ClassName "icon-arrow-up-left"

-- | A ClassName for icon-arrow-up-left2
iconArrowUpLeft2 :: ClassName
iconArrowUpLeft2 = ClassName "icon-arrow-up-left2"

-- | A ClassName for icon-arrow-up-right
iconArrowUpRight :: ClassName
iconArrowUpRight = ClassName "icon-arrow-up-right"

-- | A ClassName for icon-arrow-up-right2
iconArrowUpRight2 :: ClassName
iconArrowUpRight2 = ClassName "icon-arrow-up-right2"

-- | A ClassName for icon-attachment
iconAttachment :: ClassName
iconAttachment = ClassName "icon-attachment"

-- | A ClassName for icon-backward
iconBackward :: ClassName
iconBackward = ClassName "icon-backward"

-- | A ClassName for icon-backward2
iconBackward2 :: ClassName
iconBackward2 = ClassName "icon-backward2"

-- | A ClassName for icon-baffled
iconBaffled :: ClassName
iconBaffled = ClassName "icon-baffled"

-- | A ClassName for icon-baffled2
iconBaffled2 :: ClassName
iconBaffled2 = ClassName "icon-baffled2"

-- | A ClassName for icon-barcode
iconBarcode :: ClassName
iconBarcode = ClassName "icon-barcode"

-- | A ClassName for icon-basecamp
iconBasecamp :: ClassName
iconBasecamp = ClassName "icon-basecamp"

-- | A ClassName for icon-behance
iconBehance :: ClassName
iconBehance = ClassName "icon-behance"

-- | A ClassName for icon-behance2
iconBehance2 :: ClassName
iconBehance2 = ClassName "icon-behance2"

-- | A ClassName for icon-bell
iconBell :: ClassName
iconBell = ClassName "icon-bell"

-- | A ClassName for icon-bin
iconBin :: ClassName
iconBin = ClassName "icon-bin"

-- | A ClassName for icon-bin2
iconBin2 :: ClassName
iconBin2 = ClassName "icon-bin2"

-- | A ClassName for icon-binoculars
iconBinoculars :: ClassName
iconBinoculars = ClassName "icon-binoculars"

-- | A ClassName for icon-blocked
iconBlocked :: ClassName
iconBlocked = ClassName "icon-blocked"

-- | A ClassName for icon-blog
iconBlog :: ClassName
iconBlog = ClassName "icon-blog"

-- | A ClassName for icon-blogger
iconBlogger :: ClassName
iconBlogger = ClassName "icon-blogger"

-- | A ClassName for icon-blogger2
iconBlogger2 :: ClassName
iconBlogger2 = ClassName "icon-blogger2"

-- | A ClassName for icon-bold
iconBold :: ClassName
iconBold = ClassName "icon-bold"

-- | A ClassName for icon-book
iconBook :: ClassName
iconBook = ClassName "icon-book"

-- | A ClassName for icon-bookmark
iconBookmark :: ClassName
iconBookmark = ClassName "icon-bookmark"

-- | A ClassName for icon-bookmarks
iconBookmarks :: ClassName
iconBookmarks = ClassName "icon-bookmarks"

-- | A ClassName for icon-books
iconBooks :: ClassName
iconBooks = ClassName "icon-books"

-- | A ClassName for icon-box-add
iconBoxAdd :: ClassName
iconBoxAdd = ClassName "icon-box-add"

-- | A ClassName for icon-box-remove
iconBoxRemove :: ClassName
iconBoxRemove = ClassName "icon-box-remove"

-- | A ClassName for icon-briefcase
iconBriefcase :: ClassName
iconBriefcase = ClassName "icon-briefcase"

-- | A ClassName for icon-brightness-contrast
iconBrightnessContrast :: ClassName
iconBrightnessContrast = ClassName "icon-brightness-contrast"

-- | A ClassName for icon-bubble
iconBubble :: ClassName
iconBubble = ClassName "icon-bubble"

-- | A ClassName for icon-bubble2
iconBubble2 :: ClassName
iconBubble2 = ClassName "icon-bubble2"

-- | A ClassName for icon-bubbles
iconBubbles :: ClassName
iconBubbles = ClassName "icon-bubbles"

-- | A ClassName for icon-bubbles2
iconBubbles2 :: ClassName
iconBubbles2 = ClassName "icon-bubbles2"

-- | A ClassName for icon-bubbles3
iconBubbles3 :: ClassName
iconBubbles3 = ClassName "icon-bubbles3"

-- | A ClassName for icon-bubbles4
iconBubbles4 :: ClassName
iconBubbles4 = ClassName "icon-bubbles4"

-- | A ClassName for icon-bug
iconBug :: ClassName
iconBug = ClassName "icon-bug"

-- | A ClassName for icon-bullhorn
iconBullhorn :: ClassName
iconBullhorn = ClassName "icon-bullhorn"

-- | A ClassName for icon-calculator
iconCalculator :: ClassName
iconCalculator = ClassName "icon-calculator"

-- | A ClassName for icon-calendar
iconCalendar :: ClassName
iconCalendar = ClassName "icon-calendar"

-- | A ClassName for icon-camera
iconCamera :: ClassName
iconCamera = ClassName "icon-camera"

-- | A ClassName for icon-cancel-circle
iconCancelCircle :: ClassName
iconCancelCircle = ClassName "icon-cancel-circle"

-- | A ClassName for icon-cart
iconCart :: ClassName
iconCart = ClassName "icon-cart"

-- | A ClassName for icon-checkbox-checked
iconCheckboxChecked :: ClassName
iconCheckboxChecked = ClassName "icon-checkbox-checked"

-- | A ClassName for icon-checkbox-unchecked
iconCheckboxUnchecked :: ClassName
iconCheckboxUnchecked = ClassName "icon-checkbox-unchecked"

-- | A ClassName for icon-checkmark
iconCheckmark :: ClassName
iconCheckmark = ClassName "icon-checkmark"

-- | A ClassName for icon-checkmark2
iconCheckmark2 :: ClassName
iconCheckmark2 = ClassName "icon-checkmark2"

-- | A ClassName for icon-chrome
iconChrome :: ClassName
iconChrome = ClassName "icon-chrome"

-- | A ClassName for icon-circle-down
iconCircleDown :: ClassName
iconCircleDown = ClassName "icon-circle-down"

-- | A ClassName for icon-circle-left
iconCircleLeft :: ClassName
iconCircleLeft = ClassName "icon-circle-left"

-- | A ClassName for icon-circle-right
iconCircleRight :: ClassName
iconCircleRight = ClassName "icon-circle-right"

-- | A ClassName for icon-circle-up
iconCircleUp :: ClassName
iconCircleUp = ClassName "icon-circle-up"

-- | A ClassName for icon-clear-formatting
iconClearFormatting :: ClassName
iconClearFormatting = ClassName "icon-clear-formatting"

-- | A ClassName for icon-clipboard
iconClipboard :: ClassName
iconClipboard = ClassName "icon-clipboard"

-- | A ClassName for icon-clock
iconClock :: ClassName
iconClock = ClassName "icon-clock"

-- | A ClassName for icon-clock2
iconClock2 :: ClassName
iconClock2 = ClassName "icon-clock2"

-- | A ClassName for icon-cloud
iconCloud :: ClassName
iconCloud = ClassName "icon-cloud"

-- | A ClassName for icon-cloud-check
iconCloudCheck :: ClassName
iconCloudCheck = ClassName "icon-cloud-check"

-- | A ClassName for icon-cloud-download
iconCloudDownload :: ClassName
iconCloudDownload = ClassName "icon-cloud-download"

-- | A ClassName for icon-cloud-upload
iconCloudUpload :: ClassName
iconCloudUpload = ClassName "icon-cloud-upload"

-- | A ClassName for icon-clubs
iconClubs :: ClassName
iconClubs = ClassName "icon-clubs"

-- | A ClassName for icon-codepen
iconCodepen :: ClassName
iconCodepen = ClassName "icon-codepen"

-- | A ClassName for icon-cog
iconCog :: ClassName
iconCog = ClassName "icon-cog"

-- | A ClassName for icon-cogs
iconCogs :: ClassName
iconCogs = ClassName "icon-cogs"

-- | A ClassName for icon-coin-dollar
iconCoinDollar :: ClassName
iconCoinDollar = ClassName "icon-coin-dollar"

-- | A ClassName for icon-coin-euro
iconCoinEuro :: ClassName
iconCoinEuro = ClassName "icon-coin-euro"

-- | A ClassName for icon-coin-pound
iconCoinPound :: ClassName
iconCoinPound = ClassName "icon-coin-pound"

-- | A ClassName for icon-coin-yen
iconCoinYen :: ClassName
iconCoinYen = ClassName "icon-coin-yen"

-- | A ClassName for icon-command
iconCommand :: ClassName
iconCommand = ClassName "icon-command"

-- | A ClassName for icon-compass
iconCompass :: ClassName
iconCompass = ClassName "icon-compass"

-- | A ClassName for icon-compass2
iconCompass2 :: ClassName
iconCompass2 = ClassName "icon-compass2"

-- | A ClassName for icon-confused
iconConfused :: ClassName
iconConfused = ClassName "icon-confused"

-- | A ClassName for icon-confused2
iconConfused2 :: ClassName
iconConfused2 = ClassName "icon-confused2"

-- | A ClassName for icon-connection
iconConnection :: ClassName
iconConnection = ClassName "icon-connection"

-- | A ClassName for icon-contrast
iconContrast :: ClassName
iconContrast = ClassName "icon-contrast"

-- | A ClassName for icon-cool
iconCool :: ClassName
iconCool = ClassName "icon-cool"

-- | A ClassName for icon-cool2
iconCool2 :: ClassName
iconCool2 = ClassName "icon-cool2"

-- | A ClassName for icon-copy
iconCopy :: ClassName
iconCopy = ClassName "icon-copy"

-- | A ClassName for icon-credit-card
iconCreditCard :: ClassName
iconCreditCard = ClassName "icon-credit-card"

-- | A ClassName for icon-crop
iconCrop :: ClassName
iconCrop = ClassName "icon-crop"

-- | A ClassName for icon-cross
iconCross :: ClassName
iconCross = ClassName "icon-cross"

-- | A ClassName for icon-crying
iconCrying :: ClassName
iconCrying = ClassName "icon-crying"

-- | A ClassName for icon-crying2
iconCrying2 :: ClassName
iconCrying2 = ClassName "icon-crying2"

-- | A ClassName for icon-css3
iconCss3 :: ClassName
iconCss3 = ClassName "icon-css3"

-- | A ClassName for icon-ctrl
iconCtrl :: ClassName
iconCtrl = ClassName "icon-ctrl"

-- | A ClassName for icon-database
iconDatabase :: ClassName
iconDatabase = ClassName "icon-database"

-- | A ClassName for icon-delicious
iconDelicious :: ClassName
iconDelicious = ClassName "icon-delicious"

-- | A ClassName for icon-deviantart
iconDeviantart :: ClassName
iconDeviantart = ClassName "icon-deviantart"

-- | A ClassName for icon-diamonds
iconDiamonds :: ClassName
iconDiamonds = ClassName "icon-diamonds"

-- | A ClassName for icon-dice
iconDice :: ClassName
iconDice = ClassName "icon-dice"

-- | A ClassName for icon-display
iconDisplay :: ClassName
iconDisplay = ClassName "icon-display"

-- | A ClassName for icon-download
iconDownload :: ClassName
iconDownload = ClassName "icon-download"

-- | A ClassName for icon-download2
iconDownload2 :: ClassName
iconDownload2 = ClassName "icon-download2"

-- | A ClassName for icon-download3
iconDownload3 :: ClassName
iconDownload3 = ClassName "icon-download3"

-- | A ClassName for icon-drawer
iconDrawer :: ClassName
iconDrawer = ClassName "icon-drawer"

-- | A ClassName for icon-drawer2
iconDrawer2 :: ClassName
iconDrawer2 = ClassName "icon-drawer2"

-- | A ClassName for icon-dribbble
iconDribbble :: ClassName
iconDribbble = ClassName "icon-dribbble"

-- | A ClassName for icon-drive
iconDrive :: ClassName
iconDrive = ClassName "icon-drive"

-- | A ClassName for icon-dropbox
iconDropbox :: ClassName
iconDropbox = ClassName "icon-dropbox"

-- | A ClassName for icon-droplet
iconDroplet :: ClassName
iconDroplet = ClassName "icon-droplet"

-- | A ClassName for icon-earth
iconEarth :: ClassName
iconEarth = ClassName "icon-earth"

-- | A ClassName for icon-edge
iconEdge :: ClassName
iconEdge = ClassName "icon-edge"

-- | A ClassName for icon-eject
iconEject :: ClassName
iconEject = ClassName "icon-eject"

-- | A ClassName for icon-ello
iconEllo :: ClassName
iconEllo = ClassName "icon-ello"

-- | A ClassName for icon-embed
iconEmbed :: ClassName
iconEmbed = ClassName "icon-embed"

-- | A ClassName for icon-embed2
iconEmbed2 :: ClassName
iconEmbed2 = ClassName "icon-embed2"

-- | A ClassName for icon-enlarge
iconEnlarge :: ClassName
iconEnlarge = ClassName "icon-enlarge"

-- | A ClassName for icon-enlarge2
iconEnlarge2 :: ClassName
iconEnlarge2 = ClassName "icon-enlarge2"

-- | A ClassName for icon-enter
iconEnter :: ClassName
iconEnter = ClassName "icon-enter"

-- | A ClassName for icon-envelop
iconEnvelop :: ClassName
iconEnvelop = ClassName "icon-envelop"

-- | A ClassName for icon-equalizer
iconEqualizer :: ClassName
iconEqualizer = ClassName "icon-equalizer"

-- | A ClassName for icon-equalizer2
iconEqualizer2 :: ClassName
iconEqualizer2 = ClassName "icon-equalizer2"

-- | A ClassName for icon-evil
iconEvil :: ClassName
iconEvil = ClassName "icon-evil"

-- | A ClassName for icon-evil2
iconEvil2 :: ClassName
iconEvil2 = ClassName "icon-evil2"

-- | A ClassName for icon-exit
iconExit :: ClassName
iconExit = ClassName "icon-exit"

-- | A ClassName for icon-eye
iconEye :: ClassName
iconEye = ClassName "icon-eye"

-- | A ClassName for icon-eye-blocked
iconEyeBlocked :: ClassName
iconEyeBlocked = ClassName "icon-eye-blocked"

-- | A ClassName for icon-eye-minus
iconEyeMinus :: ClassName
iconEyeMinus = ClassName "icon-eye-minus"

-- | A ClassName for icon-eye-plus
iconEyePlus :: ClassName
iconEyePlus = ClassName "icon-eye-plus"

-- | A ClassName for icon-eyedropper
iconEyedropper :: ClassName
iconEyedropper = ClassName "icon-eyedropper"

-- | A ClassName for icon-facebook
iconFacebook :: ClassName
iconFacebook = ClassName "icon-facebook"

-- | A ClassName for icon-facebook2
iconFacebook2 :: ClassName
iconFacebook2 = ClassName "icon-facebook2"

-- | A ClassName for icon-feed
iconFeed :: ClassName
iconFeed = ClassName "icon-feed"

-- | A ClassName for icon-file-empty
iconFileEmpty :: ClassName
iconFileEmpty = ClassName "icon-file-empty"

-- | A ClassName for icon-file-excel
iconFileExcel :: ClassName
iconFileExcel = ClassName "icon-file-excel"

-- | A ClassName for icon-file-music
iconFileMusic :: ClassName
iconFileMusic = ClassName "icon-file-music"

-- | A ClassName for icon-file-openoffice
iconFileOpenoffice :: ClassName
iconFileOpenoffice = ClassName "icon-file-openoffice"

-- | A ClassName for icon-file-pdf
iconFilePdf :: ClassName
iconFilePdf = ClassName "icon-file-pdf"

-- | A ClassName for icon-file-picture
iconFilePicture :: ClassName
iconFilePicture = ClassName "icon-file-picture"

-- | A ClassName for icon-file-play
iconFilePlay :: ClassName
iconFilePlay = ClassName "icon-file-play"

-- | A ClassName for icon-file-text
iconFileText :: ClassName
iconFileText = ClassName "icon-file-text"

-- | A ClassName for icon-file-text2
iconFileText2 :: ClassName
iconFileText2 = ClassName "icon-file-text2"

-- | A ClassName for icon-file-video
iconFileVideo :: ClassName
iconFileVideo = ClassName "icon-file-video"

-- | A ClassName for icon-file-word
iconFileWord :: ClassName
iconFileWord = ClassName "icon-file-word"

-- | A ClassName for icon-file-zip
iconFileZip :: ClassName
iconFileZip = ClassName "icon-file-zip"

-- | A ClassName for icon-files-empty
iconFilesEmpty :: ClassName
iconFilesEmpty = ClassName "icon-files-empty"

-- | A ClassName for icon-film
iconFilm :: ClassName
iconFilm = ClassName "icon-film"

-- | A ClassName for icon-filter
iconFilter :: ClassName
iconFilter = ClassName "icon-filter"

-- | A ClassName for icon-finder
iconFinder :: ClassName
iconFinder = ClassName "icon-finder"

-- | A ClassName for icon-fire
iconFire :: ClassName
iconFire = ClassName "icon-fire"

-- | A ClassName for icon-firefox
iconFirefox :: ClassName
iconFirefox = ClassName "icon-firefox"

-- | A ClassName for icon-first
iconFirst :: ClassName
iconFirst = ClassName "icon-first"

-- | A ClassName for icon-flag
iconFlag :: ClassName
iconFlag = ClassName "icon-flag"

-- | A ClassName for icon-flattr
iconFlattr :: ClassName
iconFlattr = ClassName "icon-flattr"

-- | A ClassName for icon-flickr
iconFlickr :: ClassName
iconFlickr = ClassName "icon-flickr"

-- | A ClassName for icon-flickr2
iconFlickr2 :: ClassName
iconFlickr2 = ClassName "icon-flickr2"

-- | A ClassName for icon-flickr3
iconFlickr3 :: ClassName
iconFlickr3 = ClassName "icon-flickr3"

-- | A ClassName for icon-flickr4
iconFlickr4 :: ClassName
iconFlickr4 = ClassName "icon-flickr4"

-- | A ClassName for icon-floppy-disk
iconFloppyDisk :: ClassName
iconFloppyDisk = ClassName "icon-floppy-disk"

-- | A ClassName for icon-folder
iconFolder :: ClassName
iconFolder = ClassName "icon-folder"

-- | A ClassName for icon-folder-download
iconFolderDownload :: ClassName
iconFolderDownload = ClassName "icon-folder-download"

-- | A ClassName for icon-folder-minus
iconFolderMinus :: ClassName
iconFolderMinus = ClassName "icon-folder-minus"

-- | A ClassName for icon-folder-open
iconFolderOpen :: ClassName
iconFolderOpen = ClassName "icon-folder-open"

-- | A ClassName for icon-folder-plus
iconFolderPlus :: ClassName
iconFolderPlus = ClassName "icon-folder-plus"

-- | A ClassName for icon-folder-upload
iconFolderUpload :: ClassName
iconFolderUpload = ClassName "icon-folder-upload"

-- | A ClassName for icon-font
iconFont :: ClassName
iconFont = ClassName "icon-font"

-- | A ClassName for icon-font-size
iconFontSize :: ClassName
iconFontSize = ClassName "icon-font-size"

-- | A ClassName for icon-forward
iconForward :: ClassName
iconForward = ClassName "icon-forward"

-- | A ClassName for icon-forward2
iconForward2 :: ClassName
iconForward2 = ClassName "icon-forward2"

-- | A ClassName for icon-forward3
iconForward3 :: ClassName
iconForward3 = ClassName "icon-forward3"

-- | A ClassName for icon-foursquare
iconFoursquare :: ClassName
iconFoursquare = ClassName "icon-foursquare"

-- | A ClassName for icon-frustrated
iconFrustrated :: ClassName
iconFrustrated = ClassName "icon-frustrated"

-- | A ClassName for icon-frustrated2
iconFrustrated2 :: ClassName
iconFrustrated2 = ClassName "icon-frustrated2"

-- | A ClassName for icon-gift
iconGift :: ClassName
iconGift = ClassName "icon-gift"

-- | A ClassName for icon-git
iconGit :: ClassName
iconGit = ClassName "icon-git"

-- | A ClassName for icon-github
iconGithub :: ClassName
iconGithub = ClassName "icon-github"

-- | A ClassName for icon-glass
iconGlass :: ClassName
iconGlass = ClassName "icon-glass"

-- | A ClassName for icon-glass2
iconGlass2 :: ClassName
iconGlass2 = ClassName "icon-glass2"

-- | A ClassName for icon-google
iconGoogle :: ClassName
iconGoogle = ClassName "icon-google"

-- | A ClassName for icon-google2
iconGoogle2 :: ClassName
iconGoogle2 = ClassName "icon-google2"

-- | A ClassName for icon-google3
iconGoogle3 :: ClassName
iconGoogle3 = ClassName "icon-google3"

-- | A ClassName for icon-google-drive
iconGoogleDrive :: ClassName
iconGoogleDrive = ClassName "icon-google-drive"

-- | A ClassName for icon-google-plus
iconGooglePlus :: ClassName
iconGooglePlus = ClassName "icon-google-plus"

-- | A ClassName for icon-google-plus2
iconGooglePlus2 :: ClassName
iconGooglePlus2 = ClassName "icon-google-plus2"

-- | A ClassName for icon-google-plus3
iconGooglePlus3 :: ClassName
iconGooglePlus3 = ClassName "icon-google-plus3"

-- | A ClassName for icon-grin
iconGrin :: ClassName
iconGrin = ClassName "icon-grin"

-- | A ClassName for icon-grin2
iconGrin2 :: ClassName
iconGrin2 = ClassName "icon-grin2"

-- | A ClassName for icon-hackernews
iconHackernews :: ClassName
iconHackernews = ClassName "icon-hackernews"

-- | A ClassName for icon-hammer
iconHammer :: ClassName
iconHammer = ClassName "icon-hammer"

-- | A ClassName for icon-hammer2
iconHammer2 :: ClassName
iconHammer2 = ClassName "icon-hammer2"

-- | A ClassName for icon-hangouts
iconHangouts :: ClassName
iconHangouts = ClassName "icon-hangouts"

-- | A ClassName for icon-happy
iconHappy :: ClassName
iconHappy = ClassName "icon-happy"

-- | A ClassName for icon-happy2
iconHappy2 :: ClassName
iconHappy2 = ClassName "icon-happy2"

-- | A ClassName for icon-headphones
iconHeadphones :: ClassName
iconHeadphones = ClassName "icon-headphones"

-- | A ClassName for icon-heart
iconHeart :: ClassName
iconHeart = ClassName "icon-heart"

-- | A ClassName for icon-heart-broken
iconHeartBroken :: ClassName
iconHeartBroken = ClassName "icon-heart-broken"

-- | A ClassName for icon-hipster
iconHipster :: ClassName
iconHipster = ClassName "icon-hipster"

-- | A ClassName for icon-hipster2
iconHipster2 :: ClassName
iconHipster2 = ClassName "icon-hipster2"

-- | A ClassName for icon-history
iconHistory :: ClassName
iconHistory = ClassName "icon-history"

-- | A ClassName for icon-home
iconHome :: ClassName
iconHome = ClassName "icon-home"

-- | A ClassName for icon-home2
iconHome2 :: ClassName
iconHome2 = ClassName "icon-home2"

-- | A ClassName for icon-home3
iconHome3 :: ClassName
iconHome3 = ClassName "icon-home3"

-- | A ClassName for icon-hour-glass
iconHourGlass :: ClassName
iconHourGlass = ClassName "icon-hour-glass"

-- | A ClassName for icon-html-five
iconHtmlFive :: ClassName
iconHtmlFive = ClassName "icon-html-five"

-- | A ClassName for icon-html-five2
iconHtmlFive2 :: ClassName
iconHtmlFive2 = ClassName "icon-html-five2"

-- | A ClassName for icon-IcoMoon
iconIcomoon :: ClassName
iconIcomoon = ClassName "icon-IcoMoon"

-- | A ClassName for icon-IE
iconIe :: ClassName
iconIe = ClassName "icon-IE"

-- | A ClassName for icon-image
iconImage :: ClassName
iconImage = ClassName "icon-image"

-- | A ClassName for icon-images
iconImages :: ClassName
iconImages = ClassName "icon-images"

-- | A ClassName for icon-indent-decrease
iconIndentDecrease :: ClassName
iconIndentDecrease = ClassName "icon-indent-decrease"

-- | A ClassName for icon-indent-increase
iconIndentIncrease :: ClassName
iconIndentIncrease = ClassName "icon-indent-increase"

-- | A ClassName for icon-infinite
iconInfinite :: ClassName
iconInfinite = ClassName "icon-infinite"

-- | A ClassName for icon-info
iconInfo :: ClassName
iconInfo = ClassName "icon-info"

-- | A ClassName for icon-insert-template
iconInsertTemplate :: ClassName
iconInsertTemplate = ClassName "icon-insert-template"

-- | A ClassName for icon-instagram
iconInstagram :: ClassName
iconInstagram = ClassName "icon-instagram"

-- | A ClassName for icon-italic
iconItalic :: ClassName
iconItalic = ClassName "icon-italic"

-- | A ClassName for icon-joomla
iconJoomla :: ClassName
iconJoomla = ClassName "icon-joomla"

-- | A ClassName for icon-key
iconKey :: ClassName
iconKey = ClassName "icon-key"

-- | A ClassName for icon-key2
iconKey2 :: ClassName
iconKey2 = ClassName "icon-key2"

-- | A ClassName for icon-keyboard
iconKeyboard :: ClassName
iconKeyboard = ClassName "icon-keyboard"

-- | A ClassName for icon-lab
iconLab :: ClassName
iconLab = ClassName "icon-lab"

-- | A ClassName for icon-lanyrd
iconLanyrd :: ClassName
iconLanyrd = ClassName "icon-lanyrd"

-- | A ClassName for icon-laptop
iconLaptop :: ClassName
iconLaptop = ClassName "icon-laptop"

-- | A ClassName for icon-last
iconLast :: ClassName
iconLast = ClassName "icon-last"

-- | A ClassName for icon-lastfm
iconLastfm :: ClassName
iconLastfm = ClassName "icon-lastfm"

-- | A ClassName for icon-lastfm2
iconLastfm2 :: ClassName
iconLastfm2 = ClassName "icon-lastfm2"

-- | A ClassName for icon-leaf
iconLeaf :: ClassName
iconLeaf = ClassName "icon-leaf"

-- | A ClassName for icon-library
iconLibrary :: ClassName
iconLibrary = ClassName "icon-library"

-- | A ClassName for icon-libreoffice
iconLibreoffice :: ClassName
iconLibreoffice = ClassName "icon-libreoffice"

-- | A ClassName for icon-lifebuoy
iconLifebuoy :: ClassName
iconLifebuoy = ClassName "icon-lifebuoy"

-- | A ClassName for icon-ligature
iconLigature :: ClassName
iconLigature = ClassName "icon-ligature"

-- | A ClassName for icon-ligature2
iconLigature2 :: ClassName
iconLigature2 = ClassName "icon-ligature2"

-- | A ClassName for icon-link
iconLink :: ClassName
iconLink = ClassName "icon-link"

-- | A ClassName for icon-linkedin
iconLinkedin :: ClassName
iconLinkedin = ClassName "icon-linkedin"

-- | A ClassName for icon-linkedin2
iconLinkedin2 :: ClassName
iconLinkedin2 = ClassName "icon-linkedin2"

-- | A ClassName for icon-list
iconList :: ClassName
iconList = ClassName "icon-list"

-- | A ClassName for icon-list2
iconList2 :: ClassName
iconList2 = ClassName "icon-list2"

-- | A ClassName for icon-list-numbered
iconListNumbered :: ClassName
iconListNumbered = ClassName "icon-list-numbered"

-- | A ClassName for icon-location
iconLocation :: ClassName
iconLocation = ClassName "icon-location"

-- | A ClassName for icon-location2
iconLocation2 :: ClassName
iconLocation2 = ClassName "icon-location2"

-- | A ClassName for icon-lock
iconLock :: ClassName
iconLock = ClassName "icon-lock"

-- | A ClassName for icon-loop
iconLoop :: ClassName
iconLoop = ClassName "icon-loop"

-- | A ClassName for icon-loop2
iconLoop2 :: ClassName
iconLoop2 = ClassName "icon-loop2"

-- | A ClassName for icon-ltr
iconLtr :: ClassName
iconLtr = ClassName "icon-ltr"

-- | A ClassName for icon-magic-wand
iconMagicWand :: ClassName
iconMagicWand = ClassName "icon-magic-wand"

-- | A ClassName for icon-magnet
iconMagnet :: ClassName
iconMagnet = ClassName "icon-magnet"

-- | A ClassName for icon-mail
iconMail :: ClassName
iconMail = ClassName "icon-mail"

-- | A ClassName for icon-mail2
iconMail2 :: ClassName
iconMail2 = ClassName "icon-mail2"

-- | A ClassName for icon-mail3
iconMail3 :: ClassName
iconMail3 = ClassName "icon-mail3"

-- | A ClassName for icon-mail4
iconMail4 :: ClassName
iconMail4 = ClassName "icon-mail4"

-- | A ClassName for icon-make-group
iconMakeGroup :: ClassName
iconMakeGroup = ClassName "icon-make-group"

-- | A ClassName for icon-man
iconMan :: ClassName
iconMan = ClassName "icon-man"

-- | A ClassName for icon-man-woman
iconManWoman :: ClassName
iconManWoman = ClassName "icon-man-woman"

-- | A ClassName for icon-map
iconMap :: ClassName
iconMap = ClassName "icon-map"

-- | A ClassName for icon-map2
iconMap2 :: ClassName
iconMap2 = ClassName "icon-map2"

-- | A ClassName for icon-menu
iconMenu :: ClassName
iconMenu = ClassName "icon-menu"

-- | A ClassName for icon-menu2
iconMenu2 :: ClassName
iconMenu2 = ClassName "icon-menu2"

-- | A ClassName for icon-menu3
iconMenu3 :: ClassName
iconMenu3 = ClassName "icon-menu3"

-- | A ClassName for icon-menu4
iconMenu4 :: ClassName
iconMenu4 = ClassName "icon-menu4"

-- | A ClassName for icon-meter
iconMeter :: ClassName
iconMeter = ClassName "icon-meter"

-- | A ClassName for icon-meter2
iconMeter2 :: ClassName
iconMeter2 = ClassName "icon-meter2"

-- | A ClassName for icon-mic
iconMic :: ClassName
iconMic = ClassName "icon-mic"

-- | A ClassName for icon-minus
iconMinus :: ClassName
iconMinus = ClassName "icon-minus"

-- | A ClassName for icon-mobile
iconMobile :: ClassName
iconMobile = ClassName "icon-mobile"

-- | A ClassName for icon-mobile2
iconMobile2 :: ClassName
iconMobile2 = ClassName "icon-mobile2"

-- | A ClassName for icon-move-down
iconMoveDown :: ClassName
iconMoveDown = ClassName "icon-move-down"

-- | A ClassName for icon-move-up
iconMoveUp :: ClassName
iconMoveUp = ClassName "icon-move-up"

-- | A ClassName for icon-mug
iconMug :: ClassName
iconMug = ClassName "icon-mug"

-- | A ClassName for icon-music
iconMusic :: ClassName
iconMusic = ClassName "icon-music"

-- | A ClassName for icon-neutral
iconNeutral :: ClassName
iconNeutral = ClassName "icon-neutral"

-- | A ClassName for icon-neutral2
iconNeutral2 :: ClassName
iconNeutral2 = ClassName "icon-neutral2"

-- | A ClassName for icon-new-tab
iconNewTab :: ClassName
iconNewTab = ClassName "icon-new-tab"

-- | A ClassName for icon-newspaper
iconNewspaper :: ClassName
iconNewspaper = ClassName "icon-newspaper"

-- | A ClassName for icon-next
iconNext :: ClassName
iconNext = ClassName "icon-next"

-- | A ClassName for icon-next2
iconNext2 :: ClassName
iconNext2 = ClassName "icon-next2"

-- | A ClassName for icon-notification
iconNotification :: ClassName
iconNotification = ClassName "icon-notification"

-- | A ClassName for icon-npm
iconNpm :: ClassName
iconNpm = ClassName "icon-npm"

-- | A ClassName for icon-office
iconOffice :: ClassName
iconOffice = ClassName "icon-office"

-- | A ClassName for icon-omega
iconOmega :: ClassName
iconOmega = ClassName "icon-omega"

-- | A ClassName for icon-onedrive
iconOnedrive :: ClassName
iconOnedrive = ClassName "icon-onedrive"

-- | A ClassName for icon-opera
iconOpera :: ClassName
iconOpera = ClassName "icon-opera"

-- | A ClassName for icon-opt
iconOpt :: ClassName
iconOpt = ClassName "icon-opt"

-- | A ClassName for icon-pacman
iconPacman :: ClassName
iconPacman = ClassName "icon-pacman"

-- | A ClassName for icon-page-break
iconPageBreak :: ClassName
iconPageBreak = ClassName "icon-page-break"

-- | A ClassName for icon-pagebreak
iconPagebreak :: ClassName
iconPagebreak = ClassName "icon-pagebreak"

-- | A ClassName for icon-paint-format
iconPaintFormat :: ClassName
iconPaintFormat = ClassName "icon-paint-format"

-- | A ClassName for icon-paragraph-center
iconParagraphCenter :: ClassName
iconParagraphCenter = ClassName "icon-paragraph-center"

-- | A ClassName for icon-paragraph-justify
iconParagraphJustify :: ClassName
iconParagraphJustify = ClassName "icon-paragraph-justify"

-- | A ClassName for icon-paragraph-left
iconParagraphLeft :: ClassName
iconParagraphLeft = ClassName "icon-paragraph-left"

-- | A ClassName for icon-paragraph-right
iconParagraphRight :: ClassName
iconParagraphRight = ClassName "icon-paragraph-right"

-- | A ClassName for icon-paste
iconPaste :: ClassName
iconPaste = ClassName "icon-paste"

-- | A ClassName for icon-pause
iconPause :: ClassName
iconPause = ClassName "icon-pause"

-- | A ClassName for icon-pause2
iconPause2 :: ClassName
iconPause2 = ClassName "icon-pause2"

-- | A ClassName for icon-paypal
iconPaypal :: ClassName
iconPaypal = ClassName "icon-paypal"

-- | A ClassName for icon-pen
iconPen :: ClassName
iconPen = ClassName "icon-pen"

-- | A ClassName for icon-pencil
iconPencil :: ClassName
iconPencil = ClassName "icon-pencil"

-- | A ClassName for icon-pencil2
iconPencil2 :: ClassName
iconPencil2 = ClassName "icon-pencil2"

-- | A ClassName for icon-phone
iconPhone :: ClassName
iconPhone = ClassName "icon-phone"

-- | A ClassName for icon-phone-hang-up
iconPhoneHangUp :: ClassName
iconPhoneHangUp = ClassName "icon-phone-hang-up"

-- | A ClassName for icon-pie-chart
iconPieChart :: ClassName
iconPieChart = ClassName "icon-pie-chart"

-- | A ClassName for icon-pilcrow
iconPilcrow :: ClassName
iconPilcrow = ClassName "icon-pilcrow"

-- | A ClassName for icon-pinterest
iconPinterest :: ClassName
iconPinterest = ClassName "icon-pinterest"

-- | A ClassName for icon-pinterest2
iconPinterest2 :: ClassName
iconPinterest2 = ClassName "icon-pinterest2"

-- | A ClassName for icon-play
iconPlay :: ClassName
iconPlay = ClassName "icon-play"

-- | A ClassName for icon-play2
iconPlay2 :: ClassName
iconPlay2 = ClassName "icon-play2"

-- | A ClassName for icon-play3
iconPlay3 :: ClassName
iconPlay3 = ClassName "icon-play3"

-- | A ClassName for icon-plus
iconPlus :: ClassName
iconPlus = ClassName "icon-plus"

-- | A ClassName for icon-podcast
iconPodcast :: ClassName
iconPodcast = ClassName "icon-podcast"

-- | A ClassName for icon-point-down
iconPointDown :: ClassName
iconPointDown = ClassName "icon-point-down"

-- | A ClassName for icon-point-left
iconPointLeft :: ClassName
iconPointLeft = ClassName "icon-point-left"

-- | A ClassName for icon-point-right
iconPointRight :: ClassName
iconPointRight = ClassName "icon-point-right"

-- | A ClassName for icon-point-up
iconPointUp :: ClassName
iconPointUp = ClassName "icon-point-up"

-- | A ClassName for icon-power
iconPower :: ClassName
iconPower = ClassName "icon-power"

-- | A ClassName for icon-power-cord
iconPowerCord :: ClassName
iconPowerCord = ClassName "icon-power-cord"

-- | A ClassName for icon-previous
iconPrevious :: ClassName
iconPrevious = ClassName "icon-previous"

-- | A ClassName for icon-previous2
iconPrevious2 :: ClassName
iconPrevious2 = ClassName "icon-previous2"

-- | A ClassName for icon-price-tag
iconPriceTag :: ClassName
iconPriceTag = ClassName "icon-price-tag"

-- | A ClassName for icon-price-tags
iconPriceTags :: ClassName
iconPriceTags = ClassName "icon-price-tags"

-- | A ClassName for icon-printer
iconPrinter :: ClassName
iconPrinter = ClassName "icon-printer"

-- | A ClassName for icon-profile
iconProfile :: ClassName
iconProfile = ClassName "icon-profile"

-- | A ClassName for icon-pushpin
iconPushpin :: ClassName
iconPushpin = ClassName "icon-pushpin"

-- | A ClassName for icon-qrcode
iconQrcode :: ClassName
iconQrcode = ClassName "icon-qrcode"

-- | A ClassName for icon-question
iconQuestion :: ClassName
iconQuestion = ClassName "icon-question"

-- | A ClassName for icon-quill
iconQuill :: ClassName
iconQuill = ClassName "icon-quill"

-- | A ClassName for icon-quotes-left
iconQuotesLeft :: ClassName
iconQuotesLeft = ClassName "icon-quotes-left"

-- | A ClassName for icon-quotes-right
iconQuotesRight :: ClassName
iconQuotesRight = ClassName "icon-quotes-right"

-- | A ClassName for icon-radio-checked
iconRadioChecked :: ClassName
iconRadioChecked = ClassName "icon-radio-checked"

-- | A ClassName for icon-radio-checked2
iconRadioChecked2 :: ClassName
iconRadioChecked2 = ClassName "icon-radio-checked2"

-- | A ClassName for icon-radio-unchecked
iconRadioUnchecked :: ClassName
iconRadioUnchecked = ClassName "icon-radio-unchecked"

-- | A ClassName for icon-reddit
iconReddit :: ClassName
iconReddit = ClassName "icon-reddit"

-- | A ClassName for icon-redo
iconRedo :: ClassName
iconRedo = ClassName "icon-redo"

-- | A ClassName for icon-redo2
iconRedo2 :: ClassName
iconRedo2 = ClassName "icon-redo2"

-- | A ClassName for icon-renren
iconRenren :: ClassName
iconRenren = ClassName "icon-renren"

-- | A ClassName for icon-reply
iconReply :: ClassName
iconReply = ClassName "icon-reply"

-- | A ClassName for icon-road
iconRoad :: ClassName
iconRoad = ClassName "icon-road"

-- | A ClassName for icon-rocket
iconRocket :: ClassName
iconRocket = ClassName "icon-rocket"

-- | A ClassName for icon-rss
iconRss :: ClassName
iconRss = ClassName "icon-rss"

-- | A ClassName for icon-rss2
iconRss2 :: ClassName
iconRss2 = ClassName "icon-rss2"

-- | A ClassName for icon-rtl
iconRtl :: ClassName
iconRtl = ClassName "icon-rtl"

-- | A ClassName for icon-sad
iconSad :: ClassName
iconSad = ClassName "icon-sad"

-- | A ClassName for icon-sad2
iconSad2 :: ClassName
iconSad2 = ClassName "icon-sad2"

-- | A ClassName for icon-safari
iconSafari :: ClassName
iconSafari = ClassName "icon-safari"

-- | A ClassName for icon-scissors
iconScissors :: ClassName
iconScissors = ClassName "icon-scissors"

-- | A ClassName for icon-search
iconSearch :: ClassName
iconSearch = ClassName "icon-search"

-- | A ClassName for icon-section
iconSection :: ClassName
iconSection = ClassName "icon-section"

-- | A ClassName for icon-share
iconShare :: ClassName
iconShare = ClassName "icon-share"

-- | A ClassName for icon-share2
iconShare2 :: ClassName
iconShare2 = ClassName "icon-share2"

-- | A ClassName for icon-shield
iconShield :: ClassName
iconShield = ClassName "icon-shield"

-- | A ClassName for icon-shift
iconShift :: ClassName
iconShift = ClassName "icon-shift"

-- | A ClassName for icon-shocked
iconShocked :: ClassName
iconShocked = ClassName "icon-shocked"

-- | A ClassName for icon-shocked2
iconShocked2 :: ClassName
iconShocked2 = ClassName "icon-shocked2"

-- | A ClassName for icon-shrink
iconShrink :: ClassName
iconShrink = ClassName "icon-shrink"

-- | A ClassName for icon-shrink2
iconShrink2 :: ClassName
iconShrink2 = ClassName "icon-shrink2"

-- | A ClassName for icon-shuffle
iconShuffle :: ClassName
iconShuffle = ClassName "icon-shuffle"

-- | A ClassName for icon-sigma
iconSigma :: ClassName
iconSigma = ClassName "icon-sigma"

-- | A ClassName for icon-sina-weibo
iconSinaWeibo :: ClassName
iconSinaWeibo = ClassName "icon-sina-weibo"

-- | A ClassName for icon-skype
iconSkype :: ClassName
iconSkype = ClassName "icon-skype"

-- | A ClassName for icon-sleepy
iconSleepy :: ClassName
iconSleepy = ClassName "icon-sleepy"

-- | A ClassName for icon-sleepy2
iconSleepy2 :: ClassName
iconSleepy2 = ClassName "icon-sleepy2"

-- | A ClassName for icon-smile
iconSmile :: ClassName
iconSmile = ClassName "icon-smile"

-- | A ClassName for icon-smile2
iconSmile2 :: ClassName
iconSmile2 = ClassName "icon-smile2"

-- | A ClassName for icon-sort-alpha-asc
iconSortAlphaAsc :: ClassName
iconSortAlphaAsc = ClassName "icon-sort-alpha-asc"

-- | A ClassName for icon-sort-alpha-desc
iconSortAlphaDesc :: ClassName
iconSortAlphaDesc = ClassName "icon-sort-alpha-desc"

-- | A ClassName for icon-sort-amount-asc
iconSortAmountAsc :: ClassName
iconSortAmountAsc = ClassName "icon-sort-amount-asc"

-- | A ClassName for icon-sort-amount-desc
iconSortAmountDesc :: ClassName
iconSortAmountDesc = ClassName "icon-sort-amount-desc"

-- | A ClassName for icon-sort-numberic-desc
iconSortNumbericDesc :: ClassName
iconSortNumbericDesc = ClassName "icon-sort-numberic-desc"

-- | A ClassName for icon-sort-numeric-asc
iconSortNumericAsc :: ClassName
iconSortNumericAsc = ClassName "icon-sort-numeric-asc"

-- | A ClassName for icon-soundcloud
iconSoundcloud :: ClassName
iconSoundcloud = ClassName "icon-soundcloud"

-- | A ClassName for icon-soundcloud2
iconSoundcloud2 :: ClassName
iconSoundcloud2 = ClassName "icon-soundcloud2"

-- | A ClassName for icon-spades
iconSpades :: ClassName
iconSpades = ClassName "icon-spades"

-- | A ClassName for icon-spell-check
iconSpellCheck :: ClassName
iconSpellCheck = ClassName "icon-spell-check"

-- | A ClassName for icon-sphere
iconSphere :: ClassName
iconSphere = ClassName "icon-sphere"

-- | A ClassName for icon-spinner
iconSpinner :: ClassName
iconSpinner = ClassName "icon-spinner"

-- | A ClassName for icon-spinner10
iconSpinner10 :: ClassName
iconSpinner10 = ClassName "icon-spinner10"

-- | A ClassName for icon-spinner11
iconSpinner11 :: ClassName
iconSpinner11 = ClassName "icon-spinner11"

-- | A ClassName for icon-spinner2
iconSpinner2 :: ClassName
iconSpinner2 = ClassName "icon-spinner2"

-- | A ClassName for icon-spinner3
iconSpinner3 :: ClassName
iconSpinner3 = ClassName "icon-spinner3"

-- | A ClassName for icon-spinner4
iconSpinner4 :: ClassName
iconSpinner4 = ClassName "icon-spinner4"

-- | A ClassName for icon-spinner5
iconSpinner5 :: ClassName
iconSpinner5 = ClassName "icon-spinner5"

-- | A ClassName for icon-spinner6
iconSpinner6 :: ClassName
iconSpinner6 = ClassName "icon-spinner6"

-- | A ClassName for icon-spinner7
iconSpinner7 :: ClassName
iconSpinner7 = ClassName "icon-spinner7"

-- | A ClassName for icon-spinner8
iconSpinner8 :: ClassName
iconSpinner8 = ClassName "icon-spinner8"

-- | A ClassName for icon-spinner9
iconSpinner9 :: ClassName
iconSpinner9 = ClassName "icon-spinner9"

-- | A ClassName for icon-spoon-knife
iconSpoonKnife :: ClassName
iconSpoonKnife = ClassName "icon-spoon-knife"

-- | A ClassName for icon-spotify
iconSpotify :: ClassName
iconSpotify = ClassName "icon-spotify"

-- | A ClassName for icon-stack
iconStack :: ClassName
iconStack = ClassName "icon-stack"

-- | A ClassName for icon-stackoverflow
iconStackoverflow :: ClassName
iconStackoverflow = ClassName "icon-stackoverflow"

-- | A ClassName for icon-star-empty
iconStarEmpty :: ClassName
iconStarEmpty = ClassName "icon-star-empty"

-- | A ClassName for icon-star-full
iconStarFull :: ClassName
iconStarFull = ClassName "icon-star-full"

-- | A ClassName for icon-star-half
iconStarHalf :: ClassName
iconStarHalf = ClassName "icon-star-half"

-- | A ClassName for icon-stats-bars
iconStatsBars :: ClassName
iconStatsBars = ClassName "icon-stats-bars"

-- | A ClassName for icon-stats-bars2
iconStatsBars2 :: ClassName
iconStatsBars2 = ClassName "icon-stats-bars2"

-- | A ClassName for icon-stats-dots
iconStatsDots :: ClassName
iconStatsDots = ClassName "icon-stats-dots"

-- | A ClassName for icon-steam
iconSteam :: ClassName
iconSteam = ClassName "icon-steam"

-- | A ClassName for icon-steam2
iconSteam2 :: ClassName
iconSteam2 = ClassName "icon-steam2"

-- | A ClassName for icon-stop
iconStop :: ClassName
iconStop = ClassName "icon-stop"

-- | A ClassName for icon-stop2
iconStop2 :: ClassName
iconStop2 = ClassName "icon-stop2"

-- | A ClassName for icon-stopwatch
iconStopwatch :: ClassName
iconStopwatch = ClassName "icon-stopwatch"

-- | A ClassName for icon-strikethrough
iconStrikethrough :: ClassName
iconStrikethrough = ClassName "icon-strikethrough"

-- | A ClassName for icon-stumbleupon
iconStumbleupon :: ClassName
iconStumbleupon = ClassName "icon-stumbleupon"

-- | A ClassName for icon-stumbleupon2
iconStumbleupon2 :: ClassName
iconStumbleupon2 = ClassName "icon-stumbleupon2"

-- | A ClassName for icon-subscript
iconSubscript :: ClassName
iconSubscript = ClassName "icon-subscript"

-- | A ClassName for icon-subscript2
iconSubscript2 :: ClassName
iconSubscript2 = ClassName "icon-subscript2"

-- | A ClassName for icon-sun
iconSun :: ClassName
iconSun = ClassName "icon-sun"

-- | A ClassName for icon-superscript
iconSuperscript :: ClassName
iconSuperscript = ClassName "icon-superscript"

-- | A ClassName for icon-superscript2
iconSuperscript2 :: ClassName
iconSuperscript2 = ClassName "icon-superscript2"

-- | A ClassName for icon-svg
iconSvg :: ClassName
iconSvg = ClassName "icon-svg"

-- | A ClassName for icon-switch
iconSwitch :: ClassName
iconSwitch = ClassName "icon-switch"

-- | A ClassName for icon-tab
iconTab :: ClassName
iconTab = ClassName "icon-tab"

-- | A ClassName for icon-table
iconTable :: ClassName
iconTable = ClassName "icon-table"

-- | A ClassName for icon-table2
iconTable2 :: ClassName
iconTable2 = ClassName "icon-table2"

-- | A ClassName for icon-tablet
iconTablet :: ClassName
iconTablet = ClassName "icon-tablet"

-- | A ClassName for icon-target
iconTarget :: ClassName
iconTarget = ClassName "icon-target"

-- | A ClassName for icon-telegram
iconTelegram :: ClassName
iconTelegram = ClassName "icon-telegram"

-- | A ClassName for icon-terminal
iconTerminal :: ClassName
iconTerminal = ClassName "icon-terminal"

-- | A ClassName for icon-text-color
iconTextColor :: ClassName
iconTextColor = ClassName "icon-text-color"

-- | A ClassName for icon-text-height
iconTextHeight :: ClassName
iconTextHeight = ClassName "icon-text-height"

-- | A ClassName for icon-text-width
iconTextWidth :: ClassName
iconTextWidth = ClassName "icon-text-width"

-- | A ClassName for icon-ticket
iconTicket :: ClassName
iconTicket = ClassName "icon-ticket"

-- | A ClassName for icon-tongue
iconTongue :: ClassName
iconTongue = ClassName "icon-tongue"

-- | A ClassName for icon-tongue2
iconTongue2 :: ClassName
iconTongue2 = ClassName "icon-tongue2"

-- | A ClassName for icon-tree
iconTree :: ClassName
iconTree = ClassName "icon-tree"

-- | A ClassName for icon-trello
iconTrello :: ClassName
iconTrello = ClassName "icon-trello"

-- | A ClassName for icon-trophy
iconTrophy :: ClassName
iconTrophy = ClassName "icon-trophy"

-- | A ClassName for icon-truck
iconTruck :: ClassName
iconTruck = ClassName "icon-truck"

-- | A ClassName for icon-tumblr
iconTumblr :: ClassName
iconTumblr = ClassName "icon-tumblr"

-- | A ClassName for icon-tumblr2
iconTumblr2 :: ClassName
iconTumblr2 = ClassName "icon-tumblr2"

-- | A ClassName for icon-tux
iconTux :: ClassName
iconTux = ClassName "icon-tux"

-- | A ClassName for icon-tv
iconTv :: ClassName
iconTv = ClassName "icon-tv"

-- | A ClassName for icon-twitch
iconTwitch :: ClassName
iconTwitch = ClassName "icon-twitch"

-- | A ClassName for icon-twitter
iconTwitter :: ClassName
iconTwitter = ClassName "icon-twitter"

-- | A ClassName for icon-underline
iconUnderline :: ClassName
iconUnderline = ClassName "icon-underline"

-- | A ClassName for icon-undo
iconUndo :: ClassName
iconUndo = ClassName "icon-undo"

-- | A ClassName for icon-undo2
iconUndo2 :: ClassName
iconUndo2 = ClassName "icon-undo2"

-- | A ClassName for icon-ungroup
iconUngroup :: ClassName
iconUngroup = ClassName "icon-ungroup"

-- | A ClassName for icon-uni21
iconUni21 :: ClassName
iconUni21 = ClassName "icon-uni21"

-- | A ClassName for icon-uni22
iconUni22 :: ClassName
iconUni22 = ClassName "icon-uni22"

-- | A ClassName for icon-uni23
iconUni23 :: ClassName
iconUni23 = ClassName "icon-uni23"

-- | A ClassName for icon-uni24
iconUni24 :: ClassName
iconUni24 = ClassName "icon-uni24"

-- | A ClassName for icon-uni25
iconUni25 :: ClassName
iconUni25 = ClassName "icon-uni25"

-- | A ClassName for icon-uni26
iconUni26 :: ClassName
iconUni26 = ClassName "icon-uni26"

-- | A ClassName for icon-uni27
iconUni27 :: ClassName
iconUni27 = ClassName "icon-uni27"

-- | A ClassName for icon-uni28
iconUni28 :: ClassName
iconUni28 = ClassName "icon-uni28"

-- | A ClassName for icon-uni29
iconUni29 :: ClassName
iconUni29 = ClassName "icon-uni29"

-- | A ClassName for icon-uni2A
iconUni2a :: ClassName
iconUni2a = ClassName "icon-uni2A"

-- | A ClassName for icon-uni2B
iconUni2b :: ClassName
iconUni2b = ClassName "icon-uni2B"

-- | A ClassName for icon-uni2C
iconUni2c :: ClassName
iconUni2c = ClassName "icon-uni2C"

-- | A ClassName for icon-uni2D
iconUni2d :: ClassName
iconUni2d = ClassName "icon-uni2D"

-- | A ClassName for icon-uni2E
iconUni2e :: ClassName
iconUni2e = ClassName "icon-uni2E"

-- | A ClassName for icon-uni2F
iconUni2f :: ClassName
iconUni2f = ClassName "icon-uni2F"

-- | A ClassName for icon-uni30
iconUni30 :: ClassName
iconUni30 = ClassName "icon-uni30"

-- | A ClassName for icon-uni31
iconUni31 :: ClassName
iconUni31 = ClassName "icon-uni31"

-- | A ClassName for icon-uni32
iconUni32 :: ClassName
iconUni32 = ClassName "icon-uni32"

-- | A ClassName for icon-uni33
iconUni33 :: ClassName
iconUni33 = ClassName "icon-uni33"

-- | A ClassName for icon-uni34
iconUni34 :: ClassName
iconUni34 = ClassName "icon-uni34"

-- | A ClassName for icon-uni35
iconUni35 :: ClassName
iconUni35 = ClassName "icon-uni35"

-- | A ClassName for icon-uni36
iconUni36 :: ClassName
iconUni36 = ClassName "icon-uni36"

-- | A ClassName for icon-uni37
iconUni37 :: ClassName
iconUni37 = ClassName "icon-uni37"

-- | A ClassName for icon-uni38
iconUni38 :: ClassName
iconUni38 = ClassName "icon-uni38"

-- | A ClassName for icon-uni39
iconUni39 :: ClassName
iconUni39 = ClassName "icon-uni39"

-- | A ClassName for icon-uni3A
iconUni3a :: ClassName
iconUni3a = ClassName "icon-uni3A"

-- | A ClassName for icon-uni3B
iconUni3b :: ClassName
iconUni3b = ClassName "icon-uni3B"

-- | A ClassName for icon-uni3C
iconUni3c :: ClassName
iconUni3c = ClassName "icon-uni3C"

-- | A ClassName for icon-uni3D
iconUni3d :: ClassName
iconUni3d = ClassName "icon-uni3D"

-- | A ClassName for icon-uni3E
iconUni3e :: ClassName
iconUni3e = ClassName "icon-uni3E"

-- | A ClassName for icon-uni3F
iconUni3f :: ClassName
iconUni3f = ClassName "icon-uni3F"

-- | A ClassName for icon-uni40
iconUni40 :: ClassName
iconUni40 = ClassName "icon-uni40"

-- | A ClassName for icon-uni41
iconUni41 :: ClassName
iconUni41 = ClassName "icon-uni41"

-- | A ClassName for icon-uni42
iconUni42 :: ClassName
iconUni42 = ClassName "icon-uni42"

-- | A ClassName for icon-uni43
iconUni43 :: ClassName
iconUni43 = ClassName "icon-uni43"

-- | A ClassName for icon-uni44
iconUni44 :: ClassName
iconUni44 = ClassName "icon-uni44"

-- | A ClassName for icon-uni45
iconUni45 :: ClassName
iconUni45 = ClassName "icon-uni45"

-- | A ClassName for icon-uni46
iconUni46 :: ClassName
iconUni46 = ClassName "icon-uni46"

-- | A ClassName for icon-uni47
iconUni47 :: ClassName
iconUni47 = ClassName "icon-uni47"

-- | A ClassName for icon-uni48
iconUni48 :: ClassName
iconUni48 = ClassName "icon-uni48"

-- | A ClassName for icon-uni49
iconUni49 :: ClassName
iconUni49 = ClassName "icon-uni49"

-- | A ClassName for icon-uni4A
iconUni4a :: ClassName
iconUni4a = ClassName "icon-uni4A"

-- | A ClassName for icon-uni4B
iconUni4b :: ClassName
iconUni4b = ClassName "icon-uni4B"

-- | A ClassName for icon-uni4C
iconUni4c :: ClassName
iconUni4c = ClassName "icon-uni4C"

-- | A ClassName for icon-uni4D
iconUni4d :: ClassName
iconUni4d = ClassName "icon-uni4D"

-- | A ClassName for icon-uni4E
iconUni4e :: ClassName
iconUni4e = ClassName "icon-uni4E"

-- | A ClassName for icon-uni4F
iconUni4f :: ClassName
iconUni4f = ClassName "icon-uni4F"

-- | A ClassName for icon-uni50
iconUni50 :: ClassName
iconUni50 = ClassName "icon-uni50"

-- | A ClassName for icon-uni51
iconUni51 :: ClassName
iconUni51 = ClassName "icon-uni51"

-- | A ClassName for icon-uni52
iconUni52 :: ClassName
iconUni52 = ClassName "icon-uni52"

-- | A ClassName for icon-uni53
iconUni53 :: ClassName
iconUni53 = ClassName "icon-uni53"

-- | A ClassName for icon-uni54
iconUni54 :: ClassName
iconUni54 = ClassName "icon-uni54"

-- | A ClassName for icon-uni55
iconUni55 :: ClassName
iconUni55 = ClassName "icon-uni55"

-- | A ClassName for icon-uni56
iconUni56 :: ClassName
iconUni56 = ClassName "icon-uni56"

-- | A ClassName for icon-uni57
iconUni57 :: ClassName
iconUni57 = ClassName "icon-uni57"

-- | A ClassName for icon-uni58
iconUni58 :: ClassName
iconUni58 = ClassName "icon-uni58"

-- | A ClassName for icon-uni59
iconUni59 :: ClassName
iconUni59 = ClassName "icon-uni59"

-- | A ClassName for icon-uni5A
iconUni5a :: ClassName
iconUni5a = ClassName "icon-uni5A"

-- | A ClassName for icon-uni5B
iconUni5b :: ClassName
iconUni5b = ClassName "icon-uni5B"

-- | A ClassName for icon-uni5C
iconUni5c :: ClassName
iconUni5c = ClassName "icon-uni5C"

-- | A ClassName for icon-uni5D
iconUni5d :: ClassName
iconUni5d = ClassName "icon-uni5D"

-- | A ClassName for icon-uni5E
iconUni5e :: ClassName
iconUni5e = ClassName "icon-uni5E"

-- | A ClassName for icon-uni5F
iconUni5f :: ClassName
iconUni5f = ClassName "icon-uni5F"

-- | A ClassName for icon-uni60
iconUni60 :: ClassName
iconUni60 = ClassName "icon-uni60"

-- | A ClassName for icon-uni61
iconUni61 :: ClassName
iconUni61 = ClassName "icon-uni61"

-- | A ClassName for icon-uni62
iconUni62 :: ClassName
iconUni62 = ClassName "icon-uni62"

-- | A ClassName for icon-uni63
iconUni63 :: ClassName
iconUni63 = ClassName "icon-uni63"

-- | A ClassName for icon-uni64
iconUni64 :: ClassName
iconUni64 = ClassName "icon-uni64"

-- | A ClassName for icon-uni65
iconUni65 :: ClassName
iconUni65 = ClassName "icon-uni65"

-- | A ClassName for icon-uni66
iconUni66 :: ClassName
iconUni66 = ClassName "icon-uni66"

-- | A ClassName for icon-uni67
iconUni67 :: ClassName
iconUni67 = ClassName "icon-uni67"

-- | A ClassName for icon-uni68
iconUni68 :: ClassName
iconUni68 = ClassName "icon-uni68"

-- | A ClassName for icon-uni69
iconUni69 :: ClassName
iconUni69 = ClassName "icon-uni69"

-- | A ClassName for icon-uni6A
iconUni6a :: ClassName
iconUni6a = ClassName "icon-uni6A"

-- | A ClassName for icon-uni6B
iconUni6b :: ClassName
iconUni6b = ClassName "icon-uni6B"

-- | A ClassName for icon-uni6C
iconUni6c :: ClassName
iconUni6c = ClassName "icon-uni6C"

-- | A ClassName for icon-uni6D
iconUni6d :: ClassName
iconUni6d = ClassName "icon-uni6D"

-- | A ClassName for icon-uni6E
iconUni6e :: ClassName
iconUni6e = ClassName "icon-uni6E"

-- | A ClassName for icon-uni6F
iconUni6f :: ClassName
iconUni6f = ClassName "icon-uni6F"

-- | A ClassName for icon-uni70
iconUni70 :: ClassName
iconUni70 = ClassName "icon-uni70"

-- | A ClassName for icon-uni71
iconUni71 :: ClassName
iconUni71 = ClassName "icon-uni71"

-- | A ClassName for icon-uni72
iconUni72 :: ClassName
iconUni72 = ClassName "icon-uni72"

-- | A ClassName for icon-uni73
iconUni73 :: ClassName
iconUni73 = ClassName "icon-uni73"

-- | A ClassName for icon-uni74
iconUni74 :: ClassName
iconUni74 = ClassName "icon-uni74"

-- | A ClassName for icon-uni75
iconUni75 :: ClassName
iconUni75 = ClassName "icon-uni75"

-- | A ClassName for icon-uni76
iconUni76 :: ClassName
iconUni76 = ClassName "icon-uni76"

-- | A ClassName for icon-uni77
iconUni77 :: ClassName
iconUni77 = ClassName "icon-uni77"

-- | A ClassName for icon-uni78
iconUni78 :: ClassName
iconUni78 = ClassName "icon-uni78"

-- | A ClassName for icon-uni79
iconUni79 :: ClassName
iconUni79 = ClassName "icon-uni79"

-- | A ClassName for icon-uni7A
iconUni7a :: ClassName
iconUni7a = ClassName "icon-uni7A"

-- | A ClassName for icon-uni7B
iconUni7b :: ClassName
iconUni7b = ClassName "icon-uni7B"

-- | A ClassName for icon-uni7C
iconUni7c :: ClassName
iconUni7c = ClassName "icon-uni7C"

-- | A ClassName for icon-uni7D
iconUni7d :: ClassName
iconUni7d = ClassName "icon-uni7D"

-- | A ClassName for icon-uni7E
iconUni7e :: ClassName
iconUni7e = ClassName "icon-uni7E"

-- | A ClassName for icon-uniA9
iconUnia9 :: ClassName
iconUnia9 = ClassName "icon-uniA9"

-- | A ClassName for icon-unlocked
iconUnlocked :: ClassName
iconUnlocked = ClassName "icon-unlocked"

-- | A ClassName for icon-upload
iconUpload :: ClassName
iconUpload = ClassName "icon-upload"

-- | A ClassName for icon-upload2
iconUpload2 :: ClassName
iconUpload2 = ClassName "icon-upload2"

-- | A ClassName for icon-upload3
iconUpload3 :: ClassName
iconUpload3 = ClassName "icon-upload3"

-- | A ClassName for icon-user
iconUser :: ClassName
iconUser = ClassName "icon-user"

-- | A ClassName for icon-user-check
iconUserCheck :: ClassName
iconUserCheck = ClassName "icon-user-check"

-- | A ClassName for icon-user-minus
iconUserMinus :: ClassName
iconUserMinus = ClassName "icon-user-minus"

-- | A ClassName for icon-user-plus
iconUserPlus :: ClassName
iconUserPlus = ClassName "icon-user-plus"

-- | A ClassName for icon-user-tie
iconUserTie :: ClassName
iconUserTie = ClassName "icon-user-tie"

-- | A ClassName for icon-users
iconUsers :: ClassName
iconUsers = ClassName "icon-users"

-- | A ClassName for icon-video-camera
iconVideoCamera :: ClassName
iconVideoCamera = ClassName "icon-video-camera"

-- | A ClassName for icon-vimeo
iconVimeo :: ClassName
iconVimeo = ClassName "icon-vimeo"

-- | A ClassName for icon-vimeo2
iconVimeo2 :: ClassName
iconVimeo2 = ClassName "icon-vimeo2"

-- | A ClassName for icon-vine
iconVine :: ClassName
iconVine = ClassName "icon-vine"

-- | A ClassName for icon-vk
iconVk :: ClassName
iconVk = ClassName "icon-vk"

-- | A ClassName for icon-volume-decrease
iconVolumeDecrease :: ClassName
iconVolumeDecrease = ClassName "icon-volume-decrease"

-- | A ClassName for icon-volume-high
iconVolumeHigh :: ClassName
iconVolumeHigh = ClassName "icon-volume-high"

-- | A ClassName for icon-volume-increase
iconVolumeIncrease :: ClassName
iconVolumeIncrease = ClassName "icon-volume-increase"

-- | A ClassName for icon-volume-low
iconVolumeLow :: ClassName
iconVolumeLow = ClassName "icon-volume-low"

-- | A ClassName for icon-volume-medium
iconVolumeMedium :: ClassName
iconVolumeMedium = ClassName "icon-volume-medium"

-- | A ClassName for icon-volume-mute
iconVolumeMute :: ClassName
iconVolumeMute = ClassName "icon-volume-mute"

-- | A ClassName for icon-volume-mute2
iconVolumeMute2 :: ClassName
iconVolumeMute2 = ClassName "icon-volume-mute2"

-- | A ClassName for icon-warning
iconWarning :: ClassName
iconWarning = ClassName "icon-warning"

-- | A ClassName for icon-whatsapp
iconWhatsapp :: ClassName
iconWhatsapp = ClassName "icon-whatsapp"

-- | A ClassName for icon-wikipedia
iconWikipedia :: ClassName
iconWikipedia = ClassName "icon-wikipedia"

-- | A ClassName for icon-windows
iconWindows :: ClassName
iconWindows = ClassName "icon-windows"

-- | A ClassName for icon-windows8
iconWindows8 :: ClassName
iconWindows8 = ClassName "icon-windows8"

-- | A ClassName for icon-wink
iconWink :: ClassName
iconWink = ClassName "icon-wink"

-- | A ClassName for icon-wink2
iconWink2 :: ClassName
iconWink2 = ClassName "icon-wink2"

-- | A ClassName for icon-woman
iconWoman :: ClassName
iconWoman = ClassName "icon-woman"

-- | A ClassName for icon-wondering
iconWondering :: ClassName
iconWondering = ClassName "icon-wondering"

-- | A ClassName for icon-wondering2
iconWondering2 :: ClassName
iconWondering2 = ClassName "icon-wondering2"

-- | A ClassName for icon-wordpress
iconWordpress :: ClassName
iconWordpress = ClassName "icon-wordpress"

-- | A ClassName for icon-wrench
iconWrench :: ClassName
iconWrench = ClassName "icon-wrench"

-- | A ClassName for icon-xing
iconXing :: ClassName
iconXing = ClassName "icon-xing"

-- | A ClassName for icon-xing2
iconXing2 :: ClassName
iconXing2 = ClassName "icon-xing2"

-- | A ClassName for icon-yahoo
iconYahoo :: ClassName
iconYahoo = ClassName "icon-yahoo"

-- | A ClassName for icon-yahoo2
iconYahoo2 :: ClassName
iconYahoo2 = ClassName "icon-yahoo2"

-- | A ClassName for icon-yelp
iconYelp :: ClassName
iconYelp = ClassName "icon-yelp"

-- | A ClassName for icon-youtube
iconYoutube :: ClassName
iconYoutube = ClassName "icon-youtube"

-- | A ClassName for icon-youtube2
iconYoutube2 :: ClassName
iconYoutube2 = ClassName "icon-youtube2"

-- | A ClassName for icon-zoom-in
iconZoomIn :: ClassName
iconZoomIn = ClassName "icon-zoom-in"

-- | A ClassName for icon-zoom-out
iconZoomOut :: ClassName
iconZoomOut = ClassName "icon-zoom-out"

