{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Icon.Raw.OpenIconic
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= OpenIconic

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Icon.Raw.OpenIconic where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for oi
oi :: ClassName
oi = ClassName "oi"

-- | A ClassName for oi-align-center
oiAlignCenter :: ClassName
oiAlignCenter = ClassName "oi-align-center"

-- | A ClassName for oi-align-left
oiAlignLeft :: ClassName
oiAlignLeft = ClassName "oi-align-left"

-- | A ClassName for oi-align-right
oiAlignRight :: ClassName
oiAlignRight = ClassName "oi-align-right"

-- | A ClassName for oi-flip-horizontal
oiFlipHorizontal :: ClassName
oiFlipHorizontal = ClassName "oi-flip-horizontal"

-- | A ClassName for oi-flip-horizontal-vertical
oiFlipHorizontalVertical :: ClassName
oiFlipHorizontalVertical = ClassName "oi-flip-horizontal-vertical"

-- | A ClassName for oi-flip-vertical
oiFlipVertical :: ClassName
oiFlipVertical = ClassName "oi-flip-vertical"

-- | A ClassName for oi-text-replace
oiTextReplace :: ClassName
oiTextReplace = ClassName "oi-text-replace"

