{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Icon.Raw.OpenIconicBS
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= OpenIconicBS

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Icon.Raw.OpenIconicBS where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for oi
oi :: ClassName
oi = ClassName "oi"

-- | A ClassName for oi-account-login
oiAccountLogin :: ClassName
oiAccountLogin = ClassName "oi-account-login"

-- | A ClassName for oi-account-logout
oiAccountLogout :: ClassName
oiAccountLogout = ClassName "oi-account-logout"

-- | A ClassName for oi-action-redo
oiActionRedo :: ClassName
oiActionRedo = ClassName "oi-action-redo"

-- | A ClassName for oi-action-undo
oiActionUndo :: ClassName
oiActionUndo = ClassName "oi-action-undo"

-- | A ClassName for oi-align-center
oiAlignCenter :: ClassName
oiAlignCenter = ClassName "oi-align-center"

-- | A ClassName for oi-align-left
oiAlignLeft :: ClassName
oiAlignLeft = ClassName "oi-align-left"

-- | A ClassName for oi-align-right
oiAlignRight :: ClassName
oiAlignRight = ClassName "oi-align-right"

-- | A ClassName for oi-aperture
oiAperture :: ClassName
oiAperture = ClassName "oi-aperture"

-- | A ClassName for oi-arrow-bottom
oiArrowBottom :: ClassName
oiArrowBottom = ClassName "oi-arrow-bottom"

-- | A ClassName for oi-arrow-circle-bottom
oiArrowCircleBottom :: ClassName
oiArrowCircleBottom = ClassName "oi-arrow-circle-bottom"

-- | A ClassName for oi-arrow-circle-left
oiArrowCircleLeft :: ClassName
oiArrowCircleLeft = ClassName "oi-arrow-circle-left"

-- | A ClassName for oi-arrow-circle-right
oiArrowCircleRight :: ClassName
oiArrowCircleRight = ClassName "oi-arrow-circle-right"

-- | A ClassName for oi-arrow-circle-top
oiArrowCircleTop :: ClassName
oiArrowCircleTop = ClassName "oi-arrow-circle-top"

-- | A ClassName for oi-arrow-left
oiArrowLeft :: ClassName
oiArrowLeft = ClassName "oi-arrow-left"

-- | A ClassName for oi-arrow-right
oiArrowRight :: ClassName
oiArrowRight = ClassName "oi-arrow-right"

-- | A ClassName for oi-arrow-thick-bottom
oiArrowThickBottom :: ClassName
oiArrowThickBottom = ClassName "oi-arrow-thick-bottom"

-- | A ClassName for oi-arrow-thick-left
oiArrowThickLeft :: ClassName
oiArrowThickLeft = ClassName "oi-arrow-thick-left"

-- | A ClassName for oi-arrow-thick-right
oiArrowThickRight :: ClassName
oiArrowThickRight = ClassName "oi-arrow-thick-right"

-- | A ClassName for oi-arrow-thick-top
oiArrowThickTop :: ClassName
oiArrowThickTop = ClassName "oi-arrow-thick-top"

-- | A ClassName for oi-arrow-top
oiArrowTop :: ClassName
oiArrowTop = ClassName "oi-arrow-top"

-- | A ClassName for oi-audio
oiAudio :: ClassName
oiAudio = ClassName "oi-audio"

-- | A ClassName for oi-audio-spectrum
oiAudioSpectrum :: ClassName
oiAudioSpectrum = ClassName "oi-audio-spectrum"

-- | A ClassName for oi-badge
oiBadge :: ClassName
oiBadge = ClassName "oi-badge"

-- | A ClassName for oi-ban
oiBan :: ClassName
oiBan = ClassName "oi-ban"

-- | A ClassName for oi-bar-chart
oiBarChart :: ClassName
oiBarChart = ClassName "oi-bar-chart"

-- | A ClassName for oi-basket
oiBasket :: ClassName
oiBasket = ClassName "oi-basket"

-- | A ClassName for oi-battery-empty
oiBatteryEmpty :: ClassName
oiBatteryEmpty = ClassName "oi-battery-empty"

-- | A ClassName for oi-battery-full
oiBatteryFull :: ClassName
oiBatteryFull = ClassName "oi-battery-full"

-- | A ClassName for oi-beaker
oiBeaker :: ClassName
oiBeaker = ClassName "oi-beaker"

-- | A ClassName for oi-bell
oiBell :: ClassName
oiBell = ClassName "oi-bell"

-- | A ClassName for oi-bluetooth
oiBluetooth :: ClassName
oiBluetooth = ClassName "oi-bluetooth"

-- | A ClassName for oi-bold
oiBold :: ClassName
oiBold = ClassName "oi-bold"

-- | A ClassName for oi-bolt
oiBolt :: ClassName
oiBolt = ClassName "oi-bolt"

-- | A ClassName for oi-book
oiBook :: ClassName
oiBook = ClassName "oi-book"

-- | A ClassName for oi-bookmark
oiBookmark :: ClassName
oiBookmark = ClassName "oi-bookmark"

-- | A ClassName for oi-box
oiBox :: ClassName
oiBox = ClassName "oi-box"

-- | A ClassName for oi-briefcase
oiBriefcase :: ClassName
oiBriefcase = ClassName "oi-briefcase"

-- | A ClassName for oi-british-pound
oiBritishPound :: ClassName
oiBritishPound = ClassName "oi-british-pound"

-- | A ClassName for oi-browser
oiBrowser :: ClassName
oiBrowser = ClassName "oi-browser"

-- | A ClassName for oi-brush
oiBrush :: ClassName
oiBrush = ClassName "oi-brush"

-- | A ClassName for oi-bug
oiBug :: ClassName
oiBug = ClassName "oi-bug"

-- | A ClassName for oi-bullhorn
oiBullhorn :: ClassName
oiBullhorn = ClassName "oi-bullhorn"

-- | A ClassName for oi-calculator
oiCalculator :: ClassName
oiCalculator = ClassName "oi-calculator"

-- | A ClassName for oi-calendar
oiCalendar :: ClassName
oiCalendar = ClassName "oi-calendar"

-- | A ClassName for oi-camera-slr
oiCameraSlr :: ClassName
oiCameraSlr = ClassName "oi-camera-slr"

-- | A ClassName for oi-caret-bottom
oiCaretBottom :: ClassName
oiCaretBottom = ClassName "oi-caret-bottom"

-- | A ClassName for oi-caret-left
oiCaretLeft :: ClassName
oiCaretLeft = ClassName "oi-caret-left"

-- | A ClassName for oi-caret-right
oiCaretRight :: ClassName
oiCaretRight = ClassName "oi-caret-right"

-- | A ClassName for oi-caret-top
oiCaretTop :: ClassName
oiCaretTop = ClassName "oi-caret-top"

-- | A ClassName for oi-cart
oiCart :: ClassName
oiCart = ClassName "oi-cart"

-- | A ClassName for oi-chat
oiChat :: ClassName
oiChat = ClassName "oi-chat"

-- | A ClassName for oi-check
oiCheck :: ClassName
oiCheck = ClassName "oi-check"

-- | A ClassName for oi-chevron-bottom
oiChevronBottom :: ClassName
oiChevronBottom = ClassName "oi-chevron-bottom"

-- | A ClassName for oi-chevron-left
oiChevronLeft :: ClassName
oiChevronLeft = ClassName "oi-chevron-left"

-- | A ClassName for oi-chevron-right
oiChevronRight :: ClassName
oiChevronRight = ClassName "oi-chevron-right"

-- | A ClassName for oi-chevron-top
oiChevronTop :: ClassName
oiChevronTop = ClassName "oi-chevron-top"

-- | A ClassName for oi-circle-check
oiCircleCheck :: ClassName
oiCircleCheck = ClassName "oi-circle-check"

-- | A ClassName for oi-circle-x
oiCircleX :: ClassName
oiCircleX = ClassName "oi-circle-x"

-- | A ClassName for oi-clipboard
oiClipboard :: ClassName
oiClipboard = ClassName "oi-clipboard"

-- | A ClassName for oi-clock
oiClock :: ClassName
oiClock = ClassName "oi-clock"

-- | A ClassName for oi-cloud
oiCloud :: ClassName
oiCloud = ClassName "oi-cloud"

-- | A ClassName for oi-cloud-download
oiCloudDownload :: ClassName
oiCloudDownload = ClassName "oi-cloud-download"

-- | A ClassName for oi-cloud-upload
oiCloudUpload :: ClassName
oiCloudUpload = ClassName "oi-cloud-upload"

-- | A ClassName for oi-cloudy
oiCloudy :: ClassName
oiCloudy = ClassName "oi-cloudy"

-- | A ClassName for oi-code
oiCode :: ClassName
oiCode = ClassName "oi-code"

-- | A ClassName for oi-cog
oiCog :: ClassName
oiCog = ClassName "oi-cog"

-- | A ClassName for oi-collapse-down
oiCollapseDown :: ClassName
oiCollapseDown = ClassName "oi-collapse-down"

-- | A ClassName for oi-collapse-left
oiCollapseLeft :: ClassName
oiCollapseLeft = ClassName "oi-collapse-left"

-- | A ClassName for oi-collapse-right
oiCollapseRight :: ClassName
oiCollapseRight = ClassName "oi-collapse-right"

-- | A ClassName for oi-collapse-up
oiCollapseUp :: ClassName
oiCollapseUp = ClassName "oi-collapse-up"

-- | A ClassName for oi-command
oiCommand :: ClassName
oiCommand = ClassName "oi-command"

-- | A ClassName for oi-comment-square
oiCommentSquare :: ClassName
oiCommentSquare = ClassName "oi-comment-square"

-- | A ClassName for oi-compass
oiCompass :: ClassName
oiCompass = ClassName "oi-compass"

-- | A ClassName for oi-contrast
oiContrast :: ClassName
oiContrast = ClassName "oi-contrast"

-- | A ClassName for oi-copywriting
oiCopywriting :: ClassName
oiCopywriting = ClassName "oi-copywriting"

-- | A ClassName for oi-credit-card
oiCreditCard :: ClassName
oiCreditCard = ClassName "oi-credit-card"

-- | A ClassName for oi-crop
oiCrop :: ClassName
oiCrop = ClassName "oi-crop"

-- | A ClassName for oi-dashboard
oiDashboard :: ClassName
oiDashboard = ClassName "oi-dashboard"

-- | A ClassName for oi-data-transfer-download
oiDataTransferDownload :: ClassName
oiDataTransferDownload = ClassName "oi-data-transfer-download"

-- | A ClassName for oi-data-transfer-upload
oiDataTransferUpload :: ClassName
oiDataTransferUpload = ClassName "oi-data-transfer-upload"

-- | A ClassName for oi-delete
oiDelete :: ClassName
oiDelete = ClassName "oi-delete"

-- | A ClassName for oi-dial
oiDial :: ClassName
oiDial = ClassName "oi-dial"

-- | A ClassName for oi-document
oiDocument :: ClassName
oiDocument = ClassName "oi-document"

-- | A ClassName for oi-dollar
oiDollar :: ClassName
oiDollar = ClassName "oi-dollar"

-- | A ClassName for oi-double-quote-sans-left
oiDoubleQuoteSansLeft :: ClassName
oiDoubleQuoteSansLeft = ClassName "oi-double-quote-sans-left"

-- | A ClassName for oi-double-quote-sans-right
oiDoubleQuoteSansRight :: ClassName
oiDoubleQuoteSansRight = ClassName "oi-double-quote-sans-right"

-- | A ClassName for oi-double-quote-serif-left
oiDoubleQuoteSerifLeft :: ClassName
oiDoubleQuoteSerifLeft = ClassName "oi-double-quote-serif-left"

-- | A ClassName for oi-double-quote-serif-right
oiDoubleQuoteSerifRight :: ClassName
oiDoubleQuoteSerifRight = ClassName "oi-double-quote-serif-right"

-- | A ClassName for oi-droplet
oiDroplet :: ClassName
oiDroplet = ClassName "oi-droplet"

-- | A ClassName for oi-eject
oiEject :: ClassName
oiEject = ClassName "oi-eject"

-- | A ClassName for oi-elevator
oiElevator :: ClassName
oiElevator = ClassName "oi-elevator"

-- | A ClassName for oi-ellipses
oiEllipses :: ClassName
oiEllipses = ClassName "oi-ellipses"

-- | A ClassName for oi-envelope-closed
oiEnvelopeClosed :: ClassName
oiEnvelopeClosed = ClassName "oi-envelope-closed"

-- | A ClassName for oi-envelope-open
oiEnvelopeOpen :: ClassName
oiEnvelopeOpen = ClassName "oi-envelope-open"

-- | A ClassName for oi-euro
oiEuro :: ClassName
oiEuro = ClassName "oi-euro"

-- | A ClassName for oi-excerpt
oiExcerpt :: ClassName
oiExcerpt = ClassName "oi-excerpt"

-- | A ClassName for oi-expand-down
oiExpandDown :: ClassName
oiExpandDown = ClassName "oi-expand-down"

-- | A ClassName for oi-expand-left
oiExpandLeft :: ClassName
oiExpandLeft = ClassName "oi-expand-left"

-- | A ClassName for oi-expand-right
oiExpandRight :: ClassName
oiExpandRight = ClassName "oi-expand-right"

-- | A ClassName for oi-expand-up
oiExpandUp :: ClassName
oiExpandUp = ClassName "oi-expand-up"

-- | A ClassName for oi-external-link
oiExternalLink :: ClassName
oiExternalLink = ClassName "oi-external-link"

-- | A ClassName for oi-eye
oiEye :: ClassName
oiEye = ClassName "oi-eye"

-- | A ClassName for oi-eyedropper
oiEyedropper :: ClassName
oiEyedropper = ClassName "oi-eyedropper"

-- | A ClassName for oi-file
oiFile :: ClassName
oiFile = ClassName "oi-file"

-- | A ClassName for oi-fire
oiFire :: ClassName
oiFire = ClassName "oi-fire"

-- | A ClassName for oi-flag
oiFlag :: ClassName
oiFlag = ClassName "oi-flag"

-- | A ClassName for oi-flash
oiFlash :: ClassName
oiFlash = ClassName "oi-flash"

-- | A ClassName for oi-flip-horizontal
oiFlipHorizontal :: ClassName
oiFlipHorizontal = ClassName "oi-flip-horizontal"

-- | A ClassName for oi-flip-horizontal-vertical
oiFlipHorizontalVertical :: ClassName
oiFlipHorizontalVertical = ClassName "oi-flip-horizontal-vertical"

-- | A ClassName for oi-flip-vertical
oiFlipVertical :: ClassName
oiFlipVertical = ClassName "oi-flip-vertical"

-- | A ClassName for oi-folder
oiFolder :: ClassName
oiFolder = ClassName "oi-folder"

-- | A ClassName for oi-fork
oiFork :: ClassName
oiFork = ClassName "oi-fork"

-- | A ClassName for oi-fullscreen-enter
oiFullscreenEnter :: ClassName
oiFullscreenEnter = ClassName "oi-fullscreen-enter"

-- | A ClassName for oi-fullscreen-exit
oiFullscreenExit :: ClassName
oiFullscreenExit = ClassName "oi-fullscreen-exit"

-- | A ClassName for oi-globe
oiGlobe :: ClassName
oiGlobe = ClassName "oi-globe"

-- | A ClassName for oi-graph
oiGraph :: ClassName
oiGraph = ClassName "oi-graph"

-- | A ClassName for oi-grid-four-up
oiGridFourUp :: ClassName
oiGridFourUp = ClassName "oi-grid-four-up"

-- | A ClassName for oi-grid-three-up
oiGridThreeUp :: ClassName
oiGridThreeUp = ClassName "oi-grid-three-up"

-- | A ClassName for oi-grid-two-up
oiGridTwoUp :: ClassName
oiGridTwoUp = ClassName "oi-grid-two-up"

-- | A ClassName for oi-hard-drive
oiHardDrive :: ClassName
oiHardDrive = ClassName "oi-hard-drive"

-- | A ClassName for oi-header
oiHeader :: ClassName
oiHeader = ClassName "oi-header"

-- | A ClassName for oi-headphones
oiHeadphones :: ClassName
oiHeadphones = ClassName "oi-headphones"

-- | A ClassName for oi-heart
oiHeart :: ClassName
oiHeart = ClassName "oi-heart"

-- | A ClassName for oi-home
oiHome :: ClassName
oiHome = ClassName "oi-home"

-- | A ClassName for oi-image
oiImage :: ClassName
oiImage = ClassName "oi-image"

-- | A ClassName for oi-inbox
oiInbox :: ClassName
oiInbox = ClassName "oi-inbox"

-- | A ClassName for oi-infinity
oiInfinity :: ClassName
oiInfinity = ClassName "oi-infinity"

-- | A ClassName for oi-info
oiInfo :: ClassName
oiInfo = ClassName "oi-info"

-- | A ClassName for oi-italic
oiItalic :: ClassName
oiItalic = ClassName "oi-italic"

-- | A ClassName for oi-justify-center
oiJustifyCenter :: ClassName
oiJustifyCenter = ClassName "oi-justify-center"

-- | A ClassName for oi-justify-left
oiJustifyLeft :: ClassName
oiJustifyLeft = ClassName "oi-justify-left"

-- | A ClassName for oi-justify-right
oiJustifyRight :: ClassName
oiJustifyRight = ClassName "oi-justify-right"

-- | A ClassName for oi-key
oiKey :: ClassName
oiKey = ClassName "oi-key"

-- | A ClassName for oi-laptop
oiLaptop :: ClassName
oiLaptop = ClassName "oi-laptop"

-- | A ClassName for oi-layers
oiLayers :: ClassName
oiLayers = ClassName "oi-layers"

-- | A ClassName for oi-lightbulb
oiLightbulb :: ClassName
oiLightbulb = ClassName "oi-lightbulb"

-- | A ClassName for oi-link-broken
oiLinkBroken :: ClassName
oiLinkBroken = ClassName "oi-link-broken"

-- | A ClassName for oi-link-intact
oiLinkIntact :: ClassName
oiLinkIntact = ClassName "oi-link-intact"

-- | A ClassName for oi-list
oiList :: ClassName
oiList = ClassName "oi-list"

-- | A ClassName for oi-list-rich
oiListRich :: ClassName
oiListRich = ClassName "oi-list-rich"

-- | A ClassName for oi-location
oiLocation :: ClassName
oiLocation = ClassName "oi-location"

-- | A ClassName for oi-lock-locked
oiLockLocked :: ClassName
oiLockLocked = ClassName "oi-lock-locked"

-- | A ClassName for oi-lock-unlocked
oiLockUnlocked :: ClassName
oiLockUnlocked = ClassName "oi-lock-unlocked"

-- | A ClassName for oi-loop
oiLoop :: ClassName
oiLoop = ClassName "oi-loop"

-- | A ClassName for oi-loop-circular
oiLoopCircular :: ClassName
oiLoopCircular = ClassName "oi-loop-circular"

-- | A ClassName for oi-loop-square
oiLoopSquare :: ClassName
oiLoopSquare = ClassName "oi-loop-square"

-- | A ClassName for oi-magnifying-glass
oiMagnifyingGlass :: ClassName
oiMagnifyingGlass = ClassName "oi-magnifying-glass"

-- | A ClassName for oi-map
oiMap :: ClassName
oiMap = ClassName "oi-map"

-- | A ClassName for oi-map-marker
oiMapMarker :: ClassName
oiMapMarker = ClassName "oi-map-marker"

-- | A ClassName for oi-media-pause
oiMediaPause :: ClassName
oiMediaPause = ClassName "oi-media-pause"

-- | A ClassName for oi-media-play
oiMediaPlay :: ClassName
oiMediaPlay = ClassName "oi-media-play"

-- | A ClassName for oi-media-record
oiMediaRecord :: ClassName
oiMediaRecord = ClassName "oi-media-record"

-- | A ClassName for oi-media-skip-backward
oiMediaSkipBackward :: ClassName
oiMediaSkipBackward = ClassName "oi-media-skip-backward"

-- | A ClassName for oi-media-skip-forward
oiMediaSkipForward :: ClassName
oiMediaSkipForward = ClassName "oi-media-skip-forward"

-- | A ClassName for oi-media-step-backward
oiMediaStepBackward :: ClassName
oiMediaStepBackward = ClassName "oi-media-step-backward"

-- | A ClassName for oi-media-step-forward
oiMediaStepForward :: ClassName
oiMediaStepForward = ClassName "oi-media-step-forward"

-- | A ClassName for oi-media-stop
oiMediaStop :: ClassName
oiMediaStop = ClassName "oi-media-stop"

-- | A ClassName for oi-medical-cross
oiMedicalCross :: ClassName
oiMedicalCross = ClassName "oi-medical-cross"

-- | A ClassName for oi-menu
oiMenu :: ClassName
oiMenu = ClassName "oi-menu"

-- | A ClassName for oi-microphone
oiMicrophone :: ClassName
oiMicrophone = ClassName "oi-microphone"

-- | A ClassName for oi-minus
oiMinus :: ClassName
oiMinus = ClassName "oi-minus"

-- | A ClassName for oi-monitor
oiMonitor :: ClassName
oiMonitor = ClassName "oi-monitor"

-- | A ClassName for oi-moon
oiMoon :: ClassName
oiMoon = ClassName "oi-moon"

-- | A ClassName for oi-move
oiMove :: ClassName
oiMove = ClassName "oi-move"

-- | A ClassName for oi-musical-note
oiMusicalNote :: ClassName
oiMusicalNote = ClassName "oi-musical-note"

-- | A ClassName for oi-paperclip
oiPaperclip :: ClassName
oiPaperclip = ClassName "oi-paperclip"

-- | A ClassName for oi-pencil
oiPencil :: ClassName
oiPencil = ClassName "oi-pencil"

-- | A ClassName for oi-people
oiPeople :: ClassName
oiPeople = ClassName "oi-people"

-- | A ClassName for oi-person
oiPerson :: ClassName
oiPerson = ClassName "oi-person"

-- | A ClassName for oi-phone
oiPhone :: ClassName
oiPhone = ClassName "oi-phone"

-- | A ClassName for oi-pie-chart
oiPieChart :: ClassName
oiPieChart = ClassName "oi-pie-chart"

-- | A ClassName for oi-pin
oiPin :: ClassName
oiPin = ClassName "oi-pin"

-- | A ClassName for oi-play-circle
oiPlayCircle :: ClassName
oiPlayCircle = ClassName "oi-play-circle"

-- | A ClassName for oi-plus
oiPlus :: ClassName
oiPlus = ClassName "oi-plus"

-- | A ClassName for oi-power-standby
oiPowerStandby :: ClassName
oiPowerStandby = ClassName "oi-power-standby"

-- | A ClassName for oi-print
oiPrint :: ClassName
oiPrint = ClassName "oi-print"

-- | A ClassName for oi-project
oiProject :: ClassName
oiProject = ClassName "oi-project"

-- | A ClassName for oi-pulse
oiPulse :: ClassName
oiPulse = ClassName "oi-pulse"

-- | A ClassName for oi-puzzle-piece
oiPuzzlePiece :: ClassName
oiPuzzlePiece = ClassName "oi-puzzle-piece"

-- | A ClassName for oi-question-mark
oiQuestionMark :: ClassName
oiQuestionMark = ClassName "oi-question-mark"

-- | A ClassName for oi-rain
oiRain :: ClassName
oiRain = ClassName "oi-rain"

-- | A ClassName for oi-random
oiRandom :: ClassName
oiRandom = ClassName "oi-random"

-- | A ClassName for oi-reload
oiReload :: ClassName
oiReload = ClassName "oi-reload"

-- | A ClassName for oi-resize-both
oiResizeBoth :: ClassName
oiResizeBoth = ClassName "oi-resize-both"

-- | A ClassName for oi-resize-height
oiResizeHeight :: ClassName
oiResizeHeight = ClassName "oi-resize-height"

-- | A ClassName for oi-resize-width
oiResizeWidth :: ClassName
oiResizeWidth = ClassName "oi-resize-width"

-- | A ClassName for oi-rss
oiRss :: ClassName
oiRss = ClassName "oi-rss"

-- | A ClassName for oi-rss-alt
oiRssAlt :: ClassName
oiRssAlt = ClassName "oi-rss-alt"

-- | A ClassName for oi-script
oiScript :: ClassName
oiScript = ClassName "oi-script"

-- | A ClassName for oi-share
oiShare :: ClassName
oiShare = ClassName "oi-share"

-- | A ClassName for oi-share-boxed
oiShareBoxed :: ClassName
oiShareBoxed = ClassName "oi-share-boxed"

-- | A ClassName for oi-shield
oiShield :: ClassName
oiShield = ClassName "oi-shield"

-- | A ClassName for oi-signal
oiSignal :: ClassName
oiSignal = ClassName "oi-signal"

-- | A ClassName for oi-signpost
oiSignpost :: ClassName
oiSignpost = ClassName "oi-signpost"

-- | A ClassName for oi-sort-ascending
oiSortAscending :: ClassName
oiSortAscending = ClassName "oi-sort-ascending"

-- | A ClassName for oi-sort-descending
oiSortDescending :: ClassName
oiSortDescending = ClassName "oi-sort-descending"

-- | A ClassName for oi-spreadsheet
oiSpreadsheet :: ClassName
oiSpreadsheet = ClassName "oi-spreadsheet"

-- | A ClassName for oi-star
oiStar :: ClassName
oiStar = ClassName "oi-star"

-- | A ClassName for oi-sun
oiSun :: ClassName
oiSun = ClassName "oi-sun"

-- | A ClassName for oi-tablet
oiTablet :: ClassName
oiTablet = ClassName "oi-tablet"

-- | A ClassName for oi-tag
oiTag :: ClassName
oiTag = ClassName "oi-tag"

-- | A ClassName for oi-tags
oiTags :: ClassName
oiTags = ClassName "oi-tags"

-- | A ClassName for oi-target
oiTarget :: ClassName
oiTarget = ClassName "oi-target"

-- | A ClassName for oi-task
oiTask :: ClassName
oiTask = ClassName "oi-task"

-- | A ClassName for oi-terminal
oiTerminal :: ClassName
oiTerminal = ClassName "oi-terminal"

-- | A ClassName for oi-text
oiText :: ClassName
oiText = ClassName "oi-text"

-- | A ClassName for oi-thumb-down
oiThumbDown :: ClassName
oiThumbDown = ClassName "oi-thumb-down"

-- | A ClassName for oi-thumb-up
oiThumbUp :: ClassName
oiThumbUp = ClassName "oi-thumb-up"

-- | A ClassName for oi-timer
oiTimer :: ClassName
oiTimer = ClassName "oi-timer"

-- | A ClassName for oi-transfer
oiTransfer :: ClassName
oiTransfer = ClassName "oi-transfer"

-- | A ClassName for oi-trash
oiTrash :: ClassName
oiTrash = ClassName "oi-trash"

-- | A ClassName for oi-underline
oiUnderline :: ClassName
oiUnderline = ClassName "oi-underline"

-- | A ClassName for oi-vertical-align-bottom
oiVerticalAlignBottom :: ClassName
oiVerticalAlignBottom = ClassName "oi-vertical-align-bottom"

-- | A ClassName for oi-vertical-align-center
oiVerticalAlignCenter :: ClassName
oiVerticalAlignCenter = ClassName "oi-vertical-align-center"

-- | A ClassName for oi-vertical-align-top
oiVerticalAlignTop :: ClassName
oiVerticalAlignTop = ClassName "oi-vertical-align-top"

-- | A ClassName for oi-video
oiVideo :: ClassName
oiVideo = ClassName "oi-video"

-- | A ClassName for oi-volume-high
oiVolumeHigh :: ClassName
oiVolumeHigh = ClassName "oi-volume-high"

-- | A ClassName for oi-volume-low
oiVolumeLow :: ClassName
oiVolumeLow = ClassName "oi-volume-low"

-- | A ClassName for oi-volume-off
oiVolumeOff :: ClassName
oiVolumeOff = ClassName "oi-volume-off"

-- | A ClassName for oi-warning
oiWarning :: ClassName
oiWarning = ClassName "oi-warning"

-- | A ClassName for oi-wifi
oiWifi :: ClassName
oiWifi = ClassName "oi-wifi"

-- | A ClassName for oi-wrench
oiWrench :: ClassName
oiWrench = ClassName "oi-wrench"

-- | A ClassName for oi-x
oiX :: ClassName
oiX = ClassName "oi-x"

-- | A ClassName for oi-yen
oiYen :: ClassName
oiYen = ClassName "oi-yen"

-- | A ClassName for oi-zoom-in
oiZoomIn :: ClassName
oiZoomIn = ClassName "oi-zoom-in"

-- | A ClassName for oi-zoom-out
oiZoomOut :: ClassName
oiZoomOut = ClassName "oi-zoom-out"

