{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Icon.Raw.Typicons
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= Typicons

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Icon.Raw.Typicons where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for typcn
typcn :: ClassName
typcn = ClassName "typcn"

-- | A ClassName for typcn-adjust-brightness
typcnAdjustBrightness :: ClassName
typcnAdjustBrightness = ClassName "typcn-adjust-brightness"

-- | A ClassName for typcn-adjust-contrast
typcnAdjustContrast :: ClassName
typcnAdjustContrast = ClassName "typcn-adjust-contrast"

-- | A ClassName for typcn-anchor
typcnAnchor :: ClassName
typcnAnchor = ClassName "typcn-anchor"

-- | A ClassName for typcn-anchor-outline
typcnAnchorOutline :: ClassName
typcnAnchorOutline = ClassName "typcn-anchor-outline"

-- | A ClassName for typcn-archive
typcnArchive :: ClassName
typcnArchive = ClassName "typcn-archive"

-- | A ClassName for typcn-arrow-back
typcnArrowBack :: ClassName
typcnArrowBack = ClassName "typcn-arrow-back"

-- | A ClassName for typcn-arrow-back-outline
typcnArrowBackOutline :: ClassName
typcnArrowBackOutline = ClassName "typcn-arrow-back-outline"

-- | A ClassName for typcn-arrow-down
typcnArrowDown :: ClassName
typcnArrowDown = ClassName "typcn-arrow-down"

-- | A ClassName for typcn-arrow-down-outline
typcnArrowDownOutline :: ClassName
typcnArrowDownOutline = ClassName "typcn-arrow-down-outline"

-- | A ClassName for typcn-arrow-down-thick
typcnArrowDownThick :: ClassName
typcnArrowDownThick = ClassName "typcn-arrow-down-thick"

-- | A ClassName for typcn-arrow-forward
typcnArrowForward :: ClassName
typcnArrowForward = ClassName "typcn-arrow-forward"

-- | A ClassName for typcn-arrow-forward-outline
typcnArrowForwardOutline :: ClassName
typcnArrowForwardOutline = ClassName "typcn-arrow-forward-outline"

-- | A ClassName for typcn-arrow-left
typcnArrowLeft :: ClassName
typcnArrowLeft = ClassName "typcn-arrow-left"

-- | A ClassName for typcn-arrow-left-outline
typcnArrowLeftOutline :: ClassName
typcnArrowLeftOutline = ClassName "typcn-arrow-left-outline"

-- | A ClassName for typcn-arrow-left-thick
typcnArrowLeftThick :: ClassName
typcnArrowLeftThick = ClassName "typcn-arrow-left-thick"

-- | A ClassName for typcn-arrow-loop
typcnArrowLoop :: ClassName
typcnArrowLoop = ClassName "typcn-arrow-loop"

-- | A ClassName for typcn-arrow-loop-outline
typcnArrowLoopOutline :: ClassName
typcnArrowLoopOutline = ClassName "typcn-arrow-loop-outline"

-- | A ClassName for typcn-arrow-maximise
typcnArrowMaximise :: ClassName
typcnArrowMaximise = ClassName "typcn-arrow-maximise"

-- | A ClassName for typcn-arrow-maximise-outline
typcnArrowMaximiseOutline :: ClassName
typcnArrowMaximiseOutline = ClassName "typcn-arrow-maximise-outline"

-- | A ClassName for typcn-arrow-minimise
typcnArrowMinimise :: ClassName
typcnArrowMinimise = ClassName "typcn-arrow-minimise"

-- | A ClassName for typcn-arrow-minimise-outline
typcnArrowMinimiseOutline :: ClassName
typcnArrowMinimiseOutline = ClassName "typcn-arrow-minimise-outline"

-- | A ClassName for typcn-arrow-move
typcnArrowMove :: ClassName
typcnArrowMove = ClassName "typcn-arrow-move"

-- | A ClassName for typcn-arrow-move-outline
typcnArrowMoveOutline :: ClassName
typcnArrowMoveOutline = ClassName "typcn-arrow-move-outline"

-- | A ClassName for typcn-arrow-repeat
typcnArrowRepeat :: ClassName
typcnArrowRepeat = ClassName "typcn-arrow-repeat"

-- | A ClassName for typcn-arrow-repeat-outline
typcnArrowRepeatOutline :: ClassName
typcnArrowRepeatOutline = ClassName "typcn-arrow-repeat-outline"

-- | A ClassName for typcn-arrow-right
typcnArrowRight :: ClassName
typcnArrowRight = ClassName "typcn-arrow-right"

-- | A ClassName for typcn-arrow-right-outline
typcnArrowRightOutline :: ClassName
typcnArrowRightOutline = ClassName "typcn-arrow-right-outline"

-- | A ClassName for typcn-arrow-right-thick
typcnArrowRightThick :: ClassName
typcnArrowRightThick = ClassName "typcn-arrow-right-thick"

-- | A ClassName for typcn-arrow-shuffle
typcnArrowShuffle :: ClassName
typcnArrowShuffle = ClassName "typcn-arrow-shuffle"

-- | A ClassName for typcn-arrow-sorted-down
typcnArrowSortedDown :: ClassName
typcnArrowSortedDown = ClassName "typcn-arrow-sorted-down"

-- | A ClassName for typcn-arrow-sorted-up
typcnArrowSortedUp :: ClassName
typcnArrowSortedUp = ClassName "typcn-arrow-sorted-up"

-- | A ClassName for typcn-arrow-sync
typcnArrowSync :: ClassName
typcnArrowSync = ClassName "typcn-arrow-sync"

-- | A ClassName for typcn-arrow-sync-outline
typcnArrowSyncOutline :: ClassName
typcnArrowSyncOutline = ClassName "typcn-arrow-sync-outline"

-- | A ClassName for typcn-arrow-unsorted
typcnArrowUnsorted :: ClassName
typcnArrowUnsorted = ClassName "typcn-arrow-unsorted"

-- | A ClassName for typcn-arrow-up
typcnArrowUp :: ClassName
typcnArrowUp = ClassName "typcn-arrow-up"

-- | A ClassName for typcn-arrow-up-outline
typcnArrowUpOutline :: ClassName
typcnArrowUpOutline = ClassName "typcn-arrow-up-outline"

-- | A ClassName for typcn-arrow-up-thick
typcnArrowUpThick :: ClassName
typcnArrowUpThick = ClassName "typcn-arrow-up-thick"

-- | A ClassName for typcn-at
typcnAt :: ClassName
typcnAt = ClassName "typcn-at"

-- | A ClassName for typcn-attachment
typcnAttachment :: ClassName
typcnAttachment = ClassName "typcn-attachment"

-- | A ClassName for typcn-attachment-outline
typcnAttachmentOutline :: ClassName
typcnAttachmentOutline = ClassName "typcn-attachment-outline"

-- | A ClassName for typcn-backspace
typcnBackspace :: ClassName
typcnBackspace = ClassName "typcn-backspace"

-- | A ClassName for typcn-backspace-outline
typcnBackspaceOutline :: ClassName
typcnBackspaceOutline = ClassName "typcn-backspace-outline"

-- | A ClassName for typcn-battery-charge
typcnBatteryCharge :: ClassName
typcnBatteryCharge = ClassName "typcn-battery-charge"

-- | A ClassName for typcn-battery-full
typcnBatteryFull :: ClassName
typcnBatteryFull = ClassName "typcn-battery-full"

-- | A ClassName for typcn-battery-high
typcnBatteryHigh :: ClassName
typcnBatteryHigh = ClassName "typcn-battery-high"

-- | A ClassName for typcn-battery-low
typcnBatteryLow :: ClassName
typcnBatteryLow = ClassName "typcn-battery-low"

-- | A ClassName for typcn-battery-mid
typcnBatteryMid :: ClassName
typcnBatteryMid = ClassName "typcn-battery-mid"

-- | A ClassName for typcn-beaker
typcnBeaker :: ClassName
typcnBeaker = ClassName "typcn-beaker"

-- | A ClassName for typcn-beer
typcnBeer :: ClassName
typcnBeer = ClassName "typcn-beer"

-- | A ClassName for typcn-bell
typcnBell :: ClassName
typcnBell = ClassName "typcn-bell"

-- | A ClassName for typcn-book
typcnBook :: ClassName
typcnBook = ClassName "typcn-book"

-- | A ClassName for typcn-bookmark
typcnBookmark :: ClassName
typcnBookmark = ClassName "typcn-bookmark"

-- | A ClassName for typcn-briefcase
typcnBriefcase :: ClassName
typcnBriefcase = ClassName "typcn-briefcase"

-- | A ClassName for typcn-brush
typcnBrush :: ClassName
typcnBrush = ClassName "typcn-brush"

-- | A ClassName for typcn-business-card
typcnBusinessCard :: ClassName
typcnBusinessCard = ClassName "typcn-business-card"

-- | A ClassName for typcn-calculator
typcnCalculator :: ClassName
typcnCalculator = ClassName "typcn-calculator"

-- | A ClassName for typcn-calendar
typcnCalendar :: ClassName
typcnCalendar = ClassName "typcn-calendar"

-- | A ClassName for typcn-calendar-outline
typcnCalendarOutline :: ClassName
typcnCalendarOutline = ClassName "typcn-calendar-outline"

-- | A ClassName for typcn-camera
typcnCamera :: ClassName
typcnCamera = ClassName "typcn-camera"

-- | A ClassName for typcn-camera-outline
typcnCameraOutline :: ClassName
typcnCameraOutline = ClassName "typcn-camera-outline"

-- | A ClassName for typcn-cancel
typcnCancel :: ClassName
typcnCancel = ClassName "typcn-cancel"

-- | A ClassName for typcn-cancel-outline
typcnCancelOutline :: ClassName
typcnCancelOutline = ClassName "typcn-cancel-outline"

-- | A ClassName for typcn-chart-area
typcnChartArea :: ClassName
typcnChartArea = ClassName "typcn-chart-area"

-- | A ClassName for typcn-chart-area-outline
typcnChartAreaOutline :: ClassName
typcnChartAreaOutline = ClassName "typcn-chart-area-outline"

-- | A ClassName for typcn-chart-bar
typcnChartBar :: ClassName
typcnChartBar = ClassName "typcn-chart-bar"

-- | A ClassName for typcn-chart-bar-outline
typcnChartBarOutline :: ClassName
typcnChartBarOutline = ClassName "typcn-chart-bar-outline"

-- | A ClassName for typcn-chart-line
typcnChartLine :: ClassName
typcnChartLine = ClassName "typcn-chart-line"

-- | A ClassName for typcn-chart-line-outline
typcnChartLineOutline :: ClassName
typcnChartLineOutline = ClassName "typcn-chart-line-outline"

-- | A ClassName for typcn-chart-pie
typcnChartPie :: ClassName
typcnChartPie = ClassName "typcn-chart-pie"

-- | A ClassName for typcn-chart-pie-outline
typcnChartPieOutline :: ClassName
typcnChartPieOutline = ClassName "typcn-chart-pie-outline"

-- | A ClassName for typcn-chevron-left
typcnChevronLeft :: ClassName
typcnChevronLeft = ClassName "typcn-chevron-left"

-- | A ClassName for typcn-chevron-left-outline
typcnChevronLeftOutline :: ClassName
typcnChevronLeftOutline = ClassName "typcn-chevron-left-outline"

-- | A ClassName for typcn-chevron-right
typcnChevronRight :: ClassName
typcnChevronRight = ClassName "typcn-chevron-right"

-- | A ClassName for typcn-chevron-right-outline
typcnChevronRightOutline :: ClassName
typcnChevronRightOutline = ClassName "typcn-chevron-right-outline"

-- | A ClassName for typcn-clipboard
typcnClipboard :: ClassName
typcnClipboard = ClassName "typcn-clipboard"

-- | A ClassName for typcn-cloud-storage
typcnCloudStorage :: ClassName
typcnCloudStorage = ClassName "typcn-cloud-storage"

-- | A ClassName for typcn-cloud-storage-outline
typcnCloudStorageOutline :: ClassName
typcnCloudStorageOutline = ClassName "typcn-cloud-storage-outline"

-- | A ClassName for typcn-code
typcnCode :: ClassName
typcnCode = ClassName "typcn-code"

-- | A ClassName for typcn-code-outline
typcnCodeOutline :: ClassName
typcnCodeOutline = ClassName "typcn-code-outline"

-- | A ClassName for typcn-coffee
typcnCoffee :: ClassName
typcnCoffee = ClassName "typcn-coffee"

-- | A ClassName for typcn-cog
typcnCog :: ClassName
typcnCog = ClassName "typcn-cog"

-- | A ClassName for typcn-cog-outline
typcnCogOutline :: ClassName
typcnCogOutline = ClassName "typcn-cog-outline"

-- | A ClassName for typcn-compass
typcnCompass :: ClassName
typcnCompass = ClassName "typcn-compass"

-- | A ClassName for typcn-contacts
typcnContacts :: ClassName
typcnContacts = ClassName "typcn-contacts"

-- | A ClassName for typcn-credit-card
typcnCreditCard :: ClassName
typcnCreditCard = ClassName "typcn-credit-card"

-- | A ClassName for typcn-css3
typcnCss3 :: ClassName
typcnCss3 = ClassName "typcn-css3"

-- | A ClassName for typcn-database
typcnDatabase :: ClassName
typcnDatabase = ClassName "typcn-database"

-- | A ClassName for typcn-delete
typcnDelete :: ClassName
typcnDelete = ClassName "typcn-delete"

-- | A ClassName for typcn-delete-outline
typcnDeleteOutline :: ClassName
typcnDeleteOutline = ClassName "typcn-delete-outline"

-- | A ClassName for typcn-device-desktop
typcnDeviceDesktop :: ClassName
typcnDeviceDesktop = ClassName "typcn-device-desktop"

-- | A ClassName for typcn-device-laptop
typcnDeviceLaptop :: ClassName
typcnDeviceLaptop = ClassName "typcn-device-laptop"

-- | A ClassName for typcn-device-phone
typcnDevicePhone :: ClassName
typcnDevicePhone = ClassName "typcn-device-phone"

-- | A ClassName for typcn-device-tablet
typcnDeviceTablet :: ClassName
typcnDeviceTablet = ClassName "typcn-device-tablet"

-- | A ClassName for typcn-directions
typcnDirections :: ClassName
typcnDirections = ClassName "typcn-directions"

-- | A ClassName for typcn-divide
typcnDivide :: ClassName
typcnDivide = ClassName "typcn-divide"

-- | A ClassName for typcn-divide-outline
typcnDivideOutline :: ClassName
typcnDivideOutline = ClassName "typcn-divide-outline"

-- | A ClassName for typcn-document
typcnDocument :: ClassName
typcnDocument = ClassName "typcn-document"

-- | A ClassName for typcn-document-add
typcnDocumentAdd :: ClassName
typcnDocumentAdd = ClassName "typcn-document-add"

-- | A ClassName for typcn-document-delete
typcnDocumentDelete :: ClassName
typcnDocumentDelete = ClassName "typcn-document-delete"

-- | A ClassName for typcn-document-text
typcnDocumentText :: ClassName
typcnDocumentText = ClassName "typcn-document-text"

-- | A ClassName for typcn-download
typcnDownload :: ClassName
typcnDownload = ClassName "typcn-download"

-- | A ClassName for typcn-download-outline
typcnDownloadOutline :: ClassName
typcnDownloadOutline = ClassName "typcn-download-outline"

-- | A ClassName for typcn-dropbox
typcnDropbox :: ClassName
typcnDropbox = ClassName "typcn-dropbox"

-- | A ClassName for typcn-edit
typcnEdit :: ClassName
typcnEdit = ClassName "typcn-edit"

-- | A ClassName for typcn-eject
typcnEject :: ClassName
typcnEject = ClassName "typcn-eject"

-- | A ClassName for typcn-eject-outline
typcnEjectOutline :: ClassName
typcnEjectOutline = ClassName "typcn-eject-outline"

-- | A ClassName for typcn-equals
typcnEquals :: ClassName
typcnEquals = ClassName "typcn-equals"

-- | A ClassName for typcn-equals-outline
typcnEqualsOutline :: ClassName
typcnEqualsOutline = ClassName "typcn-equals-outline"

-- | A ClassName for typcn-export
typcnExport :: ClassName
typcnExport = ClassName "typcn-export"

-- | A ClassName for typcn-export-outline
typcnExportOutline :: ClassName
typcnExportOutline = ClassName "typcn-export-outline"

-- | A ClassName for typcn-eye
typcnEye :: ClassName
typcnEye = ClassName "typcn-eye"

-- | A ClassName for typcn-eye-outline
typcnEyeOutline :: ClassName
typcnEyeOutline = ClassName "typcn-eye-outline"

-- | A ClassName for typcn-feather
typcnFeather :: ClassName
typcnFeather = ClassName "typcn-feather"

-- | A ClassName for typcn-film
typcnFilm :: ClassName
typcnFilm = ClassName "typcn-film"

-- | A ClassName for typcn-filter
typcnFilter :: ClassName
typcnFilter = ClassName "typcn-filter"

-- | A ClassName for typcn-flag
typcnFlag :: ClassName
typcnFlag = ClassName "typcn-flag"

-- | A ClassName for typcn-flag-outline
typcnFlagOutline :: ClassName
typcnFlagOutline = ClassName "typcn-flag-outline"

-- | A ClassName for typcn-flash
typcnFlash :: ClassName
typcnFlash = ClassName "typcn-flash"

-- | A ClassName for typcn-flash-outline
typcnFlashOutline :: ClassName
typcnFlashOutline = ClassName "typcn-flash-outline"

-- | A ClassName for typcn-flow-children
typcnFlowChildren :: ClassName
typcnFlowChildren = ClassName "typcn-flow-children"

-- | A ClassName for typcn-flow-merge
typcnFlowMerge :: ClassName
typcnFlowMerge = ClassName "typcn-flow-merge"

-- | A ClassName for typcn-flow-parallel
typcnFlowParallel :: ClassName
typcnFlowParallel = ClassName "typcn-flow-parallel"

-- | A ClassName for typcn-flow-switch
typcnFlowSwitch :: ClassName
typcnFlowSwitch = ClassName "typcn-flow-switch"

-- | A ClassName for typcn-folder
typcnFolder :: ClassName
typcnFolder = ClassName "typcn-folder"

-- | A ClassName for typcn-folder-add
typcnFolderAdd :: ClassName
typcnFolderAdd = ClassName "typcn-folder-add"

-- | A ClassName for typcn-folder-delete
typcnFolderDelete :: ClassName
typcnFolderDelete = ClassName "typcn-folder-delete"

-- | A ClassName for typcn-folder-open
typcnFolderOpen :: ClassName
typcnFolderOpen = ClassName "typcn-folder-open"

-- | A ClassName for typcn-gift
typcnGift :: ClassName
typcnGift = ClassName "typcn-gift"

-- | A ClassName for typcn-globe
typcnGlobe :: ClassName
typcnGlobe = ClassName "typcn-globe"

-- | A ClassName for typcn-globe-outline
typcnGlobeOutline :: ClassName
typcnGlobeOutline = ClassName "typcn-globe-outline"

-- | A ClassName for typcn-group
typcnGroup :: ClassName
typcnGroup = ClassName "typcn-group"

-- | A ClassName for typcn-group-outline
typcnGroupOutline :: ClassName
typcnGroupOutline = ClassName "typcn-group-outline"

-- | A ClassName for typcn-headphones
typcnHeadphones :: ClassName
typcnHeadphones = ClassName "typcn-headphones"

-- | A ClassName for typcn-heart
typcnHeart :: ClassName
typcnHeart = ClassName "typcn-heart"

-- | A ClassName for typcn-heart-full-outline
typcnHeartFullOutline :: ClassName
typcnHeartFullOutline = ClassName "typcn-heart-full-outline"

-- | A ClassName for typcn-heart-half-outline
typcnHeartHalfOutline :: ClassName
typcnHeartHalfOutline = ClassName "typcn-heart-half-outline"

-- | A ClassName for typcn-heart-outline
typcnHeartOutline :: ClassName
typcnHeartOutline = ClassName "typcn-heart-outline"

-- | A ClassName for typcn-home
typcnHome :: ClassName
typcnHome = ClassName "typcn-home"

-- | A ClassName for typcn-home-outline
typcnHomeOutline :: ClassName
typcnHomeOutline = ClassName "typcn-home-outline"

-- | A ClassName for typcn-html5
typcnHtml5 :: ClassName
typcnHtml5 = ClassName "typcn-html5"

-- | A ClassName for typcn-image
typcnImage :: ClassName
typcnImage = ClassName "typcn-image"

-- | A ClassName for typcn-image-outline
typcnImageOutline :: ClassName
typcnImageOutline = ClassName "typcn-image-outline"

-- | A ClassName for typcn-infinity
typcnInfinity :: ClassName
typcnInfinity = ClassName "typcn-infinity"

-- | A ClassName for typcn-infinity-outline
typcnInfinityOutline :: ClassName
typcnInfinityOutline = ClassName "typcn-infinity-outline"

-- | A ClassName for typcn-info
typcnInfo :: ClassName
typcnInfo = ClassName "typcn-info"

-- | A ClassName for typcn-info-large
typcnInfoLarge :: ClassName
typcnInfoLarge = ClassName "typcn-info-large"

-- | A ClassName for typcn-info-large-outline
typcnInfoLargeOutline :: ClassName
typcnInfoLargeOutline = ClassName "typcn-info-large-outline"

-- | A ClassName for typcn-info-outline
typcnInfoOutline :: ClassName
typcnInfoOutline = ClassName "typcn-info-outline"

-- | A ClassName for typcn-input-checked
typcnInputChecked :: ClassName
typcnInputChecked = ClassName "typcn-input-checked"

-- | A ClassName for typcn-input-checked-outline
typcnInputCheckedOutline :: ClassName
typcnInputCheckedOutline = ClassName "typcn-input-checked-outline"

-- | A ClassName for typcn-key
typcnKey :: ClassName
typcnKey = ClassName "typcn-key"

-- | A ClassName for typcn-key-outline
typcnKeyOutline :: ClassName
typcnKeyOutline = ClassName "typcn-key-outline"

-- | A ClassName for typcn-keyboard
typcnKeyboard :: ClassName
typcnKeyboard = ClassName "typcn-keyboard"

-- | A ClassName for typcn-leaf
typcnLeaf :: ClassName
typcnLeaf = ClassName "typcn-leaf"

-- | A ClassName for typcn-lightbulb
typcnLightbulb :: ClassName
typcnLightbulb = ClassName "typcn-lightbulb"

-- | A ClassName for typcn-link
typcnLink :: ClassName
typcnLink = ClassName "typcn-link"

-- | A ClassName for typcn-link-outline
typcnLinkOutline :: ClassName
typcnLinkOutline = ClassName "typcn-link-outline"

-- | A ClassName for typcn-location
typcnLocation :: ClassName
typcnLocation = ClassName "typcn-location"

-- | A ClassName for typcn-location-arrow
typcnLocationArrow :: ClassName
typcnLocationArrow = ClassName "typcn-location-arrow"

-- | A ClassName for typcn-location-arrow-outline
typcnLocationArrowOutline :: ClassName
typcnLocationArrowOutline = ClassName "typcn-location-arrow-outline"

-- | A ClassName for typcn-location-outline
typcnLocationOutline :: ClassName
typcnLocationOutline = ClassName "typcn-location-outline"

-- | A ClassName for typcn-lock-closed
typcnLockClosed :: ClassName
typcnLockClosed = ClassName "typcn-lock-closed"

-- | A ClassName for typcn-lock-closed-outline
typcnLockClosedOutline :: ClassName
typcnLockClosedOutline = ClassName "typcn-lock-closed-outline"

-- | A ClassName for typcn-lock-open
typcnLockOpen :: ClassName
typcnLockOpen = ClassName "typcn-lock-open"

-- | A ClassName for typcn-lock-open-outline
typcnLockOpenOutline :: ClassName
typcnLockOpenOutline = ClassName "typcn-lock-open-outline"

-- | A ClassName for typcn-mail
typcnMail :: ClassName
typcnMail = ClassName "typcn-mail"

-- | A ClassName for typcn-map
typcnMap :: ClassName
typcnMap = ClassName "typcn-map"

-- | A ClassName for typcn-media-eject
typcnMediaEject :: ClassName
typcnMediaEject = ClassName "typcn-media-eject"

-- | A ClassName for typcn-media-eject-outline
typcnMediaEjectOutline :: ClassName
typcnMediaEjectOutline = ClassName "typcn-media-eject-outline"

-- | A ClassName for typcn-media-fast-forward
typcnMediaFastForward :: ClassName
typcnMediaFastForward = ClassName "typcn-media-fast-forward"

-- | A ClassName for typcn-media-fast-forward-outline
typcnMediaFastForwardOutline :: ClassName
typcnMediaFastForwardOutline = ClassName "typcn-media-fast-forward-outline"

-- | A ClassName for typcn-media-pause
typcnMediaPause :: ClassName
typcnMediaPause = ClassName "typcn-media-pause"

-- | A ClassName for typcn-media-pause-outline
typcnMediaPauseOutline :: ClassName
typcnMediaPauseOutline = ClassName "typcn-media-pause-outline"

-- | A ClassName for typcn-media-play
typcnMediaPlay :: ClassName
typcnMediaPlay = ClassName "typcn-media-play"

-- | A ClassName for typcn-media-play-outline
typcnMediaPlayOutline :: ClassName
typcnMediaPlayOutline = ClassName "typcn-media-play-outline"

-- | A ClassName for typcn-media-play-reverse
typcnMediaPlayReverse :: ClassName
typcnMediaPlayReverse = ClassName "typcn-media-play-reverse"

-- | A ClassName for typcn-media-play-reverse-outline
typcnMediaPlayReverseOutline :: ClassName
typcnMediaPlayReverseOutline = ClassName "typcn-media-play-reverse-outline"

-- | A ClassName for typcn-media-record
typcnMediaRecord :: ClassName
typcnMediaRecord = ClassName "typcn-media-record"

-- | A ClassName for typcn-media-record-outline
typcnMediaRecordOutline :: ClassName
typcnMediaRecordOutline = ClassName "typcn-media-record-outline"

-- | A ClassName for typcn-media-rewind
typcnMediaRewind :: ClassName
typcnMediaRewind = ClassName "typcn-media-rewind"

-- | A ClassName for typcn-media-rewind-outline
typcnMediaRewindOutline :: ClassName
typcnMediaRewindOutline = ClassName "typcn-media-rewind-outline"

-- | A ClassName for typcn-media-stop
typcnMediaStop :: ClassName
typcnMediaStop = ClassName "typcn-media-stop"

-- | A ClassName for typcn-media-stop-outline
typcnMediaStopOutline :: ClassName
typcnMediaStopOutline = ClassName "typcn-media-stop-outline"

-- | A ClassName for typcn-message
typcnMessage :: ClassName
typcnMessage = ClassName "typcn-message"

-- | A ClassName for typcn-message-typing
typcnMessageTyping :: ClassName
typcnMessageTyping = ClassName "typcn-message-typing"

-- | A ClassName for typcn-messages
typcnMessages :: ClassName
typcnMessages = ClassName "typcn-messages"

-- | A ClassName for typcn-microphone
typcnMicrophone :: ClassName
typcnMicrophone = ClassName "typcn-microphone"

-- | A ClassName for typcn-microphone-outline
typcnMicrophoneOutline :: ClassName
typcnMicrophoneOutline = ClassName "typcn-microphone-outline"

-- | A ClassName for typcn-minus
typcnMinus :: ClassName
typcnMinus = ClassName "typcn-minus"

-- | A ClassName for typcn-minus-outline
typcnMinusOutline :: ClassName
typcnMinusOutline = ClassName "typcn-minus-outline"

-- | A ClassName for typcn-mortar-board
typcnMortarBoard :: ClassName
typcnMortarBoard = ClassName "typcn-mortar-board"

-- | A ClassName for typcn-news
typcnNews :: ClassName
typcnNews = ClassName "typcn-news"

-- | A ClassName for typcn-notes
typcnNotes :: ClassName
typcnNotes = ClassName "typcn-notes"

-- | A ClassName for typcn-notes-outline
typcnNotesOutline :: ClassName
typcnNotesOutline = ClassName "typcn-notes-outline"

-- | A ClassName for typcn-pen
typcnPen :: ClassName
typcnPen = ClassName "typcn-pen"

-- | A ClassName for typcn-pencil
typcnPencil :: ClassName
typcnPencil = ClassName "typcn-pencil"

-- | A ClassName for typcn-phone
typcnPhone :: ClassName
typcnPhone = ClassName "typcn-phone"

-- | A ClassName for typcn-phone-outline
typcnPhoneOutline :: ClassName
typcnPhoneOutline = ClassName "typcn-phone-outline"

-- | A ClassName for typcn-pi
typcnPi :: ClassName
typcnPi = ClassName "typcn-pi"

-- | A ClassName for typcn-pi-outline
typcnPiOutline :: ClassName
typcnPiOutline = ClassName "typcn-pi-outline"

-- | A ClassName for typcn-pin
typcnPin :: ClassName
typcnPin = ClassName "typcn-pin"

-- | A ClassName for typcn-pin-outline
typcnPinOutline :: ClassName
typcnPinOutline = ClassName "typcn-pin-outline"

-- | A ClassName for typcn-pipette
typcnPipette :: ClassName
typcnPipette = ClassName "typcn-pipette"

-- | A ClassName for typcn-plane
typcnPlane :: ClassName
typcnPlane = ClassName "typcn-plane"

-- | A ClassName for typcn-plane-outline
typcnPlaneOutline :: ClassName
typcnPlaneOutline = ClassName "typcn-plane-outline"

-- | A ClassName for typcn-plug
typcnPlug :: ClassName
typcnPlug = ClassName "typcn-plug"

-- | A ClassName for typcn-plus
typcnPlus :: ClassName
typcnPlus = ClassName "typcn-plus"

-- | A ClassName for typcn-plus-outline
typcnPlusOutline :: ClassName
typcnPlusOutline = ClassName "typcn-plus-outline"

-- | A ClassName for typcn-point-of-interest
typcnPointOfInterest :: ClassName
typcnPointOfInterest = ClassName "typcn-point-of-interest"

-- | A ClassName for typcn-point-of-interest-outline
typcnPointOfInterestOutline :: ClassName
typcnPointOfInterestOutline = ClassName "typcn-point-of-interest-outline"

-- | A ClassName for typcn-power
typcnPower :: ClassName
typcnPower = ClassName "typcn-power"

-- | A ClassName for typcn-power-outline
typcnPowerOutline :: ClassName
typcnPowerOutline = ClassName "typcn-power-outline"

-- | A ClassName for typcn-printer
typcnPrinter :: ClassName
typcnPrinter = ClassName "typcn-printer"

-- | A ClassName for typcn-puzzle
typcnPuzzle :: ClassName
typcnPuzzle = ClassName "typcn-puzzle"

-- | A ClassName for typcn-puzzle-outline
typcnPuzzleOutline :: ClassName
typcnPuzzleOutline = ClassName "typcn-puzzle-outline"

-- | A ClassName for typcn-radar
typcnRadar :: ClassName
typcnRadar = ClassName "typcn-radar"

-- | A ClassName for typcn-radar-outline
typcnRadarOutline :: ClassName
typcnRadarOutline = ClassName "typcn-radar-outline"

-- | A ClassName for typcn-refresh
typcnRefresh :: ClassName
typcnRefresh = ClassName "typcn-refresh"

-- | A ClassName for typcn-refresh-outline
typcnRefreshOutline :: ClassName
typcnRefreshOutline = ClassName "typcn-refresh-outline"

-- | A ClassName for typcn-rss
typcnRss :: ClassName
typcnRss = ClassName "typcn-rss"

-- | A ClassName for typcn-rss-outline
typcnRssOutline :: ClassName
typcnRssOutline = ClassName "typcn-rss-outline"

-- | A ClassName for typcn-scissors
typcnScissors :: ClassName
typcnScissors = ClassName "typcn-scissors"

-- | A ClassName for typcn-scissors-outline
typcnScissorsOutline :: ClassName
typcnScissorsOutline = ClassName "typcn-scissors-outline"

-- | A ClassName for typcn-shopping-bag
typcnShoppingBag :: ClassName
typcnShoppingBag = ClassName "typcn-shopping-bag"

-- | A ClassName for typcn-shopping-cart
typcnShoppingCart :: ClassName
typcnShoppingCart = ClassName "typcn-shopping-cart"

-- | A ClassName for typcn-social-at-circular
typcnSocialAtCircular :: ClassName
typcnSocialAtCircular = ClassName "typcn-social-at-circular"

-- | A ClassName for typcn-social-dribbble
typcnSocialDribbble :: ClassName
typcnSocialDribbble = ClassName "typcn-social-dribbble"

-- | A ClassName for typcn-social-dribbble-circular
typcnSocialDribbbleCircular :: ClassName
typcnSocialDribbbleCircular = ClassName "typcn-social-dribbble-circular"

-- | A ClassName for typcn-social-facebook
typcnSocialFacebook :: ClassName
typcnSocialFacebook = ClassName "typcn-social-facebook"

-- | A ClassName for typcn-social-facebook-circular
typcnSocialFacebookCircular :: ClassName
typcnSocialFacebookCircular = ClassName "typcn-social-facebook-circular"

-- | A ClassName for typcn-social-flickr
typcnSocialFlickr :: ClassName
typcnSocialFlickr = ClassName "typcn-social-flickr"

-- | A ClassName for typcn-social-flickr-circular
typcnSocialFlickrCircular :: ClassName
typcnSocialFlickrCircular = ClassName "typcn-social-flickr-circular"

-- | A ClassName for typcn-social-github
typcnSocialGithub :: ClassName
typcnSocialGithub = ClassName "typcn-social-github"

-- | A ClassName for typcn-social-github-circular
typcnSocialGithubCircular :: ClassName
typcnSocialGithubCircular = ClassName "typcn-social-github-circular"

-- | A ClassName for typcn-social-google-plus
typcnSocialGooglePlus :: ClassName
typcnSocialGooglePlus = ClassName "typcn-social-google-plus"

-- | A ClassName for typcn-social-google-plus-circular
typcnSocialGooglePlusCircular :: ClassName
typcnSocialGooglePlusCircular = ClassName "typcn-social-google-plus-circular"

-- | A ClassName for typcn-social-instagram
typcnSocialInstagram :: ClassName
typcnSocialInstagram = ClassName "typcn-social-instagram"

-- | A ClassName for typcn-social-instagram-circular
typcnSocialInstagramCircular :: ClassName
typcnSocialInstagramCircular = ClassName "typcn-social-instagram-circular"

-- | A ClassName for typcn-social-last-fm
typcnSocialLastFm :: ClassName
typcnSocialLastFm = ClassName "typcn-social-last-fm"

-- | A ClassName for typcn-social-last-fm-circular
typcnSocialLastFmCircular :: ClassName
typcnSocialLastFmCircular = ClassName "typcn-social-last-fm-circular"

-- | A ClassName for typcn-social-linkedin
typcnSocialLinkedin :: ClassName
typcnSocialLinkedin = ClassName "typcn-social-linkedin"

-- | A ClassName for typcn-social-linkedin-circular
typcnSocialLinkedinCircular :: ClassName
typcnSocialLinkedinCircular = ClassName "typcn-social-linkedin-circular"

-- | A ClassName for typcn-social-pinterest
typcnSocialPinterest :: ClassName
typcnSocialPinterest = ClassName "typcn-social-pinterest"

-- | A ClassName for typcn-social-pinterest-circular
typcnSocialPinterestCircular :: ClassName
typcnSocialPinterestCircular = ClassName "typcn-social-pinterest-circular"

-- | A ClassName for typcn-social-skype
typcnSocialSkype :: ClassName
typcnSocialSkype = ClassName "typcn-social-skype"

-- | A ClassName for typcn-social-skype-outline
typcnSocialSkypeOutline :: ClassName
typcnSocialSkypeOutline = ClassName "typcn-social-skype-outline"

-- | A ClassName for typcn-social-tumbler
typcnSocialTumbler :: ClassName
typcnSocialTumbler = ClassName "typcn-social-tumbler"

-- | A ClassName for typcn-social-tumbler-circular
typcnSocialTumblerCircular :: ClassName
typcnSocialTumblerCircular = ClassName "typcn-social-tumbler-circular"

-- | A ClassName for typcn-social-twitter
typcnSocialTwitter :: ClassName
typcnSocialTwitter = ClassName "typcn-social-twitter"

-- | A ClassName for typcn-social-twitter-circular
typcnSocialTwitterCircular :: ClassName
typcnSocialTwitterCircular = ClassName "typcn-social-twitter-circular"

-- | A ClassName for typcn-social-vimeo
typcnSocialVimeo :: ClassName
typcnSocialVimeo = ClassName "typcn-social-vimeo"

-- | A ClassName for typcn-social-vimeo-circular
typcnSocialVimeoCircular :: ClassName
typcnSocialVimeoCircular = ClassName "typcn-social-vimeo-circular"

-- | A ClassName for typcn-social-youtube
typcnSocialYoutube :: ClassName
typcnSocialYoutube = ClassName "typcn-social-youtube"

-- | A ClassName for typcn-social-youtube-circular
typcnSocialYoutubeCircular :: ClassName
typcnSocialYoutubeCircular = ClassName "typcn-social-youtube-circular"

-- | A ClassName for typcn-sort-alphabetically
typcnSortAlphabetically :: ClassName
typcnSortAlphabetically = ClassName "typcn-sort-alphabetically"

-- | A ClassName for typcn-sort-alphabetically-outline
typcnSortAlphabeticallyOutline :: ClassName
typcnSortAlphabeticallyOutline = ClassName "typcn-sort-alphabetically-outline"

-- | A ClassName for typcn-sort-numerically
typcnSortNumerically :: ClassName
typcnSortNumerically = ClassName "typcn-sort-numerically"

-- | A ClassName for typcn-sort-numerically-outline
typcnSortNumericallyOutline :: ClassName
typcnSortNumericallyOutline = ClassName "typcn-sort-numerically-outline"

-- | A ClassName for typcn-spanner
typcnSpanner :: ClassName
typcnSpanner = ClassName "typcn-spanner"

-- | A ClassName for typcn-spanner-outline
typcnSpannerOutline :: ClassName
typcnSpannerOutline = ClassName "typcn-spanner-outline"

-- | A ClassName for typcn-spiral
typcnSpiral :: ClassName
typcnSpiral = ClassName "typcn-spiral"

-- | A ClassName for typcn-star
typcnStar :: ClassName
typcnStar = ClassName "typcn-star"

-- | A ClassName for typcn-star-full-outline
typcnStarFullOutline :: ClassName
typcnStarFullOutline = ClassName "typcn-star-full-outline"

-- | A ClassName for typcn-star-half
typcnStarHalf :: ClassName
typcnStarHalf = ClassName "typcn-star-half"

-- | A ClassName for typcn-star-half-outline
typcnStarHalfOutline :: ClassName
typcnStarHalfOutline = ClassName "typcn-star-half-outline"

-- | A ClassName for typcn-star-outline
typcnStarOutline :: ClassName
typcnStarOutline = ClassName "typcn-star-outline"

-- | A ClassName for typcn-starburst
typcnStarburst :: ClassName
typcnStarburst = ClassName "typcn-starburst"

-- | A ClassName for typcn-starburst-outline
typcnStarburstOutline :: ClassName
typcnStarburstOutline = ClassName "typcn-starburst-outline"

-- | A ClassName for typcn-stopwatch
typcnStopwatch :: ClassName
typcnStopwatch = ClassName "typcn-stopwatch"

-- | A ClassName for typcn-support
typcnSupport :: ClassName
typcnSupport = ClassName "typcn-support"

-- | A ClassName for typcn-tabs-outline
typcnTabsOutline :: ClassName
typcnTabsOutline = ClassName "typcn-tabs-outline"

-- | A ClassName for typcn-tag
typcnTag :: ClassName
typcnTag = ClassName "typcn-tag"

-- | A ClassName for typcn-tags
typcnTags :: ClassName
typcnTags = ClassName "typcn-tags"

-- | A ClassName for typcn-th-large
typcnThLarge :: ClassName
typcnThLarge = ClassName "typcn-th-large"

-- | A ClassName for typcn-th-large-outline
typcnThLargeOutline :: ClassName
typcnThLargeOutline = ClassName "typcn-th-large-outline"

-- | A ClassName for typcn-th-list
typcnThList :: ClassName
typcnThList = ClassName "typcn-th-list"

-- | A ClassName for typcn-th-list-outline
typcnThListOutline :: ClassName
typcnThListOutline = ClassName "typcn-th-list-outline"

-- | A ClassName for typcn-th-menu
typcnThMenu :: ClassName
typcnThMenu = ClassName "typcn-th-menu"

-- | A ClassName for typcn-th-menu-outline
typcnThMenuOutline :: ClassName
typcnThMenuOutline = ClassName "typcn-th-menu-outline"

-- | A ClassName for typcn-th-small
typcnThSmall :: ClassName
typcnThSmall = ClassName "typcn-th-small"

-- | A ClassName for typcn-th-small-outline
typcnThSmallOutline :: ClassName
typcnThSmallOutline = ClassName "typcn-th-small-outline"

-- | A ClassName for typcn-thermometer
typcnThermometer :: ClassName
typcnThermometer = ClassName "typcn-thermometer"

-- | A ClassName for typcn-thumbs-down
typcnThumbsDown :: ClassName
typcnThumbsDown = ClassName "typcn-thumbs-down"

-- | A ClassName for typcn-thumbs-ok
typcnThumbsOk :: ClassName
typcnThumbsOk = ClassName "typcn-thumbs-ok"

-- | A ClassName for typcn-thumbs-up
typcnThumbsUp :: ClassName
typcnThumbsUp = ClassName "typcn-thumbs-up"

-- | A ClassName for typcn-tick
typcnTick :: ClassName
typcnTick = ClassName "typcn-tick"

-- | A ClassName for typcn-tick-outline
typcnTickOutline :: ClassName
typcnTickOutline = ClassName "typcn-tick-outline"

-- | A ClassName for typcn-ticket
typcnTicket :: ClassName
typcnTicket = ClassName "typcn-ticket"

-- | A ClassName for typcn-time
typcnTime :: ClassName
typcnTime = ClassName "typcn-time"

-- | A ClassName for typcn-times
typcnTimes :: ClassName
typcnTimes = ClassName "typcn-times"

-- | A ClassName for typcn-times-outline
typcnTimesOutline :: ClassName
typcnTimesOutline = ClassName "typcn-times-outline"

-- | A ClassName for typcn-trash
typcnTrash :: ClassName
typcnTrash = ClassName "typcn-trash"

-- | A ClassName for typcn-tree
typcnTree :: ClassName
typcnTree = ClassName "typcn-tree"

-- | A ClassName for typcn-upload
typcnUpload :: ClassName
typcnUpload = ClassName "typcn-upload"

-- | A ClassName for typcn-upload-outline
typcnUploadOutline :: ClassName
typcnUploadOutline = ClassName "typcn-upload-outline"

-- | A ClassName for typcn-user
typcnUser :: ClassName
typcnUser = ClassName "typcn-user"

-- | A ClassName for typcn-user-add
typcnUserAdd :: ClassName
typcnUserAdd = ClassName "typcn-user-add"

-- | A ClassName for typcn-user-add-outline
typcnUserAddOutline :: ClassName
typcnUserAddOutline = ClassName "typcn-user-add-outline"

-- | A ClassName for typcn-user-delete
typcnUserDelete :: ClassName
typcnUserDelete = ClassName "typcn-user-delete"

-- | A ClassName for typcn-user-delete-outline
typcnUserDeleteOutline :: ClassName
typcnUserDeleteOutline = ClassName "typcn-user-delete-outline"

-- | A ClassName for typcn-user-outline
typcnUserOutline :: ClassName
typcnUserOutline = ClassName "typcn-user-outline"

-- | A ClassName for typcn-vendor-android
typcnVendorAndroid :: ClassName
typcnVendorAndroid = ClassName "typcn-vendor-android"

-- | A ClassName for typcn-vendor-apple
typcnVendorApple :: ClassName
typcnVendorApple = ClassName "typcn-vendor-apple"

-- | A ClassName for typcn-vendor-microsoft
typcnVendorMicrosoft :: ClassName
typcnVendorMicrosoft = ClassName "typcn-vendor-microsoft"

-- | A ClassName for typcn-video
typcnVideo :: ClassName
typcnVideo = ClassName "typcn-video"

-- | A ClassName for typcn-video-outline
typcnVideoOutline :: ClassName
typcnVideoOutline = ClassName "typcn-video-outline"

-- | A ClassName for typcn-volume
typcnVolume :: ClassName
typcnVolume = ClassName "typcn-volume"

-- | A ClassName for typcn-volume-down
typcnVolumeDown :: ClassName
typcnVolumeDown = ClassName "typcn-volume-down"

-- | A ClassName for typcn-volume-mute
typcnVolumeMute :: ClassName
typcnVolumeMute = ClassName "typcn-volume-mute"

-- | A ClassName for typcn-volume-up
typcnVolumeUp :: ClassName
typcnVolumeUp = ClassName "typcn-volume-up"

-- | A ClassName for typcn-warning
typcnWarning :: ClassName
typcnWarning = ClassName "typcn-warning"

-- | A ClassName for typcn-warning-outline
typcnWarningOutline :: ClassName
typcnWarningOutline = ClassName "typcn-warning-outline"

-- | A ClassName for typcn-watch
typcnWatch :: ClassName
typcnWatch = ClassName "typcn-watch"

-- | A ClassName for typcn-waves
typcnWaves :: ClassName
typcnWaves = ClassName "typcn-waves"

-- | A ClassName for typcn-waves-outline
typcnWavesOutline :: ClassName
typcnWavesOutline = ClassName "typcn-waves-outline"

-- | A ClassName for typcn-weather-cloudy
typcnWeatherCloudy :: ClassName
typcnWeatherCloudy = ClassName "typcn-weather-cloudy"

-- | A ClassName for typcn-weather-downpour
typcnWeatherDownpour :: ClassName
typcnWeatherDownpour = ClassName "typcn-weather-downpour"

-- | A ClassName for typcn-weather-night
typcnWeatherNight :: ClassName
typcnWeatherNight = ClassName "typcn-weather-night"

-- | A ClassName for typcn-weather-partly-sunny
typcnWeatherPartlySunny :: ClassName
typcnWeatherPartlySunny = ClassName "typcn-weather-partly-sunny"

-- | A ClassName for typcn-weather-shower
typcnWeatherShower :: ClassName
typcnWeatherShower = ClassName "typcn-weather-shower"

-- | A ClassName for typcn-weather-snow
typcnWeatherSnow :: ClassName
typcnWeatherSnow = ClassName "typcn-weather-snow"

-- | A ClassName for typcn-weather-stormy
typcnWeatherStormy :: ClassName
typcnWeatherStormy = ClassName "typcn-weather-stormy"

-- | A ClassName for typcn-weather-sunny
typcnWeatherSunny :: ClassName
typcnWeatherSunny = ClassName "typcn-weather-sunny"

-- | A ClassName for typcn-weather-windy
typcnWeatherWindy :: ClassName
typcnWeatherWindy = ClassName "typcn-weather-windy"

-- | A ClassName for typcn-weather-windy-cloudy
typcnWeatherWindyCloudy :: ClassName
typcnWeatherWindyCloudy = ClassName "typcn-weather-windy-cloudy"

-- | A ClassName for typcn-wi-fi
typcnWiFi :: ClassName
typcnWiFi = ClassName "typcn-wi-fi"

-- | A ClassName for typcn-wi-fi-outline
typcnWiFiOutline :: ClassName
typcnWiFiOutline = ClassName "typcn-wi-fi-outline"

-- | A ClassName for typcn-wine
typcnWine :: ClassName
typcnWine = ClassName "typcn-wine"

-- | A ClassName for typcn-world
typcnWorld :: ClassName
typcnWorld = ClassName "typcn-world"

-- | A ClassName for typcn-world-outline
typcnWorldOutline :: ClassName
typcnWorldOutline = ClassName "typcn-world-outline"

-- | A ClassName for typcn-zoom
typcnZoom :: ClassName
typcnZoom = ClassName "typcn-zoom"

-- | A ClassName for typcn-zoom-in
typcnZoomIn :: ClassName
typcnZoomIn = ClassName "typcn-zoom-in"

-- | A ClassName for typcn-zoom-in-outline
typcnZoomInOutline :: ClassName
typcnZoomInOutline = ClassName "typcn-zoom-in-outline"

-- | A ClassName for typcn-zoom-out
typcnZoomOut :: ClassName
typcnZoomOut = ClassName "typcn-zoom-out"

-- | A ClassName for typcn-zoom-out-outline
typcnZoomOutOutline :: ClassName
typcnZoomOutOutline = ClassName "typcn-zoom-out-outline"

-- | A ClassName for typcn-zoom-outline
typcnZoomOutline :: ClassName
typcnZoomOutline = ClassName "typcn-zoom-outline"

