{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Theme.Raw.Bulma
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= Bulma

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Theme.Raw.Bulma where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for block
block :: ClassName
block = ClassName "block"

-- | A ClassName for box
box :: ClassName
box = ClassName "box"

-- | A ClassName for breadcrumb
breadcrumb :: ClassName
breadcrumb = ClassName "breadcrumb"

-- | A ClassName for button
button :: ClassName
button = ClassName "button"

-- | A ClassName for buttons
buttons :: ClassName
buttons = ClassName "buttons"

-- | A ClassName for card
card :: ClassName
card = ClassName "card"

-- | A ClassName for card-content
cardContent :: ClassName
cardContent = ClassName "card-content"

-- | A ClassName for card-footer
cardFooter :: ClassName
cardFooter = ClassName "card-footer"

-- | A ClassName for card-footer-item
cardFooterItem :: ClassName
cardFooterItem = ClassName "card-footer-item"

-- | A ClassName for card-header
cardHeader :: ClassName
cardHeader = ClassName "card-header"

-- | A ClassName for card-header-icon
cardHeaderIcon :: ClassName
cardHeaderIcon = ClassName "card-header-icon"

-- | A ClassName for card-header-title
cardHeaderTitle :: ClassName
cardHeaderTitle = ClassName "card-header-title"

-- | A ClassName for card-image
cardImage :: ClassName
cardImage = ClassName "card-image"

-- | A ClassName for checkbox
checkbox :: ClassName
checkbox = ClassName "checkbox"

-- | A ClassName for column
column :: ClassName
column = ClassName "column"

-- | A ClassName for columns
columns :: ClassName
columns = ClassName "columns"

-- | A ClassName for container
container :: ClassName
container = ClassName "container"

-- | A ClassName for content
content :: ClassName
content = ClassName "content"

-- | A ClassName for control
control :: ClassName
control = ClassName "control"

-- | A ClassName for delete
delete :: ClassName
delete = ClassName "delete"

-- | A ClassName for dropdown
dropdown :: ClassName
dropdown = ClassName "dropdown"

-- | A ClassName for dropdown-content
dropdownContent :: ClassName
dropdownContent = ClassName "dropdown-content"

-- | A ClassName for dropdown-divider
dropdownDivider :: ClassName
dropdownDivider = ClassName "dropdown-divider"

-- | A ClassName for dropdown-item
dropdownItem :: ClassName
dropdownItem = ClassName "dropdown-item"

-- | A ClassName for dropdown-menu
dropdownMenu :: ClassName
dropdownMenu = ClassName "dropdown-menu"

-- | A ClassName for fa
fa :: ClassName
fa = ClassName "fa"

-- | A ClassName for field
field :: ClassName
field = ClassName "field"

-- | A ClassName for field-body
fieldBody :: ClassName
fieldBody = ClassName "field-body"

-- | A ClassName for field-label
fieldLabel :: ClassName
fieldLabel = ClassName "field-label"

-- | A ClassName for file
file :: ClassName
file = ClassName "file"

-- | A ClassName for file-cta
fileCta :: ClassName
fileCta = ClassName "file-cta"

-- | A ClassName for file-icon
fileIcon :: ClassName
fileIcon = ClassName "file-icon"

-- | A ClassName for file-input
fileInput :: ClassName
fileInput = ClassName "file-input"

-- | A ClassName for file-label
fileLabel :: ClassName
fileLabel = ClassName "file-label"

-- | A ClassName for file-name
fileName :: ClassName
fileName = ClassName "file-name"

-- | A ClassName for footer
footer :: ClassName
footer = ClassName "footer"

-- | A ClassName for has-addons
hasAddons :: ClassName
hasAddons = ClassName "has-addons"

-- | A ClassName for has-addons-centered
hasAddonsCentered :: ClassName
hasAddonsCentered = ClassName "has-addons-centered"

-- | A ClassName for has-addons-fullwidth
hasAddonsFullwidth :: ClassName
hasAddonsFullwidth = ClassName "has-addons-fullwidth"

-- | A ClassName for has-addons-right
hasAddonsRight :: ClassName
hasAddonsRight = ClassName "has-addons-right"

-- | A ClassName for has-arrow-separator
hasArrowSeparator :: ClassName
hasArrowSeparator = ClassName "has-arrow-separator"

-- | A ClassName for has-background-black
hasBackgroundBlack :: ClassName
hasBackgroundBlack = ClassName "has-background-black"

-- | A ClassName for has-background-black-bis
hasBackgroundBlackBis :: ClassName
hasBackgroundBlackBis = ClassName "has-background-black-bis"

-- | A ClassName for has-background-black-ter
hasBackgroundBlackTer :: ClassName
hasBackgroundBlackTer = ClassName "has-background-black-ter"

-- | A ClassName for has-background-danger
hasBackgroundDanger :: ClassName
hasBackgroundDanger = ClassName "has-background-danger"

-- | A ClassName for has-background-dark
hasBackgroundDark :: ClassName
hasBackgroundDark = ClassName "has-background-dark"

-- | A ClassName for has-background-grey
hasBackgroundGrey :: ClassName
hasBackgroundGrey = ClassName "has-background-grey"

-- | A ClassName for has-background-grey-dark
hasBackgroundGreyDark :: ClassName
hasBackgroundGreyDark = ClassName "has-background-grey-dark"

-- | A ClassName for has-background-grey-darker
hasBackgroundGreyDarker :: ClassName
hasBackgroundGreyDarker = ClassName "has-background-grey-darker"

-- | A ClassName for has-background-grey-light
hasBackgroundGreyLight :: ClassName
hasBackgroundGreyLight = ClassName "has-background-grey-light"

-- | A ClassName for has-background-grey-lighter
hasBackgroundGreyLighter :: ClassName
hasBackgroundGreyLighter = ClassName "has-background-grey-lighter"

-- | A ClassName for has-background-info
hasBackgroundInfo :: ClassName
hasBackgroundInfo = ClassName "has-background-info"

-- | A ClassName for has-background-light
hasBackgroundLight :: ClassName
hasBackgroundLight = ClassName "has-background-light"

-- | A ClassName for has-background-link
hasBackgroundLink :: ClassName
hasBackgroundLink = ClassName "has-background-link"

-- | A ClassName for has-background-primary
hasBackgroundPrimary :: ClassName
hasBackgroundPrimary = ClassName "has-background-primary"

-- | A ClassName for has-background-success
hasBackgroundSuccess :: ClassName
hasBackgroundSuccess = ClassName "has-background-success"

-- | A ClassName for has-background-warning
hasBackgroundWarning :: ClassName
hasBackgroundWarning = ClassName "has-background-warning"

-- | A ClassName for has-background-white
hasBackgroundWhite :: ClassName
hasBackgroundWhite = ClassName "has-background-white"

-- | A ClassName for has-background-white-bis
hasBackgroundWhiteBis :: ClassName
hasBackgroundWhiteBis = ClassName "has-background-white-bis"

-- | A ClassName for has-background-white-ter
hasBackgroundWhiteTer :: ClassName
hasBackgroundWhiteTer = ClassName "has-background-white-ter"

-- | A ClassName for has-bullet-separator
hasBulletSeparator :: ClassName
hasBulletSeparator = ClassName "has-bullet-separator"

-- | A ClassName for has-dot-separator
hasDotSeparator :: ClassName
hasDotSeparator = ClassName "has-dot-separator"

-- | A ClassName for has-dropdown
hasDropdown :: ClassName
hasDropdown = ClassName "has-dropdown"

-- | A ClassName for has-dropdown-up
hasDropdownUp :: ClassName
hasDropdownUp = ClassName "has-dropdown-up"

-- | A ClassName for has-fixed-size
hasFixedSize :: ClassName
hasFixedSize = ClassName "has-fixed-size"

-- | A ClassName for has-icon
hasIcon :: ClassName
hasIcon = ClassName "has-icon"

-- | A ClassName for has-icon-right
hasIconRight :: ClassName
hasIconRight = ClassName "has-icon-right"

-- | A ClassName for has-icons-left
hasIconsLeft :: ClassName
hasIconsLeft = ClassName "has-icons-left"

-- | A ClassName for has-icons-right
hasIconsRight :: ClassName
hasIconsRight = ClassName "has-icons-right"

-- | A ClassName for has-name
hasName :: ClassName
hasName = ClassName "has-name"

-- | A ClassName for has-navbar-fixed-bottom
hasNavbarFixedBottom :: ClassName
hasNavbarFixedBottom = ClassName "has-navbar-fixed-bottom"

-- | A ClassName for has-navbar-fixed-bottom-desktop
hasNavbarFixedBottomDesktop :: ClassName
hasNavbarFixedBottomDesktop = ClassName "has-navbar-fixed-bottom-desktop"

-- | A ClassName for has-navbar-fixed-bottom-touch
hasNavbarFixedBottomTouch :: ClassName
hasNavbarFixedBottomTouch = ClassName "has-navbar-fixed-bottom-touch"

-- | A ClassName for has-navbar-fixed-top
hasNavbarFixedTop :: ClassName
hasNavbarFixedTop = ClassName "has-navbar-fixed-top"

-- | A ClassName for has-navbar-fixed-top-desktop
hasNavbarFixedTopDesktop :: ClassName
hasNavbarFixedTopDesktop = ClassName "has-navbar-fixed-top-desktop"

-- | A ClassName for has-navbar-fixed-top-touch
hasNavbarFixedTopTouch :: ClassName
hasNavbarFixedTopTouch = ClassName "has-navbar-fixed-top-touch"

-- | A ClassName for has-shadow
hasShadow :: ClassName
hasShadow = ClassName "has-shadow"

-- | A ClassName for has-spaced-navbar-fixed-bottom
hasSpacedNavbarFixedBottom :: ClassName
hasSpacedNavbarFixedBottom = ClassName "has-spaced-navbar-fixed-bottom"

-- | A ClassName for has-spaced-navbar-fixed-top
hasSpacedNavbarFixedTop :: ClassName
hasSpacedNavbarFixedTop = ClassName "has-spaced-navbar-fixed-top"

-- | A ClassName for has-succeeds-separator
hasSucceedsSeparator :: ClassName
hasSucceedsSeparator = ClassName "has-succeeds-separator"

-- | A ClassName for has-text-black
hasTextBlack :: ClassName
hasTextBlack = ClassName "has-text-black"

-- | A ClassName for has-text-black-bis
hasTextBlackBis :: ClassName
hasTextBlackBis = ClassName "has-text-black-bis"

-- | A ClassName for has-text-black-ter
hasTextBlackTer :: ClassName
hasTextBlackTer = ClassName "has-text-black-ter"

-- | A ClassName for has-text-centered
hasTextCentered :: ClassName
hasTextCentered = ClassName "has-text-centered"

-- | A ClassName for has-text-centered-desktop
hasTextCenteredDesktop :: ClassName
hasTextCenteredDesktop = ClassName "has-text-centered-desktop"

-- | A ClassName for has-text-centered-desktop-only
hasTextCenteredDesktopOnly :: ClassName
hasTextCenteredDesktopOnly = ClassName "has-text-centered-desktop-only"

-- | A ClassName for has-text-centered-fullhd
hasTextCenteredFullhd :: ClassName
hasTextCenteredFullhd = ClassName "has-text-centered-fullhd"

-- | A ClassName for has-text-centered-mobile
hasTextCenteredMobile :: ClassName
hasTextCenteredMobile = ClassName "has-text-centered-mobile"

-- | A ClassName for has-text-centered-tablet
hasTextCenteredTablet :: ClassName
hasTextCenteredTablet = ClassName "has-text-centered-tablet"

-- | A ClassName for has-text-centered-tablet-only
hasTextCenteredTabletOnly :: ClassName
hasTextCenteredTabletOnly = ClassName "has-text-centered-tablet-only"

-- | A ClassName for has-text-centered-touch
hasTextCenteredTouch :: ClassName
hasTextCenteredTouch = ClassName "has-text-centered-touch"

-- | A ClassName for has-text-centered-widescreen
hasTextCenteredWidescreen :: ClassName
hasTextCenteredWidescreen = ClassName "has-text-centered-widescreen"

-- | A ClassName for has-text-centered-widescreen-only
hasTextCenteredWidescreenOnly :: ClassName
hasTextCenteredWidescreenOnly = ClassName "has-text-centered-widescreen-only"

-- | A ClassName for has-text-danger
hasTextDanger :: ClassName
hasTextDanger = ClassName "has-text-danger"

-- | A ClassName for has-text-dark
hasTextDark :: ClassName
hasTextDark = ClassName "has-text-dark"

-- | A ClassName for has-text-grey
hasTextGrey :: ClassName
hasTextGrey = ClassName "has-text-grey"

-- | A ClassName for has-text-grey-dark
hasTextGreyDark :: ClassName
hasTextGreyDark = ClassName "has-text-grey-dark"

-- | A ClassName for has-text-grey-darker
hasTextGreyDarker :: ClassName
hasTextGreyDarker = ClassName "has-text-grey-darker"

-- | A ClassName for has-text-grey-light
hasTextGreyLight :: ClassName
hasTextGreyLight = ClassName "has-text-grey-light"

-- | A ClassName for has-text-grey-lighter
hasTextGreyLighter :: ClassName
hasTextGreyLighter = ClassName "has-text-grey-lighter"

-- | A ClassName for has-text-info
hasTextInfo :: ClassName
hasTextInfo = ClassName "has-text-info"

-- | A ClassName for has-text-justified
hasTextJustified :: ClassName
hasTextJustified = ClassName "has-text-justified"

-- | A ClassName for has-text-justified-desktop
hasTextJustifiedDesktop :: ClassName
hasTextJustifiedDesktop = ClassName "has-text-justified-desktop"

-- | A ClassName for has-text-justified-desktop-only
hasTextJustifiedDesktopOnly :: ClassName
hasTextJustifiedDesktopOnly = ClassName "has-text-justified-desktop-only"

-- | A ClassName for has-text-justified-fullhd
hasTextJustifiedFullhd :: ClassName
hasTextJustifiedFullhd = ClassName "has-text-justified-fullhd"

-- | A ClassName for has-text-justified-mobile
hasTextJustifiedMobile :: ClassName
hasTextJustifiedMobile = ClassName "has-text-justified-mobile"

-- | A ClassName for has-text-justified-tablet
hasTextJustifiedTablet :: ClassName
hasTextJustifiedTablet = ClassName "has-text-justified-tablet"

-- | A ClassName for has-text-justified-tablet-only
hasTextJustifiedTabletOnly :: ClassName
hasTextJustifiedTabletOnly = ClassName "has-text-justified-tablet-only"

-- | A ClassName for has-text-justified-touch
hasTextJustifiedTouch :: ClassName
hasTextJustifiedTouch = ClassName "has-text-justified-touch"

-- | A ClassName for has-text-justified-widescreen
hasTextJustifiedWidescreen :: ClassName
hasTextJustifiedWidescreen = ClassName "has-text-justified-widescreen"

-- | A ClassName for has-text-justified-widescreen-only
hasTextJustifiedWidescreenOnly :: ClassName
hasTextJustifiedWidescreenOnly = ClassName "has-text-justified-widescreen-only"

-- | A ClassName for has-text-left
hasTextLeft :: ClassName
hasTextLeft = ClassName "has-text-left"

-- | A ClassName for has-text-left-desktop
hasTextLeftDesktop :: ClassName
hasTextLeftDesktop = ClassName "has-text-left-desktop"

-- | A ClassName for has-text-left-desktop-only
hasTextLeftDesktopOnly :: ClassName
hasTextLeftDesktopOnly = ClassName "has-text-left-desktop-only"

-- | A ClassName for has-text-left-fullhd
hasTextLeftFullhd :: ClassName
hasTextLeftFullhd = ClassName "has-text-left-fullhd"

-- | A ClassName for has-text-left-mobile
hasTextLeftMobile :: ClassName
hasTextLeftMobile = ClassName "has-text-left-mobile"

-- | A ClassName for has-text-left-tablet
hasTextLeftTablet :: ClassName
hasTextLeftTablet = ClassName "has-text-left-tablet"

-- | A ClassName for has-text-left-tablet-only
hasTextLeftTabletOnly :: ClassName
hasTextLeftTabletOnly = ClassName "has-text-left-tablet-only"

-- | A ClassName for has-text-left-touch
hasTextLeftTouch :: ClassName
hasTextLeftTouch = ClassName "has-text-left-touch"

-- | A ClassName for has-text-left-widescreen
hasTextLeftWidescreen :: ClassName
hasTextLeftWidescreen = ClassName "has-text-left-widescreen"

-- | A ClassName for has-text-left-widescreen-only
hasTextLeftWidescreenOnly :: ClassName
hasTextLeftWidescreenOnly = ClassName "has-text-left-widescreen-only"

-- | A ClassName for has-text-light
hasTextLight :: ClassName
hasTextLight = ClassName "has-text-light"

-- | A ClassName for has-text-link
hasTextLink :: ClassName
hasTextLink = ClassName "has-text-link"

-- | A ClassName for has-text-primary
hasTextPrimary :: ClassName
hasTextPrimary = ClassName "has-text-primary"

-- | A ClassName for has-text-right
hasTextRight :: ClassName
hasTextRight = ClassName "has-text-right"

-- | A ClassName for has-text-right-desktop
hasTextRightDesktop :: ClassName
hasTextRightDesktop = ClassName "has-text-right-desktop"

-- | A ClassName for has-text-right-desktop-only
hasTextRightDesktopOnly :: ClassName
hasTextRightDesktopOnly = ClassName "has-text-right-desktop-only"

-- | A ClassName for has-text-right-fullhd
hasTextRightFullhd :: ClassName
hasTextRightFullhd = ClassName "has-text-right-fullhd"

-- | A ClassName for has-text-right-mobile
hasTextRightMobile :: ClassName
hasTextRightMobile = ClassName "has-text-right-mobile"

-- | A ClassName for has-text-right-tablet
hasTextRightTablet :: ClassName
hasTextRightTablet = ClassName "has-text-right-tablet"

-- | A ClassName for has-text-right-tablet-only
hasTextRightTabletOnly :: ClassName
hasTextRightTabletOnly = ClassName "has-text-right-tablet-only"

-- | A ClassName for has-text-right-touch
hasTextRightTouch :: ClassName
hasTextRightTouch = ClassName "has-text-right-touch"

-- | A ClassName for has-text-right-widescreen
hasTextRightWidescreen :: ClassName
hasTextRightWidescreen = ClassName "has-text-right-widescreen"

-- | A ClassName for has-text-right-widescreen-only
hasTextRightWidescreenOnly :: ClassName
hasTextRightWidescreenOnly = ClassName "has-text-right-widescreen-only"

-- | A ClassName for has-text-success
hasTextSuccess :: ClassName
hasTextSuccess = ClassName "has-text-success"

-- | A ClassName for has-text-warning
hasTextWarning :: ClassName
hasTextWarning = ClassName "has-text-warning"

-- | A ClassName for has-text-weight-bold
hasTextWeightBold :: ClassName
hasTextWeightBold = ClassName "has-text-weight-bold"

-- | A ClassName for has-text-weight-light
hasTextWeightLight :: ClassName
hasTextWeightLight = ClassName "has-text-weight-light"

-- | A ClassName for has-text-weight-normal
hasTextWeightNormal :: ClassName
hasTextWeightNormal = ClassName "has-text-weight-normal"

-- | A ClassName for has-text-weight-semibold
hasTextWeightSemibold :: ClassName
hasTextWeightSemibold = ClassName "has-text-weight-semibold"

-- | A ClassName for has-text-white
hasTextWhite :: ClassName
hasTextWhite = ClassName "has-text-white"

-- | A ClassName for has-text-white-bis
hasTextWhiteBis :: ClassName
hasTextWhiteBis = ClassName "has-text-white-bis"

-- | A ClassName for has-text-white-ter
hasTextWhiteTer :: ClassName
hasTextWhiteTer = ClassName "has-text-white-ter"

-- | A ClassName for heading
heading :: ClassName
heading = ClassName "heading"

-- | A ClassName for help
help :: ClassName
help = ClassName "help"

-- | A ClassName for hero
hero :: ClassName
hero = ClassName "hero"

-- | A ClassName for hero-body
heroBody :: ClassName
heroBody = ClassName "hero-body"

-- | A ClassName for hero-buttons
heroButtons :: ClassName
heroButtons = ClassName "hero-buttons"

-- | A ClassName for hero-foot
heroFoot :: ClassName
heroFoot = ClassName "hero-foot"

-- | A ClassName for hero-head
heroHead :: ClassName
heroHead = ClassName "hero-head"

-- | A ClassName for hero-video
heroVideo :: ClassName
heroVideo = ClassName "hero-video"

-- | A ClassName for highlight
highlight :: ClassName
highlight = ClassName "highlight"

-- | A ClassName for icon
icon :: ClassName
icon = ClassName "icon"

-- | A ClassName for image
image :: ClassName
image = ClassName "image"

-- | A ClassName for input
input :: ClassName
input = ClassName "input"

-- | A ClassName for is-0
is0 :: ClassName
is0 = ClassName "is-0"

-- | A ClassName for is-1
is1 :: ClassName
is1 = ClassName "is-1"

-- | A ClassName for is-10
is10 :: ClassName
is10 = ClassName "is-10"

-- | A ClassName for is-10-desktop
is10Desktop :: ClassName
is10Desktop = ClassName "is-10-desktop"

-- | A ClassName for is-10-fullhd
is10Fullhd :: ClassName
is10Fullhd = ClassName "is-10-fullhd"

-- | A ClassName for is-10-mobile
is10Mobile :: ClassName
is10Mobile = ClassName "is-10-mobile"

-- | A ClassName for is-10-tablet
is10Tablet :: ClassName
is10Tablet = ClassName "is-10-tablet"

-- | A ClassName for is-10-touch
is10Touch :: ClassName
is10Touch = ClassName "is-10-touch"

-- | A ClassName for is-10-widescreen
is10Widescreen :: ClassName
is10Widescreen = ClassName "is-10-widescreen"

-- | A ClassName for is-11
is11 :: ClassName
is11 = ClassName "is-11"

-- | A ClassName for is-11-desktop
is11Desktop :: ClassName
is11Desktop = ClassName "is-11-desktop"

-- | A ClassName for is-11-fullhd
is11Fullhd :: ClassName
is11Fullhd = ClassName "is-11-fullhd"

-- | A ClassName for is-11-mobile
is11Mobile :: ClassName
is11Mobile = ClassName "is-11-mobile"

-- | A ClassName for is-11-tablet
is11Tablet :: ClassName
is11Tablet = ClassName "is-11-tablet"

-- | A ClassName for is-11-touch
is11Touch :: ClassName
is11Touch = ClassName "is-11-touch"

-- | A ClassName for is-11-widescreen
is11Widescreen :: ClassName
is11Widescreen = ClassName "is-11-widescreen"

-- | A ClassName for is-12
is12 :: ClassName
is12 = ClassName "is-12"

-- | A ClassName for is-128x128
is128X128 :: ClassName
is128X128 = ClassName "is-128x128"

-- | A ClassName for is-12-desktop
is12Desktop :: ClassName
is12Desktop = ClassName "is-12-desktop"

-- | A ClassName for is-12-fullhd
is12Fullhd :: ClassName
is12Fullhd = ClassName "is-12-fullhd"

-- | A ClassName for is-12-mobile
is12Mobile :: ClassName
is12Mobile = ClassName "is-12-mobile"

-- | A ClassName for is-12-tablet
is12Tablet :: ClassName
is12Tablet = ClassName "is-12-tablet"

-- | A ClassName for is-12-touch
is12Touch :: ClassName
is12Touch = ClassName "is-12-touch"

-- | A ClassName for is-12-widescreen
is12Widescreen :: ClassName
is12Widescreen = ClassName "is-12-widescreen"

-- | A ClassName for is-16by9
is16By9 :: ClassName
is16By9 = ClassName "is-16by9"

-- | A ClassName for is-16x16
is16X16 :: ClassName
is16X16 = ClassName "is-16x16"

-- | A ClassName for is-1by1
is1By1 :: ClassName
is1By1 = ClassName "is-1by1"

-- | A ClassName for is-1by2
is1By2 :: ClassName
is1By2 = ClassName "is-1by2"

-- | A ClassName for is-1by3
is1By3 :: ClassName
is1By3 = ClassName "is-1by3"

-- | A ClassName for is-1-desktop
is1Desktop :: ClassName
is1Desktop = ClassName "is-1-desktop"

-- | A ClassName for is-1-fullhd
is1Fullhd :: ClassName
is1Fullhd = ClassName "is-1-fullhd"

-- | A ClassName for is-1-mobile
is1Mobile :: ClassName
is1Mobile = ClassName "is-1-mobile"

-- | A ClassName for is-1-tablet
is1Tablet :: ClassName
is1Tablet = ClassName "is-1-tablet"

-- | A ClassName for is-1-touch
is1Touch :: ClassName
is1Touch = ClassName "is-1-touch"

-- | A ClassName for is-1-widescreen
is1Widescreen :: ClassName
is1Widescreen = ClassName "is-1-widescreen"

-- | A ClassName for is-2
is2 :: ClassName
is2 = ClassName "is-2"

-- | A ClassName for is-24x24
is24X24 :: ClassName
is24X24 = ClassName "is-24x24"

-- | A ClassName for is-2by1
is2By1 :: ClassName
is2By1 = ClassName "is-2by1"

-- | A ClassName for is-2by3
is2By3 :: ClassName
is2By3 = ClassName "is-2by3"

-- | A ClassName for is-2-desktop
is2Desktop :: ClassName
is2Desktop = ClassName "is-2-desktop"

-- | A ClassName for is-2-fullhd
is2Fullhd :: ClassName
is2Fullhd = ClassName "is-2-fullhd"

-- | A ClassName for is-2-mobile
is2Mobile :: ClassName
is2Mobile = ClassName "is-2-mobile"

-- | A ClassName for is-2-tablet
is2Tablet :: ClassName
is2Tablet = ClassName "is-2-tablet"

-- | A ClassName for is-2-touch
is2Touch :: ClassName
is2Touch = ClassName "is-2-touch"

-- | A ClassName for is-2-widescreen
is2Widescreen :: ClassName
is2Widescreen = ClassName "is-2-widescreen"

-- | A ClassName for is-3
is3 :: ClassName
is3 = ClassName "is-3"

-- | A ClassName for is-32x32
is32X32 :: ClassName
is32X32 = ClassName "is-32x32"

-- | A ClassName for is-3by1
is3By1 :: ClassName
is3By1 = ClassName "is-3by1"

-- | A ClassName for is-3by2
is3By2 :: ClassName
is3By2 = ClassName "is-3by2"

-- | A ClassName for is-3by4
is3By4 :: ClassName
is3By4 = ClassName "is-3by4"

-- | A ClassName for is-3by5
is3By5 :: ClassName
is3By5 = ClassName "is-3by5"

-- | A ClassName for is-3-desktop
is3Desktop :: ClassName
is3Desktop = ClassName "is-3-desktop"

-- | A ClassName for is-3-fullhd
is3Fullhd :: ClassName
is3Fullhd = ClassName "is-3-fullhd"

-- | A ClassName for is-3-mobile
is3Mobile :: ClassName
is3Mobile = ClassName "is-3-mobile"

-- | A ClassName for is-3-tablet
is3Tablet :: ClassName
is3Tablet = ClassName "is-3-tablet"

-- | A ClassName for is-3-touch
is3Touch :: ClassName
is3Touch = ClassName "is-3-touch"

-- | A ClassName for is-3-widescreen
is3Widescreen :: ClassName
is3Widescreen = ClassName "is-3-widescreen"

-- | A ClassName for is-4
is4 :: ClassName
is4 = ClassName "is-4"

-- | A ClassName for is-48x48
is48X48 :: ClassName
is48X48 = ClassName "is-48x48"

-- | A ClassName for is-4by3
is4By3 :: ClassName
is4By3 = ClassName "is-4by3"

-- | A ClassName for is-4by5
is4By5 :: ClassName
is4By5 = ClassName "is-4by5"

-- | A ClassName for is-4-desktop
is4Desktop :: ClassName
is4Desktop = ClassName "is-4-desktop"

-- | A ClassName for is-4-fullhd
is4Fullhd :: ClassName
is4Fullhd = ClassName "is-4-fullhd"

-- | A ClassName for is-4-mobile
is4Mobile :: ClassName
is4Mobile = ClassName "is-4-mobile"

-- | A ClassName for is-4-tablet
is4Tablet :: ClassName
is4Tablet = ClassName "is-4-tablet"

-- | A ClassName for is-4-touch
is4Touch :: ClassName
is4Touch = ClassName "is-4-touch"

-- | A ClassName for is-4-widescreen
is4Widescreen :: ClassName
is4Widescreen = ClassName "is-4-widescreen"

-- | A ClassName for is-5
is5 :: ClassName
is5 = ClassName "is-5"

-- | A ClassName for is-5by3
is5By3 :: ClassName
is5By3 = ClassName "is-5by3"

-- | A ClassName for is-5by4
is5By4 :: ClassName
is5By4 = ClassName "is-5by4"

-- | A ClassName for is-5-desktop
is5Desktop :: ClassName
is5Desktop = ClassName "is-5-desktop"

-- | A ClassName for is-5-fullhd
is5Fullhd :: ClassName
is5Fullhd = ClassName "is-5-fullhd"

-- | A ClassName for is-5-mobile
is5Mobile :: ClassName
is5Mobile = ClassName "is-5-mobile"

-- | A ClassName for is-5-tablet
is5Tablet :: ClassName
is5Tablet = ClassName "is-5-tablet"

-- | A ClassName for is-5-touch
is5Touch :: ClassName
is5Touch = ClassName "is-5-touch"

-- | A ClassName for is-5-widescreen
is5Widescreen :: ClassName
is5Widescreen = ClassName "is-5-widescreen"

-- | A ClassName for is-6
is6 :: ClassName
is6 = ClassName "is-6"

-- | A ClassName for is-64x64
is64X64 :: ClassName
is64X64 = ClassName "is-64x64"

-- | A ClassName for is-6-desktop
is6Desktop :: ClassName
is6Desktop = ClassName "is-6-desktop"

-- | A ClassName for is-6-fullhd
is6Fullhd :: ClassName
is6Fullhd = ClassName "is-6-fullhd"

-- | A ClassName for is-6-mobile
is6Mobile :: ClassName
is6Mobile = ClassName "is-6-mobile"

-- | A ClassName for is-6-tablet
is6Tablet :: ClassName
is6Tablet = ClassName "is-6-tablet"

-- | A ClassName for is-6-touch
is6Touch :: ClassName
is6Touch = ClassName "is-6-touch"

-- | A ClassName for is-6-widescreen
is6Widescreen :: ClassName
is6Widescreen = ClassName "is-6-widescreen"

-- | A ClassName for is-7
is7 :: ClassName
is7 = ClassName "is-7"

-- | A ClassName for is-7-desktop
is7Desktop :: ClassName
is7Desktop = ClassName "is-7-desktop"

-- | A ClassName for is-7-fullhd
is7Fullhd :: ClassName
is7Fullhd = ClassName "is-7-fullhd"

-- | A ClassName for is-7-mobile
is7Mobile :: ClassName
is7Mobile = ClassName "is-7-mobile"

-- | A ClassName for is-7-tablet
is7Tablet :: ClassName
is7Tablet = ClassName "is-7-tablet"

-- | A ClassName for is-7-touch
is7Touch :: ClassName
is7Touch = ClassName "is-7-touch"

-- | A ClassName for is-7-widescreen
is7Widescreen :: ClassName
is7Widescreen = ClassName "is-7-widescreen"

-- | A ClassName for is-8
is8 :: ClassName
is8 = ClassName "is-8"

-- | A ClassName for is-8-desktop
is8Desktop :: ClassName
is8Desktop = ClassName "is-8-desktop"

-- | A ClassName for is-8-fullhd
is8Fullhd :: ClassName
is8Fullhd = ClassName "is-8-fullhd"

-- | A ClassName for is-8-mobile
is8Mobile :: ClassName
is8Mobile = ClassName "is-8-mobile"

-- | A ClassName for is-8-tablet
is8Tablet :: ClassName
is8Tablet = ClassName "is-8-tablet"

-- | A ClassName for is-8-touch
is8Touch :: ClassName
is8Touch = ClassName "is-8-touch"

-- | A ClassName for is-8-widescreen
is8Widescreen :: ClassName
is8Widescreen = ClassName "is-8-widescreen"

-- | A ClassName for is-9
is9 :: ClassName
is9 = ClassName "is-9"

-- | A ClassName for is-96x96
is96X96 :: ClassName
is96X96 = ClassName "is-96x96"

-- | A ClassName for is-9by16
is9By16 :: ClassName
is9By16 = ClassName "is-9by16"

-- | A ClassName for is-9-desktop
is9Desktop :: ClassName
is9Desktop = ClassName "is-9-desktop"

-- | A ClassName for is-9-fullhd
is9Fullhd :: ClassName
is9Fullhd = ClassName "is-9-fullhd"

-- | A ClassName for is-9-mobile
is9Mobile :: ClassName
is9Mobile = ClassName "is-9-mobile"

-- | A ClassName for is-9-tablet
is9Tablet :: ClassName
is9Tablet = ClassName "is-9-tablet"

-- | A ClassName for is-9-touch
is9Touch :: ClassName
is9Touch = ClassName "is-9-touch"

-- | A ClassName for is-9-widescreen
is9Widescreen :: ClassName
is9Widescreen = ClassName "is-9-widescreen"

-- | A ClassName for is-active
isActive :: ClassName
isActive = ClassName "is-active"

-- | A ClassName for is-ancestor
isAncestor :: ClassName
isAncestor = ClassName "is-ancestor"

-- | A ClassName for is-black
isBlack :: ClassName
isBlack = ClassName "is-black"

-- | A ClassName for is-block
isBlock :: ClassName
isBlock = ClassName "is-block"

-- | A ClassName for is-block-desktop
isBlockDesktop :: ClassName
isBlockDesktop = ClassName "is-block-desktop"

-- | A ClassName for is-block-desktop-only
isBlockDesktopOnly :: ClassName
isBlockDesktopOnly = ClassName "is-block-desktop-only"

-- | A ClassName for is-block-fullhd
isBlockFullhd :: ClassName
isBlockFullhd = ClassName "is-block-fullhd"

-- | A ClassName for is-block-mobile
isBlockMobile :: ClassName
isBlockMobile = ClassName "is-block-mobile"

-- | A ClassName for is-block-tablet
isBlockTablet :: ClassName
isBlockTablet = ClassName "is-block-tablet"

-- | A ClassName for is-block-tablet-only
isBlockTabletOnly :: ClassName
isBlockTabletOnly = ClassName "is-block-tablet-only"

-- | A ClassName for is-block-touch
isBlockTouch :: ClassName
isBlockTouch = ClassName "is-block-touch"

-- | A ClassName for is-block-widescreen
isBlockWidescreen :: ClassName
isBlockWidescreen = ClassName "is-block-widescreen"

-- | A ClassName for is-block-widescreen-only
isBlockWidescreenOnly :: ClassName
isBlockWidescreenOnly = ClassName "is-block-widescreen-only"

-- | A ClassName for is-bold
isBold :: ClassName
isBold = ClassName "is-bold"

-- | A ClassName for is-bordered
isBordered :: ClassName
isBordered = ClassName "is-bordered"

-- | A ClassName for is-boxed
isBoxed :: ClassName
isBoxed = ClassName "is-boxed"

-- | A ClassName for is-capitalized
isCapitalized :: ClassName
isCapitalized = ClassName "is-capitalized"

-- | A ClassName for is-center
isCenter :: ClassName
isCenter = ClassName "is-center"

-- | A ClassName for is-centered
isCentered :: ClassName
isCentered = ClassName "is-centered"

-- | A ClassName for is-child
isChild :: ClassName
isChild = ClassName "is-child"

-- | A ClassName for is-clearfix
isClearfix :: ClassName
isClearfix = ClassName "is-clearfix"

-- | A ClassName for is-clipped
isClipped :: ClassName
isClipped = ClassName "is-clipped"

-- | A ClassName for is-current
isCurrent :: ClassName
isCurrent = ClassName "is-current"

-- | A ClassName for is-danger
isDanger :: ClassName
isDanger = ClassName "is-danger"

-- | A ClassName for is-dark
isDark :: ClassName
isDark = ClassName "is-dark"

-- | A ClassName for is-delete
isDelete :: ClassName
isDelete = ClassName "is-delete"

-- | A ClassName for is-desktop
isDesktop :: ClassName
isDesktop = ClassName "is-desktop"

-- | A ClassName for is-disabled
isDisabled :: ClassName
isDisabled = ClassName "is-disabled"

-- | A ClassName for is-empty
isEmpty :: ClassName
isEmpty = ClassName "is-empty"

-- | A ClassName for is-expanded
isExpanded :: ClassName
isExpanded = ClassName "is-expanded"

-- | A ClassName for is-fixed-bottom
isFixedBottom :: ClassName
isFixedBottom = ClassName "is-fixed-bottom"

-- | A ClassName for is-fixed-bottom-desktop
isFixedBottomDesktop :: ClassName
isFixedBottomDesktop = ClassName "is-fixed-bottom-desktop"

-- | A ClassName for is-fixed-bottom-touch
isFixedBottomTouch :: ClassName
isFixedBottomTouch = ClassName "is-fixed-bottom-touch"

-- | A ClassName for is-fixed-top
isFixedTop :: ClassName
isFixedTop = ClassName "is-fixed-top"

-- | A ClassName for is-fixed-top-desktop
isFixedTopDesktop :: ClassName
isFixedTopDesktop = ClassName "is-fixed-top-desktop"

-- | A ClassName for is-fixed-top-touch
isFixedTopTouch :: ClassName
isFixedTopTouch = ClassName "is-fixed-top-touch"

-- | A ClassName for is-flex
isFlex :: ClassName
isFlex = ClassName "is-flex"

-- | A ClassName for is-flex-desktop
isFlexDesktop :: ClassName
isFlexDesktop = ClassName "is-flex-desktop"

-- | A ClassName for is-flex-desktop-only
isFlexDesktopOnly :: ClassName
isFlexDesktopOnly = ClassName "is-flex-desktop-only"

-- | A ClassName for is-flex-fullhd
isFlexFullhd :: ClassName
isFlexFullhd = ClassName "is-flex-fullhd"

-- | A ClassName for is-flex-mobile
isFlexMobile :: ClassName
isFlexMobile = ClassName "is-flex-mobile"

-- | A ClassName for is-flex-tablet
isFlexTablet :: ClassName
isFlexTablet = ClassName "is-flex-tablet"

-- | A ClassName for is-flex-tablet-only
isFlexTabletOnly :: ClassName
isFlexTabletOnly = ClassName "is-flex-tablet-only"

-- | A ClassName for is-flex-touch
isFlexTouch :: ClassName
isFlexTouch = ClassName "is-flex-touch"

-- | A ClassName for is-flex-widescreen
isFlexWidescreen :: ClassName
isFlexWidescreen = ClassName "is-flex-widescreen"

-- | A ClassName for is-flex-widescreen-only
isFlexWidescreenOnly :: ClassName
isFlexWidescreenOnly = ClassName "is-flex-widescreen-only"

-- | A ClassName for is-flexible
isFlexible :: ClassName
isFlexible = ClassName "is-flexible"

-- | A ClassName for is-fluid
isFluid :: ClassName
isFluid = ClassName "is-fluid"

-- | A ClassName for is-focused
isFocused :: ClassName
isFocused = ClassName "is-focused"

-- | A ClassName for is-four-fifths
isFourFifths :: ClassName
isFourFifths = ClassName "is-four-fifths"

-- | A ClassName for is-four-fifths-desktop
isFourFifthsDesktop :: ClassName
isFourFifthsDesktop = ClassName "is-four-fifths-desktop"

-- | A ClassName for is-four-fifths-fullhd
isFourFifthsFullhd :: ClassName
isFourFifthsFullhd = ClassName "is-four-fifths-fullhd"

-- | A ClassName for is-four-fifths-mobile
isFourFifthsMobile :: ClassName
isFourFifthsMobile = ClassName "is-four-fifths-mobile"

-- | A ClassName for is-four-fifths-tablet
isFourFifthsTablet :: ClassName
isFourFifthsTablet = ClassName "is-four-fifths-tablet"

-- | A ClassName for is-four-fifths-touch
isFourFifthsTouch :: ClassName
isFourFifthsTouch = ClassName "is-four-fifths-touch"

-- | A ClassName for is-four-fifths-widescreen
isFourFifthsWidescreen :: ClassName
isFourFifthsWidescreen = ClassName "is-four-fifths-widescreen"

-- | A ClassName for is-full
isFull :: ClassName
isFull = ClassName "is-full"

-- | A ClassName for is-full-desktop
isFullDesktop :: ClassName
isFullDesktop = ClassName "is-full-desktop"

-- | A ClassName for is-full-fullhd
isFullFullhd :: ClassName
isFullFullhd = ClassName "is-full-fullhd"

-- | A ClassName for is-full-mobile
isFullMobile :: ClassName
isFullMobile = ClassName "is-full-mobile"

-- | A ClassName for is-full-tablet
isFullTablet :: ClassName
isFullTablet = ClassName "is-full-tablet"

-- | A ClassName for is-full-touch
isFullTouch :: ClassName
isFullTouch = ClassName "is-full-touch"

-- | A ClassName for is-full-widescreen
isFullWidescreen :: ClassName
isFullWidescreen = ClassName "is-full-widescreen"

-- | A ClassName for is-fullhd
isFullhd :: ClassName
isFullhd = ClassName "is-fullhd"

-- | A ClassName for is-fullheight
isFullheight :: ClassName
isFullheight = ClassName "is-fullheight"

-- | A ClassName for is-fullwidth
isFullwidth :: ClassName
isFullwidth = ClassName "is-fullwidth"

-- | A ClassName for is-gapless
isGapless :: ClassName
isGapless = ClassName "is-gapless"

-- | A ClassName for is-grouped
isGrouped :: ClassName
isGrouped = ClassName "is-grouped"

-- | A ClassName for is-grouped-centered
isGroupedCentered :: ClassName
isGroupedCentered = ClassName "is-grouped-centered"

-- | A ClassName for is-grouped-multiline
isGroupedMultiline :: ClassName
isGroupedMultiline = ClassName "is-grouped-multiline"

-- | A ClassName for is-grouped-right
isGroupedRight :: ClassName
isGroupedRight = ClassName "is-grouped-right"

-- | A ClassName for is-half
isHalf :: ClassName
isHalf = ClassName "is-half"

-- | A ClassName for is-half-desktop
isHalfDesktop :: ClassName
isHalfDesktop = ClassName "is-half-desktop"

-- | A ClassName for is-half-fullhd
isHalfFullhd :: ClassName
isHalfFullhd = ClassName "is-half-fullhd"

-- | A ClassName for is-half-mobile
isHalfMobile :: ClassName
isHalfMobile = ClassName "is-half-mobile"

-- | A ClassName for is-half-tablet
isHalfTablet :: ClassName
isHalfTablet = ClassName "is-half-tablet"

-- | A ClassName for is-half-touch
isHalfTouch :: ClassName
isHalfTouch = ClassName "is-half-touch"

-- | A ClassName for is-half-widescreen
isHalfWidescreen :: ClassName
isHalfWidescreen = ClassName "is-half-widescreen"

-- | A ClassName for is-halfheight
isHalfheight :: ClassName
isHalfheight = ClassName "is-halfheight"

-- | A ClassName for is-hidden
isHidden :: ClassName
isHidden = ClassName "is-hidden"

-- | A ClassName for is-hidden-desktop
isHiddenDesktop :: ClassName
isHiddenDesktop = ClassName "is-hidden-desktop"

-- | A ClassName for is-hidden-desktop-only
isHiddenDesktopOnly :: ClassName
isHiddenDesktopOnly = ClassName "is-hidden-desktop-only"

-- | A ClassName for is-hidden-fullhd
isHiddenFullhd :: ClassName
isHiddenFullhd = ClassName "is-hidden-fullhd"

-- | A ClassName for is-hidden-mobile
isHiddenMobile :: ClassName
isHiddenMobile = ClassName "is-hidden-mobile"

-- | A ClassName for is-hidden-tablet
isHiddenTablet :: ClassName
isHiddenTablet = ClassName "is-hidden-tablet"

-- | A ClassName for is-hidden-tablet-only
isHiddenTabletOnly :: ClassName
isHiddenTabletOnly = ClassName "is-hidden-tablet-only"

-- | A ClassName for is-hidden-touch
isHiddenTouch :: ClassName
isHiddenTouch = ClassName "is-hidden-touch"

-- | A ClassName for is-hidden-widescreen
isHiddenWidescreen :: ClassName
isHiddenWidescreen = ClassName "is-hidden-widescreen"

-- | A ClassName for is-hidden-widescreen-only
isHiddenWidescreenOnly :: ClassName
isHiddenWidescreenOnly = ClassName "is-hidden-widescreen-only"

-- | A ClassName for is-horizontal
isHorizontal :: ClassName
isHorizontal = ClassName "is-horizontal"

-- | A ClassName for is-hoverable
isHoverable :: ClassName
isHoverable = ClassName "is-hoverable"

-- | A ClassName for is-hovered
isHovered :: ClassName
isHovered = ClassName "is-hovered"

-- | A ClassName for is-info
isInfo :: ClassName
isInfo = ClassName "is-info"

-- | A ClassName for is-inline
isInline :: ClassName
isInline = ClassName "is-inline"

-- | A ClassName for is-inline-block
isInlineBlock :: ClassName
isInlineBlock = ClassName "is-inline-block"

-- | A ClassName for is-inline-block-desktop
isInlineBlockDesktop :: ClassName
isInlineBlockDesktop = ClassName "is-inline-block-desktop"

-- | A ClassName for is-inline-block-desktop-only
isInlineBlockDesktopOnly :: ClassName
isInlineBlockDesktopOnly = ClassName "is-inline-block-desktop-only"

-- | A ClassName for is-inline-block-fullhd
isInlineBlockFullhd :: ClassName
isInlineBlockFullhd = ClassName "is-inline-block-fullhd"

-- | A ClassName for is-inline-block-mobile
isInlineBlockMobile :: ClassName
isInlineBlockMobile = ClassName "is-inline-block-mobile"

-- | A ClassName for is-inline-block-tablet
isInlineBlockTablet :: ClassName
isInlineBlockTablet = ClassName "is-inline-block-tablet"

-- | A ClassName for is-inline-block-tablet-only
isInlineBlockTabletOnly :: ClassName
isInlineBlockTabletOnly = ClassName "is-inline-block-tablet-only"

-- | A ClassName for is-inline-block-touch
isInlineBlockTouch :: ClassName
isInlineBlockTouch = ClassName "is-inline-block-touch"

-- | A ClassName for is-inline-block-widescreen
isInlineBlockWidescreen :: ClassName
isInlineBlockWidescreen = ClassName "is-inline-block-widescreen"

-- | A ClassName for is-inline-block-widescreen-only
isInlineBlockWidescreenOnly :: ClassName
isInlineBlockWidescreenOnly = ClassName "is-inline-block-widescreen-only"

-- | A ClassName for is-inline-desktop
isInlineDesktop :: ClassName
isInlineDesktop = ClassName "is-inline-desktop"

-- | A ClassName for is-inline-desktop-only
isInlineDesktopOnly :: ClassName
isInlineDesktopOnly = ClassName "is-inline-desktop-only"

-- | A ClassName for is-inline-flex
isInlineFlex :: ClassName
isInlineFlex = ClassName "is-inline-flex"

-- | A ClassName for is-inline-flex-desktop
isInlineFlexDesktop :: ClassName
isInlineFlexDesktop = ClassName "is-inline-flex-desktop"

-- | A ClassName for is-inline-flex-desktop-only
isInlineFlexDesktopOnly :: ClassName
isInlineFlexDesktopOnly = ClassName "is-inline-flex-desktop-only"

-- | A ClassName for is-inline-flex-fullhd
isInlineFlexFullhd :: ClassName
isInlineFlexFullhd = ClassName "is-inline-flex-fullhd"

-- | A ClassName for is-inline-flex-mobile
isInlineFlexMobile :: ClassName
isInlineFlexMobile = ClassName "is-inline-flex-mobile"

-- | A ClassName for is-inline-flex-tablet
isInlineFlexTablet :: ClassName
isInlineFlexTablet = ClassName "is-inline-flex-tablet"

-- | A ClassName for is-inline-flex-tablet-only
isInlineFlexTabletOnly :: ClassName
isInlineFlexTabletOnly = ClassName "is-inline-flex-tablet-only"

-- | A ClassName for is-inline-flex-touch
isInlineFlexTouch :: ClassName
isInlineFlexTouch = ClassName "is-inline-flex-touch"

-- | A ClassName for is-inline-flex-widescreen
isInlineFlexWidescreen :: ClassName
isInlineFlexWidescreen = ClassName "is-inline-flex-widescreen"

-- | A ClassName for is-inline-flex-widescreen-only
isInlineFlexWidescreenOnly :: ClassName
isInlineFlexWidescreenOnly = ClassName "is-inline-flex-widescreen-only"

-- | A ClassName for is-inline-fullhd
isInlineFullhd :: ClassName
isInlineFullhd = ClassName "is-inline-fullhd"

-- | A ClassName for is-inline-mobile
isInlineMobile :: ClassName
isInlineMobile = ClassName "is-inline-mobile"

-- | A ClassName for is-inline-tablet
isInlineTablet :: ClassName
isInlineTablet = ClassName "is-inline-tablet"

-- | A ClassName for is-inline-tablet-only
isInlineTabletOnly :: ClassName
isInlineTabletOnly = ClassName "is-inline-tablet-only"

-- | A ClassName for is-inline-touch
isInlineTouch :: ClassName
isInlineTouch = ClassName "is-inline-touch"

-- | A ClassName for is-inline-widescreen
isInlineWidescreen :: ClassName
isInlineWidescreen = ClassName "is-inline-widescreen"

-- | A ClassName for is-inline-widescreen-only
isInlineWidescreenOnly :: ClassName
isInlineWidescreenOnly = ClassName "is-inline-widescreen-only"

-- | A ClassName for is-inverted
isInverted :: ClassName
isInverted = ClassName "is-inverted"

-- | A ClassName for is-invisible
isInvisible :: ClassName
isInvisible = ClassName "is-invisible"

-- | A ClassName for is-invisible-desktop
isInvisibleDesktop :: ClassName
isInvisibleDesktop = ClassName "is-invisible-desktop"

-- | A ClassName for is-invisible-desktop-only
isInvisibleDesktopOnly :: ClassName
isInvisibleDesktopOnly = ClassName "is-invisible-desktop-only"

-- | A ClassName for is-invisible-fullhd
isInvisibleFullhd :: ClassName
isInvisibleFullhd = ClassName "is-invisible-fullhd"

-- | A ClassName for is-invisible-mobile
isInvisibleMobile :: ClassName
isInvisibleMobile = ClassName "is-invisible-mobile"

-- | A ClassName for is-invisible-tablet
isInvisibleTablet :: ClassName
isInvisibleTablet = ClassName "is-invisible-tablet"

-- | A ClassName for is-invisible-tablet-only
isInvisibleTabletOnly :: ClassName
isInvisibleTabletOnly = ClassName "is-invisible-tablet-only"

-- | A ClassName for is-invisible-touch
isInvisibleTouch :: ClassName
isInvisibleTouch = ClassName "is-invisible-touch"

-- | A ClassName for is-invisible-widescreen
isInvisibleWidescreen :: ClassName
isInvisibleWidescreen = ClassName "is-invisible-widescreen"

-- | A ClassName for is-invisible-widescreen-only
isInvisibleWidescreenOnly :: ClassName
isInvisibleWidescreenOnly = ClassName "is-invisible-widescreen-only"

-- | A ClassName for is-italic
isItalic :: ClassName
isItalic = ClassName "is-italic"

-- | A ClassName for is-large
isLarge :: ClassName
isLarge = ClassName "is-large"

-- | A ClassName for is-left
isLeft :: ClassName
isLeft = ClassName "is-left"

-- | A ClassName for is-light
isLight :: ClassName
isLight = ClassName "is-light"

-- | A ClassName for is-link
isLink :: ClassName
isLink = ClassName "is-link"

-- | A ClassName for is-loading
isLoading :: ClassName
isLoading = ClassName "is-loading"

-- | A ClassName for is-lowercase
isLowercase :: ClassName
isLowercase = ClassName "is-lowercase"

-- | A ClassName for is-marginless
isMarginless :: ClassName
isMarginless = ClassName "is-marginless"

-- | A ClassName for is-medium
isMedium :: ClassName
isMedium = ClassName "is-medium"

-- | A ClassName for is-mobile
isMobile :: ClassName
isMobile = ClassName "is-mobile"

-- | A ClassName for is-multiline
isMultiline :: ClassName
isMultiline = ClassName "is-multiline"

-- | A ClassName for is-multiple
isMultiple :: ClassName
isMultiple = ClassName "is-multiple"

-- | A ClassName for is-narrow
isNarrow :: ClassName
isNarrow = ClassName "is-narrow"

-- | A ClassName for is-narrow-desktop
isNarrowDesktop :: ClassName
isNarrowDesktop = ClassName "is-narrow-desktop"

-- | A ClassName for is-narrow-fullhd
isNarrowFullhd :: ClassName
isNarrowFullhd = ClassName "is-narrow-fullhd"

-- | A ClassName for is-narrow-mobile
isNarrowMobile :: ClassName
isNarrowMobile = ClassName "is-narrow-mobile"

-- | A ClassName for is-narrow-tablet
isNarrowTablet :: ClassName
isNarrowTablet = ClassName "is-narrow-tablet"

-- | A ClassName for is-narrow-touch
isNarrowTouch :: ClassName
isNarrowTouch = ClassName "is-narrow-touch"

-- | A ClassName for is-narrow-widescreen
isNarrowWidescreen :: ClassName
isNarrowWidescreen = ClassName "is-narrow-widescreen"

-- | A ClassName for is-normal
isNormal :: ClassName
isNormal = ClassName "is-normal"

-- | A ClassName for is-offset-1
isOffset1 :: ClassName
isOffset1 = ClassName "is-offset-1"

-- | A ClassName for is-offset-10
isOffset10 :: ClassName
isOffset10 = ClassName "is-offset-10"

-- | A ClassName for is-offset-10-desktop
isOffset10Desktop :: ClassName
isOffset10Desktop = ClassName "is-offset-10-desktop"

-- | A ClassName for is-offset-10-fullhd
isOffset10Fullhd :: ClassName
isOffset10Fullhd = ClassName "is-offset-10-fullhd"

-- | A ClassName for is-offset-10-mobile
isOffset10Mobile :: ClassName
isOffset10Mobile = ClassName "is-offset-10-mobile"

-- | A ClassName for is-offset-10-tablet
isOffset10Tablet :: ClassName
isOffset10Tablet = ClassName "is-offset-10-tablet"

-- | A ClassName for is-offset-10-touch
isOffset10Touch :: ClassName
isOffset10Touch = ClassName "is-offset-10-touch"

-- | A ClassName for is-offset-10-widescreen
isOffset10Widescreen :: ClassName
isOffset10Widescreen = ClassName "is-offset-10-widescreen"

-- | A ClassName for is-offset-11
isOffset11 :: ClassName
isOffset11 = ClassName "is-offset-11"

-- | A ClassName for is-offset-11-desktop
isOffset11Desktop :: ClassName
isOffset11Desktop = ClassName "is-offset-11-desktop"

-- | A ClassName for is-offset-11-fullhd
isOffset11Fullhd :: ClassName
isOffset11Fullhd = ClassName "is-offset-11-fullhd"

-- | A ClassName for is-offset-11-mobile
isOffset11Mobile :: ClassName
isOffset11Mobile = ClassName "is-offset-11-mobile"

-- | A ClassName for is-offset-11-tablet
isOffset11Tablet :: ClassName
isOffset11Tablet = ClassName "is-offset-11-tablet"

-- | A ClassName for is-offset-11-touch
isOffset11Touch :: ClassName
isOffset11Touch = ClassName "is-offset-11-touch"

-- | A ClassName for is-offset-11-widescreen
isOffset11Widescreen :: ClassName
isOffset11Widescreen = ClassName "is-offset-11-widescreen"

-- | A ClassName for is-offset-12
isOffset12 :: ClassName
isOffset12 = ClassName "is-offset-12"

-- | A ClassName for is-offset-12-desktop
isOffset12Desktop :: ClassName
isOffset12Desktop = ClassName "is-offset-12-desktop"

-- | A ClassName for is-offset-12-fullhd
isOffset12Fullhd :: ClassName
isOffset12Fullhd = ClassName "is-offset-12-fullhd"

-- | A ClassName for is-offset-12-mobile
isOffset12Mobile :: ClassName
isOffset12Mobile = ClassName "is-offset-12-mobile"

-- | A ClassName for is-offset-12-tablet
isOffset12Tablet :: ClassName
isOffset12Tablet = ClassName "is-offset-12-tablet"

-- | A ClassName for is-offset-12-touch
isOffset12Touch :: ClassName
isOffset12Touch = ClassName "is-offset-12-touch"

-- | A ClassName for is-offset-12-widescreen
isOffset12Widescreen :: ClassName
isOffset12Widescreen = ClassName "is-offset-12-widescreen"

-- | A ClassName for is-offset-1-desktop
isOffset1Desktop :: ClassName
isOffset1Desktop = ClassName "is-offset-1-desktop"

-- | A ClassName for is-offset-1-fullhd
isOffset1Fullhd :: ClassName
isOffset1Fullhd = ClassName "is-offset-1-fullhd"

-- | A ClassName for is-offset-1-mobile
isOffset1Mobile :: ClassName
isOffset1Mobile = ClassName "is-offset-1-mobile"

-- | A ClassName for is-offset-1-tablet
isOffset1Tablet :: ClassName
isOffset1Tablet = ClassName "is-offset-1-tablet"

-- | A ClassName for is-offset-1-touch
isOffset1Touch :: ClassName
isOffset1Touch = ClassName "is-offset-1-touch"

-- | A ClassName for is-offset-1-widescreen
isOffset1Widescreen :: ClassName
isOffset1Widescreen = ClassName "is-offset-1-widescreen"

-- | A ClassName for is-offset-2
isOffset2 :: ClassName
isOffset2 = ClassName "is-offset-2"

-- | A ClassName for is-offset-2-desktop
isOffset2Desktop :: ClassName
isOffset2Desktop = ClassName "is-offset-2-desktop"

-- | A ClassName for is-offset-2-fullhd
isOffset2Fullhd :: ClassName
isOffset2Fullhd = ClassName "is-offset-2-fullhd"

-- | A ClassName for is-offset-2-mobile
isOffset2Mobile :: ClassName
isOffset2Mobile = ClassName "is-offset-2-mobile"

-- | A ClassName for is-offset-2-tablet
isOffset2Tablet :: ClassName
isOffset2Tablet = ClassName "is-offset-2-tablet"

-- | A ClassName for is-offset-2-touch
isOffset2Touch :: ClassName
isOffset2Touch = ClassName "is-offset-2-touch"

-- | A ClassName for is-offset-2-widescreen
isOffset2Widescreen :: ClassName
isOffset2Widescreen = ClassName "is-offset-2-widescreen"

-- | A ClassName for is-offset-3
isOffset3 :: ClassName
isOffset3 = ClassName "is-offset-3"

-- | A ClassName for is-offset-3-desktop
isOffset3Desktop :: ClassName
isOffset3Desktop = ClassName "is-offset-3-desktop"

-- | A ClassName for is-offset-3-fullhd
isOffset3Fullhd :: ClassName
isOffset3Fullhd = ClassName "is-offset-3-fullhd"

-- | A ClassName for is-offset-3-mobile
isOffset3Mobile :: ClassName
isOffset3Mobile = ClassName "is-offset-3-mobile"

-- | A ClassName for is-offset-3-tablet
isOffset3Tablet :: ClassName
isOffset3Tablet = ClassName "is-offset-3-tablet"

-- | A ClassName for is-offset-3-touch
isOffset3Touch :: ClassName
isOffset3Touch = ClassName "is-offset-3-touch"

-- | A ClassName for is-offset-3-widescreen
isOffset3Widescreen :: ClassName
isOffset3Widescreen = ClassName "is-offset-3-widescreen"

-- | A ClassName for is-offset-4
isOffset4 :: ClassName
isOffset4 = ClassName "is-offset-4"

-- | A ClassName for is-offset-4-desktop
isOffset4Desktop :: ClassName
isOffset4Desktop = ClassName "is-offset-4-desktop"

-- | A ClassName for is-offset-4-fullhd
isOffset4Fullhd :: ClassName
isOffset4Fullhd = ClassName "is-offset-4-fullhd"

-- | A ClassName for is-offset-4-mobile
isOffset4Mobile :: ClassName
isOffset4Mobile = ClassName "is-offset-4-mobile"

-- | A ClassName for is-offset-4-tablet
isOffset4Tablet :: ClassName
isOffset4Tablet = ClassName "is-offset-4-tablet"

-- | A ClassName for is-offset-4-touch
isOffset4Touch :: ClassName
isOffset4Touch = ClassName "is-offset-4-touch"

-- | A ClassName for is-offset-4-widescreen
isOffset4Widescreen :: ClassName
isOffset4Widescreen = ClassName "is-offset-4-widescreen"

-- | A ClassName for is-offset-5
isOffset5 :: ClassName
isOffset5 = ClassName "is-offset-5"

-- | A ClassName for is-offset-5-desktop
isOffset5Desktop :: ClassName
isOffset5Desktop = ClassName "is-offset-5-desktop"

-- | A ClassName for is-offset-5-fullhd
isOffset5Fullhd :: ClassName
isOffset5Fullhd = ClassName "is-offset-5-fullhd"

-- | A ClassName for is-offset-5-mobile
isOffset5Mobile :: ClassName
isOffset5Mobile = ClassName "is-offset-5-mobile"

-- | A ClassName for is-offset-5-tablet
isOffset5Tablet :: ClassName
isOffset5Tablet = ClassName "is-offset-5-tablet"

-- | A ClassName for is-offset-5-touch
isOffset5Touch :: ClassName
isOffset5Touch = ClassName "is-offset-5-touch"

-- | A ClassName for is-offset-5-widescreen
isOffset5Widescreen :: ClassName
isOffset5Widescreen = ClassName "is-offset-5-widescreen"

-- | A ClassName for is-offset-6
isOffset6 :: ClassName
isOffset6 = ClassName "is-offset-6"

-- | A ClassName for is-offset-6-desktop
isOffset6Desktop :: ClassName
isOffset6Desktop = ClassName "is-offset-6-desktop"

-- | A ClassName for is-offset-6-fullhd
isOffset6Fullhd :: ClassName
isOffset6Fullhd = ClassName "is-offset-6-fullhd"

-- | A ClassName for is-offset-6-mobile
isOffset6Mobile :: ClassName
isOffset6Mobile = ClassName "is-offset-6-mobile"

-- | A ClassName for is-offset-6-tablet
isOffset6Tablet :: ClassName
isOffset6Tablet = ClassName "is-offset-6-tablet"

-- | A ClassName for is-offset-6-touch
isOffset6Touch :: ClassName
isOffset6Touch = ClassName "is-offset-6-touch"

-- | A ClassName for is-offset-6-widescreen
isOffset6Widescreen :: ClassName
isOffset6Widescreen = ClassName "is-offset-6-widescreen"

-- | A ClassName for is-offset-7
isOffset7 :: ClassName
isOffset7 = ClassName "is-offset-7"

-- | A ClassName for is-offset-7-desktop
isOffset7Desktop :: ClassName
isOffset7Desktop = ClassName "is-offset-7-desktop"

-- | A ClassName for is-offset-7-fullhd
isOffset7Fullhd :: ClassName
isOffset7Fullhd = ClassName "is-offset-7-fullhd"

-- | A ClassName for is-offset-7-mobile
isOffset7Mobile :: ClassName
isOffset7Mobile = ClassName "is-offset-7-mobile"

-- | A ClassName for is-offset-7-tablet
isOffset7Tablet :: ClassName
isOffset7Tablet = ClassName "is-offset-7-tablet"

-- | A ClassName for is-offset-7-touch
isOffset7Touch :: ClassName
isOffset7Touch = ClassName "is-offset-7-touch"

-- | A ClassName for is-offset-7-widescreen
isOffset7Widescreen :: ClassName
isOffset7Widescreen = ClassName "is-offset-7-widescreen"

-- | A ClassName for is-offset-8
isOffset8 :: ClassName
isOffset8 = ClassName "is-offset-8"

-- | A ClassName for is-offset-8-desktop
isOffset8Desktop :: ClassName
isOffset8Desktop = ClassName "is-offset-8-desktop"

-- | A ClassName for is-offset-8-fullhd
isOffset8Fullhd :: ClassName
isOffset8Fullhd = ClassName "is-offset-8-fullhd"

-- | A ClassName for is-offset-8-mobile
isOffset8Mobile :: ClassName
isOffset8Mobile = ClassName "is-offset-8-mobile"

-- | A ClassName for is-offset-8-tablet
isOffset8Tablet :: ClassName
isOffset8Tablet = ClassName "is-offset-8-tablet"

-- | A ClassName for is-offset-8-touch
isOffset8Touch :: ClassName
isOffset8Touch = ClassName "is-offset-8-touch"

-- | A ClassName for is-offset-8-widescreen
isOffset8Widescreen :: ClassName
isOffset8Widescreen = ClassName "is-offset-8-widescreen"

-- | A ClassName for is-offset-9
isOffset9 :: ClassName
isOffset9 = ClassName "is-offset-9"

-- | A ClassName for is-offset-9-desktop
isOffset9Desktop :: ClassName
isOffset9Desktop = ClassName "is-offset-9-desktop"

-- | A ClassName for is-offset-9-fullhd
isOffset9Fullhd :: ClassName
isOffset9Fullhd = ClassName "is-offset-9-fullhd"

-- | A ClassName for is-offset-9-mobile
isOffset9Mobile :: ClassName
isOffset9Mobile = ClassName "is-offset-9-mobile"

-- | A ClassName for is-offset-9-tablet
isOffset9Tablet :: ClassName
isOffset9Tablet = ClassName "is-offset-9-tablet"

-- | A ClassName for is-offset-9-touch
isOffset9Touch :: ClassName
isOffset9Touch = ClassName "is-offset-9-touch"

-- | A ClassName for is-offset-9-widescreen
isOffset9Widescreen :: ClassName
isOffset9Widescreen = ClassName "is-offset-9-widescreen"

-- | A ClassName for is-offset-four-fifths
isOffsetFourFifths :: ClassName
isOffsetFourFifths = ClassName "is-offset-four-fifths"

-- | A ClassName for is-offset-four-fifths-desktop
isOffsetFourFifthsDesktop :: ClassName
isOffsetFourFifthsDesktop = ClassName "is-offset-four-fifths-desktop"

-- | A ClassName for is-offset-four-fifths-fullhd
isOffsetFourFifthsFullhd :: ClassName
isOffsetFourFifthsFullhd = ClassName "is-offset-four-fifths-fullhd"

-- | A ClassName for is-offset-four-fifths-mobile
isOffsetFourFifthsMobile :: ClassName
isOffsetFourFifthsMobile = ClassName "is-offset-four-fifths-mobile"

-- | A ClassName for is-offset-four-fifths-tablet
isOffsetFourFifthsTablet :: ClassName
isOffsetFourFifthsTablet = ClassName "is-offset-four-fifths-tablet"

-- | A ClassName for is-offset-four-fifths-touch
isOffsetFourFifthsTouch :: ClassName
isOffsetFourFifthsTouch = ClassName "is-offset-four-fifths-touch"

-- | A ClassName for is-offset-four-fifths-widescreen
isOffsetFourFifthsWidescreen :: ClassName
isOffsetFourFifthsWidescreen = ClassName "is-offset-four-fifths-widescreen"

-- | A ClassName for is-offset-half
isOffsetHalf :: ClassName
isOffsetHalf = ClassName "is-offset-half"

-- | A ClassName for is-offset-half-desktop
isOffsetHalfDesktop :: ClassName
isOffsetHalfDesktop = ClassName "is-offset-half-desktop"

-- | A ClassName for is-offset-half-fullhd
isOffsetHalfFullhd :: ClassName
isOffsetHalfFullhd = ClassName "is-offset-half-fullhd"

-- | A ClassName for is-offset-half-mobile
isOffsetHalfMobile :: ClassName
isOffsetHalfMobile = ClassName "is-offset-half-mobile"

-- | A ClassName for is-offset-half-tablet
isOffsetHalfTablet :: ClassName
isOffsetHalfTablet = ClassName "is-offset-half-tablet"

-- | A ClassName for is-offset-half-touch
isOffsetHalfTouch :: ClassName
isOffsetHalfTouch = ClassName "is-offset-half-touch"

-- | A ClassName for is-offset-half-widescreen
isOffsetHalfWidescreen :: ClassName
isOffsetHalfWidescreen = ClassName "is-offset-half-widescreen"

-- | A ClassName for is-offset-one-fifth
isOffsetOneFifth :: ClassName
isOffsetOneFifth = ClassName "is-offset-one-fifth"

-- | A ClassName for is-offset-one-fifth-desktop
isOffsetOneFifthDesktop :: ClassName
isOffsetOneFifthDesktop = ClassName "is-offset-one-fifth-desktop"

-- | A ClassName for is-offset-one-fifth-fullhd
isOffsetOneFifthFullhd :: ClassName
isOffsetOneFifthFullhd = ClassName "is-offset-one-fifth-fullhd"

-- | A ClassName for is-offset-one-fifth-mobile
isOffsetOneFifthMobile :: ClassName
isOffsetOneFifthMobile = ClassName "is-offset-one-fifth-mobile"

-- | A ClassName for is-offset-one-fifth-tablet
isOffsetOneFifthTablet :: ClassName
isOffsetOneFifthTablet = ClassName "is-offset-one-fifth-tablet"

-- | A ClassName for is-offset-one-fifth-touch
isOffsetOneFifthTouch :: ClassName
isOffsetOneFifthTouch = ClassName "is-offset-one-fifth-touch"

-- | A ClassName for is-offset-one-fifth-widescreen
isOffsetOneFifthWidescreen :: ClassName
isOffsetOneFifthWidescreen = ClassName "is-offset-one-fifth-widescreen"

-- | A ClassName for is-offset-one-quarter
isOffsetOneQuarter :: ClassName
isOffsetOneQuarter = ClassName "is-offset-one-quarter"

-- | A ClassName for is-offset-one-quarter-desktop
isOffsetOneQuarterDesktop :: ClassName
isOffsetOneQuarterDesktop = ClassName "is-offset-one-quarter-desktop"

-- | A ClassName for is-offset-one-quarter-fullhd
isOffsetOneQuarterFullhd :: ClassName
isOffsetOneQuarterFullhd = ClassName "is-offset-one-quarter-fullhd"

-- | A ClassName for is-offset-one-quarter-mobile
isOffsetOneQuarterMobile :: ClassName
isOffsetOneQuarterMobile = ClassName "is-offset-one-quarter-mobile"

-- | A ClassName for is-offset-one-quarter-tablet
isOffsetOneQuarterTablet :: ClassName
isOffsetOneQuarterTablet = ClassName "is-offset-one-quarter-tablet"

-- | A ClassName for is-offset-one-quarter-touch
isOffsetOneQuarterTouch :: ClassName
isOffsetOneQuarterTouch = ClassName "is-offset-one-quarter-touch"

-- | A ClassName for is-offset-one-quarter-widescreen
isOffsetOneQuarterWidescreen :: ClassName
isOffsetOneQuarterWidescreen = ClassName "is-offset-one-quarter-widescreen"

-- | A ClassName for is-offset-one-third
isOffsetOneThird :: ClassName
isOffsetOneThird = ClassName "is-offset-one-third"

-- | A ClassName for is-offset-one-third-desktop
isOffsetOneThirdDesktop :: ClassName
isOffsetOneThirdDesktop = ClassName "is-offset-one-third-desktop"

-- | A ClassName for is-offset-one-third-fullhd
isOffsetOneThirdFullhd :: ClassName
isOffsetOneThirdFullhd = ClassName "is-offset-one-third-fullhd"

-- | A ClassName for is-offset-one-third-mobile
isOffsetOneThirdMobile :: ClassName
isOffsetOneThirdMobile = ClassName "is-offset-one-third-mobile"

-- | A ClassName for is-offset-one-third-tablet
isOffsetOneThirdTablet :: ClassName
isOffsetOneThirdTablet = ClassName "is-offset-one-third-tablet"

-- | A ClassName for is-offset-one-third-touch
isOffsetOneThirdTouch :: ClassName
isOffsetOneThirdTouch = ClassName "is-offset-one-third-touch"

-- | A ClassName for is-offset-one-third-widescreen
isOffsetOneThirdWidescreen :: ClassName
isOffsetOneThirdWidescreen = ClassName "is-offset-one-third-widescreen"

-- | A ClassName for is-offset-three-fifths
isOffsetThreeFifths :: ClassName
isOffsetThreeFifths = ClassName "is-offset-three-fifths"

-- | A ClassName for is-offset-three-fifths-desktop
isOffsetThreeFifthsDesktop :: ClassName
isOffsetThreeFifthsDesktop = ClassName "is-offset-three-fifths-desktop"

-- | A ClassName for is-offset-three-fifths-fullhd
isOffsetThreeFifthsFullhd :: ClassName
isOffsetThreeFifthsFullhd = ClassName "is-offset-three-fifths-fullhd"

-- | A ClassName for is-offset-three-fifths-mobile
isOffsetThreeFifthsMobile :: ClassName
isOffsetThreeFifthsMobile = ClassName "is-offset-three-fifths-mobile"

-- | A ClassName for is-offset-three-fifths-tablet
isOffsetThreeFifthsTablet :: ClassName
isOffsetThreeFifthsTablet = ClassName "is-offset-three-fifths-tablet"

-- | A ClassName for is-offset-three-fifths-touch
isOffsetThreeFifthsTouch :: ClassName
isOffsetThreeFifthsTouch = ClassName "is-offset-three-fifths-touch"

-- | A ClassName for is-offset-three-fifths-widescreen
isOffsetThreeFifthsWidescreen :: ClassName
isOffsetThreeFifthsWidescreen = ClassName "is-offset-three-fifths-widescreen"

-- | A ClassName for is-offset-three-quarters
isOffsetThreeQuarters :: ClassName
isOffsetThreeQuarters = ClassName "is-offset-three-quarters"

-- | A ClassName for is-offset-three-quarters-desktop
isOffsetThreeQuartersDesktop :: ClassName
isOffsetThreeQuartersDesktop = ClassName "is-offset-three-quarters-desktop"

-- | A ClassName for is-offset-three-quarters-fullhd
isOffsetThreeQuartersFullhd :: ClassName
isOffsetThreeQuartersFullhd = ClassName "is-offset-three-quarters-fullhd"

-- | A ClassName for is-offset-three-quarters-mobile
isOffsetThreeQuartersMobile :: ClassName
isOffsetThreeQuartersMobile = ClassName "is-offset-three-quarters-mobile"

-- | A ClassName for is-offset-three-quarters-tablet
isOffsetThreeQuartersTablet :: ClassName
isOffsetThreeQuartersTablet = ClassName "is-offset-three-quarters-tablet"

-- | A ClassName for is-offset-three-quarters-touch
isOffsetThreeQuartersTouch :: ClassName
isOffsetThreeQuartersTouch = ClassName "is-offset-three-quarters-touch"

-- | A ClassName for is-offset-three-quarters-widescreen
isOffsetThreeQuartersWidescreen :: ClassName
isOffsetThreeQuartersWidescreen = ClassName "is-offset-three-quarters-widescreen"

-- | A ClassName for is-offset-two-fifths
isOffsetTwoFifths :: ClassName
isOffsetTwoFifths = ClassName "is-offset-two-fifths"

-- | A ClassName for is-offset-two-fifths-desktop
isOffsetTwoFifthsDesktop :: ClassName
isOffsetTwoFifthsDesktop = ClassName "is-offset-two-fifths-desktop"

-- | A ClassName for is-offset-two-fifths-fullhd
isOffsetTwoFifthsFullhd :: ClassName
isOffsetTwoFifthsFullhd = ClassName "is-offset-two-fifths-fullhd"

-- | A ClassName for is-offset-two-fifths-mobile
isOffsetTwoFifthsMobile :: ClassName
isOffsetTwoFifthsMobile = ClassName "is-offset-two-fifths-mobile"

-- | A ClassName for is-offset-two-fifths-tablet
isOffsetTwoFifthsTablet :: ClassName
isOffsetTwoFifthsTablet = ClassName "is-offset-two-fifths-tablet"

-- | A ClassName for is-offset-two-fifths-touch
isOffsetTwoFifthsTouch :: ClassName
isOffsetTwoFifthsTouch = ClassName "is-offset-two-fifths-touch"

-- | A ClassName for is-offset-two-fifths-widescreen
isOffsetTwoFifthsWidescreen :: ClassName
isOffsetTwoFifthsWidescreen = ClassName "is-offset-two-fifths-widescreen"

-- | A ClassName for is-offset-two-thirds
isOffsetTwoThirds :: ClassName
isOffsetTwoThirds = ClassName "is-offset-two-thirds"

-- | A ClassName for is-offset-two-thirds-desktop
isOffsetTwoThirdsDesktop :: ClassName
isOffsetTwoThirdsDesktop = ClassName "is-offset-two-thirds-desktop"

-- | A ClassName for is-offset-two-thirds-fullhd
isOffsetTwoThirdsFullhd :: ClassName
isOffsetTwoThirdsFullhd = ClassName "is-offset-two-thirds-fullhd"

-- | A ClassName for is-offset-two-thirds-mobile
isOffsetTwoThirdsMobile :: ClassName
isOffsetTwoThirdsMobile = ClassName "is-offset-two-thirds-mobile"

-- | A ClassName for is-offset-two-thirds-tablet
isOffsetTwoThirdsTablet :: ClassName
isOffsetTwoThirdsTablet = ClassName "is-offset-two-thirds-tablet"

-- | A ClassName for is-offset-two-thirds-touch
isOffsetTwoThirdsTouch :: ClassName
isOffsetTwoThirdsTouch = ClassName "is-offset-two-thirds-touch"

-- | A ClassName for is-offset-two-thirds-widescreen
isOffsetTwoThirdsWidescreen :: ClassName
isOffsetTwoThirdsWidescreen = ClassName "is-offset-two-thirds-widescreen"

-- | A ClassName for is-one-fifth
isOneFifth :: ClassName
isOneFifth = ClassName "is-one-fifth"

-- | A ClassName for is-one-fifth-desktop
isOneFifthDesktop :: ClassName
isOneFifthDesktop = ClassName "is-one-fifth-desktop"

-- | A ClassName for is-one-fifth-fullhd
isOneFifthFullhd :: ClassName
isOneFifthFullhd = ClassName "is-one-fifth-fullhd"

-- | A ClassName for is-one-fifth-mobile
isOneFifthMobile :: ClassName
isOneFifthMobile = ClassName "is-one-fifth-mobile"

-- | A ClassName for is-one-fifth-tablet
isOneFifthTablet :: ClassName
isOneFifthTablet = ClassName "is-one-fifth-tablet"

-- | A ClassName for is-one-fifth-touch
isOneFifthTouch :: ClassName
isOneFifthTouch = ClassName "is-one-fifth-touch"

-- | A ClassName for is-one-fifth-widescreen
isOneFifthWidescreen :: ClassName
isOneFifthWidescreen = ClassName "is-one-fifth-widescreen"

-- | A ClassName for is-one-quarter
isOneQuarter :: ClassName
isOneQuarter = ClassName "is-one-quarter"

-- | A ClassName for is-one-quarter-desktop
isOneQuarterDesktop :: ClassName
isOneQuarterDesktop = ClassName "is-one-quarter-desktop"

-- | A ClassName for is-one-quarter-fullhd
isOneQuarterFullhd :: ClassName
isOneQuarterFullhd = ClassName "is-one-quarter-fullhd"

-- | A ClassName for is-one-quarter-mobile
isOneQuarterMobile :: ClassName
isOneQuarterMobile = ClassName "is-one-quarter-mobile"

-- | A ClassName for is-one-quarter-tablet
isOneQuarterTablet :: ClassName
isOneQuarterTablet = ClassName "is-one-quarter-tablet"

-- | A ClassName for is-one-quarter-touch
isOneQuarterTouch :: ClassName
isOneQuarterTouch = ClassName "is-one-quarter-touch"

-- | A ClassName for is-one-quarter-widescreen
isOneQuarterWidescreen :: ClassName
isOneQuarterWidescreen = ClassName "is-one-quarter-widescreen"

-- | A ClassName for is-one-third
isOneThird :: ClassName
isOneThird = ClassName "is-one-third"

-- | A ClassName for is-one-third-desktop
isOneThirdDesktop :: ClassName
isOneThirdDesktop = ClassName "is-one-third-desktop"

-- | A ClassName for is-one-third-fullhd
isOneThirdFullhd :: ClassName
isOneThirdFullhd = ClassName "is-one-third-fullhd"

-- | A ClassName for is-one-third-mobile
isOneThirdMobile :: ClassName
isOneThirdMobile = ClassName "is-one-third-mobile"

-- | A ClassName for is-one-third-tablet
isOneThirdTablet :: ClassName
isOneThirdTablet = ClassName "is-one-third-tablet"

-- | A ClassName for is-one-third-touch
isOneThirdTouch :: ClassName
isOneThirdTouch = ClassName "is-one-third-touch"

-- | A ClassName for is-one-third-widescreen
isOneThirdWidescreen :: ClassName
isOneThirdWidescreen = ClassName "is-one-third-widescreen"

-- | A ClassName for is-outlined
isOutlined :: ClassName
isOutlined = ClassName "is-outlined"

-- | A ClassName for is-overlay
isOverlay :: ClassName
isOverlay = ClassName "is-overlay"

-- | A ClassName for is-paddingless
isPaddingless :: ClassName
isPaddingless = ClassName "is-paddingless"

-- | A ClassName for is-parent
isParent :: ClassName
isParent = ClassName "is-parent"

-- | A ClassName for is-primary
isPrimary :: ClassName
isPrimary = ClassName "is-primary"

-- | A ClassName for is-pulled-left
isPulledLeft :: ClassName
isPulledLeft = ClassName "is-pulled-left"

-- | A ClassName for is-pulled-right
isPulledRight :: ClassName
isPulledRight = ClassName "is-pulled-right"

-- | A ClassName for is-radiusless
isRadiusless :: ClassName
isRadiusless = ClassName "is-radiusless"

-- | A ClassName for is-right
isRight :: ClassName
isRight = ClassName "is-right"

-- | A ClassName for is-rounded
isRounded :: ClassName
isRounded = ClassName "is-rounded"

-- | A ClassName for is-selected
isSelected :: ClassName
isSelected = ClassName "is-selected"

-- | A ClassName for is-shadowless
isShadowless :: ClassName
isShadowless = ClassName "is-shadowless"

-- | A ClassName for is-size-1
isSize1 :: ClassName
isSize1 = ClassName "is-size-1"

-- | A ClassName for is-size-1-desktop
isSize1Desktop :: ClassName
isSize1Desktop = ClassName "is-size-1-desktop"

-- | A ClassName for is-size-1-fullhd
isSize1Fullhd :: ClassName
isSize1Fullhd = ClassName "is-size-1-fullhd"

-- | A ClassName for is-size-1-mobile
isSize1Mobile :: ClassName
isSize1Mobile = ClassName "is-size-1-mobile"

-- | A ClassName for is-size-1-tablet
isSize1Tablet :: ClassName
isSize1Tablet = ClassName "is-size-1-tablet"

-- | A ClassName for is-size-1-touch
isSize1Touch :: ClassName
isSize1Touch = ClassName "is-size-1-touch"

-- | A ClassName for is-size-1-widescreen
isSize1Widescreen :: ClassName
isSize1Widescreen = ClassName "is-size-1-widescreen"

-- | A ClassName for is-size-2
isSize2 :: ClassName
isSize2 = ClassName "is-size-2"

-- | A ClassName for is-size-2-desktop
isSize2Desktop :: ClassName
isSize2Desktop = ClassName "is-size-2-desktop"

-- | A ClassName for is-size-2-fullhd
isSize2Fullhd :: ClassName
isSize2Fullhd = ClassName "is-size-2-fullhd"

-- | A ClassName for is-size-2-mobile
isSize2Mobile :: ClassName
isSize2Mobile = ClassName "is-size-2-mobile"

-- | A ClassName for is-size-2-tablet
isSize2Tablet :: ClassName
isSize2Tablet = ClassName "is-size-2-tablet"

-- | A ClassName for is-size-2-touch
isSize2Touch :: ClassName
isSize2Touch = ClassName "is-size-2-touch"

-- | A ClassName for is-size-2-widescreen
isSize2Widescreen :: ClassName
isSize2Widescreen = ClassName "is-size-2-widescreen"

-- | A ClassName for is-size-3
isSize3 :: ClassName
isSize3 = ClassName "is-size-3"

-- | A ClassName for is-size-3-desktop
isSize3Desktop :: ClassName
isSize3Desktop = ClassName "is-size-3-desktop"

-- | A ClassName for is-size-3-fullhd
isSize3Fullhd :: ClassName
isSize3Fullhd = ClassName "is-size-3-fullhd"

-- | A ClassName for is-size-3-mobile
isSize3Mobile :: ClassName
isSize3Mobile = ClassName "is-size-3-mobile"

-- | A ClassName for is-size-3-tablet
isSize3Tablet :: ClassName
isSize3Tablet = ClassName "is-size-3-tablet"

-- | A ClassName for is-size-3-touch
isSize3Touch :: ClassName
isSize3Touch = ClassName "is-size-3-touch"

-- | A ClassName for is-size-3-widescreen
isSize3Widescreen :: ClassName
isSize3Widescreen = ClassName "is-size-3-widescreen"

-- | A ClassName for is-size-4
isSize4 :: ClassName
isSize4 = ClassName "is-size-4"

-- | A ClassName for is-size-4-desktop
isSize4Desktop :: ClassName
isSize4Desktop = ClassName "is-size-4-desktop"

-- | A ClassName for is-size-4-fullhd
isSize4Fullhd :: ClassName
isSize4Fullhd = ClassName "is-size-4-fullhd"

-- | A ClassName for is-size-4-mobile
isSize4Mobile :: ClassName
isSize4Mobile = ClassName "is-size-4-mobile"

-- | A ClassName for is-size-4-tablet
isSize4Tablet :: ClassName
isSize4Tablet = ClassName "is-size-4-tablet"

-- | A ClassName for is-size-4-touch
isSize4Touch :: ClassName
isSize4Touch = ClassName "is-size-4-touch"

-- | A ClassName for is-size-4-widescreen
isSize4Widescreen :: ClassName
isSize4Widescreen = ClassName "is-size-4-widescreen"

-- | A ClassName for is-size-5
isSize5 :: ClassName
isSize5 = ClassName "is-size-5"

-- | A ClassName for is-size-5-desktop
isSize5Desktop :: ClassName
isSize5Desktop = ClassName "is-size-5-desktop"

-- | A ClassName for is-size-5-fullhd
isSize5Fullhd :: ClassName
isSize5Fullhd = ClassName "is-size-5-fullhd"

-- | A ClassName for is-size-5-mobile
isSize5Mobile :: ClassName
isSize5Mobile = ClassName "is-size-5-mobile"

-- | A ClassName for is-size-5-tablet
isSize5Tablet :: ClassName
isSize5Tablet = ClassName "is-size-5-tablet"

-- | A ClassName for is-size-5-touch
isSize5Touch :: ClassName
isSize5Touch = ClassName "is-size-5-touch"

-- | A ClassName for is-size-5-widescreen
isSize5Widescreen :: ClassName
isSize5Widescreen = ClassName "is-size-5-widescreen"

-- | A ClassName for is-size-6
isSize6 :: ClassName
isSize6 = ClassName "is-size-6"

-- | A ClassName for is-size-6-desktop
isSize6Desktop :: ClassName
isSize6Desktop = ClassName "is-size-6-desktop"

-- | A ClassName for is-size-6-fullhd
isSize6Fullhd :: ClassName
isSize6Fullhd = ClassName "is-size-6-fullhd"

-- | A ClassName for is-size-6-mobile
isSize6Mobile :: ClassName
isSize6Mobile = ClassName "is-size-6-mobile"

-- | A ClassName for is-size-6-tablet
isSize6Tablet :: ClassName
isSize6Tablet = ClassName "is-size-6-tablet"

-- | A ClassName for is-size-6-touch
isSize6Touch :: ClassName
isSize6Touch = ClassName "is-size-6-touch"

-- | A ClassName for is-size-6-widescreen
isSize6Widescreen :: ClassName
isSize6Widescreen = ClassName "is-size-6-widescreen"

-- | A ClassName for is-size-7
isSize7 :: ClassName
isSize7 = ClassName "is-size-7"

-- | A ClassName for is-size-7-desktop
isSize7Desktop :: ClassName
isSize7Desktop = ClassName "is-size-7-desktop"

-- | A ClassName for is-size-7-fullhd
isSize7Fullhd :: ClassName
isSize7Fullhd = ClassName "is-size-7-fullhd"

-- | A ClassName for is-size-7-mobile
isSize7Mobile :: ClassName
isSize7Mobile = ClassName "is-size-7-mobile"

-- | A ClassName for is-size-7-tablet
isSize7Tablet :: ClassName
isSize7Tablet = ClassName "is-size-7-tablet"

-- | A ClassName for is-size-7-touch
isSize7Touch :: ClassName
isSize7Touch = ClassName "is-size-7-touch"

-- | A ClassName for is-size-7-widescreen
isSize7Widescreen :: ClassName
isSize7Widescreen = ClassName "is-size-7-widescreen"

-- | A ClassName for is-small
isSmall :: ClassName
isSmall = ClassName "is-small"

-- | A ClassName for is-spaced
isSpaced :: ClassName
isSpaced = ClassName "is-spaced"

-- | A ClassName for is-square
isSquare :: ClassName
isSquare = ClassName "is-square"

-- | A ClassName for is-static
isStatic :: ClassName
isStatic = ClassName "is-static"

-- | A ClassName for is-striped
isStriped :: ClassName
isStriped = ClassName "is-striped"

-- | A ClassName for is-success
isSuccess :: ClassName
isSuccess = ClassName "is-success"

-- | A ClassName for is-tab
isTab :: ClassName
isTab = ClassName "is-tab"

-- | A ClassName for is-text
isText :: ClassName
isText = ClassName "is-text"

-- | A ClassName for is-three-fifths
isThreeFifths :: ClassName
isThreeFifths = ClassName "is-three-fifths"

-- | A ClassName for is-three-fifths-desktop
isThreeFifthsDesktop :: ClassName
isThreeFifthsDesktop = ClassName "is-three-fifths-desktop"

-- | A ClassName for is-three-fifths-fullhd
isThreeFifthsFullhd :: ClassName
isThreeFifthsFullhd = ClassName "is-three-fifths-fullhd"

-- | A ClassName for is-three-fifths-mobile
isThreeFifthsMobile :: ClassName
isThreeFifthsMobile = ClassName "is-three-fifths-mobile"

-- | A ClassName for is-three-fifths-tablet
isThreeFifthsTablet :: ClassName
isThreeFifthsTablet = ClassName "is-three-fifths-tablet"

-- | A ClassName for is-three-fifths-touch
isThreeFifthsTouch :: ClassName
isThreeFifthsTouch = ClassName "is-three-fifths-touch"

-- | A ClassName for is-three-fifths-widescreen
isThreeFifthsWidescreen :: ClassName
isThreeFifthsWidescreen = ClassName "is-three-fifths-widescreen"

-- | A ClassName for is-three-quarters
isThreeQuarters :: ClassName
isThreeQuarters = ClassName "is-three-quarters"

-- | A ClassName for is-three-quarters-desktop
isThreeQuartersDesktop :: ClassName
isThreeQuartersDesktop = ClassName "is-three-quarters-desktop"

-- | A ClassName for is-three-quarters-fullhd
isThreeQuartersFullhd :: ClassName
isThreeQuartersFullhd = ClassName "is-three-quarters-fullhd"

-- | A ClassName for is-three-quarters-mobile
isThreeQuartersMobile :: ClassName
isThreeQuartersMobile = ClassName "is-three-quarters-mobile"

-- | A ClassName for is-three-quarters-tablet
isThreeQuartersTablet :: ClassName
isThreeQuartersTablet = ClassName "is-three-quarters-tablet"

-- | A ClassName for is-three-quarters-touch
isThreeQuartersTouch :: ClassName
isThreeQuartersTouch = ClassName "is-three-quarters-touch"

-- | A ClassName for is-three-quarters-widescreen
isThreeQuartersWidescreen :: ClassName
isThreeQuartersWidescreen = ClassName "is-three-quarters-widescreen"

-- | A ClassName for is-toggle
isToggle :: ClassName
isToggle = ClassName "is-toggle"

-- | A ClassName for is-toggle-rounded
isToggleRounded :: ClassName
isToggleRounded = ClassName "is-toggle-rounded"

-- | A ClassName for is-transparent
isTransparent :: ClassName
isTransparent = ClassName "is-transparent"

-- | A ClassName for is-two-fifths
isTwoFifths :: ClassName
isTwoFifths = ClassName "is-two-fifths"

-- | A ClassName for is-two-fifths-desktop
isTwoFifthsDesktop :: ClassName
isTwoFifthsDesktop = ClassName "is-two-fifths-desktop"

-- | A ClassName for is-two-fifths-fullhd
isTwoFifthsFullhd :: ClassName
isTwoFifthsFullhd = ClassName "is-two-fifths-fullhd"

-- | A ClassName for is-two-fifths-mobile
isTwoFifthsMobile :: ClassName
isTwoFifthsMobile = ClassName "is-two-fifths-mobile"

-- | A ClassName for is-two-fifths-tablet
isTwoFifthsTablet :: ClassName
isTwoFifthsTablet = ClassName "is-two-fifths-tablet"

-- | A ClassName for is-two-fifths-touch
isTwoFifthsTouch :: ClassName
isTwoFifthsTouch = ClassName "is-two-fifths-touch"

-- | A ClassName for is-two-fifths-widescreen
isTwoFifthsWidescreen :: ClassName
isTwoFifthsWidescreen = ClassName "is-two-fifths-widescreen"

-- | A ClassName for is-two-thirds
isTwoThirds :: ClassName
isTwoThirds = ClassName "is-two-thirds"

-- | A ClassName for is-two-thirds-desktop
isTwoThirdsDesktop :: ClassName
isTwoThirdsDesktop = ClassName "is-two-thirds-desktop"

-- | A ClassName for is-two-thirds-fullhd
isTwoThirdsFullhd :: ClassName
isTwoThirdsFullhd = ClassName "is-two-thirds-fullhd"

-- | A ClassName for is-two-thirds-mobile
isTwoThirdsMobile :: ClassName
isTwoThirdsMobile = ClassName "is-two-thirds-mobile"

-- | A ClassName for is-two-thirds-tablet
isTwoThirdsTablet :: ClassName
isTwoThirdsTablet = ClassName "is-two-thirds-tablet"

-- | A ClassName for is-two-thirds-touch
isTwoThirdsTouch :: ClassName
isTwoThirdsTouch = ClassName "is-two-thirds-touch"

-- | A ClassName for is-two-thirds-widescreen
isTwoThirdsWidescreen :: ClassName
isTwoThirdsWidescreen = ClassName "is-two-thirds-widescreen"

-- | A ClassName for is-unselectable
isUnselectable :: ClassName
isUnselectable = ClassName "is-unselectable"

-- | A ClassName for is-up
isUp :: ClassName
isUp = ClassName "is-up"

-- | A ClassName for is-uppercase
isUppercase :: ClassName
isUppercase = ClassName "is-uppercase"

-- | A ClassName for is-variable
isVariable :: ClassName
isVariable = ClassName "is-variable"

-- | A ClassName for is-vcentered
isVcentered :: ClassName
isVcentered = ClassName "is-vcentered"

-- | A ClassName for is-vertical
isVertical :: ClassName
isVertical = ClassName "is-vertical"

-- | A ClassName for is-warning
isWarning :: ClassName
isWarning = ClassName "is-warning"

-- | A ClassName for is-white
isWhite :: ClassName
isWhite = ClassName "is-white"

-- | A ClassName for is-widescreen
isWidescreen :: ClassName
isWidescreen = ClassName "is-widescreen"

-- | A ClassName for is-wrapped
isWrapped :: ClassName
isWrapped = ClassName "is-wrapped"

-- | A ClassName for label
label :: ClassName
label = ClassName "label"

-- | A ClassName for level
level :: ClassName
level = ClassName "level"

-- | A ClassName for level-item
levelItem :: ClassName
levelItem = ClassName "level-item"

-- | A ClassName for level-left
levelLeft :: ClassName
levelLeft = ClassName "level-left"

-- | A ClassName for level-right
levelRight :: ClassName
levelRight = ClassName "level-right"

-- | A ClassName for loader
loader :: ClassName
loader = ClassName "loader"

-- | A ClassName for media
media :: ClassName
media = ClassName "media"

-- | A ClassName for media-content
mediaContent :: ClassName
mediaContent = ClassName "media-content"

-- | A ClassName for media-left
mediaLeft :: ClassName
mediaLeft = ClassName "media-left"

-- | A ClassName for media-right
mediaRight :: ClassName
mediaRight = ClassName "media-right"

-- | A ClassName for menu
menu :: ClassName
menu = ClassName "menu"

-- | A ClassName for menu-label
menuLabel :: ClassName
menuLabel = ClassName "menu-label"

-- | A ClassName for menu-list
menuList :: ClassName
menuList = ClassName "menu-list"

-- | A ClassName for message
message :: ClassName
message = ClassName "message"

-- | A ClassName for message-body
messageBody :: ClassName
messageBody = ClassName "message-body"

-- | A ClassName for message-header
messageHeader :: ClassName
messageHeader = ClassName "message-header"

-- | A ClassName for modal
modal :: ClassName
modal = ClassName "modal"

-- | A ClassName for modal-background
modalBackground :: ClassName
modalBackground = ClassName "modal-background"

-- | A ClassName for modal-card
modalCard :: ClassName
modalCard = ClassName "modal-card"

-- | A ClassName for modal-card-body
modalCardBody :: ClassName
modalCardBody = ClassName "modal-card-body"

-- | A ClassName for modal-card-foot
modalCardFoot :: ClassName
modalCardFoot = ClassName "modal-card-foot"

-- | A ClassName for modal-card-head
modalCardHead :: ClassName
modalCardHead = ClassName "modal-card-head"

-- | A ClassName for modal-card-title
modalCardTitle :: ClassName
modalCardTitle = ClassName "modal-card-title"

-- | A ClassName for modal-close
modalClose :: ClassName
modalClose = ClassName "modal-close"

-- | A ClassName for modal-content
modalContent :: ClassName
modalContent = ClassName "modal-content"

-- | A ClassName for navbar
navbar :: ClassName
navbar = ClassName "navbar"

-- | A ClassName for navbar-brand
navbarBrand :: ClassName
navbarBrand = ClassName "navbar-brand"

-- | A ClassName for navbar-burger
navbarBurger :: ClassName
navbarBurger = ClassName "navbar-burger"

-- | A ClassName for navbar-content
navbarContent :: ClassName
navbarContent = ClassName "navbar-content"

-- | A ClassName for navbar-divider
navbarDivider :: ClassName
navbarDivider = ClassName "navbar-divider"

-- | A ClassName for navbar-dropdown
navbarDropdown :: ClassName
navbarDropdown = ClassName "navbar-dropdown"

-- | A ClassName for navbar-end
navbarEnd :: ClassName
navbarEnd = ClassName "navbar-end"

-- | A ClassName for navbar-item
navbarItem :: ClassName
navbarItem = ClassName "navbar-item"

-- | A ClassName for navbar-link
navbarLink :: ClassName
navbarLink = ClassName "navbar-link"

-- | A ClassName for navbar-menu
navbarMenu :: ClassName
navbarMenu = ClassName "navbar-menu"

-- | A ClassName for navbar-start
navbarStart :: ClassName
navbarStart = ClassName "navbar-start"

-- | A ClassName for navbar-tabs
navbarTabs :: ClassName
navbarTabs = ClassName "navbar-tabs"

-- | A ClassName for notification
notification :: ClassName
notification = ClassName "notification"

-- | A ClassName for number
number :: ClassName
number = ClassName "number"

-- | A ClassName for pagination
pagination :: ClassName
pagination = ClassName "pagination"

-- | A ClassName for pagination-ellipsis
paginationEllipsis :: ClassName
paginationEllipsis = ClassName "pagination-ellipsis"

-- | A ClassName for pagination-link
paginationLink :: ClassName
paginationLink = ClassName "pagination-link"

-- | A ClassName for pagination-list
paginationList :: ClassName
paginationList = ClassName "pagination-list"

-- | A ClassName for pagination-next
paginationNext :: ClassName
paginationNext = ClassName "pagination-next"

-- | A ClassName for pagination-previous
paginationPrevious :: ClassName
paginationPrevious = ClassName "pagination-previous"

-- | A ClassName for panel
panel :: ClassName
panel = ClassName "panel"

-- | A ClassName for panel-block
panelBlock :: ClassName
panelBlock = ClassName "panel-block"

-- | A ClassName for panel-heading
panelHeading :: ClassName
panelHeading = ClassName "panel-heading"

-- | A ClassName for panel-icon
panelIcon :: ClassName
panelIcon = ClassName "panel-icon"

-- | A ClassName for panel-list
panelList :: ClassName
panelList = ClassName "panel-list"

-- | A ClassName for panel-tabs
panelTabs :: ClassName
panelTabs = ClassName "panel-tabs"

-- | A ClassName for progress
progress :: ClassName
progress = ClassName "progress"

-- | A ClassName for radio
radio :: ClassName
radio = ClassName "radio"

-- | A ClassName for section
section :: ClassName
section = ClassName "section"

-- | A ClassName for select
select :: ClassName
select = ClassName "select"

-- | A ClassName for subtitle
subtitle :: ClassName
subtitle = ClassName "subtitle"

-- | A ClassName for table
table :: ClassName
table = ClassName "table"

-- | A ClassName for table-container
tableContainer :: ClassName
tableContainer = ClassName "table-container"

-- | A ClassName for tabs
tabs :: ClassName
tabs = ClassName "tabs"

-- | A ClassName for tag
tag :: ClassName
tag = ClassName "tag"

-- | A ClassName for tags
tags :: ClassName
tags = ClassName "tags"

-- | A ClassName for textarea
textarea :: ClassName
textarea = ClassName "textarea"

-- | A ClassName for tile
tile :: ClassName
tile = ClassName "tile"

-- | A ClassName for title
title :: ClassName
title = ClassName "title"

