{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Theme.Raw.Foundation
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= Foundation

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Theme.Raw.Foundation where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for accordion
fouAccordion :: ClassName
fouAccordion = ClassName "accordion"

-- | A ClassName for accordion-content
fouAccordionContent :: ClassName
fouAccordionContent = ClassName "accordion-content"

-- | A ClassName for accordion-item
fouAccordionItem :: ClassName
fouAccordionItem = ClassName "accordion-item"

-- | A ClassName for accordion-menu
fouAccordionMenu :: ClassName
fouAccordionMenu = ClassName "accordion-menu"

-- | A ClassName for accordion-title
fouAccordionTitle :: ClassName
fouAccordionTitle = ClassName "accordion-title"

-- | A ClassName for active
fouActive :: ClassName
fouActive = ClassName "active"

-- | A ClassName for alert
fouAlert :: ClassName
fouAlert = ClassName "alert"

-- | A ClassName for align-bottom
fouAlignBottom :: ClassName
fouAlignBottom = ClassName "align-bottom"

-- | A ClassName for align-center
fouAlignCenter :: ClassName
fouAlignCenter = ClassName "align-center"

-- | A ClassName for align-center-middle
fouAlignCenterMiddle :: ClassName
fouAlignCenterMiddle = ClassName "align-center-middle"

-- | A ClassName for align-justify
fouAlignJustify :: ClassName
fouAlignJustify = ClassName "align-justify"

-- | A ClassName for align-left
fouAlignLeft :: ClassName
fouAlignLeft = ClassName "align-left"

-- | A ClassName for align-middle
fouAlignMiddle :: ClassName
fouAlignMiddle = ClassName "align-middle"

-- | A ClassName for align-right
fouAlignRight :: ClassName
fouAlignRight = ClassName "align-right"

-- | A ClassName for align-self-bottom
fouAlignSelfBottom :: ClassName
fouAlignSelfBottom = ClassName "align-self-bottom"

-- | A ClassName for align-self-middle
fouAlignSelfMiddle :: ClassName
fouAlignSelfMiddle = ClassName "align-self-middle"

-- | A ClassName for align-self-stretch
fouAlignSelfStretch :: ClassName
fouAlignSelfStretch = ClassName "align-self-stretch"

-- | A ClassName for align-self-top
fouAlignSelfTop :: ClassName
fouAlignSelfTop = ClassName "align-self-top"

-- | A ClassName for align-spaced
fouAlignSpaced :: ClassName
fouAlignSpaced = ClassName "align-spaced"

-- | A ClassName for align-stretch
fouAlignStretch :: ClassName
fouAlignStretch = ClassName "align-stretch"

-- | A ClassName for align-top
fouAlignTop :: ClassName
fouAlignTop = ClassName "align-top"

-- | A ClassName for animate-height
fouAnimateHeight :: ClassName
fouAnimateHeight = ClassName "animate-height"

-- | A ClassName for arrow-only
fouArrowOnly :: ClassName
fouArrowOnly = ClassName "arrow-only"

-- | A ClassName for auto
fouAuto :: ClassName
fouAuto = ClassName "auto"

-- | A ClassName for badge
fouBadge :: ClassName
fouBadge = ClassName "badge"

-- | A ClassName for bottom
fouBottom :: ClassName
fouBottom = ClassName "bottom"

-- | A ClassName for bounce-in
fouBounceIn :: ClassName
fouBounceIn = ClassName "bounce-in"

-- | A ClassName for bounce-in-out
fouBounceInOut :: ClassName
fouBounceInOut = ClassName "bounce-in-out"

-- | A ClassName for bounce-out
fouBounceOut :: ClassName
fouBounceOut = ClassName "bounce-out"

-- | A ClassName for breadcrumbs
fouBreadcrumbs :: ClassName
fouBreadcrumbs = ClassName "breadcrumbs"

-- | A ClassName for button
fouButton :: ClassName
fouButton = ClassName "button"

-- | A ClassName for button-group
fouButtonGroup :: ClassName
fouButtonGroup = ClassName "button-group"

-- | A ClassName for callout
fouCallout :: ClassName
fouCallout = ClassName "callout"

-- | A ClassName for card
fouCard :: ClassName
fouCard = ClassName "card"

-- | A ClassName for card-divider
fouCardDivider :: ClassName
fouCardDivider = ClassName "card-divider"

-- | A ClassName for card-image
fouCardImage :: ClassName
fouCardImage = ClassName "card-image"

-- | A ClassName for card-section
fouCardSection :: ClassName
fouCardSection = ClassName "card-section"

-- | A ClassName for cell
fouCell :: ClassName
fouCell = ClassName "cell"

-- | A ClassName for cell-block
fouCellBlock :: ClassName
fouCellBlock = ClassName "cell-block"

-- | A ClassName for cell-block-container
fouCellBlockContainer :: ClassName
fouCellBlockContainer = ClassName "cell-block-container"

-- | A ClassName for cell-block-y
fouCellBlockY :: ClassName
fouCellBlockY = ClassName "cell-block-y"

-- | A ClassName for clear
fouClear :: ClassName
fouClear = ClassName "clear"

-- | A ClassName for clearfix
fouClearfix :: ClassName
fouClearfix = ClassName "clearfix"

-- | A ClassName for close-button
fouCloseButton :: ClassName
fouCloseButton = ClassName "close-button"

-- | A ClassName for collapse
fouCollapse :: ClassName
fouCollapse = ClassName "collapse"

-- | A ClassName for column
fouColumn :: ClassName
fouColumn = ClassName "column"

-- | A ClassName for current
fouCurrent :: ClassName
fouCurrent = ClassName "current"

-- | A ClassName for dark
fouDark :: ClassName
fouDark = ClassName "dark"

-- | A ClassName for disabled
fouDisabled :: ClassName
fouDisabled = ClassName "disabled"

-- | A ClassName for drilldown
fouDrilldown :: ClassName
fouDrilldown = ClassName "drilldown"

-- | A ClassName for drilldown-submenu-cover-previous
fouDrilldownSubmenuCoverPrevious :: ClassName
fouDrilldownSubmenuCoverPrevious = ClassName "drilldown-submenu-cover-previous"

-- | A ClassName for dropdown
fouDropdown :: ClassName
fouDropdown = ClassName "dropdown"

-- | A ClassName for dropdown-pane
fouDropdownPane :: ClassName
fouDropdownPane = ClassName "dropdown-pane"

-- | A ClassName for ease
fouEase :: ClassName
fouEase = ClassName "ease"

-- | A ClassName for ease-in
fouEaseIn :: ClassName
fouEaseIn = ClassName "ease-in"

-- | A ClassName for ease-in-out
fouEaseInOut :: ClassName
fouEaseInOut = ClassName "ease-in-out"

-- | A ClassName for ease-out
fouEaseOut :: ClassName
fouEaseOut = ClassName "ease-out"

-- | A ClassName for ellipsis
fouEllipsis :: ClassName
fouEllipsis = ClassName "ellipsis"

-- | A ClassName for expanded
fouExpanded :: ClassName
fouExpanded = ClassName "expanded"

-- | A ClassName for fade-in
fouFadeIn :: ClassName
fouFadeIn = ClassName "fade-in"

-- | A ClassName for fade-out
fouFadeOut :: ClassName
fouFadeOut = ClassName "fade-out"

-- | A ClassName for fast
fouFast :: ClassName
fouFast = ClassName "fast"

-- | A ClassName for fieldset
fouFieldset :: ClassName
fouFieldset = ClassName "fieldset"

-- | A ClassName for first-sub
fouFirstSub :: ClassName
fouFirstSub = ClassName "first-sub"

-- | A ClassName for flex-child-auto
fouFlexChildAuto :: ClassName
fouFlexChildAuto = ClassName "flex-child-auto"

-- | A ClassName for flex-child-grow
fouFlexChildGrow :: ClassName
fouFlexChildGrow = ClassName "flex-child-grow"

-- | A ClassName for flex-child-shrink
fouFlexChildShrink :: ClassName
fouFlexChildShrink = ClassName "flex-child-shrink"

-- | A ClassName for flex-container
fouFlexContainer :: ClassName
fouFlexContainer = ClassName "flex-container"

-- | A ClassName for flex-dir-column
fouFlexDirColumn :: ClassName
fouFlexDirColumn = ClassName "flex-dir-column"

-- | A ClassName for flex-dir-column-reverse
fouFlexDirColumnReverse :: ClassName
fouFlexDirColumnReverse = ClassName "flex-dir-column-reverse"

-- | A ClassName for flex-dir-row
fouFlexDirRow :: ClassName
fouFlexDirRow = ClassName "flex-dir-row"

-- | A ClassName for flex-dir-row-reverse
fouFlexDirRowReverse :: ClassName
fouFlexDirRowReverse = ClassName "flex-dir-row-reverse"

-- | A ClassName for flex-video
fouFlexVideo :: ClassName
fouFlexVideo = ClassName "flex-video"

-- | A ClassName for float-center
fouFloatCenter :: ClassName
fouFloatCenter = ClassName "float-center"

-- | A ClassName for float-left
fouFloatLeft :: ClassName
fouFloatLeft = ClassName "float-left"

-- | A ClassName for float-right
fouFloatRight :: ClassName
fouFloatRight = ClassName "float-right"

-- | A ClassName for fluid
fouFluid :: ClassName
fouFluid = ClassName "fluid"

-- | A ClassName for form-error
fouFormError :: ClassName
fouFormError = ClassName "form-error"

-- | A ClassName for foundation-mq
fouFoundationMq :: ClassName
fouFoundationMq = ClassName "foundation-mq"

-- | A ClassName for full
fouFull :: ClassName
fouFull = ClassName "full"

-- | A ClassName for grid-container
fouGridContainer :: ClassName
fouGridContainer = ClassName "grid-container"

-- | A ClassName for grid-frame
fouGridFrame :: ClassName
fouGridFrame = ClassName "grid-frame"

-- | A ClassName for grid-margin-x
fouGridMarginX :: ClassName
fouGridMarginX = ClassName "grid-margin-x"

-- | A ClassName for grid-margin-y
fouGridMarginY :: ClassName
fouGridMarginY = ClassName "grid-margin-y"

-- | A ClassName for grid-padding-x
fouGridPaddingX :: ClassName
fouGridPaddingX = ClassName "grid-padding-x"

-- | A ClassName for grid-padding-y
fouGridPaddingY :: ClassName
fouGridPaddingY = ClassName "grid-padding-y"

-- | A ClassName for grid-x
fouGridX :: ClassName
fouGridX = ClassName "grid-x"

-- | A ClassName for grid-y
fouGridY :: ClassName
fouGridY = ClassName "grid-y"

-- | A ClassName for h1
fouH1 :: ClassName
fouH1 = ClassName "h1"

-- | A ClassName for h2
fouH2 :: ClassName
fouH2 = ClassName "h2"

-- | A ClassName for h3
fouH3 :: ClassName
fouH3 = ClassName "h3"

-- | A ClassName for h4
fouH4 :: ClassName
fouH4 = ClassName "h4"

-- | A ClassName for h5
fouH5 :: ClassName
fouH5 = ClassName "h5"

-- | A ClassName for h6
fouH6 :: ClassName
fouH6 = ClassName "h6"

-- | A ClassName for has-reveal-bottom
fouHasRevealBottom :: ClassName
fouHasRevealBottom = ClassName "has-reveal-bottom"

-- | A ClassName for has-reveal-left
fouHasRevealLeft :: ClassName
fouHasRevealLeft = ClassName "has-reveal-left"

-- | A ClassName for has-reveal-right
fouHasRevealRight :: ClassName
fouHasRevealRight = ClassName "has-reveal-right"

-- | A ClassName for has-reveal-top
fouHasRevealTop :: ClassName
fouHasRevealTop = ClassName "has-reveal-top"

-- | A ClassName for has-submenu-toggle
fouHasSubmenuToggle :: ClassName
fouHasSubmenuToggle = ClassName "has-submenu-toggle"

-- | A ClassName for has-tip
fouHasTip :: ClassName
fouHasTip = ClassName "has-tip"

-- | A ClassName for has-transition-push
fouHasTransitionPush :: ClassName
fouHasTransitionPush = ClassName "has-transition-push"

-- | A ClassName for help-text
fouHelpText :: ClassName
fouHelpText = ClassName "help-text"

-- | A ClassName for hide
fouHide :: ClassName
fouHide = ClassName "hide"

-- | A ClassName for hide-for-landscape
fouHideForLandscape :: ClassName
fouHideForLandscape = ClassName "hide-for-landscape"

-- | A ClassName for hide-for-large
fouHideForLarge :: ClassName
fouHideForLarge = ClassName "hide-for-large"

-- | A ClassName for hide-for-large-only
fouHideForLargeOnly :: ClassName
fouHideForLargeOnly = ClassName "hide-for-large-only"

-- | A ClassName for hide-for-medium
fouHideForMedium :: ClassName
fouHideForMedium = ClassName "hide-for-medium"

-- | A ClassName for hide-for-medium-only
fouHideForMediumOnly :: ClassName
fouHideForMediumOnly = ClassName "hide-for-medium-only"

-- | A ClassName for hide-for-portrait
fouHideForPortrait :: ClassName
fouHideForPortrait = ClassName "hide-for-portrait"

-- | A ClassName for hide-for-print
fouHideForPrint :: ClassName
fouHideForPrint = ClassName "hide-for-print"

-- | A ClassName for hide-for-small-only
fouHideForSmallOnly :: ClassName
fouHideForSmallOnly = ClassName "hide-for-small-only"

-- | A ClassName for hinge-in-from-bottom
fouHingeInFromBottom :: ClassName
fouHingeInFromBottom = ClassName "hinge-in-from-bottom"

-- | A ClassName for hinge-in-from-left
fouHingeInFromLeft :: ClassName
fouHingeInFromLeft = ClassName "hinge-in-from-left"

-- | A ClassName for hinge-in-from-middle-x
fouHingeInFromMiddleX :: ClassName
fouHingeInFromMiddleX = ClassName "hinge-in-from-middle-x"

-- | A ClassName for hinge-in-from-middle-y
fouHingeInFromMiddleY :: ClassName
fouHingeInFromMiddleY = ClassName "hinge-in-from-middle-y"

-- | A ClassName for hinge-in-from-right
fouHingeInFromRight :: ClassName
fouHingeInFromRight = ClassName "hinge-in-from-right"

-- | A ClassName for hinge-in-from-top
fouHingeInFromTop :: ClassName
fouHingeInFromTop = ClassName "hinge-in-from-top"

-- | A ClassName for hinge-out-from-bottom
fouHingeOutFromBottom :: ClassName
fouHingeOutFromBottom = ClassName "hinge-out-from-bottom"

-- | A ClassName for hinge-out-from-left
fouHingeOutFromLeft :: ClassName
fouHingeOutFromLeft = ClassName "hinge-out-from-left"

-- | A ClassName for hinge-out-from-middle-x
fouHingeOutFromMiddleX :: ClassName
fouHingeOutFromMiddleX = ClassName "hinge-out-from-middle-x"

-- | A ClassName for hinge-out-from-middle-y
fouHingeOutFromMiddleY :: ClassName
fouHingeOutFromMiddleY = ClassName "hinge-out-from-middle-y"

-- | A ClassName for hinge-out-from-right
fouHingeOutFromRight :: ClassName
fouHingeOutFromRight = ClassName "hinge-out-from-right"

-- | A ClassName for hinge-out-from-top
fouHingeOutFromTop :: ClassName
fouHingeOutFromTop = ClassName "hinge-out-from-top"

-- | A ClassName for hollow
fouHollow :: ClassName
fouHollow = ClassName "hollow"

-- | A ClassName for horizontal
fouHorizontal :: ClassName
fouHorizontal = ClassName "horizontal"

-- | A ClassName for hover
fouHover :: ClassName
fouHover = ClassName "hover"

-- | A ClassName for icon-bottom
fouIconBottom :: ClassName
fouIconBottom = ClassName "icon-bottom"

-- | A ClassName for icon-left
fouIconLeft :: ClassName
fouIconLeft = ClassName "icon-left"

-- | A ClassName for icon-right
fouIconRight :: ClassName
fouIconRight = ClassName "icon-right"

-- | A ClassName for icon-top
fouIconTop :: ClassName
fouIconTop = ClassName "icon-top"

-- | A ClassName for icons
fouIcons :: ClassName
fouIcons = ClassName "icons"

-- | A ClassName for in-canvas-for-large
fouInCanvasForLarge :: ClassName
fouInCanvasForLarge = ClassName "in-canvas-for-large"

-- | A ClassName for in-canvas-for-medium
fouInCanvasForMedium :: ClassName
fouInCanvasForMedium = ClassName "in-canvas-for-medium"

-- | A ClassName for infinite
fouInfinite :: ClassName
fouInfinite = ClassName "infinite"

-- | A ClassName for input-group
fouInputGroup :: ClassName
fouInputGroup = ClassName "input-group"

-- | A ClassName for input-group-button
fouInputGroupButton :: ClassName
fouInputGroupButton = ClassName "input-group-button"

-- | A ClassName for input-group-field
fouInputGroupField :: ClassName
fouInputGroupField = ClassName "input-group-field"

-- | A ClassName for input-group-label
fouInputGroupLabel :: ClassName
fouInputGroupLabel = ClassName "input-group-label"

-- | A ClassName for invisible
fouInvisible :: ClassName
fouInvisible = ClassName "invisible"

-- | A ClassName for ir
fouIr :: ClassName
fouIr = ClassName "ir"

-- | A ClassName for is-accordion-submenu
fouIsAccordionSubmenu :: ClassName
fouIsAccordionSubmenu = ClassName "is-accordion-submenu"

-- | A ClassName for is-accordion-submenu-parent
fouIsAccordionSubmenuParent :: ClassName
fouIsAccordionSubmenuParent = ClassName "is-accordion-submenu-parent"

-- | A ClassName for is-active
fouIsActive :: ClassName
fouIsActive = ClassName "is-active"

-- | A ClassName for is-anchored
fouIsAnchored :: ClassName
fouIsAnchored = ClassName "is-anchored"

-- | A ClassName for is-at-bottom
fouIsAtBottom :: ClassName
fouIsAtBottom = ClassName "is-at-bottom"

-- | A ClassName for is-at-top
fouIsAtTop :: ClassName
fouIsAtTop = ClassName "is-at-top"

-- | A ClassName for is-closable
fouIsClosable :: ClassName
fouIsClosable = ClassName "is-closable"

-- | A ClassName for is-closed
fouIsClosed :: ClassName
fouIsClosed = ClassName "is-closed"

-- | A ClassName for is-closing
fouIsClosing :: ClassName
fouIsClosing = ClassName "is-closing"

-- | A ClassName for is-dragging
fouIsDragging :: ClassName
fouIsDragging = ClassName "is-dragging"

-- | A ClassName for is-drilldown
fouIsDrilldown :: ClassName
fouIsDrilldown = ClassName "is-drilldown"

-- | A ClassName for is-drilldown-submenu
fouIsDrilldownSubmenu :: ClassName
fouIsDrilldownSubmenu = ClassName "is-drilldown-submenu"

-- | A ClassName for is-drilldown-submenu-parent
fouIsDrilldownSubmenuParent :: ClassName
fouIsDrilldownSubmenuParent = ClassName "is-drilldown-submenu-parent"

-- | A ClassName for is-dropdown-menu
fouIsDropdownMenu :: ClassName
fouIsDropdownMenu = ClassName "is-dropdown-menu"

-- | A ClassName for is-dropdown-submenu
fouIsDropdownSubmenu :: ClassName
fouIsDropdownSubmenu = ClassName "is-dropdown-submenu"

-- | A ClassName for is-dropdown-submenu-parent
fouIsDropdownSubmenuParent :: ClassName
fouIsDropdownSubmenuParent = ClassName "is-dropdown-submenu-parent"

-- | A ClassName for is-hidden
fouIsHidden :: ClassName
fouIsHidden = ClassName "is-hidden"

-- | A ClassName for is-invalid-input
fouIsInvalidInput :: ClassName
fouIsInvalidInput = ClassName "is-invalid-input"

-- | A ClassName for is-invalid-label
fouIsInvalidLabel :: ClassName
fouIsInvalidLabel = ClassName "is-invalid-label"

-- | A ClassName for is-off-canvas-open
fouIsOffCanvasOpen :: ClassName
fouIsOffCanvasOpen = ClassName "is-off-canvas-open"

-- | A ClassName for is-open
fouIsOpen :: ClassName
fouIsOpen = ClassName "is-open"

-- | A ClassName for is-open-bottom
fouIsOpenBottom :: ClassName
fouIsOpenBottom = ClassName "is-open-bottom"

-- | A ClassName for is-open-left
fouIsOpenLeft :: ClassName
fouIsOpenLeft = ClassName "is-open-left"

-- | A ClassName for is-open-right
fouIsOpenRight :: ClassName
fouIsOpenRight = ClassName "is-open-right"

-- | A ClassName for is-open-top
fouIsOpenTop :: ClassName
fouIsOpenTop = ClassName "is-open-top"

-- | A ClassName for is-opening
fouIsOpening :: ClassName
fouIsOpening = ClassName "is-opening"

-- | A ClassName for is-overlay-absolute
fouIsOverlayAbsolute :: ClassName
fouIsOverlayAbsolute = ClassName "is-overlay-absolute"

-- | A ClassName for is-overlay-fixed
fouIsOverlayFixed :: ClassName
fouIsOverlayFixed = ClassName "is-overlay-fixed"

-- | A ClassName for is-reveal-open
fouIsRevealOpen :: ClassName
fouIsRevealOpen = ClassName "is-reveal-open"

-- | A ClassName for is-stuck
fouIsStuck :: ClassName
fouIsStuck = ClassName "is-stuck"

-- | A ClassName for is-transition-overlap
fouIsTransitionOverlap :: ClassName
fouIsTransitionOverlap = ClassName "is-transition-overlap"

-- | A ClassName for is-transition-push
fouIsTransitionPush :: ClassName
fouIsTransitionPush = ClassName "is-transition-push"

-- | A ClassName for is-visible
fouIsVisible :: ClassName
fouIsVisible = ClassName "is-visible"

-- | A ClassName for js-drilldown-back
fouJsDrilldownBack :: ClassName
fouJsDrilldownBack = ClassName "js-drilldown-back"

-- | A ClassName for js-dropdown-active
fouJsDropdownActive :: ClassName
fouJsDropdownActive = ClassName "js-dropdown-active"

-- | A ClassName for js-off-canvas-overlay
fouJsOffCanvasOverlay :: ClassName
fouJsOffCanvasOverlay = ClassName "js-off-canvas-overlay"

-- | A ClassName for label
fouLabel :: ClassName
fouLabel = ClassName "label"

-- | A ClassName for large
fouLarge :: ClassName
fouLarge = ClassName "large"

-- | A ClassName for large-1
fouLarge1 :: ClassName
fouLarge1 = ClassName "large-1"

-- | A ClassName for large-10
fouLarge10 :: ClassName
fouLarge10 = ClassName "large-10"

-- | A ClassName for large-11
fouLarge11 :: ClassName
fouLarge11 = ClassName "large-11"

-- | A ClassName for large-12
fouLarge12 :: ClassName
fouLarge12 = ClassName "large-12"

-- | A ClassName for large-2
fouLarge2 :: ClassName
fouLarge2 = ClassName "large-2"

-- | A ClassName for large-3
fouLarge3 :: ClassName
fouLarge3 = ClassName "large-3"

-- | A ClassName for large-4
fouLarge4 :: ClassName
fouLarge4 = ClassName "large-4"

-- | A ClassName for large-5
fouLarge5 :: ClassName
fouLarge5 = ClassName "large-5"

-- | A ClassName for large-6
fouLarge6 :: ClassName
fouLarge6 = ClassName "large-6"

-- | A ClassName for large-7
fouLarge7 :: ClassName
fouLarge7 = ClassName "large-7"

-- | A ClassName for large-8
fouLarge8 :: ClassName
fouLarge8 = ClassName "large-8"

-- | A ClassName for large-9
fouLarge9 :: ClassName
fouLarge9 = ClassName "large-9"

-- | A ClassName for large-auto
fouLargeAuto :: ClassName
fouLargeAuto = ClassName "large-auto"

-- | A ClassName for large-cell-block
fouLargeCellBlock :: ClassName
fouLargeCellBlock = ClassName "large-cell-block"

-- | A ClassName for large-cell-block-container
fouLargeCellBlockContainer :: ClassName
fouLargeCellBlockContainer = ClassName "large-cell-block-container"

-- | A ClassName for large-cell-block-y
fouLargeCellBlockY :: ClassName
fouLargeCellBlockY = ClassName "large-cell-block-y"

-- | A ClassName for large-expanded
fouLargeExpanded :: ClassName
fouLargeExpanded = ClassName "large-expanded"

-- | A ClassName for large-flex-child-auto
fouLargeFlexChildAuto :: ClassName
fouLargeFlexChildAuto = ClassName "large-flex-child-auto"

-- | A ClassName for large-flex-child-grow
fouLargeFlexChildGrow :: ClassName
fouLargeFlexChildGrow = ClassName "large-flex-child-grow"

-- | A ClassName for large-flex-child-shrink
fouLargeFlexChildShrink :: ClassName
fouLargeFlexChildShrink = ClassName "large-flex-child-shrink"

-- | A ClassName for large-flex-container
fouLargeFlexContainer :: ClassName
fouLargeFlexContainer = ClassName "large-flex-container"

-- | A ClassName for large-flex-dir-column
fouLargeFlexDirColumn :: ClassName
fouLargeFlexDirColumn = ClassName "large-flex-dir-column"

-- | A ClassName for large-flex-dir-column-reverse
fouLargeFlexDirColumnReverse :: ClassName
fouLargeFlexDirColumnReverse = ClassName "large-flex-dir-column-reverse"

-- | A ClassName for large-flex-dir-row
fouLargeFlexDirRow :: ClassName
fouLargeFlexDirRow = ClassName "large-flex-dir-row"

-- | A ClassName for large-flex-dir-row-reverse
fouLargeFlexDirRowReverse :: ClassName
fouLargeFlexDirRowReverse = ClassName "large-flex-dir-row-reverse"

-- | A ClassName for large-full
fouLargeFull :: ClassName
fouLargeFull = ClassName "large-full"

-- | A ClassName for large-grid-frame
fouLargeGridFrame :: ClassName
fouLargeGridFrame = ClassName "large-grid-frame"

-- | A ClassName for large-horizontal
fouLargeHorizontal :: ClassName
fouLargeHorizontal = ClassName "large-horizontal"

-- | A ClassName for large-margin-collapse
fouLargeMarginCollapse :: ClassName
fouLargeMarginCollapse = ClassName "large-margin-collapse"

-- | A ClassName for large-offset-0
fouLargeOffset0 :: ClassName
fouLargeOffset0 = ClassName "large-offset-0"

-- | A ClassName for large-offset-1
fouLargeOffset1 :: ClassName
fouLargeOffset1 = ClassName "large-offset-1"

-- | A ClassName for large-offset-10
fouLargeOffset10 :: ClassName
fouLargeOffset10 = ClassName "large-offset-10"

-- | A ClassName for large-offset-11
fouLargeOffset11 :: ClassName
fouLargeOffset11 = ClassName "large-offset-11"

-- | A ClassName for large-offset-2
fouLargeOffset2 :: ClassName
fouLargeOffset2 = ClassName "large-offset-2"

-- | A ClassName for large-offset-3
fouLargeOffset3 :: ClassName
fouLargeOffset3 = ClassName "large-offset-3"

-- | A ClassName for large-offset-4
fouLargeOffset4 :: ClassName
fouLargeOffset4 = ClassName "large-offset-4"

-- | A ClassName for large-offset-5
fouLargeOffset5 :: ClassName
fouLargeOffset5 = ClassName "large-offset-5"

-- | A ClassName for large-offset-6
fouLargeOffset6 :: ClassName
fouLargeOffset6 = ClassName "large-offset-6"

-- | A ClassName for large-offset-7
fouLargeOffset7 :: ClassName
fouLargeOffset7 = ClassName "large-offset-7"

-- | A ClassName for large-offset-8
fouLargeOffset8 :: ClassName
fouLargeOffset8 = ClassName "large-offset-8"

-- | A ClassName for large-offset-9
fouLargeOffset9 :: ClassName
fouLargeOffset9 = ClassName "large-offset-9"

-- | A ClassName for large-order-1
fouLargeOrder1 :: ClassName
fouLargeOrder1 = ClassName "large-order-1"

-- | A ClassName for large-order-2
fouLargeOrder2 :: ClassName
fouLargeOrder2 = ClassName "large-order-2"

-- | A ClassName for large-order-3
fouLargeOrder3 :: ClassName
fouLargeOrder3 = ClassName "large-order-3"

-- | A ClassName for large-order-4
fouLargeOrder4 :: ClassName
fouLargeOrder4 = ClassName "large-order-4"

-- | A ClassName for large-order-5
fouLargeOrder5 :: ClassName
fouLargeOrder5 = ClassName "large-order-5"

-- | A ClassName for large-order-6
fouLargeOrder6 :: ClassName
fouLargeOrder6 = ClassName "large-order-6"

-- | A ClassName for large-padding-collapse
fouLargePaddingCollapse :: ClassName
fouLargePaddingCollapse = ClassName "large-padding-collapse"

-- | A ClassName for large-shrink
fouLargeShrink :: ClassName
fouLargeShrink = ClassName "large-shrink"

-- | A ClassName for large-simple
fouLargeSimple :: ClassName
fouLargeSimple = ClassName "large-simple"

-- | A ClassName for large-text-center
fouLargeTextCenter :: ClassName
fouLargeTextCenter = ClassName "large-text-center"

-- | A ClassName for large-text-justify
fouLargeTextJustify :: ClassName
fouLargeTextJustify = ClassName "large-text-justify"

-- | A ClassName for large-text-left
fouLargeTextLeft :: ClassName
fouLargeTextLeft = ClassName "large-text-left"

-- | A ClassName for large-text-right
fouLargeTextRight :: ClassName
fouLargeTextRight = ClassName "large-text-right"

-- | A ClassName for large-up-1
fouLargeUp1 :: ClassName
fouLargeUp1 = ClassName "large-up-1"

-- | A ClassName for large-up-2
fouLargeUp2 :: ClassName
fouLargeUp2 = ClassName "large-up-2"

-- | A ClassName for large-up-3
fouLargeUp3 :: ClassName
fouLargeUp3 = ClassName "large-up-3"

-- | A ClassName for large-up-4
fouLargeUp4 :: ClassName
fouLargeUp4 = ClassName "large-up-4"

-- | A ClassName for large-up-5
fouLargeUp5 :: ClassName
fouLargeUp5 = ClassName "large-up-5"

-- | A ClassName for large-up-6
fouLargeUp6 :: ClassName
fouLargeUp6 = ClassName "large-up-6"

-- | A ClassName for large-up-7
fouLargeUp7 :: ClassName
fouLargeUp7 = ClassName "large-up-7"

-- | A ClassName for large-up-8
fouLargeUp8 :: ClassName
fouLargeUp8 = ClassName "large-up-8"

-- | A ClassName for large-vertical
fouLargeVertical :: ClassName
fouLargeVertical = ClassName "large-vertical"

-- | A ClassName for lead
fouLead :: ClassName
fouLead = ClassName "lead"

-- | A ClassName for left
fouLeft :: ClassName
fouLeft = ClassName "left"

-- | A ClassName for linear
fouLinear :: ClassName
fouLinear = ClassName "linear"

-- | A ClassName for long-delay
fouLongDelay :: ClassName
fouLongDelay = ClassName "long-delay"

-- | A ClassName for main-section
fouMainSection :: ClassName
fouMainSection = ClassName "main-section"

-- | A ClassName for map_canvas
fouMapCanvas :: ClassName
fouMapCanvas = ClassName "map_canvas"

-- | A ClassName for media-object
fouMediaObject :: ClassName
fouMediaObject = ClassName "media-object"

-- | A ClassName for media-object-section
fouMediaObjectSection :: ClassName
fouMediaObjectSection = ClassName "media-object-section"

-- | A ClassName for medium
fouMedium :: ClassName
fouMedium = ClassName "medium"

-- | A ClassName for medium-1
fouMedium1 :: ClassName
fouMedium1 = ClassName "medium-1"

-- | A ClassName for medium-10
fouMedium10 :: ClassName
fouMedium10 = ClassName "medium-10"

-- | A ClassName for medium-11
fouMedium11 :: ClassName
fouMedium11 = ClassName "medium-11"

-- | A ClassName for medium-12
fouMedium12 :: ClassName
fouMedium12 = ClassName "medium-12"

-- | A ClassName for medium-2
fouMedium2 :: ClassName
fouMedium2 = ClassName "medium-2"

-- | A ClassName for medium-3
fouMedium3 :: ClassName
fouMedium3 = ClassName "medium-3"

-- | A ClassName for medium-4
fouMedium4 :: ClassName
fouMedium4 = ClassName "medium-4"

-- | A ClassName for medium-5
fouMedium5 :: ClassName
fouMedium5 = ClassName "medium-5"

-- | A ClassName for medium-6
fouMedium6 :: ClassName
fouMedium6 = ClassName "medium-6"

-- | A ClassName for medium-7
fouMedium7 :: ClassName
fouMedium7 = ClassName "medium-7"

-- | A ClassName for medium-8
fouMedium8 :: ClassName
fouMedium8 = ClassName "medium-8"

-- | A ClassName for medium-9
fouMedium9 :: ClassName
fouMedium9 = ClassName "medium-9"

-- | A ClassName for medium-auto
fouMediumAuto :: ClassName
fouMediumAuto = ClassName "medium-auto"

-- | A ClassName for medium-cell-block
fouMediumCellBlock :: ClassName
fouMediumCellBlock = ClassName "medium-cell-block"

-- | A ClassName for medium-cell-block-container
fouMediumCellBlockContainer :: ClassName
fouMediumCellBlockContainer = ClassName "medium-cell-block-container"

-- | A ClassName for medium-cell-block-y
fouMediumCellBlockY :: ClassName
fouMediumCellBlockY = ClassName "medium-cell-block-y"

-- | A ClassName for medium-expanded
fouMediumExpanded :: ClassName
fouMediumExpanded = ClassName "medium-expanded"

-- | A ClassName for medium-flex-child-auto
fouMediumFlexChildAuto :: ClassName
fouMediumFlexChildAuto = ClassName "medium-flex-child-auto"

-- | A ClassName for medium-flex-child-grow
fouMediumFlexChildGrow :: ClassName
fouMediumFlexChildGrow = ClassName "medium-flex-child-grow"

-- | A ClassName for medium-flex-child-shrink
fouMediumFlexChildShrink :: ClassName
fouMediumFlexChildShrink = ClassName "medium-flex-child-shrink"

-- | A ClassName for medium-flex-container
fouMediumFlexContainer :: ClassName
fouMediumFlexContainer = ClassName "medium-flex-container"

-- | A ClassName for medium-flex-dir-column
fouMediumFlexDirColumn :: ClassName
fouMediumFlexDirColumn = ClassName "medium-flex-dir-column"

-- | A ClassName for medium-flex-dir-column-reverse
fouMediumFlexDirColumnReverse :: ClassName
fouMediumFlexDirColumnReverse = ClassName "medium-flex-dir-column-reverse"

-- | A ClassName for medium-flex-dir-row
fouMediumFlexDirRow :: ClassName
fouMediumFlexDirRow = ClassName "medium-flex-dir-row"

-- | A ClassName for medium-flex-dir-row-reverse
fouMediumFlexDirRowReverse :: ClassName
fouMediumFlexDirRowReverse = ClassName "medium-flex-dir-row-reverse"

-- | A ClassName for medium-full
fouMediumFull :: ClassName
fouMediumFull = ClassName "medium-full"

-- | A ClassName for medium-grid-frame
fouMediumGridFrame :: ClassName
fouMediumGridFrame = ClassName "medium-grid-frame"

-- | A ClassName for medium-horizontal
fouMediumHorizontal :: ClassName
fouMediumHorizontal = ClassName "medium-horizontal"

-- | A ClassName for medium-margin-collapse
fouMediumMarginCollapse :: ClassName
fouMediumMarginCollapse = ClassName "medium-margin-collapse"

-- | A ClassName for medium-offset-0
fouMediumOffset0 :: ClassName
fouMediumOffset0 = ClassName "medium-offset-0"

-- | A ClassName for medium-offset-1
fouMediumOffset1 :: ClassName
fouMediumOffset1 = ClassName "medium-offset-1"

-- | A ClassName for medium-offset-10
fouMediumOffset10 :: ClassName
fouMediumOffset10 = ClassName "medium-offset-10"

-- | A ClassName for medium-offset-11
fouMediumOffset11 :: ClassName
fouMediumOffset11 = ClassName "medium-offset-11"

-- | A ClassName for medium-offset-2
fouMediumOffset2 :: ClassName
fouMediumOffset2 = ClassName "medium-offset-2"

-- | A ClassName for medium-offset-3
fouMediumOffset3 :: ClassName
fouMediumOffset3 = ClassName "medium-offset-3"

-- | A ClassName for medium-offset-4
fouMediumOffset4 :: ClassName
fouMediumOffset4 = ClassName "medium-offset-4"

-- | A ClassName for medium-offset-5
fouMediumOffset5 :: ClassName
fouMediumOffset5 = ClassName "medium-offset-5"

-- | A ClassName for medium-offset-6
fouMediumOffset6 :: ClassName
fouMediumOffset6 = ClassName "medium-offset-6"

-- | A ClassName for medium-offset-7
fouMediumOffset7 :: ClassName
fouMediumOffset7 = ClassName "medium-offset-7"

-- | A ClassName for medium-offset-8
fouMediumOffset8 :: ClassName
fouMediumOffset8 = ClassName "medium-offset-8"

-- | A ClassName for medium-offset-9
fouMediumOffset9 :: ClassName
fouMediumOffset9 = ClassName "medium-offset-9"

-- | A ClassName for medium-order-1
fouMediumOrder1 :: ClassName
fouMediumOrder1 = ClassName "medium-order-1"

-- | A ClassName for medium-order-2
fouMediumOrder2 :: ClassName
fouMediumOrder2 = ClassName "medium-order-2"

-- | A ClassName for medium-order-3
fouMediumOrder3 :: ClassName
fouMediumOrder3 = ClassName "medium-order-3"

-- | A ClassName for medium-order-4
fouMediumOrder4 :: ClassName
fouMediumOrder4 = ClassName "medium-order-4"

-- | A ClassName for medium-order-5
fouMediumOrder5 :: ClassName
fouMediumOrder5 = ClassName "medium-order-5"

-- | A ClassName for medium-order-6
fouMediumOrder6 :: ClassName
fouMediumOrder6 = ClassName "medium-order-6"

-- | A ClassName for medium-padding-collapse
fouMediumPaddingCollapse :: ClassName
fouMediumPaddingCollapse = ClassName "medium-padding-collapse"

-- | A ClassName for medium-shrink
fouMediumShrink :: ClassName
fouMediumShrink = ClassName "medium-shrink"

-- | A ClassName for medium-simple
fouMediumSimple :: ClassName
fouMediumSimple = ClassName "medium-simple"

-- | A ClassName for medium-text-center
fouMediumTextCenter :: ClassName
fouMediumTextCenter = ClassName "medium-text-center"

-- | A ClassName for medium-text-justify
fouMediumTextJustify :: ClassName
fouMediumTextJustify = ClassName "medium-text-justify"

-- | A ClassName for medium-text-left
fouMediumTextLeft :: ClassName
fouMediumTextLeft = ClassName "medium-text-left"

-- | A ClassName for medium-text-right
fouMediumTextRight :: ClassName
fouMediumTextRight = ClassName "medium-text-right"

-- | A ClassName for medium-up-1
fouMediumUp1 :: ClassName
fouMediumUp1 = ClassName "medium-up-1"

-- | A ClassName for medium-up-2
fouMediumUp2 :: ClassName
fouMediumUp2 = ClassName "medium-up-2"

-- | A ClassName for medium-up-3
fouMediumUp3 :: ClassName
fouMediumUp3 = ClassName "medium-up-3"

-- | A ClassName for medium-up-4
fouMediumUp4 :: ClassName
fouMediumUp4 = ClassName "medium-up-4"

-- | A ClassName for medium-up-5
fouMediumUp5 :: ClassName
fouMediumUp5 = ClassName "medium-up-5"

-- | A ClassName for medium-up-6
fouMediumUp6 :: ClassName
fouMediumUp6 = ClassName "medium-up-6"

-- | A ClassName for medium-up-7
fouMediumUp7 :: ClassName
fouMediumUp7 = ClassName "medium-up-7"

-- | A ClassName for medium-up-8
fouMediumUp8 :: ClassName
fouMediumUp8 = ClassName "medium-up-8"

-- | A ClassName for medium-vertical
fouMediumVertical :: ClassName
fouMediumVertical = ClassName "medium-vertical"

-- | A ClassName for menu
fouMenu :: ClassName
fouMenu = ClassName "menu"

-- | A ClassName for menu-centered
fouMenuCentered :: ClassName
fouMenuCentered = ClassName "menu-centered"

-- | A ClassName for menu-icon
fouMenuIcon :: ClassName
fouMenuIcon = ClassName "menu-icon"

-- | A ClassName for menu-text
fouMenuText :: ClassName
fouMenuText = ClassName "menu-text"

-- | A ClassName for middle
fouMiddle :: ClassName
fouMiddle = ClassName "middle"

-- | A ClassName for mqa-display
fouMqaDisplay :: ClassName
fouMqaDisplay = ClassName "mqa-display"

-- | A ClassName for mui-enter
fouMuiEnter :: ClassName
fouMuiEnter = ClassName "mui-enter"

-- | A ClassName for mui-enter-active
fouMuiEnterActive :: ClassName
fouMuiEnterActive = ClassName "mui-enter-active"

-- | A ClassName for mui-leave
fouMuiLeave :: ClassName
fouMuiLeave = ClassName "mui-leave"

-- | A ClassName for mui-leave-active
fouMuiLeaveActive :: ClassName
fouMuiLeaveActive = ClassName "mui-leave-active"

-- | A ClassName for nested
fouNested :: ClassName
fouNested = ClassName "nested"

-- | A ClassName for no-bullet
fouNoBullet :: ClassName
fouNoBullet = ClassName "no-bullet"

-- | A ClassName for no-js
fouNoJs :: ClassName
fouNoJs = ClassName "no-js"

-- | A ClassName for no-motionui
fouNoMotionui :: ClassName
fouNoMotionui = ClassName "no-motionui"

-- | A ClassName for off-canvas
fouOffCanvas :: ClassName
fouOffCanvas = ClassName "off-canvas"

-- | A ClassName for off-canvas-absolute
fouOffCanvasAbsolute :: ClassName
fouOffCanvasAbsolute = ClassName "off-canvas-absolute"

-- | A ClassName for off-canvas-content
fouOffCanvasContent :: ClassName
fouOffCanvasContent = ClassName "off-canvas-content"

-- | A ClassName for off-canvas-wrapper
fouOffCanvasWrapper :: ClassName
fouOffCanvasWrapper = ClassName "off-canvas-wrapper"

-- | A ClassName for opens-inner
fouOpensInner :: ClassName
fouOpensInner = ClassName "opens-inner"

-- | A ClassName for opens-left
fouOpensLeft :: ClassName
fouOpensLeft = ClassName "opens-left"

-- | A ClassName for opens-right
fouOpensRight :: ClassName
fouOpensRight = ClassName "opens-right"

-- | A ClassName for orbit
fouOrbit :: ClassName
fouOrbit = ClassName "orbit"

-- | A ClassName for orbit-bullets
fouOrbitBullets :: ClassName
fouOrbitBullets = ClassName "orbit-bullets"

-- | A ClassName for orbit-caption
fouOrbitCaption :: ClassName
fouOrbitCaption = ClassName "orbit-caption"

-- | A ClassName for orbit-container
fouOrbitContainer :: ClassName
fouOrbitContainer = ClassName "orbit-container"

-- | A ClassName for orbit-figure
fouOrbitFigure :: ClassName
fouOrbitFigure = ClassName "orbit-figure"

-- | A ClassName for orbit-image
fouOrbitImage :: ClassName
fouOrbitImage = ClassName "orbit-image"

-- | A ClassName for orbit-next
fouOrbitNext :: ClassName
fouOrbitNext = ClassName "orbit-next"

-- | A ClassName for orbit-previous
fouOrbitPrevious :: ClassName
fouOrbitPrevious = ClassName "orbit-previous"

-- | A ClassName for orbit-slide
fouOrbitSlide :: ClassName
fouOrbitSlide = ClassName "orbit-slide"

-- | A ClassName for pagination
fouPagination :: ClassName
fouPagination = ClassName "pagination"

-- | A ClassName for pagination-next
fouPaginationNext :: ClassName
fouPaginationNext = ClassName "pagination-next"

-- | A ClassName for pagination-previous
fouPaginationPrevious :: ClassName
fouPaginationPrevious = ClassName "pagination-previous"

-- | A ClassName for position-bottom
fouPositionBottom :: ClassName
fouPositionBottom = ClassName "position-bottom"

-- | A ClassName for position-left
fouPositionLeft :: ClassName
fouPositionLeft = ClassName "position-left"

-- | A ClassName for position-right
fouPositionRight :: ClassName
fouPositionRight = ClassName "position-right"

-- | A ClassName for position-top
fouPositionTop :: ClassName
fouPositionTop = ClassName "position-top"

-- | A ClassName for primary
fouPrimary :: ClassName
fouPrimary = ClassName "primary"

-- | A ClassName for print-break-inside
fouPrintBreakInside :: ClassName
fouPrintBreakInside = ClassName "print-break-inside"

-- | A ClassName for progress
fouProgress :: ClassName
fouProgress = ClassName "progress"

-- | A ClassName for progress-meter
fouProgressMeter :: ClassName
fouProgressMeter = ClassName "progress-meter"

-- | A ClassName for progress-meter-text
fouProgressMeterText :: ClassName
fouProgressMeterText = ClassName "progress-meter-text"

-- | A ClassName for responsive-embed
fouResponsiveEmbed :: ClassName
fouResponsiveEmbed = ClassName "responsive-embed"

-- | A ClassName for reveal
fouReveal :: ClassName
fouReveal = ClassName "reveal"

-- | A ClassName for reveal-for-large
fouRevealForLarge :: ClassName
fouRevealForLarge = ClassName "reveal-for-large"

-- | A ClassName for reveal-for-medium
fouRevealForMedium :: ClassName
fouRevealForMedium = ClassName "reveal-for-medium"

-- | A ClassName for reveal-overlay
fouRevealOverlay :: ClassName
fouRevealOverlay = ClassName "reveal-overlay"

-- | A ClassName for right
fouRight :: ClassName
fouRight = ClassName "right"

-- | A ClassName for scale-in-down
fouScaleInDown :: ClassName
fouScaleInDown = ClassName "scale-in-down"

-- | A ClassName for scale-in-up
fouScaleInUp :: ClassName
fouScaleInUp = ClassName "scale-in-up"

-- | A ClassName for scale-out-down
fouScaleOutDown :: ClassName
fouScaleOutDown = ClassName "scale-out-down"

-- | A ClassName for scale-out-up
fouScaleOutUp :: ClassName
fouScaleOutUp = ClassName "scale-out-up"

-- | A ClassName for scroll
fouScroll :: ClassName
fouScroll = ClassName "scroll"

-- | A ClassName for secondary
fouSecondary :: ClassName
fouSecondary = ClassName "secondary"

-- | A ClassName for shake
fouShake :: ClassName
fouShake = ClassName "shake"

-- | A ClassName for short-delay
fouShortDelay :: ClassName
fouShortDelay = ClassName "short-delay"

-- | A ClassName for show-for-landscape
fouShowForLandscape :: ClassName
fouShowForLandscape = ClassName "show-for-landscape"

-- | A ClassName for show-for-large
fouShowForLarge :: ClassName
fouShowForLarge = ClassName "show-for-large"

-- | A ClassName for show-for-large-only
fouShowForLargeOnly :: ClassName
fouShowForLargeOnly = ClassName "show-for-large-only"

-- | A ClassName for show-for-medium
fouShowForMedium :: ClassName
fouShowForMedium = ClassName "show-for-medium"

-- | A ClassName for show-for-medium-only
fouShowForMediumOnly :: ClassName
fouShowForMediumOnly = ClassName "show-for-medium-only"

-- | A ClassName for show-for-portrait
fouShowForPortrait :: ClassName
fouShowForPortrait = ClassName "show-for-portrait"

-- | A ClassName for show-for-print
fouShowForPrint :: ClassName
fouShowForPrint = ClassName "show-for-print"

-- | A ClassName for show-for-small-only
fouShowForSmallOnly :: ClassName
fouShowForSmallOnly = ClassName "show-for-small-only"

-- | A ClassName for show-for-sr
fouShowForSr :: ClassName
fouShowForSr = ClassName "show-for-sr"

-- | A ClassName for show-on-focus
fouShowOnFocus :: ClassName
fouShowOnFocus = ClassName "show-on-focus"

-- | A ClassName for shrink
fouShrink :: ClassName
fouShrink = ClassName "shrink"

-- | A ClassName for simple
fouSimple :: ClassName
fouSimple = ClassName "simple"

-- | A ClassName for slide-in-down
fouSlideInDown :: ClassName
fouSlideInDown = ClassName "slide-in-down"

-- | A ClassName for slide-in-left
fouSlideInLeft :: ClassName
fouSlideInLeft = ClassName "slide-in-left"

-- | A ClassName for slide-in-right
fouSlideInRight :: ClassName
fouSlideInRight = ClassName "slide-in-right"

-- | A ClassName for slide-in-up
fouSlideInUp :: ClassName
fouSlideInUp = ClassName "slide-in-up"

-- | A ClassName for slide-out-down
fouSlideOutDown :: ClassName
fouSlideOutDown = ClassName "slide-out-down"

-- | A ClassName for slide-out-left
fouSlideOutLeft :: ClassName
fouSlideOutLeft = ClassName "slide-out-left"

-- | A ClassName for slide-out-right
fouSlideOutRight :: ClassName
fouSlideOutRight = ClassName "slide-out-right"

-- | A ClassName for slide-out-up
fouSlideOutUp :: ClassName
fouSlideOutUp = ClassName "slide-out-up"

-- | A ClassName for slider
fouSlider :: ClassName
fouSlider = ClassName "slider"

-- | A ClassName for slider-fill
fouSliderFill :: ClassName
fouSliderFill = ClassName "slider-fill"

-- | A ClassName for slider-handle
fouSliderHandle :: ClassName
fouSliderHandle = ClassName "slider-handle"

-- | A ClassName for slow
fouSlow :: ClassName
fouSlow = ClassName "slow"

-- | A ClassName for small
fouSmall :: ClassName
fouSmall = ClassName "small"

-- | A ClassName for small-1
fouSmall1 :: ClassName
fouSmall1 = ClassName "small-1"

-- | A ClassName for small-10
fouSmall10 :: ClassName
fouSmall10 = ClassName "small-10"

-- | A ClassName for small-11
fouSmall11 :: ClassName
fouSmall11 = ClassName "small-11"

-- | A ClassName for small-12
fouSmall12 :: ClassName
fouSmall12 = ClassName "small-12"

-- | A ClassName for small-2
fouSmall2 :: ClassName
fouSmall2 = ClassName "small-2"

-- | A ClassName for small-3
fouSmall3 :: ClassName
fouSmall3 = ClassName "small-3"

-- | A ClassName for small-4
fouSmall4 :: ClassName
fouSmall4 = ClassName "small-4"

-- | A ClassName for small-5
fouSmall5 :: ClassName
fouSmall5 = ClassName "small-5"

-- | A ClassName for small-6
fouSmall6 :: ClassName
fouSmall6 = ClassName "small-6"

-- | A ClassName for small-7
fouSmall7 :: ClassName
fouSmall7 = ClassName "small-7"

-- | A ClassName for small-8
fouSmall8 :: ClassName
fouSmall8 = ClassName "small-8"

-- | A ClassName for small-9
fouSmall9 :: ClassName
fouSmall9 = ClassName "small-9"

-- | A ClassName for small-full
fouSmallFull :: ClassName
fouSmallFull = ClassName "small-full"

-- | A ClassName for small-margin-collapse
fouSmallMarginCollapse :: ClassName
fouSmallMarginCollapse = ClassName "small-margin-collapse"

-- | A ClassName for small-offset-0
fouSmallOffset0 :: ClassName
fouSmallOffset0 = ClassName "small-offset-0"

-- | A ClassName for small-offset-1
fouSmallOffset1 :: ClassName
fouSmallOffset1 = ClassName "small-offset-1"

-- | A ClassName for small-offset-10
fouSmallOffset10 :: ClassName
fouSmallOffset10 = ClassName "small-offset-10"

-- | A ClassName for small-offset-11
fouSmallOffset11 :: ClassName
fouSmallOffset11 = ClassName "small-offset-11"

-- | A ClassName for small-offset-2
fouSmallOffset2 :: ClassName
fouSmallOffset2 = ClassName "small-offset-2"

-- | A ClassName for small-offset-3
fouSmallOffset3 :: ClassName
fouSmallOffset3 = ClassName "small-offset-3"

-- | A ClassName for small-offset-4
fouSmallOffset4 :: ClassName
fouSmallOffset4 = ClassName "small-offset-4"

-- | A ClassName for small-offset-5
fouSmallOffset5 :: ClassName
fouSmallOffset5 = ClassName "small-offset-5"

-- | A ClassName for small-offset-6
fouSmallOffset6 :: ClassName
fouSmallOffset6 = ClassName "small-offset-6"

-- | A ClassName for small-offset-7
fouSmallOffset7 :: ClassName
fouSmallOffset7 = ClassName "small-offset-7"

-- | A ClassName for small-offset-8
fouSmallOffset8 :: ClassName
fouSmallOffset8 = ClassName "small-offset-8"

-- | A ClassName for small-offset-9
fouSmallOffset9 :: ClassName
fouSmallOffset9 = ClassName "small-offset-9"

-- | A ClassName for small-order-1
fouSmallOrder1 :: ClassName
fouSmallOrder1 = ClassName "small-order-1"

-- | A ClassName for small-order-2
fouSmallOrder2 :: ClassName
fouSmallOrder2 = ClassName "small-order-2"

-- | A ClassName for small-order-3
fouSmallOrder3 :: ClassName
fouSmallOrder3 = ClassName "small-order-3"

-- | A ClassName for small-order-4
fouSmallOrder4 :: ClassName
fouSmallOrder4 = ClassName "small-order-4"

-- | A ClassName for small-order-5
fouSmallOrder5 :: ClassName
fouSmallOrder5 = ClassName "small-order-5"

-- | A ClassName for small-order-6
fouSmallOrder6 :: ClassName
fouSmallOrder6 = ClassName "small-order-6"

-- | A ClassName for small-padding-collapse
fouSmallPaddingCollapse :: ClassName
fouSmallPaddingCollapse = ClassName "small-padding-collapse"

-- | A ClassName for small-shrink
fouSmallShrink :: ClassName
fouSmallShrink = ClassName "small-shrink"

-- | A ClassName for small-up-1
fouSmallUp1 :: ClassName
fouSmallUp1 = ClassName "small-up-1"

-- | A ClassName for small-up-2
fouSmallUp2 :: ClassName
fouSmallUp2 = ClassName "small-up-2"

-- | A ClassName for small-up-3
fouSmallUp3 :: ClassName
fouSmallUp3 = ClassName "small-up-3"

-- | A ClassName for small-up-4
fouSmallUp4 :: ClassName
fouSmallUp4 = ClassName "small-up-4"

-- | A ClassName for small-up-5
fouSmallUp5 :: ClassName
fouSmallUp5 = ClassName "small-up-5"

-- | A ClassName for small-up-6
fouSmallUp6 :: ClassName
fouSmallUp6 = ClassName "small-up-6"

-- | A ClassName for small-up-7
fouSmallUp7 :: ClassName
fouSmallUp7 = ClassName "small-up-7"

-- | A ClassName for small-up-8
fouSmallUp8 :: ClassName
fouSmallUp8 = ClassName "small-up-8"

-- | A ClassName for spin-ccw
fouSpinCcw :: ClassName
fouSpinCcw = ClassName "spin-ccw"

-- | A ClassName for spin-cw
fouSpinCw :: ClassName
fouSpinCw = ClassName "spin-cw"

-- | A ClassName for spin-in
fouSpinIn :: ClassName
fouSpinIn = ClassName "spin-in"

-- | A ClassName for spin-in-ccw
fouSpinInCcw :: ClassName
fouSpinInCcw = ClassName "spin-in-ccw"

-- | A ClassName for spin-out
fouSpinOut :: ClassName
fouSpinOut = ClassName "spin-out"

-- | A ClassName for spin-out-ccw
fouSpinOutCcw :: ClassName
fouSpinOutCcw = ClassName "spin-out-ccw"

-- | A ClassName for stack
fouStack :: ClassName
fouStack = ClassName "stack"

-- | A ClassName for stack-for-small
fouStackForSmall :: ClassName
fouStackForSmall = ClassName "stack-for-small"

-- | A ClassName for stacked
fouStacked :: ClassName
fouStacked = ClassName "stacked"

-- | A ClassName for stacked-for-large
fouStackedForLarge :: ClassName
fouStackedForLarge = ClassName "stacked-for-large"

-- | A ClassName for stacked-for-medium
fouStackedForMedium :: ClassName
fouStackedForMedium = ClassName "stacked-for-medium"

-- | A ClassName for stacked-for-small
fouStackedForSmall :: ClassName
fouStackedForSmall = ClassName "stacked-for-small"

-- | A ClassName for stat
fouStat :: ClassName
fouStat = ClassName "stat"

-- | A ClassName for sticky
fouSticky :: ClassName
fouSticky = ClassName "sticky"

-- | A ClassName for sticky-container
fouStickyContainer :: ClassName
fouStickyContainer = ClassName "sticky-container"

-- | A ClassName for subheader
fouSubheader :: ClassName
fouSubheader = ClassName "subheader"

-- | A ClassName for submenu
fouSubmenu :: ClassName
fouSubmenu = ClassName "submenu"

-- | A ClassName for submenu-toggle
fouSubmenuToggle :: ClassName
fouSubmenuToggle = ClassName "submenu-toggle"

-- | A ClassName for submenu-toggle-text
fouSubmenuToggleText :: ClassName
fouSubmenuToggleText = ClassName "submenu-toggle-text"

-- | A ClassName for success
fouSuccess :: ClassName
fouSuccess = ClassName "success"

-- | A ClassName for switch
fouSwitch :: ClassName
fouSwitch = ClassName "switch"

-- | A ClassName for switch-active
fouSwitchActive :: ClassName
fouSwitchActive = ClassName "switch-active"

-- | A ClassName for switch-inactive
fouSwitchInactive :: ClassName
fouSwitchInactive = ClassName "switch-inactive"

-- | A ClassName for switch-input
fouSwitchInput :: ClassName
fouSwitchInput = ClassName "switch-input"

-- | A ClassName for switch-paddle
fouSwitchPaddle :: ClassName
fouSwitchPaddle = ClassName "switch-paddle"

-- | A ClassName for table-scroll
fouTableScroll :: ClassName
fouTableScroll = ClassName "table-scroll"

-- | A ClassName for tabs
fouTabs :: ClassName
fouTabs = ClassName "tabs"

-- | A ClassName for tabs-content
fouTabsContent :: ClassName
fouTabsContent = ClassName "tabs-content"

-- | A ClassName for tabs-panel
fouTabsPanel :: ClassName
fouTabsPanel = ClassName "tabs-panel"

-- | A ClassName for tabs-title
fouTabsTitle :: ClassName
fouTabsTitle = ClassName "tabs-title"

-- | A ClassName for text-center
fouTextCenter :: ClassName
fouTextCenter = ClassName "text-center"

-- | A ClassName for text-justify
fouTextJustify :: ClassName
fouTextJustify = ClassName "text-justify"

-- | A ClassName for text-left
fouTextLeft :: ClassName
fouTextLeft = ClassName "text-left"

-- | A ClassName for text-right
fouTextRight :: ClassName
fouTextRight = ClassName "text-right"

-- | A ClassName for thumbnail
fouThumbnail :: ClassName
fouThumbnail = ClassName "thumbnail"

-- | A ClassName for tiny
fouTiny :: ClassName
fouTiny = ClassName "tiny"

-- | A ClassName for title-bar
fouTitleBar :: ClassName
fouTitleBar = ClassName "title-bar"

-- | A ClassName for title-bar-left
fouTitleBarLeft :: ClassName
fouTitleBarLeft = ClassName "title-bar-left"

-- | A ClassName for title-bar-right
fouTitleBarRight :: ClassName
fouTitleBarRight = ClassName "title-bar-right"

-- | A ClassName for title-bar-title
fouTitleBarTitle :: ClassName
fouTitleBarTitle = ClassName "title-bar-title"

-- | A ClassName for tooltip
fouTooltip :: ClassName
fouTooltip = ClassName "tooltip"

-- | A ClassName for top
fouTop :: ClassName
fouTop = ClassName "top"

-- | A ClassName for top-bar
fouTopBar :: ClassName
fouTopBar = ClassName "top-bar"

-- | A ClassName for top-bar-left
fouTopBarLeft :: ClassName
fouTopBarLeft = ClassName "top-bar-left"

-- | A ClassName for top-bar-right
fouTopBarRight :: ClassName
fouTopBarRight = ClassName "top-bar-right"

-- | A ClassName for top-bar-title
fouTopBarTitle :: ClassName
fouTopBarTitle = ClassName "top-bar-title"

-- | A ClassName for unstriped
fouUnstriped :: ClassName
fouUnstriped = ClassName "unstriped"

-- | A ClassName for vertical
fouVertical :: ClassName
fouVertical = ClassName "vertical"

-- | A ClassName for warning
fouWarning :: ClassName
fouWarning = ClassName "warning"

-- | A ClassName for widescreen
fouWidescreen :: ClassName
fouWidescreen = ClassName "widescreen"

-- | A ClassName for wiggle
fouWiggle :: ClassName
fouWiggle = ClassName "wiggle"

-- | A ClassName for without-overlay
fouWithoutOverlay :: ClassName
fouWithoutOverlay = ClassName "without-overlay"

