{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Reflex.Dom.Theme.Raw.W3
Description : Auto-generated file to give hs-constants for css-file.
Copyright   : (c) gspia 2017- 
Licence     : BSD3
Maintainer  : gspia

= W3

This file contains hs-constants for a css-file. The generated file is included
in the reflex-dom-themes -package, see https://github.com/gspia/reflex-dom-themes
and the examples in there.

To use the results with reflex-dom-themes, the app should include the chosen
css-files (or links to them). Some of the css-files can be found from various CDNs
together with the fonts. If not, then you should get the fonts and put them into
correct sub-directory.

This file was generated with https://github.com/gspia/css2HsClassName

-}

module Reflex.Dom.Theme.Raw.W3 where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


-- | A ClassName for l1
l1 :: ClassName
l1 = ClassName "l1"

-- | A ClassName for l10
l10 :: ClassName
l10 = ClassName "l10"

-- | A ClassName for l11
l11 :: ClassName
l11 = ClassName "l11"

-- | A ClassName for l12
l12 :: ClassName
l12 = ClassName "l12"

-- | A ClassName for l2
l2 :: ClassName
l2 = ClassName "l2"

-- | A ClassName for l3
l3 :: ClassName
l3 = ClassName "l3"

-- | A ClassName for l4
l4 :: ClassName
l4 = ClassName "l4"

-- | A ClassName for l5
l5 :: ClassName
l5 = ClassName "l5"

-- | A ClassName for l6
l6 :: ClassName
l6 = ClassName "l6"

-- | A ClassName for l7
l7 :: ClassName
l7 = ClassName "l7"

-- | A ClassName for l8
l8 :: ClassName
l8 = ClassName "l8"

-- | A ClassName for l9
l9 :: ClassName
l9 = ClassName "l9"

-- | A ClassName for m1
m1 :: ClassName
m1 = ClassName "m1"

-- | A ClassName for m10
m10 :: ClassName
m10 = ClassName "m10"

-- | A ClassName for m11
m11 :: ClassName
m11 = ClassName "m11"

-- | A ClassName for m12
m12 :: ClassName
m12 = ClassName "m12"

-- | A ClassName for m2
m2 :: ClassName
m2 = ClassName "m2"

-- | A ClassName for m3
m3 :: ClassName
m3 = ClassName "m3"

-- | A ClassName for m4
m4 :: ClassName
m4 = ClassName "m4"

-- | A ClassName for m5
m5 :: ClassName
m5 = ClassName "m5"

-- | A ClassName for m6
m6 :: ClassName
m6 = ClassName "m6"

-- | A ClassName for m7
m7 :: ClassName
m7 = ClassName "m7"

-- | A ClassName for m8
m8 :: ClassName
m8 = ClassName "m8"

-- | A ClassName for m9
m9 :: ClassName
m9 = ClassName "m9"

-- | A ClassName for s1
s1 :: ClassName
s1 = ClassName "s1"

-- | A ClassName for s10
s10 :: ClassName
s10 = ClassName "s10"

-- | A ClassName for s11
s11 :: ClassName
s11 = ClassName "s11"

-- | A ClassName for s12
s12 :: ClassName
s12 = ClassName "s12"

-- | A ClassName for s2
s2 :: ClassName
s2 = ClassName "s2"

-- | A ClassName for s3
s3 :: ClassName
s3 = ClassName "s3"

-- | A ClassName for s4
s4 :: ClassName
s4 = ClassName "s4"

-- | A ClassName for s5
s5 :: ClassName
s5 = ClassName "s5"

-- | A ClassName for s6
s6 :: ClassName
s6 = ClassName "s6"

-- | A ClassName for s7
s7 :: ClassName
s7 = ClassName "s7"

-- | A ClassName for s8
s8 :: ClassName
s8 = ClassName "s8"

-- | A ClassName for s9
s9 :: ClassName
s9 = ClassName "s9"

-- | A ClassName for w3-amber
w3Amber :: ClassName
w3Amber = ClassName "w3-amber"

-- | A ClassName for w3-animate-bottom
w3AnimateBottom :: ClassName
w3AnimateBottom = ClassName "w3-animate-bottom"

-- | A ClassName for w3-animate-fading
w3AnimateFading :: ClassName
w3AnimateFading = ClassName "w3-animate-fading"

-- | A ClassName for w3-animate-input
w3AnimateInput :: ClassName
w3AnimateInput = ClassName "w3-animate-input"

-- | A ClassName for w3-animate-left
w3AnimateLeft :: ClassName
w3AnimateLeft = ClassName "w3-animate-left"

-- | A ClassName for w3-animate-opacity
w3AnimateOpacity :: ClassName
w3AnimateOpacity = ClassName "w3-animate-opacity"

-- | A ClassName for w3-animate-right
w3AnimateRight :: ClassName
w3AnimateRight = ClassName "w3-animate-right"

-- | A ClassName for w3-animate-top
w3AnimateTop :: ClassName
w3AnimateTop = ClassName "w3-animate-top"

-- | A ClassName for w3-animate-zoom
w3AnimateZoom :: ClassName
w3AnimateZoom = ClassName "w3-animate-zoom"

-- | A ClassName for w3-aqua
w3Aqua :: ClassName
w3Aqua = ClassName "w3-aqua"

-- | A ClassName for w3-badge
w3Badge :: ClassName
w3Badge = ClassName "w3-badge"

-- | A ClassName for w3-bar
w3Bar :: ClassName
w3Bar = ClassName "w3-bar"

-- | A ClassName for w3-bar-block
w3BarBlock :: ClassName
w3BarBlock = ClassName "w3-bar-block"

-- | A ClassName for w3-bar-item
w3BarItem :: ClassName
w3BarItem = ClassName "w3-bar-item"

-- | A ClassName for w3-black
w3Black :: ClassName
w3Black = ClassName "w3-black"

-- | A ClassName for w3-block
w3Block :: ClassName
w3Block = ClassName "w3-block"

-- | A ClassName for w3-blue
w3Blue :: ClassName
w3Blue = ClassName "w3-blue"

-- | A ClassName for w3-blue-gray
w3BlueGray :: ClassName
w3BlueGray = ClassName "w3-blue-gray"

-- | A ClassName for w3-blue-grey
w3BlueGrey :: ClassName
w3BlueGrey = ClassName "w3-blue-grey"

-- | A ClassName for w3-border
w3Border :: ClassName
w3Border = ClassName "w3-border"

-- | A ClassName for w3-border-0
w3Border0 :: ClassName
w3Border0 = ClassName "w3-border-0"

-- | A ClassName for w3-border-amber
w3BorderAmber :: ClassName
w3BorderAmber = ClassName "w3-border-amber"

-- | A ClassName for w3-border-aqua
w3BorderAqua :: ClassName
w3BorderAqua = ClassName "w3-border-aqua"

-- | A ClassName for w3-border-black
w3BorderBlack :: ClassName
w3BorderBlack = ClassName "w3-border-black"

-- | A ClassName for w3-border-blue
w3BorderBlue :: ClassName
w3BorderBlue = ClassName "w3-border-blue"

-- | A ClassName for w3-border-blue-gray
w3BorderBlueGray :: ClassName
w3BorderBlueGray = ClassName "w3-border-blue-gray"

-- | A ClassName for w3-border-blue-grey
w3BorderBlueGrey :: ClassName
w3BorderBlueGrey = ClassName "w3-border-blue-grey"

-- | A ClassName for w3-border-bottom
w3BorderBottom :: ClassName
w3BorderBottom = ClassName "w3-border-bottom"

-- | A ClassName for w3-border-brown
w3BorderBrown :: ClassName
w3BorderBrown = ClassName "w3-border-brown"

-- | A ClassName for w3-border-cyan
w3BorderCyan :: ClassName
w3BorderCyan = ClassName "w3-border-cyan"

-- | A ClassName for w3-border-dark-gray
w3BorderDarkGray :: ClassName
w3BorderDarkGray = ClassName "w3-border-dark-gray"

-- | A ClassName for w3-border-dark-grey
w3BorderDarkGrey :: ClassName
w3BorderDarkGrey = ClassName "w3-border-dark-grey"

-- | A ClassName for w3-border-deep-orange
w3BorderDeepOrange :: ClassName
w3BorderDeepOrange = ClassName "w3-border-deep-orange"

-- | A ClassName for w3-border-deep-purple
w3BorderDeepPurple :: ClassName
w3BorderDeepPurple = ClassName "w3-border-deep-purple"

-- | A ClassName for w3-border-gray
w3BorderGray :: ClassName
w3BorderGray = ClassName "w3-border-gray"

-- | A ClassName for w3-border-green
w3BorderGreen :: ClassName
w3BorderGreen = ClassName "w3-border-green"

-- | A ClassName for w3-border-grey
w3BorderGrey :: ClassName
w3BorderGrey = ClassName "w3-border-grey"

-- | A ClassName for w3-border-indigo
w3BorderIndigo :: ClassName
w3BorderIndigo = ClassName "w3-border-indigo"

-- | A ClassName for w3-border-khaki
w3BorderKhaki :: ClassName
w3BorderKhaki = ClassName "w3-border-khaki"

-- | A ClassName for w3-border-left
w3BorderLeft :: ClassName
w3BorderLeft = ClassName "w3-border-left"

-- | A ClassName for w3-border-light-blue
w3BorderLightBlue :: ClassName
w3BorderLightBlue = ClassName "w3-border-light-blue"

-- | A ClassName for w3-border-light-gray
w3BorderLightGray :: ClassName
w3BorderLightGray = ClassName "w3-border-light-gray"

-- | A ClassName for w3-border-light-green
w3BorderLightGreen :: ClassName
w3BorderLightGreen = ClassName "w3-border-light-green"

-- | A ClassName for w3-border-light-grey
w3BorderLightGrey :: ClassName
w3BorderLightGrey = ClassName "w3-border-light-grey"

-- | A ClassName for w3-border-lime
w3BorderLime :: ClassName
w3BorderLime = ClassName "w3-border-lime"

-- | A ClassName for w3-border-orange
w3BorderOrange :: ClassName
w3BorderOrange = ClassName "w3-border-orange"

-- | A ClassName for w3-border-pale-blue
w3BorderPaleBlue :: ClassName
w3BorderPaleBlue = ClassName "w3-border-pale-blue"

-- | A ClassName for w3-border-pale-green
w3BorderPaleGreen :: ClassName
w3BorderPaleGreen = ClassName "w3-border-pale-green"

-- | A ClassName for w3-border-pale-red
w3BorderPaleRed :: ClassName
w3BorderPaleRed = ClassName "w3-border-pale-red"

-- | A ClassName for w3-border-pale-yellow
w3BorderPaleYellow :: ClassName
w3BorderPaleYellow = ClassName "w3-border-pale-yellow"

-- | A ClassName for w3-border-pink
w3BorderPink :: ClassName
w3BorderPink = ClassName "w3-border-pink"

-- | A ClassName for w3-border-purple
w3BorderPurple :: ClassName
w3BorderPurple = ClassName "w3-border-purple"

-- | A ClassName for w3-border-red
w3BorderRed :: ClassName
w3BorderRed = ClassName "w3-border-red"

-- | A ClassName for w3-border-right
w3BorderRight :: ClassName
w3BorderRight = ClassName "w3-border-right"

-- | A ClassName for w3-border-sand
w3BorderSand :: ClassName
w3BorderSand = ClassName "w3-border-sand"

-- | A ClassName for w3-border-teal
w3BorderTeal :: ClassName
w3BorderTeal = ClassName "w3-border-teal"

-- | A ClassName for w3-border-top
w3BorderTop :: ClassName
w3BorderTop = ClassName "w3-border-top"

-- | A ClassName for w3-border-white
w3BorderWhite :: ClassName
w3BorderWhite = ClassName "w3-border-white"

-- | A ClassName for w3-border-yellow
w3BorderYellow :: ClassName
w3BorderYellow = ClassName "w3-border-yellow"

-- | A ClassName for w3-bordered
w3Bordered :: ClassName
w3Bordered = ClassName "w3-bordered"

-- | A ClassName for w3-bottom
w3Bottom :: ClassName
w3Bottom = ClassName "w3-bottom"

-- | A ClassName for w3-bottombar
w3Bottombar :: ClassName
w3Bottombar = ClassName "w3-bottombar"

-- | A ClassName for w3-brown
w3Brown :: ClassName
w3Brown = ClassName "w3-brown"

-- | A ClassName for w3-btn
w3Btn :: ClassName
w3Btn = ClassName "w3-btn"

-- | A ClassName for w3-button
w3Button :: ClassName
w3Button = ClassName "w3-button"

-- | A ClassName for w3-card
w3Card :: ClassName
w3Card = ClassName "w3-card"

-- | A ClassName for w3-card-2
w3Card2 :: ClassName
w3Card2 = ClassName "w3-card-2"

-- | A ClassName for w3-card-4
w3Card4 :: ClassName
w3Card4 = ClassName "w3-card-4"

-- | A ClassName for w3-cell
w3Cell :: ClassName
w3Cell = ClassName "w3-cell"

-- | A ClassName for w3-cell-bottom
w3CellBottom :: ClassName
w3CellBottom = ClassName "w3-cell-bottom"

-- | A ClassName for w3-cell-middle
w3CellMiddle :: ClassName
w3CellMiddle = ClassName "w3-cell-middle"

-- | A ClassName for w3-cell-row
w3CellRow :: ClassName
w3CellRow = ClassName "w3-cell-row"

-- | A ClassName for w3-cell-top
w3CellTop :: ClassName
w3CellTop = ClassName "w3-cell-top"

-- | A ClassName for w3-center
w3Center :: ClassName
w3Center = ClassName "w3-center"

-- | A ClassName for w3-centered
w3Centered :: ClassName
w3Centered = ClassName "w3-centered"

-- | A ClassName for w3-check
w3Check :: ClassName
w3Check = ClassName "w3-check"

-- | A ClassName for w3-circle
w3Circle :: ClassName
w3Circle = ClassName "w3-circle"

-- | A ClassName for w3-clear
w3Clear :: ClassName
w3Clear = ClassName "w3-clear"

-- | A ClassName for w3-code
w3Code :: ClassName
w3Code = ClassName "w3-code"

-- | A ClassName for w3-codespan
w3Codespan :: ClassName
w3Codespan = ClassName "w3-codespan"

-- | A ClassName for w3-col
w3Col :: ClassName
w3Col = ClassName "w3-col"

-- | A ClassName for w3-collapse
w3Collapse :: ClassName
w3Collapse = ClassName "w3-collapse"

-- | A ClassName for w3-container
w3Container :: ClassName
w3Container = ClassName "w3-container"

-- | A ClassName for w3-content
w3Content :: ClassName
w3Content = ClassName "w3-content"

-- | A ClassName for w3-cyan
w3Cyan :: ClassName
w3Cyan = ClassName "w3-cyan"

-- | A ClassName for w3-dark-gray
w3DarkGray :: ClassName
w3DarkGray = ClassName "w3-dark-gray"

-- | A ClassName for w3-dark-grey
w3DarkGrey :: ClassName
w3DarkGrey = ClassName "w3-dark-grey"

-- | A ClassName for w3-deep-orange
w3DeepOrange :: ClassName
w3DeepOrange = ClassName "w3-deep-orange"

-- | A ClassName for w3-deep-purple
w3DeepPurple :: ClassName
w3DeepPurple = ClassName "w3-deep-purple"

-- | A ClassName for w3-disabled
w3Disabled :: ClassName
w3Disabled = ClassName "w3-disabled"

-- | A ClassName for w3-display-bottomleft
w3DisplayBottomleft :: ClassName
w3DisplayBottomleft = ClassName "w3-display-bottomleft"

-- | A ClassName for w3-display-bottommiddle
w3DisplayBottommiddle :: ClassName
w3DisplayBottommiddle = ClassName "w3-display-bottommiddle"

-- | A ClassName for w3-display-bottomright
w3DisplayBottomright :: ClassName
w3DisplayBottomright = ClassName "w3-display-bottomright"

-- | A ClassName for w3-display-container
w3DisplayContainer :: ClassName
w3DisplayContainer = ClassName "w3-display-container"

-- | A ClassName for w3-display-hover
w3DisplayHover :: ClassName
w3DisplayHover = ClassName "w3-display-hover"

-- | A ClassName for w3-display-left
w3DisplayLeft :: ClassName
w3DisplayLeft = ClassName "w3-display-left"

-- | A ClassName for w3-display-middle
w3DisplayMiddle :: ClassName
w3DisplayMiddle = ClassName "w3-display-middle"

-- | A ClassName for w3-display-position
w3DisplayPosition :: ClassName
w3DisplayPosition = ClassName "w3-display-position"

-- | A ClassName for w3-display-right
w3DisplayRight :: ClassName
w3DisplayRight = ClassName "w3-display-right"

-- | A ClassName for w3-display-topleft
w3DisplayTopleft :: ClassName
w3DisplayTopleft = ClassName "w3-display-topleft"

-- | A ClassName for w3-display-topmiddle
w3DisplayTopmiddle :: ClassName
w3DisplayTopmiddle = ClassName "w3-display-topmiddle"

-- | A ClassName for w3-display-topright
w3DisplayTopright :: ClassName
w3DisplayTopright = ClassName "w3-display-topright"

-- | A ClassName for w3-dropdown-click
w3DropdownClick :: ClassName
w3DropdownClick = ClassName "w3-dropdown-click"

-- | A ClassName for w3-dropdown-content
w3DropdownContent :: ClassName
w3DropdownContent = ClassName "w3-dropdown-content"

-- | A ClassName for w3-dropdown-hover
w3DropdownHover :: ClassName
w3DropdownHover = ClassName "w3-dropdown-hover"

-- | A ClassName for w3-gray
w3Gray :: ClassName
w3Gray = ClassName "w3-gray"

-- | A ClassName for w3-grayscale
w3Grayscale :: ClassName
w3Grayscale = ClassName "w3-grayscale"

-- | A ClassName for w3-grayscale-max
w3GrayscaleMax :: ClassName
w3GrayscaleMax = ClassName "w3-grayscale-max"

-- | A ClassName for w3-grayscale-min
w3GrayscaleMin :: ClassName
w3GrayscaleMin = ClassName "w3-grayscale-min"

-- | A ClassName for w3-green
w3Green :: ClassName
w3Green = ClassName "w3-green"

-- | A ClassName for w3-grey
w3Grey :: ClassName
w3Grey = ClassName "w3-grey"

-- | A ClassName for w3-greyscale
w3Greyscale :: ClassName
w3Greyscale = ClassName "w3-greyscale"

-- | A ClassName for w3-greyscale-max
w3GreyscaleMax :: ClassName
w3GreyscaleMax = ClassName "w3-greyscale-max"

-- | A ClassName for w3-greyscale-min
w3GreyscaleMin :: ClassName
w3GreyscaleMin = ClassName "w3-greyscale-min"

-- | A ClassName for w3-half
w3Half :: ClassName
w3Half = ClassName "w3-half"

-- | A ClassName for w3-hide
w3Hide :: ClassName
w3Hide = ClassName "w3-hide"

-- | A ClassName for w3-hide-large
w3HideLarge :: ClassName
w3HideLarge = ClassName "w3-hide-large"

-- | A ClassName for w3-hide-medium
w3HideMedium :: ClassName
w3HideMedium = ClassName "w3-hide-medium"

-- | A ClassName for w3-hide-small
w3HideSmall :: ClassName
w3HideSmall = ClassName "w3-hide-small"

-- | A ClassName for w3-hover-amber
w3HoverAmber :: ClassName
w3HoverAmber = ClassName "w3-hover-amber"

-- | A ClassName for w3-hover-aqua
w3HoverAqua :: ClassName
w3HoverAqua = ClassName "w3-hover-aqua"

-- | A ClassName for w3-hover-black
w3HoverBlack :: ClassName
w3HoverBlack = ClassName "w3-hover-black"

-- | A ClassName for w3-hover-blue
w3HoverBlue :: ClassName
w3HoverBlue = ClassName "w3-hover-blue"

-- | A ClassName for w3-hover-blue-gray
w3HoverBlueGray :: ClassName
w3HoverBlueGray = ClassName "w3-hover-blue-gray"

-- | A ClassName for w3-hover-blue-grey
w3HoverBlueGrey :: ClassName
w3HoverBlueGrey = ClassName "w3-hover-blue-grey"

-- | A ClassName for w3-hover-border-amber
w3HoverBorderAmber :: ClassName
w3HoverBorderAmber = ClassName "w3-hover-border-amber"

-- | A ClassName for w3-hover-border-aqua
w3HoverBorderAqua :: ClassName
w3HoverBorderAqua = ClassName "w3-hover-border-aqua"

-- | A ClassName for w3-hover-border-black
w3HoverBorderBlack :: ClassName
w3HoverBorderBlack = ClassName "w3-hover-border-black"

-- | A ClassName for w3-hover-border-blue
w3HoverBorderBlue :: ClassName
w3HoverBorderBlue = ClassName "w3-hover-border-blue"

-- | A ClassName for w3-hover-border-blue-gray
w3HoverBorderBlueGray :: ClassName
w3HoverBorderBlueGray = ClassName "w3-hover-border-blue-gray"

-- | A ClassName for w3-hover-border-blue-grey
w3HoverBorderBlueGrey :: ClassName
w3HoverBorderBlueGrey = ClassName "w3-hover-border-blue-grey"

-- | A ClassName for w3-hover-border-brown
w3HoverBorderBrown :: ClassName
w3HoverBorderBrown = ClassName "w3-hover-border-brown"

-- | A ClassName for w3-hover-border-cyan
w3HoverBorderCyan :: ClassName
w3HoverBorderCyan = ClassName "w3-hover-border-cyan"

-- | A ClassName for w3-hover-border-dark-gray
w3HoverBorderDarkGray :: ClassName
w3HoverBorderDarkGray = ClassName "w3-hover-border-dark-gray"

-- | A ClassName for w3-hover-border-dark-grey
w3HoverBorderDarkGrey :: ClassName
w3HoverBorderDarkGrey = ClassName "w3-hover-border-dark-grey"

-- | A ClassName for w3-hover-border-deep-orange
w3HoverBorderDeepOrange :: ClassName
w3HoverBorderDeepOrange = ClassName "w3-hover-border-deep-orange"

-- | A ClassName for w3-hover-border-deep-purple
w3HoverBorderDeepPurple :: ClassName
w3HoverBorderDeepPurple = ClassName "w3-hover-border-deep-purple"

-- | A ClassName for w3-hover-border-gray
w3HoverBorderGray :: ClassName
w3HoverBorderGray = ClassName "w3-hover-border-gray"

-- | A ClassName for w3-hover-border-green
w3HoverBorderGreen :: ClassName
w3HoverBorderGreen = ClassName "w3-hover-border-green"

-- | A ClassName for w3-hover-border-grey
w3HoverBorderGrey :: ClassName
w3HoverBorderGrey = ClassName "w3-hover-border-grey"

-- | A ClassName for w3-hover-border-indigo
w3HoverBorderIndigo :: ClassName
w3HoverBorderIndigo = ClassName "w3-hover-border-indigo"

-- | A ClassName for w3-hover-border-khaki
w3HoverBorderKhaki :: ClassName
w3HoverBorderKhaki = ClassName "w3-hover-border-khaki"

-- | A ClassName for w3-hover-border-light-blue
w3HoverBorderLightBlue :: ClassName
w3HoverBorderLightBlue = ClassName "w3-hover-border-light-blue"

-- | A ClassName for w3-hover-border-light-gray
w3HoverBorderLightGray :: ClassName
w3HoverBorderLightGray = ClassName "w3-hover-border-light-gray"

-- | A ClassName for w3-hover-border-light-green
w3HoverBorderLightGreen :: ClassName
w3HoverBorderLightGreen = ClassName "w3-hover-border-light-green"

-- | A ClassName for w3-hover-border-light-grey
w3HoverBorderLightGrey :: ClassName
w3HoverBorderLightGrey = ClassName "w3-hover-border-light-grey"

-- | A ClassName for w3-hover-border-lime
w3HoverBorderLime :: ClassName
w3HoverBorderLime = ClassName "w3-hover-border-lime"

-- | A ClassName for w3-hover-border-orange
w3HoverBorderOrange :: ClassName
w3HoverBorderOrange = ClassName "w3-hover-border-orange"

-- | A ClassName for w3-hover-border-pale-blue
w3HoverBorderPaleBlue :: ClassName
w3HoverBorderPaleBlue = ClassName "w3-hover-border-pale-blue"

-- | A ClassName for w3-hover-border-pale-green
w3HoverBorderPaleGreen :: ClassName
w3HoverBorderPaleGreen = ClassName "w3-hover-border-pale-green"

-- | A ClassName for w3-hover-border-pale-red
w3HoverBorderPaleRed :: ClassName
w3HoverBorderPaleRed = ClassName "w3-hover-border-pale-red"

-- | A ClassName for w3-hover-border-pale-yellow
w3HoverBorderPaleYellow :: ClassName
w3HoverBorderPaleYellow = ClassName "w3-hover-border-pale-yellow"

-- | A ClassName for w3-hover-border-pink
w3HoverBorderPink :: ClassName
w3HoverBorderPink = ClassName "w3-hover-border-pink"

-- | A ClassName for w3-hover-border-purple
w3HoverBorderPurple :: ClassName
w3HoverBorderPurple = ClassName "w3-hover-border-purple"

-- | A ClassName for w3-hover-border-red
w3HoverBorderRed :: ClassName
w3HoverBorderRed = ClassName "w3-hover-border-red"

-- | A ClassName for w3-hover-border-sand
w3HoverBorderSand :: ClassName
w3HoverBorderSand = ClassName "w3-hover-border-sand"

-- | A ClassName for w3-hover-border-teal
w3HoverBorderTeal :: ClassName
w3HoverBorderTeal = ClassName "w3-hover-border-teal"

-- | A ClassName for w3-hover-border-white
w3HoverBorderWhite :: ClassName
w3HoverBorderWhite = ClassName "w3-hover-border-white"

-- | A ClassName for w3-hover-border-yellow
w3HoverBorderYellow :: ClassName
w3HoverBorderYellow = ClassName "w3-hover-border-yellow"

-- | A ClassName for w3-hover-brown
w3HoverBrown :: ClassName
w3HoverBrown = ClassName "w3-hover-brown"

-- | A ClassName for w3-hover-cyan
w3HoverCyan :: ClassName
w3HoverCyan = ClassName "w3-hover-cyan"

-- | A ClassName for w3-hover-dark-gray
w3HoverDarkGray :: ClassName
w3HoverDarkGray = ClassName "w3-hover-dark-gray"

-- | A ClassName for w3-hover-dark-grey
w3HoverDarkGrey :: ClassName
w3HoverDarkGrey = ClassName "w3-hover-dark-grey"

-- | A ClassName for w3-hover-deep-orange
w3HoverDeepOrange :: ClassName
w3HoverDeepOrange = ClassName "w3-hover-deep-orange"

-- | A ClassName for w3-hover-deep-purple
w3HoverDeepPurple :: ClassName
w3HoverDeepPurple = ClassName "w3-hover-deep-purple"

-- | A ClassName for w3-hover-gray
w3HoverGray :: ClassName
w3HoverGray = ClassName "w3-hover-gray"

-- | A ClassName for w3-hover-grayscale
w3HoverGrayscale :: ClassName
w3HoverGrayscale = ClassName "w3-hover-grayscale"

-- | A ClassName for w3-hover-green
w3HoverGreen :: ClassName
w3HoverGreen = ClassName "w3-hover-green"

-- | A ClassName for w3-hover-grey
w3HoverGrey :: ClassName
w3HoverGrey = ClassName "w3-hover-grey"

-- | A ClassName for w3-hover-greyscale
w3HoverGreyscale :: ClassName
w3HoverGreyscale = ClassName "w3-hover-greyscale"

-- | A ClassName for w3-hover-indigo
w3HoverIndigo :: ClassName
w3HoverIndigo = ClassName "w3-hover-indigo"

-- | A ClassName for w3-hover-khaki
w3HoverKhaki :: ClassName
w3HoverKhaki = ClassName "w3-hover-khaki"

-- | A ClassName for w3-hover-light-blue
w3HoverLightBlue :: ClassName
w3HoverLightBlue = ClassName "w3-hover-light-blue"

-- | A ClassName for w3-hover-light-gray
w3HoverLightGray :: ClassName
w3HoverLightGray = ClassName "w3-hover-light-gray"

-- | A ClassName for w3-hover-light-green
w3HoverLightGreen :: ClassName
w3HoverLightGreen = ClassName "w3-hover-light-green"

-- | A ClassName for w3-hover-light-grey
w3HoverLightGrey :: ClassName
w3HoverLightGrey = ClassName "w3-hover-light-grey"

-- | A ClassName for w3-hover-lime
w3HoverLime :: ClassName
w3HoverLime = ClassName "w3-hover-lime"

-- | A ClassName for w3-hover-none
w3HoverNone :: ClassName
w3HoverNone = ClassName "w3-hover-none"

-- | A ClassName for w3-hover-opacity
w3HoverOpacity :: ClassName
w3HoverOpacity = ClassName "w3-hover-opacity"

-- | A ClassName for w3-hover-opacity-off
w3HoverOpacityOff :: ClassName
w3HoverOpacityOff = ClassName "w3-hover-opacity-off"

-- | A ClassName for w3-hover-orange
w3HoverOrange :: ClassName
w3HoverOrange = ClassName "w3-hover-orange"

-- | A ClassName for w3-hover-pale-blue
w3HoverPaleBlue :: ClassName
w3HoverPaleBlue = ClassName "w3-hover-pale-blue"

-- | A ClassName for w3-hover-pale-green
w3HoverPaleGreen :: ClassName
w3HoverPaleGreen = ClassName "w3-hover-pale-green"

-- | A ClassName for w3-hover-pale-red
w3HoverPaleRed :: ClassName
w3HoverPaleRed = ClassName "w3-hover-pale-red"

-- | A ClassName for w3-hover-pale-yellow
w3HoverPaleYellow :: ClassName
w3HoverPaleYellow = ClassName "w3-hover-pale-yellow"

-- | A ClassName for w3-hover-pink
w3HoverPink :: ClassName
w3HoverPink = ClassName "w3-hover-pink"

-- | A ClassName for w3-hover-purple
w3HoverPurple :: ClassName
w3HoverPurple = ClassName "w3-hover-purple"

-- | A ClassName for w3-hover-red
w3HoverRed :: ClassName
w3HoverRed = ClassName "w3-hover-red"

-- | A ClassName for w3-hover-sand
w3HoverSand :: ClassName
w3HoverSand = ClassName "w3-hover-sand"

-- | A ClassName for w3-hover-sepia
w3HoverSepia :: ClassName
w3HoverSepia = ClassName "w3-hover-sepia"

-- | A ClassName for w3-hover-shadow
w3HoverShadow :: ClassName
w3HoverShadow = ClassName "w3-hover-shadow"

-- | A ClassName for w3-hover-teal
w3HoverTeal :: ClassName
w3HoverTeal = ClassName "w3-hover-teal"

-- | A ClassName for w3-hover-text-amber
w3HoverTextAmber :: ClassName
w3HoverTextAmber = ClassName "w3-hover-text-amber"

-- | A ClassName for w3-hover-text-aqua
w3HoverTextAqua :: ClassName
w3HoverTextAqua = ClassName "w3-hover-text-aqua"

-- | A ClassName for w3-hover-text-black
w3HoverTextBlack :: ClassName
w3HoverTextBlack = ClassName "w3-hover-text-black"

-- | A ClassName for w3-hover-text-blue
w3HoverTextBlue :: ClassName
w3HoverTextBlue = ClassName "w3-hover-text-blue"

-- | A ClassName for w3-hover-text-blue-gray
w3HoverTextBlueGray :: ClassName
w3HoverTextBlueGray = ClassName "w3-hover-text-blue-gray"

-- | A ClassName for w3-hover-text-blue-grey
w3HoverTextBlueGrey :: ClassName
w3HoverTextBlueGrey = ClassName "w3-hover-text-blue-grey"

-- | A ClassName for w3-hover-text-brown
w3HoverTextBrown :: ClassName
w3HoverTextBrown = ClassName "w3-hover-text-brown"

-- | A ClassName for w3-hover-text-cyan
w3HoverTextCyan :: ClassName
w3HoverTextCyan = ClassName "w3-hover-text-cyan"

-- | A ClassName for w3-hover-text-dark-gray
w3HoverTextDarkGray :: ClassName
w3HoverTextDarkGray = ClassName "w3-hover-text-dark-gray"

-- | A ClassName for w3-hover-text-dark-grey
w3HoverTextDarkGrey :: ClassName
w3HoverTextDarkGrey = ClassName "w3-hover-text-dark-grey"

-- | A ClassName for w3-hover-text-deep-orange
w3HoverTextDeepOrange :: ClassName
w3HoverTextDeepOrange = ClassName "w3-hover-text-deep-orange"

-- | A ClassName for w3-hover-text-deep-purple
w3HoverTextDeepPurple :: ClassName
w3HoverTextDeepPurple = ClassName "w3-hover-text-deep-purple"

-- | A ClassName for w3-hover-text-gray
w3HoverTextGray :: ClassName
w3HoverTextGray = ClassName "w3-hover-text-gray"

-- | A ClassName for w3-hover-text-green
w3HoverTextGreen :: ClassName
w3HoverTextGreen = ClassName "w3-hover-text-green"

-- | A ClassName for w3-hover-text-grey
w3HoverTextGrey :: ClassName
w3HoverTextGrey = ClassName "w3-hover-text-grey"

-- | A ClassName for w3-hover-text-indigo
w3HoverTextIndigo :: ClassName
w3HoverTextIndigo = ClassName "w3-hover-text-indigo"

-- | A ClassName for w3-hover-text-khaki
w3HoverTextKhaki :: ClassName
w3HoverTextKhaki = ClassName "w3-hover-text-khaki"

-- | A ClassName for w3-hover-text-light-blue
w3HoverTextLightBlue :: ClassName
w3HoverTextLightBlue = ClassName "w3-hover-text-light-blue"

-- | A ClassName for w3-hover-text-light-gray
w3HoverTextLightGray :: ClassName
w3HoverTextLightGray = ClassName "w3-hover-text-light-gray"

-- | A ClassName for w3-hover-text-light-green
w3HoverTextLightGreen :: ClassName
w3HoverTextLightGreen = ClassName "w3-hover-text-light-green"

-- | A ClassName for w3-hover-text-light-grey
w3HoverTextLightGrey :: ClassName
w3HoverTextLightGrey = ClassName "w3-hover-text-light-grey"

-- | A ClassName for w3-hover-text-lime
w3HoverTextLime :: ClassName
w3HoverTextLime = ClassName "w3-hover-text-lime"

-- | A ClassName for w3-hover-text-orange
w3HoverTextOrange :: ClassName
w3HoverTextOrange = ClassName "w3-hover-text-orange"

-- | A ClassName for w3-hover-text-pink
w3HoverTextPink :: ClassName
w3HoverTextPink = ClassName "w3-hover-text-pink"

-- | A ClassName for w3-hover-text-purple
w3HoverTextPurple :: ClassName
w3HoverTextPurple = ClassName "w3-hover-text-purple"

-- | A ClassName for w3-hover-text-red
w3HoverTextRed :: ClassName
w3HoverTextRed = ClassName "w3-hover-text-red"

-- | A ClassName for w3-hover-text-sand
w3HoverTextSand :: ClassName
w3HoverTextSand = ClassName "w3-hover-text-sand"

-- | A ClassName for w3-hover-text-teal
w3HoverTextTeal :: ClassName
w3HoverTextTeal = ClassName "w3-hover-text-teal"

-- | A ClassName for w3-hover-text-white
w3HoverTextWhite :: ClassName
w3HoverTextWhite = ClassName "w3-hover-text-white"

-- | A ClassName for w3-hover-text-yellow
w3HoverTextYellow :: ClassName
w3HoverTextYellow = ClassName "w3-hover-text-yellow"

-- | A ClassName for w3-hover-white
w3HoverWhite :: ClassName
w3HoverWhite = ClassName "w3-hover-white"

-- | A ClassName for w3-hover-yellow
w3HoverYellow :: ClassName
w3HoverYellow = ClassName "w3-hover-yellow"

-- | A ClassName for w3-hoverable
w3Hoverable :: ClassName
w3Hoverable = ClassName "w3-hoverable"

-- | A ClassName for w3-image
w3Image :: ClassName
w3Image = ClassName "w3-image"

-- | A ClassName for w3-indigo
w3Indigo :: ClassName
w3Indigo = ClassName "w3-indigo"

-- | A ClassName for w3-input
w3Input :: ClassName
w3Input = ClassName "w3-input"

-- | A ClassName for w3-jumbo
w3Jumbo :: ClassName
w3Jumbo = ClassName "w3-jumbo"

-- | A ClassName for w3-justify
w3Justify :: ClassName
w3Justify = ClassName "w3-justify"

-- | A ClassName for w3-khaki
w3Khaki :: ClassName
w3Khaki = ClassName "w3-khaki"

-- | A ClassName for w3-large
w3Large :: ClassName
w3Large = ClassName "w3-large"

-- | A ClassName for w3-left
w3Left :: ClassName
w3Left = ClassName "w3-left"

-- | A ClassName for w3-left-align
w3LeftAlign :: ClassName
w3LeftAlign = ClassName "w3-left-align"

-- | A ClassName for w3-leftbar
w3Leftbar :: ClassName
w3Leftbar = ClassName "w3-leftbar"

-- | A ClassName for w3-light-blue
w3LightBlue :: ClassName
w3LightBlue = ClassName "w3-light-blue"

-- | A ClassName for w3-light-gray
w3LightGray :: ClassName
w3LightGray = ClassName "w3-light-gray"

-- | A ClassName for w3-light-green
w3LightGreen :: ClassName
w3LightGreen = ClassName "w3-light-green"

-- | A ClassName for w3-light-grey
w3LightGrey :: ClassName
w3LightGrey = ClassName "w3-light-grey"

-- | A ClassName for w3-lime
w3Lime :: ClassName
w3Lime = ClassName "w3-lime"

-- | A ClassName for w3-main
w3Main :: ClassName
w3Main = ClassName "w3-main"

-- | A ClassName for w3-margin
w3Margin :: ClassName
w3Margin = ClassName "w3-margin"

-- | A ClassName for w3-margin-bottom
w3MarginBottom :: ClassName
w3MarginBottom = ClassName "w3-margin-bottom"

-- | A ClassName for w3-margin-left
w3MarginLeft :: ClassName
w3MarginLeft = ClassName "w3-margin-left"

-- | A ClassName for w3-margin-right
w3MarginRight :: ClassName
w3MarginRight = ClassName "w3-margin-right"

-- | A ClassName for w3-margin-top
w3MarginTop :: ClassName
w3MarginTop = ClassName "w3-margin-top"

-- | A ClassName for w3-medium
w3Medium :: ClassName
w3Medium = ClassName "w3-medium"

-- | A ClassName for w3-mobile
w3Mobile :: ClassName
w3Mobile = ClassName "w3-mobile"

-- | A ClassName for w3-modal
w3Modal :: ClassName
w3Modal = ClassName "w3-modal"

-- | A ClassName for w3-modal-content
w3ModalContent :: ClassName
w3ModalContent = ClassName "w3-modal-content"

-- | A ClassName for w3-opacity
w3Opacity :: ClassName
w3Opacity = ClassName "w3-opacity"

-- | A ClassName for w3-opacity-max
w3OpacityMax :: ClassName
w3OpacityMax = ClassName "w3-opacity-max"

-- | A ClassName for w3-opacity-min
w3OpacityMin :: ClassName
w3OpacityMin = ClassName "w3-opacity-min"

-- | A ClassName for w3-opacity-off
w3OpacityOff :: ClassName
w3OpacityOff = ClassName "w3-opacity-off"

-- | A ClassName for w3-orange
w3Orange :: ClassName
w3Orange = ClassName "w3-orange"

-- | A ClassName for w3-overlay
w3Overlay :: ClassName
w3Overlay = ClassName "w3-overlay"

-- | A ClassName for w3-padding
w3Padding :: ClassName
w3Padding = ClassName "w3-padding"

-- | A ClassName for w3-padding-16
w3Padding16 :: ClassName
w3Padding16 = ClassName "w3-padding-16"

-- | A ClassName for w3-padding-24
w3Padding24 :: ClassName
w3Padding24 = ClassName "w3-padding-24"

-- | A ClassName for w3-padding-32
w3Padding32 :: ClassName
w3Padding32 = ClassName "w3-padding-32"

-- | A ClassName for w3-padding-48
w3Padding48 :: ClassName
w3Padding48 = ClassName "w3-padding-48"

-- | A ClassName for w3-padding-64
w3Padding64 :: ClassName
w3Padding64 = ClassName "w3-padding-64"

-- | A ClassName for w3-padding-large
w3PaddingLarge :: ClassName
w3PaddingLarge = ClassName "w3-padding-large"

-- | A ClassName for w3-padding-small
w3PaddingSmall :: ClassName
w3PaddingSmall = ClassName "w3-padding-small"

-- | A ClassName for w3-pale-blue
w3PaleBlue :: ClassName
w3PaleBlue = ClassName "w3-pale-blue"

-- | A ClassName for w3-pale-green
w3PaleGreen :: ClassName
w3PaleGreen = ClassName "w3-pale-green"

-- | A ClassName for w3-pale-red
w3PaleRed :: ClassName
w3PaleRed = ClassName "w3-pale-red"

-- | A ClassName for w3-pale-yellow
w3PaleYellow :: ClassName
w3PaleYellow = ClassName "w3-pale-yellow"

-- | A ClassName for w3-panel
w3Panel :: ClassName
w3Panel = ClassName "w3-panel"

-- | A ClassName for w3-pink
w3Pink :: ClassName
w3Pink = ClassName "w3-pink"

-- | A ClassName for w3-purple
w3Purple :: ClassName
w3Purple = ClassName "w3-purple"

-- | A ClassName for w3-quarter
w3Quarter :: ClassName
w3Quarter = ClassName "w3-quarter"

-- | A ClassName for w3-radio
w3Radio :: ClassName
w3Radio = ClassName "w3-radio"

-- | A ClassName for w3-red
w3Red :: ClassName
w3Red = ClassName "w3-red"

-- | A ClassName for w3-responsive
w3Responsive :: ClassName
w3Responsive = ClassName "w3-responsive"

-- | A ClassName for w3-rest
w3Rest :: ClassName
w3Rest = ClassName "w3-rest"

-- | A ClassName for w3-right
w3Right :: ClassName
w3Right = ClassName "w3-right"

-- | A ClassName for w3-right-align
w3RightAlign :: ClassName
w3RightAlign = ClassName "w3-right-align"

-- | A ClassName for w3-rightbar
w3Rightbar :: ClassName
w3Rightbar = ClassName "w3-rightbar"

-- | A ClassName for w3-ripple
w3Ripple :: ClassName
w3Ripple = ClassName "w3-ripple"

-- | A ClassName for w3-round
w3Round :: ClassName
w3Round = ClassName "w3-round"

-- | A ClassName for w3-round-large
w3RoundLarge :: ClassName
w3RoundLarge = ClassName "w3-round-large"

-- | A ClassName for w3-round-medium
w3RoundMedium :: ClassName
w3RoundMedium = ClassName "w3-round-medium"

-- | A ClassName for w3-round-small
w3RoundSmall :: ClassName
w3RoundSmall = ClassName "w3-round-small"

-- | A ClassName for w3-round-xlarge
w3RoundXlarge :: ClassName
w3RoundXlarge = ClassName "w3-round-xlarge"

-- | A ClassName for w3-round-xxlarge
w3RoundXxlarge :: ClassName
w3RoundXxlarge = ClassName "w3-round-xxlarge"

-- | A ClassName for w3-row
w3Row :: ClassName
w3Row = ClassName "w3-row"

-- | A ClassName for w3-row-padding
w3RowPadding :: ClassName
w3RowPadding = ClassName "w3-row-padding"

-- | A ClassName for w3-sand
w3Sand :: ClassName
w3Sand = ClassName "w3-sand"

-- | A ClassName for w3-section
w3Section :: ClassName
w3Section = ClassName "w3-section"

-- | A ClassName for w3-select
w3Select :: ClassName
w3Select = ClassName "w3-select"

-- | A ClassName for w3-sepia
w3Sepia :: ClassName
w3Sepia = ClassName "w3-sepia"

-- | A ClassName for w3-sepia-max
w3SepiaMax :: ClassName
w3SepiaMax = ClassName "w3-sepia-max"

-- | A ClassName for w3-sepia-min
w3SepiaMin :: ClassName
w3SepiaMin = ClassName "w3-sepia-min"

-- | A ClassName for w3-serif
w3Serif :: ClassName
w3Serif = ClassName "w3-serif"

-- | A ClassName for w3-show
w3Show :: ClassName
w3Show = ClassName "w3-show"

-- | A ClassName for w3-show-block
w3ShowBlock :: ClassName
w3ShowBlock = ClassName "w3-show-block"

-- | A ClassName for w3-show-inline-block
w3ShowInlineBlock :: ClassName
w3ShowInlineBlock = ClassName "w3-show-inline-block"

-- | A ClassName for w3-sidebar
w3Sidebar :: ClassName
w3Sidebar = ClassName "w3-sidebar"

-- | A ClassName for w3-small
w3Small :: ClassName
w3Small = ClassName "w3-small"

-- | A ClassName for w3-spin
w3Spin :: ClassName
w3Spin = ClassName "w3-spin"

-- | A ClassName for w3-striped
w3Striped :: ClassName
w3Striped = ClassName "w3-striped"

-- | A ClassName for w3-table
w3Table :: ClassName
w3Table = ClassName "w3-table"

-- | A ClassName for w3-table-all
w3TableAll :: ClassName
w3TableAll = ClassName "w3-table-all"

-- | A ClassName for w3-tag
w3Tag :: ClassName
w3Tag = ClassName "w3-tag"

-- | A ClassName for w3-teal
w3Teal :: ClassName
w3Teal = ClassName "w3-teal"

-- | A ClassName for w3-text
w3Text :: ClassName
w3Text = ClassName "w3-text"

-- | A ClassName for w3-text-amber
w3TextAmber :: ClassName
w3TextAmber = ClassName "w3-text-amber"

-- | A ClassName for w3-text-aqua
w3TextAqua :: ClassName
w3TextAqua = ClassName "w3-text-aqua"

-- | A ClassName for w3-text-black
w3TextBlack :: ClassName
w3TextBlack = ClassName "w3-text-black"

-- | A ClassName for w3-text-blue
w3TextBlue :: ClassName
w3TextBlue = ClassName "w3-text-blue"

-- | A ClassName for w3-text-blue-gray
w3TextBlueGray :: ClassName
w3TextBlueGray = ClassName "w3-text-blue-gray"

-- | A ClassName for w3-text-blue-grey
w3TextBlueGrey :: ClassName
w3TextBlueGrey = ClassName "w3-text-blue-grey"

-- | A ClassName for w3-text-brown
w3TextBrown :: ClassName
w3TextBrown = ClassName "w3-text-brown"

-- | A ClassName for w3-text-cyan
w3TextCyan :: ClassName
w3TextCyan = ClassName "w3-text-cyan"

-- | A ClassName for w3-text-dark-gray
w3TextDarkGray :: ClassName
w3TextDarkGray = ClassName "w3-text-dark-gray"

-- | A ClassName for w3-text-dark-grey
w3TextDarkGrey :: ClassName
w3TextDarkGrey = ClassName "w3-text-dark-grey"

-- | A ClassName for w3-text-deep-orange
w3TextDeepOrange :: ClassName
w3TextDeepOrange = ClassName "w3-text-deep-orange"

-- | A ClassName for w3-text-deep-purple
w3TextDeepPurple :: ClassName
w3TextDeepPurple = ClassName "w3-text-deep-purple"

-- | A ClassName for w3-text-gray
w3TextGray :: ClassName
w3TextGray = ClassName "w3-text-gray"

-- | A ClassName for w3-text-green
w3TextGreen :: ClassName
w3TextGreen = ClassName "w3-text-green"

-- | A ClassName for w3-text-grey
w3TextGrey :: ClassName
w3TextGrey = ClassName "w3-text-grey"

-- | A ClassName for w3-text-indigo
w3TextIndigo :: ClassName
w3TextIndigo = ClassName "w3-text-indigo"

-- | A ClassName for w3-text-khaki
w3TextKhaki :: ClassName
w3TextKhaki = ClassName "w3-text-khaki"

-- | A ClassName for w3-text-light-blue
w3TextLightBlue :: ClassName
w3TextLightBlue = ClassName "w3-text-light-blue"

-- | A ClassName for w3-text-light-gray
w3TextLightGray :: ClassName
w3TextLightGray = ClassName "w3-text-light-gray"

-- | A ClassName for w3-text-light-green
w3TextLightGreen :: ClassName
w3TextLightGreen = ClassName "w3-text-light-green"

-- | A ClassName for w3-text-light-grey
w3TextLightGrey :: ClassName
w3TextLightGrey = ClassName "w3-text-light-grey"

-- | A ClassName for w3-text-lime
w3TextLime :: ClassName
w3TextLime = ClassName "w3-text-lime"

-- | A ClassName for w3-text-orange
w3TextOrange :: ClassName
w3TextOrange = ClassName "w3-text-orange"

-- | A ClassName for w3-text-pink
w3TextPink :: ClassName
w3TextPink = ClassName "w3-text-pink"

-- | A ClassName for w3-text-purple
w3TextPurple :: ClassName
w3TextPurple = ClassName "w3-text-purple"

-- | A ClassName for w3-text-red
w3TextRed :: ClassName
w3TextRed = ClassName "w3-text-red"

-- | A ClassName for w3-text-sand
w3TextSand :: ClassName
w3TextSand = ClassName "w3-text-sand"

-- | A ClassName for w3-text-teal
w3TextTeal :: ClassName
w3TextTeal = ClassName "w3-text-teal"

-- | A ClassName for w3-text-white
w3TextWhite :: ClassName
w3TextWhite = ClassName "w3-text-white"

-- | A ClassName for w3-text-yellow
w3TextYellow :: ClassName
w3TextYellow = ClassName "w3-text-yellow"

-- | A ClassName for w3-third
w3Third :: ClassName
w3Third = ClassName "w3-third"

-- | A ClassName for w3-threequarter
w3Threequarter :: ClassName
w3Threequarter = ClassName "w3-threequarter"

-- | A ClassName for w3-tiny
w3Tiny :: ClassName
w3Tiny = ClassName "w3-tiny"

-- | A ClassName for w3-tooltip
w3Tooltip :: ClassName
w3Tooltip = ClassName "w3-tooltip"

-- | A ClassName for w3-top
w3Top :: ClassName
w3Top = ClassName "w3-top"

-- | A ClassName for w3-topbar
w3Topbar :: ClassName
w3Topbar = ClassName "w3-topbar"

-- | A ClassName for w3-transparent
w3Transparent :: ClassName
w3Transparent = ClassName "w3-transparent"

-- | A ClassName for w3-twothird
w3Twothird :: ClassName
w3Twothird = ClassName "w3-twothird"

-- | A ClassName for w3-ul
w3Ul :: ClassName
w3Ul = ClassName "w3-ul"

-- | A ClassName for w3-white
w3White :: ClassName
w3White = ClassName "w3-white"

-- | A ClassName for w3-wide
w3Wide :: ClassName
w3Wide = ClassName "w3-wide"

-- | A ClassName for w3-xlarge
w3Xlarge :: ClassName
w3Xlarge = ClassName "w3-xlarge"

-- | A ClassName for w3-xxlarge
w3Xxlarge :: ClassName
w3Xxlarge = ClassName "w3-xxlarge"

-- | A ClassName for w3-xxxlarge
w3Xxxlarge :: ClassName
w3Xxxlarge = ClassName "w3-xxxlarge"

-- | A ClassName for w3-yellow
w3Yellow :: ClassName
w3Yellow = ClassName "w3-yellow"

