{-# LANGUAGE OverloadedStrings #-}
module Reflex.Dom.Themes.Raw.Foundation where

import Reflex.Dom.HTML5.Attrs (ClassName (ClassName))


-- This file is automatically generated. 


fouAccordion :: ClassName
fouAccordion = ClassName "accordion"

fouAccordionContent :: ClassName
fouAccordionContent = ClassName "accordion-content"

fouAccordionItem :: ClassName
fouAccordionItem = ClassName "accordion-item"

fouAccordionMenu :: ClassName
fouAccordionMenu = ClassName "accordion-menu"

fouAccordionTitle :: ClassName
fouAccordionTitle = ClassName "accordion-title"

fouActive :: ClassName
fouActive = ClassName "active"

fouAlert :: ClassName
fouAlert = ClassName "alert"

fouAlignBottom :: ClassName
fouAlignBottom = ClassName "align-bottom"

fouAlignCenter :: ClassName
fouAlignCenter = ClassName "align-center"

fouAlignCenterMiddle :: ClassName
fouAlignCenterMiddle = ClassName "align-center-middle"

fouAlignJustify :: ClassName
fouAlignJustify = ClassName "align-justify"

fouAlignLeft :: ClassName
fouAlignLeft = ClassName "align-left"

fouAlignMiddle :: ClassName
fouAlignMiddle = ClassName "align-middle"

fouAlignRight :: ClassName
fouAlignRight = ClassName "align-right"

fouAlignSelfBottom :: ClassName
fouAlignSelfBottom = ClassName "align-self-bottom"

fouAlignSelfMiddle :: ClassName
fouAlignSelfMiddle = ClassName "align-self-middle"

fouAlignSelfStretch :: ClassName
fouAlignSelfStretch = ClassName "align-self-stretch"

fouAlignSelfTop :: ClassName
fouAlignSelfTop = ClassName "align-self-top"

fouAlignSpaced :: ClassName
fouAlignSpaced = ClassName "align-spaced"

fouAlignStretch :: ClassName
fouAlignStretch = ClassName "align-stretch"

fouAlignTop :: ClassName
fouAlignTop = ClassName "align-top"

fouAnimateHeight :: ClassName
fouAnimateHeight = ClassName "animate-height"

fouArrowOnly :: ClassName
fouArrowOnly = ClassName "arrow-only"

fouAuto :: ClassName
fouAuto = ClassName "auto"

fouBadge :: ClassName
fouBadge = ClassName "badge"

fouBottom :: ClassName
fouBottom = ClassName "bottom"

fouBounceIn :: ClassName
fouBounceIn = ClassName "bounce-in"

fouBounceInOut :: ClassName
fouBounceInOut = ClassName "bounce-in-out"

fouBounceOut :: ClassName
fouBounceOut = ClassName "bounce-out"

fouBreadcrumbs :: ClassName
fouBreadcrumbs = ClassName "breadcrumbs"

fouButton :: ClassName
fouButton = ClassName "button"

fouButtonGroup :: ClassName
fouButtonGroup = ClassName "button-group"

fouCallout :: ClassName
fouCallout = ClassName "callout"

fouCard :: ClassName
fouCard = ClassName "card"

fouCardDivider :: ClassName
fouCardDivider = ClassName "card-divider"

fouCardImage :: ClassName
fouCardImage = ClassName "card-image"

fouCardSection :: ClassName
fouCardSection = ClassName "card-section"

fouCell :: ClassName
fouCell = ClassName "cell"

fouCellBlock :: ClassName
fouCellBlock = ClassName "cell-block"

fouCellBlockContainer :: ClassName
fouCellBlockContainer = ClassName "cell-block-container"

fouCellBlockY :: ClassName
fouCellBlockY = ClassName "cell-block-y"

fouClear :: ClassName
fouClear = ClassName "clear"

fouClearfix :: ClassName
fouClearfix = ClassName "clearfix"

fouCloseButton :: ClassName
fouCloseButton = ClassName "close-button"

fouCollapse :: ClassName
fouCollapse = ClassName "collapse"

fouColumn :: ClassName
fouColumn = ClassName "column"

fouCurrent :: ClassName
fouCurrent = ClassName "current"

fouDark :: ClassName
fouDark = ClassName "dark"

fouDisabled :: ClassName
fouDisabled = ClassName "disabled"

fouDrilldown :: ClassName
fouDrilldown = ClassName "drilldown"

fouDrilldownSubmenuCoverPrevious :: ClassName
fouDrilldownSubmenuCoverPrevious = ClassName "drilldown-submenu-cover-previous"

fouDropdown :: ClassName
fouDropdown = ClassName "dropdown"

fouDropdownPane :: ClassName
fouDropdownPane = ClassName "dropdown-pane"

fouEase :: ClassName
fouEase = ClassName "ease"

fouEaseIn :: ClassName
fouEaseIn = ClassName "ease-in"

fouEaseInOut :: ClassName
fouEaseInOut = ClassName "ease-in-out"

fouEaseOut :: ClassName
fouEaseOut = ClassName "ease-out"

fouEllipsis :: ClassName
fouEllipsis = ClassName "ellipsis"

fouExpanded :: ClassName
fouExpanded = ClassName "expanded"

fouFadeIn :: ClassName
fouFadeIn = ClassName "fade-in"

fouFadeOut :: ClassName
fouFadeOut = ClassName "fade-out"

fouFast :: ClassName
fouFast = ClassName "fast"

fouFieldset :: ClassName
fouFieldset = ClassName "fieldset"

fouFirstSub :: ClassName
fouFirstSub = ClassName "first-sub"

fouFlexChildAuto :: ClassName
fouFlexChildAuto = ClassName "flex-child-auto"

fouFlexChildGrow :: ClassName
fouFlexChildGrow = ClassName "flex-child-grow"

fouFlexChildShrink :: ClassName
fouFlexChildShrink = ClassName "flex-child-shrink"

fouFlexContainer :: ClassName
fouFlexContainer = ClassName "flex-container"

fouFlexDirColumn :: ClassName
fouFlexDirColumn = ClassName "flex-dir-column"

fouFlexDirColumnReverse :: ClassName
fouFlexDirColumnReverse = ClassName "flex-dir-column-reverse"

fouFlexDirRow :: ClassName
fouFlexDirRow = ClassName "flex-dir-row"

fouFlexDirRowReverse :: ClassName
fouFlexDirRowReverse = ClassName "flex-dir-row-reverse"

fouFlexVideo :: ClassName
fouFlexVideo = ClassName "flex-video"

fouFloatCenter :: ClassName
fouFloatCenter = ClassName "float-center"

fouFloatLeft :: ClassName
fouFloatLeft = ClassName "float-left"

fouFloatRight :: ClassName
fouFloatRight = ClassName "float-right"

fouFluid :: ClassName
fouFluid = ClassName "fluid"

fouFormError :: ClassName
fouFormError = ClassName "form-error"

fouFoundationMq :: ClassName
fouFoundationMq = ClassName "foundation-mq"

fouFull :: ClassName
fouFull = ClassName "full"

fouGridContainer :: ClassName
fouGridContainer = ClassName "grid-container"

fouGridFrame :: ClassName
fouGridFrame = ClassName "grid-frame"

fouGridMarginX :: ClassName
fouGridMarginX = ClassName "grid-margin-x"

fouGridMarginY :: ClassName
fouGridMarginY = ClassName "grid-margin-y"

fouGridPaddingX :: ClassName
fouGridPaddingX = ClassName "grid-padding-x"

fouGridPaddingY :: ClassName
fouGridPaddingY = ClassName "grid-padding-y"

fouGridX :: ClassName
fouGridX = ClassName "grid-x"

fouGridY :: ClassName
fouGridY = ClassName "grid-y"

fouH1 :: ClassName
fouH1 = ClassName "h1"

fouH2 :: ClassName
fouH2 = ClassName "h2"

fouH3 :: ClassName
fouH3 = ClassName "h3"

fouH4 :: ClassName
fouH4 = ClassName "h4"

fouH5 :: ClassName
fouH5 = ClassName "h5"

fouH6 :: ClassName
fouH6 = ClassName "h6"

fouHasRevealBottom :: ClassName
fouHasRevealBottom = ClassName "has-reveal-bottom"

fouHasRevealLeft :: ClassName
fouHasRevealLeft = ClassName "has-reveal-left"

fouHasRevealRight :: ClassName
fouHasRevealRight = ClassName "has-reveal-right"

fouHasRevealTop :: ClassName
fouHasRevealTop = ClassName "has-reveal-top"

fouHasSubmenuToggle :: ClassName
fouHasSubmenuToggle = ClassName "has-submenu-toggle"

fouHasTip :: ClassName
fouHasTip = ClassName "has-tip"

fouHasTransitionPush :: ClassName
fouHasTransitionPush = ClassName "has-transition-push"

fouHelpText :: ClassName
fouHelpText = ClassName "help-text"

fouHide :: ClassName
fouHide = ClassName "hide"

fouHideForLandscape :: ClassName
fouHideForLandscape = ClassName "hide-for-landscape"

fouHideForLarge :: ClassName
fouHideForLarge = ClassName "hide-for-large"

fouHideForLargeOnly :: ClassName
fouHideForLargeOnly = ClassName "hide-for-large-only"

fouHideForMedium :: ClassName
fouHideForMedium = ClassName "hide-for-medium"

fouHideForMediumOnly :: ClassName
fouHideForMediumOnly = ClassName "hide-for-medium-only"

fouHideForPortrait :: ClassName
fouHideForPortrait = ClassName "hide-for-portrait"

fouHideForPrint :: ClassName
fouHideForPrint = ClassName "hide-for-print"

fouHideForSmallOnly :: ClassName
fouHideForSmallOnly = ClassName "hide-for-small-only"

fouHingeInFromBottom :: ClassName
fouHingeInFromBottom = ClassName "hinge-in-from-bottom"

fouHingeInFromLeft :: ClassName
fouHingeInFromLeft = ClassName "hinge-in-from-left"

fouHingeInFromMiddleX :: ClassName
fouHingeInFromMiddleX = ClassName "hinge-in-from-middle-x"

fouHingeInFromMiddleY :: ClassName
fouHingeInFromMiddleY = ClassName "hinge-in-from-middle-y"

fouHingeInFromRight :: ClassName
fouHingeInFromRight = ClassName "hinge-in-from-right"

fouHingeInFromTop :: ClassName
fouHingeInFromTop = ClassName "hinge-in-from-top"

fouHingeOutFromBottom :: ClassName
fouHingeOutFromBottom = ClassName "hinge-out-from-bottom"

fouHingeOutFromLeft :: ClassName
fouHingeOutFromLeft = ClassName "hinge-out-from-left"

fouHingeOutFromMiddleX :: ClassName
fouHingeOutFromMiddleX = ClassName "hinge-out-from-middle-x"

fouHingeOutFromMiddleY :: ClassName
fouHingeOutFromMiddleY = ClassName "hinge-out-from-middle-y"

fouHingeOutFromRight :: ClassName
fouHingeOutFromRight = ClassName "hinge-out-from-right"

fouHingeOutFromTop :: ClassName
fouHingeOutFromTop = ClassName "hinge-out-from-top"

fouHollow :: ClassName
fouHollow = ClassName "hollow"

fouHorizontal :: ClassName
fouHorizontal = ClassName "horizontal"

fouHover :: ClassName
fouHover = ClassName "hover"

fouIconBottom :: ClassName
fouIconBottom = ClassName "icon-bottom"

fouIconLeft :: ClassName
fouIconLeft = ClassName "icon-left"

fouIconRight :: ClassName
fouIconRight = ClassName "icon-right"

fouIconTop :: ClassName
fouIconTop = ClassName "icon-top"

fouIcons :: ClassName
fouIcons = ClassName "icons"

fouInCanvasForLarge :: ClassName
fouInCanvasForLarge = ClassName "in-canvas-for-large"

fouInCanvasForMedium :: ClassName
fouInCanvasForMedium = ClassName "in-canvas-for-medium"

fouInfinite :: ClassName
fouInfinite = ClassName "infinite"

fouInputGroup :: ClassName
fouInputGroup = ClassName "input-group"

fouInputGroupButton :: ClassName
fouInputGroupButton = ClassName "input-group-button"

fouInputGroupField :: ClassName
fouInputGroupField = ClassName "input-group-field"

fouInputGroupLabel :: ClassName
fouInputGroupLabel = ClassName "input-group-label"

fouInvisible :: ClassName
fouInvisible = ClassName "invisible"

fouIr :: ClassName
fouIr = ClassName "ir"

fouIsAccordionSubmenu :: ClassName
fouIsAccordionSubmenu = ClassName "is-accordion-submenu"

fouIsAccordionSubmenuParent :: ClassName
fouIsAccordionSubmenuParent = ClassName "is-accordion-submenu-parent"

fouIsActive :: ClassName
fouIsActive = ClassName "is-active"

fouIsAnchored :: ClassName
fouIsAnchored = ClassName "is-anchored"

fouIsAtBottom :: ClassName
fouIsAtBottom = ClassName "is-at-bottom"

fouIsAtTop :: ClassName
fouIsAtTop = ClassName "is-at-top"

fouIsClosable :: ClassName
fouIsClosable = ClassName "is-closable"

fouIsClosed :: ClassName
fouIsClosed = ClassName "is-closed"

fouIsClosing :: ClassName
fouIsClosing = ClassName "is-closing"

fouIsDragging :: ClassName
fouIsDragging = ClassName "is-dragging"

fouIsDrilldown :: ClassName
fouIsDrilldown = ClassName "is-drilldown"

fouIsDrilldownSubmenu :: ClassName
fouIsDrilldownSubmenu = ClassName "is-drilldown-submenu"

fouIsDrilldownSubmenuParent :: ClassName
fouIsDrilldownSubmenuParent = ClassName "is-drilldown-submenu-parent"

fouIsDropdownMenu :: ClassName
fouIsDropdownMenu = ClassName "is-dropdown-menu"

fouIsDropdownSubmenu :: ClassName
fouIsDropdownSubmenu = ClassName "is-dropdown-submenu"

fouIsDropdownSubmenuParent :: ClassName
fouIsDropdownSubmenuParent = ClassName "is-dropdown-submenu-parent"

fouIsHidden :: ClassName
fouIsHidden = ClassName "is-hidden"

fouIsInvalidInput :: ClassName
fouIsInvalidInput = ClassName "is-invalid-input"

fouIsInvalidLabel :: ClassName
fouIsInvalidLabel = ClassName "is-invalid-label"

fouIsOffCanvasOpen :: ClassName
fouIsOffCanvasOpen = ClassName "is-off-canvas-open"

fouIsOpen :: ClassName
fouIsOpen = ClassName "is-open"

fouIsOpenBottom :: ClassName
fouIsOpenBottom = ClassName "is-open-bottom"

fouIsOpenLeft :: ClassName
fouIsOpenLeft = ClassName "is-open-left"

fouIsOpenRight :: ClassName
fouIsOpenRight = ClassName "is-open-right"

fouIsOpenTop :: ClassName
fouIsOpenTop = ClassName "is-open-top"

fouIsOpening :: ClassName
fouIsOpening = ClassName "is-opening"

fouIsOverlayAbsolute :: ClassName
fouIsOverlayAbsolute = ClassName "is-overlay-absolute"

fouIsOverlayFixed :: ClassName
fouIsOverlayFixed = ClassName "is-overlay-fixed"

fouIsRevealOpen :: ClassName
fouIsRevealOpen = ClassName "is-reveal-open"

fouIsStuck :: ClassName
fouIsStuck = ClassName "is-stuck"

fouIsTransitionOverlap :: ClassName
fouIsTransitionOverlap = ClassName "is-transition-overlap"

fouIsTransitionPush :: ClassName
fouIsTransitionPush = ClassName "is-transition-push"

fouIsVisible :: ClassName
fouIsVisible = ClassName "is-visible"

fouJsDrilldownBack :: ClassName
fouJsDrilldownBack = ClassName "js-drilldown-back"

fouJsDropdownActive :: ClassName
fouJsDropdownActive = ClassName "js-dropdown-active"

fouJsOffCanvasOverlay :: ClassName
fouJsOffCanvasOverlay = ClassName "js-off-canvas-overlay"

fouLabel :: ClassName
fouLabel = ClassName "label"

fouLarge :: ClassName
fouLarge = ClassName "large"

fouLarge1 :: ClassName
fouLarge1 = ClassName "large-1"

fouLarge10 :: ClassName
fouLarge10 = ClassName "large-10"

fouLarge11 :: ClassName
fouLarge11 = ClassName "large-11"

fouLarge12 :: ClassName
fouLarge12 = ClassName "large-12"

fouLarge2 :: ClassName
fouLarge2 = ClassName "large-2"

fouLarge3 :: ClassName
fouLarge3 = ClassName "large-3"

fouLarge4 :: ClassName
fouLarge4 = ClassName "large-4"

fouLarge5 :: ClassName
fouLarge5 = ClassName "large-5"

fouLarge6 :: ClassName
fouLarge6 = ClassName "large-6"

fouLarge7 :: ClassName
fouLarge7 = ClassName "large-7"

fouLarge8 :: ClassName
fouLarge8 = ClassName "large-8"

fouLarge9 :: ClassName
fouLarge9 = ClassName "large-9"

fouLargeAuto :: ClassName
fouLargeAuto = ClassName "large-auto"

fouLargeCellBlock :: ClassName
fouLargeCellBlock = ClassName "large-cell-block"

fouLargeCellBlockContainer :: ClassName
fouLargeCellBlockContainer = ClassName "large-cell-block-container"

fouLargeCellBlockY :: ClassName
fouLargeCellBlockY = ClassName "large-cell-block-y"

fouLargeExpanded :: ClassName
fouLargeExpanded = ClassName "large-expanded"

fouLargeFlexChildAuto :: ClassName
fouLargeFlexChildAuto = ClassName "large-flex-child-auto"

fouLargeFlexChildGrow :: ClassName
fouLargeFlexChildGrow = ClassName "large-flex-child-grow"

fouLargeFlexChildShrink :: ClassName
fouLargeFlexChildShrink = ClassName "large-flex-child-shrink"

fouLargeFlexContainer :: ClassName
fouLargeFlexContainer = ClassName "large-flex-container"

fouLargeFlexDirColumn :: ClassName
fouLargeFlexDirColumn = ClassName "large-flex-dir-column"

fouLargeFlexDirColumnReverse :: ClassName
fouLargeFlexDirColumnReverse = ClassName "large-flex-dir-column-reverse"

fouLargeFlexDirRow :: ClassName
fouLargeFlexDirRow = ClassName "large-flex-dir-row"

fouLargeFlexDirRowReverse :: ClassName
fouLargeFlexDirRowReverse = ClassName "large-flex-dir-row-reverse"

fouLargeFull :: ClassName
fouLargeFull = ClassName "large-full"

fouLargeGridFrame :: ClassName
fouLargeGridFrame = ClassName "large-grid-frame"

fouLargeHorizontal :: ClassName
fouLargeHorizontal = ClassName "large-horizontal"

fouLargeMarginCollapse :: ClassName
fouLargeMarginCollapse = ClassName "large-margin-collapse"

fouLargeOffset0 :: ClassName
fouLargeOffset0 = ClassName "large-offset-0"

fouLargeOffset1 :: ClassName
fouLargeOffset1 = ClassName "large-offset-1"

fouLargeOffset10 :: ClassName
fouLargeOffset10 = ClassName "large-offset-10"

fouLargeOffset11 :: ClassName
fouLargeOffset11 = ClassName "large-offset-11"

fouLargeOffset2 :: ClassName
fouLargeOffset2 = ClassName "large-offset-2"

fouLargeOffset3 :: ClassName
fouLargeOffset3 = ClassName "large-offset-3"

fouLargeOffset4 :: ClassName
fouLargeOffset4 = ClassName "large-offset-4"

fouLargeOffset5 :: ClassName
fouLargeOffset5 = ClassName "large-offset-5"

fouLargeOffset6 :: ClassName
fouLargeOffset6 = ClassName "large-offset-6"

fouLargeOffset7 :: ClassName
fouLargeOffset7 = ClassName "large-offset-7"

fouLargeOffset8 :: ClassName
fouLargeOffset8 = ClassName "large-offset-8"

fouLargeOffset9 :: ClassName
fouLargeOffset9 = ClassName "large-offset-9"

fouLargeOrder1 :: ClassName
fouLargeOrder1 = ClassName "large-order-1"

fouLargeOrder2 :: ClassName
fouLargeOrder2 = ClassName "large-order-2"

fouLargeOrder3 :: ClassName
fouLargeOrder3 = ClassName "large-order-3"

fouLargeOrder4 :: ClassName
fouLargeOrder4 = ClassName "large-order-4"

fouLargeOrder5 :: ClassName
fouLargeOrder5 = ClassName "large-order-5"

fouLargeOrder6 :: ClassName
fouLargeOrder6 = ClassName "large-order-6"

fouLargePaddingCollapse :: ClassName
fouLargePaddingCollapse = ClassName "large-padding-collapse"

fouLargeShrink :: ClassName
fouLargeShrink = ClassName "large-shrink"

fouLargeSimple :: ClassName
fouLargeSimple = ClassName "large-simple"

fouLargeTextCenter :: ClassName
fouLargeTextCenter = ClassName "large-text-center"

fouLargeTextJustify :: ClassName
fouLargeTextJustify = ClassName "large-text-justify"

fouLargeTextLeft :: ClassName
fouLargeTextLeft = ClassName "large-text-left"

fouLargeTextRight :: ClassName
fouLargeTextRight = ClassName "large-text-right"

fouLargeUp1 :: ClassName
fouLargeUp1 = ClassName "large-up-1"

fouLargeUp2 :: ClassName
fouLargeUp2 = ClassName "large-up-2"

fouLargeUp3 :: ClassName
fouLargeUp3 = ClassName "large-up-3"

fouLargeUp4 :: ClassName
fouLargeUp4 = ClassName "large-up-4"

fouLargeUp5 :: ClassName
fouLargeUp5 = ClassName "large-up-5"

fouLargeUp6 :: ClassName
fouLargeUp6 = ClassName "large-up-6"

fouLargeUp7 :: ClassName
fouLargeUp7 = ClassName "large-up-7"

fouLargeUp8 :: ClassName
fouLargeUp8 = ClassName "large-up-8"

fouLargeVertical :: ClassName
fouLargeVertical = ClassName "large-vertical"

fouLead :: ClassName
fouLead = ClassName "lead"

fouLeft :: ClassName
fouLeft = ClassName "left"

fouLinear :: ClassName
fouLinear = ClassName "linear"

fouLongDelay :: ClassName
fouLongDelay = ClassName "long-delay"

fouMainSection :: ClassName
fouMainSection = ClassName "main-section"

fouMapCanvas :: ClassName
fouMapCanvas = ClassName "map_canvas"

fouMediaObject :: ClassName
fouMediaObject = ClassName "media-object"

fouMediaObjectSection :: ClassName
fouMediaObjectSection = ClassName "media-object-section"

fouMedium :: ClassName
fouMedium = ClassName "medium"

fouMedium1 :: ClassName
fouMedium1 = ClassName "medium-1"

fouMedium10 :: ClassName
fouMedium10 = ClassName "medium-10"

fouMedium11 :: ClassName
fouMedium11 = ClassName "medium-11"

fouMedium12 :: ClassName
fouMedium12 = ClassName "medium-12"

fouMedium2 :: ClassName
fouMedium2 = ClassName "medium-2"

fouMedium3 :: ClassName
fouMedium3 = ClassName "medium-3"

fouMedium4 :: ClassName
fouMedium4 = ClassName "medium-4"

fouMedium5 :: ClassName
fouMedium5 = ClassName "medium-5"

fouMedium6 :: ClassName
fouMedium6 = ClassName "medium-6"

fouMedium7 :: ClassName
fouMedium7 = ClassName "medium-7"

fouMedium8 :: ClassName
fouMedium8 = ClassName "medium-8"

fouMedium9 :: ClassName
fouMedium9 = ClassName "medium-9"

fouMediumAuto :: ClassName
fouMediumAuto = ClassName "medium-auto"

fouMediumCellBlock :: ClassName
fouMediumCellBlock = ClassName "medium-cell-block"

fouMediumCellBlockContainer :: ClassName
fouMediumCellBlockContainer = ClassName "medium-cell-block-container"

fouMediumCellBlockY :: ClassName
fouMediumCellBlockY = ClassName "medium-cell-block-y"

fouMediumExpanded :: ClassName
fouMediumExpanded = ClassName "medium-expanded"

fouMediumFlexChildAuto :: ClassName
fouMediumFlexChildAuto = ClassName "medium-flex-child-auto"

fouMediumFlexChildGrow :: ClassName
fouMediumFlexChildGrow = ClassName "medium-flex-child-grow"

fouMediumFlexChildShrink :: ClassName
fouMediumFlexChildShrink = ClassName "medium-flex-child-shrink"

fouMediumFlexContainer :: ClassName
fouMediumFlexContainer = ClassName "medium-flex-container"

fouMediumFlexDirColumn :: ClassName
fouMediumFlexDirColumn = ClassName "medium-flex-dir-column"

fouMediumFlexDirColumnReverse :: ClassName
fouMediumFlexDirColumnReverse = ClassName "medium-flex-dir-column-reverse"

fouMediumFlexDirRow :: ClassName
fouMediumFlexDirRow = ClassName "medium-flex-dir-row"

fouMediumFlexDirRowReverse :: ClassName
fouMediumFlexDirRowReverse = ClassName "medium-flex-dir-row-reverse"

fouMediumFull :: ClassName
fouMediumFull = ClassName "medium-full"

fouMediumGridFrame :: ClassName
fouMediumGridFrame = ClassName "medium-grid-frame"

fouMediumHorizontal :: ClassName
fouMediumHorizontal = ClassName "medium-horizontal"

fouMediumMarginCollapse :: ClassName
fouMediumMarginCollapse = ClassName "medium-margin-collapse"

fouMediumOffset0 :: ClassName
fouMediumOffset0 = ClassName "medium-offset-0"

fouMediumOffset1 :: ClassName
fouMediumOffset1 = ClassName "medium-offset-1"

fouMediumOffset10 :: ClassName
fouMediumOffset10 = ClassName "medium-offset-10"

fouMediumOffset11 :: ClassName
fouMediumOffset11 = ClassName "medium-offset-11"

fouMediumOffset2 :: ClassName
fouMediumOffset2 = ClassName "medium-offset-2"

fouMediumOffset3 :: ClassName
fouMediumOffset3 = ClassName "medium-offset-3"

fouMediumOffset4 :: ClassName
fouMediumOffset4 = ClassName "medium-offset-4"

fouMediumOffset5 :: ClassName
fouMediumOffset5 = ClassName "medium-offset-5"

fouMediumOffset6 :: ClassName
fouMediumOffset6 = ClassName "medium-offset-6"

fouMediumOffset7 :: ClassName
fouMediumOffset7 = ClassName "medium-offset-7"

fouMediumOffset8 :: ClassName
fouMediumOffset8 = ClassName "medium-offset-8"

fouMediumOffset9 :: ClassName
fouMediumOffset9 = ClassName "medium-offset-9"

fouMediumOrder1 :: ClassName
fouMediumOrder1 = ClassName "medium-order-1"

fouMediumOrder2 :: ClassName
fouMediumOrder2 = ClassName "medium-order-2"

fouMediumOrder3 :: ClassName
fouMediumOrder3 = ClassName "medium-order-3"

fouMediumOrder4 :: ClassName
fouMediumOrder4 = ClassName "medium-order-4"

fouMediumOrder5 :: ClassName
fouMediumOrder5 = ClassName "medium-order-5"

fouMediumOrder6 :: ClassName
fouMediumOrder6 = ClassName "medium-order-6"

fouMediumPaddingCollapse :: ClassName
fouMediumPaddingCollapse = ClassName "medium-padding-collapse"

fouMediumShrink :: ClassName
fouMediumShrink = ClassName "medium-shrink"

fouMediumSimple :: ClassName
fouMediumSimple = ClassName "medium-simple"

fouMediumTextCenter :: ClassName
fouMediumTextCenter = ClassName "medium-text-center"

fouMediumTextJustify :: ClassName
fouMediumTextJustify = ClassName "medium-text-justify"

fouMediumTextLeft :: ClassName
fouMediumTextLeft = ClassName "medium-text-left"

fouMediumTextRight :: ClassName
fouMediumTextRight = ClassName "medium-text-right"

fouMediumUp1 :: ClassName
fouMediumUp1 = ClassName "medium-up-1"

fouMediumUp2 :: ClassName
fouMediumUp2 = ClassName "medium-up-2"

fouMediumUp3 :: ClassName
fouMediumUp3 = ClassName "medium-up-3"

fouMediumUp4 :: ClassName
fouMediumUp4 = ClassName "medium-up-4"

fouMediumUp5 :: ClassName
fouMediumUp5 = ClassName "medium-up-5"

fouMediumUp6 :: ClassName
fouMediumUp6 = ClassName "medium-up-6"

fouMediumUp7 :: ClassName
fouMediumUp7 = ClassName "medium-up-7"

fouMediumUp8 :: ClassName
fouMediumUp8 = ClassName "medium-up-8"

fouMediumVertical :: ClassName
fouMediumVertical = ClassName "medium-vertical"

fouMenu :: ClassName
fouMenu = ClassName "menu"

fouMenuCentered :: ClassName
fouMenuCentered = ClassName "menu-centered"

fouMenuIcon :: ClassName
fouMenuIcon = ClassName "menu-icon"

fouMenuText :: ClassName
fouMenuText = ClassName "menu-text"

fouMiddle :: ClassName
fouMiddle = ClassName "middle"

fouMqaDisplay :: ClassName
fouMqaDisplay = ClassName "mqa-display"

fouMuiEnter :: ClassName
fouMuiEnter = ClassName "mui-enter"

fouMuiEnterActive :: ClassName
fouMuiEnterActive = ClassName "mui-enter-active"

fouMuiLeave :: ClassName
fouMuiLeave = ClassName "mui-leave"

fouMuiLeaveActive :: ClassName
fouMuiLeaveActive = ClassName "mui-leave-active"

fouNested :: ClassName
fouNested = ClassName "nested"

fouNoBullet :: ClassName
fouNoBullet = ClassName "no-bullet"

fouNoJs :: ClassName
fouNoJs = ClassName "no-js"

fouNoMotionui :: ClassName
fouNoMotionui = ClassName "no-motionui"

fouOffCanvas :: ClassName
fouOffCanvas = ClassName "off-canvas"

fouOffCanvasAbsolute :: ClassName
fouOffCanvasAbsolute = ClassName "off-canvas-absolute"

fouOffCanvasContent :: ClassName
fouOffCanvasContent = ClassName "off-canvas-content"

fouOffCanvasWrapper :: ClassName
fouOffCanvasWrapper = ClassName "off-canvas-wrapper"

fouOpensInner :: ClassName
fouOpensInner = ClassName "opens-inner"

fouOpensLeft :: ClassName
fouOpensLeft = ClassName "opens-left"

fouOpensRight :: ClassName
fouOpensRight = ClassName "opens-right"

fouOrbit :: ClassName
fouOrbit = ClassName "orbit"

fouOrbitBullets :: ClassName
fouOrbitBullets = ClassName "orbit-bullets"

fouOrbitCaption :: ClassName
fouOrbitCaption = ClassName "orbit-caption"

fouOrbitContainer :: ClassName
fouOrbitContainer = ClassName "orbit-container"

fouOrbitFigure :: ClassName
fouOrbitFigure = ClassName "orbit-figure"

fouOrbitImage :: ClassName
fouOrbitImage = ClassName "orbit-image"

fouOrbitNext :: ClassName
fouOrbitNext = ClassName "orbit-next"

fouOrbitPrevious :: ClassName
fouOrbitPrevious = ClassName "orbit-previous"

fouOrbitSlide :: ClassName
fouOrbitSlide = ClassName "orbit-slide"

fouPagination :: ClassName
fouPagination = ClassName "pagination"

fouPaginationNext :: ClassName
fouPaginationNext = ClassName "pagination-next"

fouPaginationPrevious :: ClassName
fouPaginationPrevious = ClassName "pagination-previous"

fouPositionBottom :: ClassName
fouPositionBottom = ClassName "position-bottom"

fouPositionLeft :: ClassName
fouPositionLeft = ClassName "position-left"

fouPositionRight :: ClassName
fouPositionRight = ClassName "position-right"

fouPositionTop :: ClassName
fouPositionTop = ClassName "position-top"

fouPrimary :: ClassName
fouPrimary = ClassName "primary"

fouPrintBreakInside :: ClassName
fouPrintBreakInside = ClassName "print-break-inside"

fouProgress :: ClassName
fouProgress = ClassName "progress"

fouProgressMeter :: ClassName
fouProgressMeter = ClassName "progress-meter"

fouProgressMeterText :: ClassName
fouProgressMeterText = ClassName "progress-meter-text"

fouResponsiveEmbed :: ClassName
fouResponsiveEmbed = ClassName "responsive-embed"

fouReveal :: ClassName
fouReveal = ClassName "reveal"

fouRevealForLarge :: ClassName
fouRevealForLarge = ClassName "reveal-for-large"

fouRevealForMedium :: ClassName
fouRevealForMedium = ClassName "reveal-for-medium"

fouRevealOverlay :: ClassName
fouRevealOverlay = ClassName "reveal-overlay"

fouRight :: ClassName
fouRight = ClassName "right"

fouScaleInDown :: ClassName
fouScaleInDown = ClassName "scale-in-down"

fouScaleInUp :: ClassName
fouScaleInUp = ClassName "scale-in-up"

fouScaleOutDown :: ClassName
fouScaleOutDown = ClassName "scale-out-down"

fouScaleOutUp :: ClassName
fouScaleOutUp = ClassName "scale-out-up"

fouScroll :: ClassName
fouScroll = ClassName "scroll"

fouSecondary :: ClassName
fouSecondary = ClassName "secondary"

fouShake :: ClassName
fouShake = ClassName "shake"

fouShortDelay :: ClassName
fouShortDelay = ClassName "short-delay"

fouShowForLandscape :: ClassName
fouShowForLandscape = ClassName "show-for-landscape"

fouShowForLarge :: ClassName
fouShowForLarge = ClassName "show-for-large"

fouShowForLargeOnly :: ClassName
fouShowForLargeOnly = ClassName "show-for-large-only"

fouShowForMedium :: ClassName
fouShowForMedium = ClassName "show-for-medium"

fouShowForMediumOnly :: ClassName
fouShowForMediumOnly = ClassName "show-for-medium-only"

fouShowForPortrait :: ClassName
fouShowForPortrait = ClassName "show-for-portrait"

fouShowForPrint :: ClassName
fouShowForPrint = ClassName "show-for-print"

fouShowForSmallOnly :: ClassName
fouShowForSmallOnly = ClassName "show-for-small-only"

fouShowForSr :: ClassName
fouShowForSr = ClassName "show-for-sr"

fouShowOnFocus :: ClassName
fouShowOnFocus = ClassName "show-on-focus"

fouShrink :: ClassName
fouShrink = ClassName "shrink"

fouSimple :: ClassName
fouSimple = ClassName "simple"

fouSlideInDown :: ClassName
fouSlideInDown = ClassName "slide-in-down"

fouSlideInLeft :: ClassName
fouSlideInLeft = ClassName "slide-in-left"

fouSlideInRight :: ClassName
fouSlideInRight = ClassName "slide-in-right"

fouSlideInUp :: ClassName
fouSlideInUp = ClassName "slide-in-up"

fouSlideOutDown :: ClassName
fouSlideOutDown = ClassName "slide-out-down"

fouSlideOutLeft :: ClassName
fouSlideOutLeft = ClassName "slide-out-left"

fouSlideOutRight :: ClassName
fouSlideOutRight = ClassName "slide-out-right"

fouSlideOutUp :: ClassName
fouSlideOutUp = ClassName "slide-out-up"

fouSlider :: ClassName
fouSlider = ClassName "slider"

fouSliderFill :: ClassName
fouSliderFill = ClassName "slider-fill"

fouSliderHandle :: ClassName
fouSliderHandle = ClassName "slider-handle"

fouSlow :: ClassName
fouSlow = ClassName "slow"

fouSmall :: ClassName
fouSmall = ClassName "small"

fouSmall1 :: ClassName
fouSmall1 = ClassName "small-1"

fouSmall10 :: ClassName
fouSmall10 = ClassName "small-10"

fouSmall11 :: ClassName
fouSmall11 = ClassName "small-11"

fouSmall12 :: ClassName
fouSmall12 = ClassName "small-12"

fouSmall2 :: ClassName
fouSmall2 = ClassName "small-2"

fouSmall3 :: ClassName
fouSmall3 = ClassName "small-3"

fouSmall4 :: ClassName
fouSmall4 = ClassName "small-4"

fouSmall5 :: ClassName
fouSmall5 = ClassName "small-5"

fouSmall6 :: ClassName
fouSmall6 = ClassName "small-6"

fouSmall7 :: ClassName
fouSmall7 = ClassName "small-7"

fouSmall8 :: ClassName
fouSmall8 = ClassName "small-8"

fouSmall9 :: ClassName
fouSmall9 = ClassName "small-9"

fouSmallFull :: ClassName
fouSmallFull = ClassName "small-full"

fouSmallMarginCollapse :: ClassName
fouSmallMarginCollapse = ClassName "small-margin-collapse"

fouSmallOffset0 :: ClassName
fouSmallOffset0 = ClassName "small-offset-0"

fouSmallOffset1 :: ClassName
fouSmallOffset1 = ClassName "small-offset-1"

fouSmallOffset10 :: ClassName
fouSmallOffset10 = ClassName "small-offset-10"

fouSmallOffset11 :: ClassName
fouSmallOffset11 = ClassName "small-offset-11"

fouSmallOffset2 :: ClassName
fouSmallOffset2 = ClassName "small-offset-2"

fouSmallOffset3 :: ClassName
fouSmallOffset3 = ClassName "small-offset-3"

fouSmallOffset4 :: ClassName
fouSmallOffset4 = ClassName "small-offset-4"

fouSmallOffset5 :: ClassName
fouSmallOffset5 = ClassName "small-offset-5"

fouSmallOffset6 :: ClassName
fouSmallOffset6 = ClassName "small-offset-6"

fouSmallOffset7 :: ClassName
fouSmallOffset7 = ClassName "small-offset-7"

fouSmallOffset8 :: ClassName
fouSmallOffset8 = ClassName "small-offset-8"

fouSmallOffset9 :: ClassName
fouSmallOffset9 = ClassName "small-offset-9"

fouSmallOrder1 :: ClassName
fouSmallOrder1 = ClassName "small-order-1"

fouSmallOrder2 :: ClassName
fouSmallOrder2 = ClassName "small-order-2"

fouSmallOrder3 :: ClassName
fouSmallOrder3 = ClassName "small-order-3"

fouSmallOrder4 :: ClassName
fouSmallOrder4 = ClassName "small-order-4"

fouSmallOrder5 :: ClassName
fouSmallOrder5 = ClassName "small-order-5"

fouSmallOrder6 :: ClassName
fouSmallOrder6 = ClassName "small-order-6"

fouSmallPaddingCollapse :: ClassName
fouSmallPaddingCollapse = ClassName "small-padding-collapse"

fouSmallShrink :: ClassName
fouSmallShrink = ClassName "small-shrink"

fouSmallUp1 :: ClassName
fouSmallUp1 = ClassName "small-up-1"

fouSmallUp2 :: ClassName
fouSmallUp2 = ClassName "small-up-2"

fouSmallUp3 :: ClassName
fouSmallUp3 = ClassName "small-up-3"

fouSmallUp4 :: ClassName
fouSmallUp4 = ClassName "small-up-4"

fouSmallUp5 :: ClassName
fouSmallUp5 = ClassName "small-up-5"

fouSmallUp6 :: ClassName
fouSmallUp6 = ClassName "small-up-6"

fouSmallUp7 :: ClassName
fouSmallUp7 = ClassName "small-up-7"

fouSmallUp8 :: ClassName
fouSmallUp8 = ClassName "small-up-8"

fouSpinCcw :: ClassName
fouSpinCcw = ClassName "spin-ccw"

fouSpinCw :: ClassName
fouSpinCw = ClassName "spin-cw"

fouSpinIn :: ClassName
fouSpinIn = ClassName "spin-in"

fouSpinInCcw :: ClassName
fouSpinInCcw = ClassName "spin-in-ccw"

fouSpinOut :: ClassName
fouSpinOut = ClassName "spin-out"

fouSpinOutCcw :: ClassName
fouSpinOutCcw = ClassName "spin-out-ccw"

fouStack :: ClassName
fouStack = ClassName "stack"

fouStackForSmall :: ClassName
fouStackForSmall = ClassName "stack-for-small"

fouStacked :: ClassName
fouStacked = ClassName "stacked"

fouStackedForLarge :: ClassName
fouStackedForLarge = ClassName "stacked-for-large"

fouStackedForMedium :: ClassName
fouStackedForMedium = ClassName "stacked-for-medium"

fouStackedForSmall :: ClassName
fouStackedForSmall = ClassName "stacked-for-small"

fouStat :: ClassName
fouStat = ClassName "stat"

fouSticky :: ClassName
fouSticky = ClassName "sticky"

fouStickyContainer :: ClassName
fouStickyContainer = ClassName "sticky-container"

fouSubheader :: ClassName
fouSubheader = ClassName "subheader"

fouSubmenu :: ClassName
fouSubmenu = ClassName "submenu"

fouSubmenuToggle :: ClassName
fouSubmenuToggle = ClassName "submenu-toggle"

fouSubmenuToggleText :: ClassName
fouSubmenuToggleText = ClassName "submenu-toggle-text"

fouSuccess :: ClassName
fouSuccess = ClassName "success"

fouSwitch :: ClassName
fouSwitch = ClassName "switch"

fouSwitchActive :: ClassName
fouSwitchActive = ClassName "switch-active"

fouSwitchInactive :: ClassName
fouSwitchInactive = ClassName "switch-inactive"

fouSwitchInput :: ClassName
fouSwitchInput = ClassName "switch-input"

fouSwitchPaddle :: ClassName
fouSwitchPaddle = ClassName "switch-paddle"

fouTableScroll :: ClassName
fouTableScroll = ClassName "table-scroll"

fouTabs :: ClassName
fouTabs = ClassName "tabs"

fouTabsContent :: ClassName
fouTabsContent = ClassName "tabs-content"

fouTabsPanel :: ClassName
fouTabsPanel = ClassName "tabs-panel"

fouTabsTitle :: ClassName
fouTabsTitle = ClassName "tabs-title"

fouTextCenter :: ClassName
fouTextCenter = ClassName "text-center"

fouTextJustify :: ClassName
fouTextJustify = ClassName "text-justify"

fouTextLeft :: ClassName
fouTextLeft = ClassName "text-left"

fouTextRight :: ClassName
fouTextRight = ClassName "text-right"

fouThumbnail :: ClassName
fouThumbnail = ClassName "thumbnail"

fouTiny :: ClassName
fouTiny = ClassName "tiny"

fouTitleBar :: ClassName
fouTitleBar = ClassName "title-bar"

fouTitleBarLeft :: ClassName
fouTitleBarLeft = ClassName "title-bar-left"

fouTitleBarRight :: ClassName
fouTitleBarRight = ClassName "title-bar-right"

fouTitleBarTitle :: ClassName
fouTitleBarTitle = ClassName "title-bar-title"

fouTooltip :: ClassName
fouTooltip = ClassName "tooltip"

fouTop :: ClassName
fouTop = ClassName "top"

fouTopBar :: ClassName
fouTopBar = ClassName "top-bar"

fouTopBarLeft :: ClassName
fouTopBarLeft = ClassName "top-bar-left"

fouTopBarRight :: ClassName
fouTopBarRight = ClassName "top-bar-right"

fouTopBarTitle :: ClassName
fouTopBarTitle = ClassName "top-bar-title"

fouUnstriped :: ClassName
fouUnstriped = ClassName "unstriped"

fouVertical :: ClassName
fouVertical = ClassName "vertical"

fouWarning :: ClassName
fouWarning = ClassName "warning"

fouWidescreen :: ClassName
fouWidescreen = ClassName "widescreen"

fouWiggle :: ClassName
fouWiggle = ClassName "wiggle"

fouWithoutOverlay :: ClassName
fouWithoutOverlay = ClassName "without-overlay"

